### ISSUE TITLE
Use 3rd party "decorator" module to fix introspection for decorated functions

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#103]
### Description

Some internal functions are decorated by `@needs_host` or other decorators, and thus lose their ability to be introspected, including by Sphinx autodoc. This makes me sad.

Thankfully, the [decorator](http://pypi.python.org/pypi/decorator/) module has ways to work around this, and looks quite useful. It will add another external dependency but I don't think that's enough of a drawback to be a big concern.

See also an email to me from Matt Wilson dated 2009-09-09 about `@needs_host`, which is where he informed me about the module in question.

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2009-11-11** at **11:49pm EST**

**Comment by markstos** [comment]
May I humbly suggest that if the auto-documentation was desired in 2011 still isn't working yet, perhaps it's time for an alternate approach to improving the docs? Manual documentation (gasp!) or another doc-generator that parses documentation in a template?

Here it is 5 years later and the docs still aren't clear on which positional argument to `put()` is which (#1452). That seems like a basic thing to address. Even some clearer examples would do the trick in that case:

     put('/path/to/local/file.jpg','/path/on/remote/server/file.png');

Instead, the current example provides no clue to which arg is which:

    put('bin/project.zip', '/tmp/project.zip')

Without waiting for a big-picture fix so targeted improvements like this could be helpful.

**Comment by bitprophet** [comment]
I _think_ this is handled for 2.0 and Invoke via http://invocations.readthedocs.io/en/latest/api/autodoc.html (made during https://github.com/pyinvoke/invoke/issues/520).

It's not 100% ideal but solves the primary case of wanting Sphinx docs for `@task`-decorated APIs.

Note that this is (AFAIK) distinct from https://github.com/pyinvoke/invoke/issues/555 re: decorator ordering issues.

**Comment by lsh-0** [comment]
has this made it into a release? I'm still seeing broken behaviour in `Invoke 1.1.0`/`Fabric 2.2.1`
