### ISSUE TITLE
fabric.contrib.django does not use virtualenv django version

### ISSUE THREAD

**Issue by anentropic** [fabric/fabric#1033]
I have activated my virtualenv and installed fabric via pip:

```
(myvenv)$ which fab
~/virtualenvs/myvenv/bin/fab
```

On my web host (WebFaction) there is a systemwide Django (1.3.3) and I have a newer version installed into the virtualenv for my project:

```
(myvenv)$ ipython
In [1]: import django

In [2]: django.get_version()
Out[2]: '1.4.10'
```

In my fabfile I added:

```
from fabric.contrib import django

django.settings_module('myapp.settings')
import django
print(django.get_version())
from django.conf import settings
```

I see the following:

```
(myvenv)$ fab
1.3.3
Traceback (most recent call last):
...
ValueError: Unable to configure filter 'require_debug_false': Cannot resolve 'django.utils.log.RequireDebugFalse': No module named RequireDebugFalse
```

So I'm getting an error due to fabric not using the virtualenv version of django

**Comment by kaaveland** [comment]
Bit hard to pintpoint this without some more information. I'd be very interested in knowing what happens if this file is launched like a normal python module eg `python fabfile.py` ? That way, it should not use fabrics custom module loading.

Fabric does do some changes to `sys.path` in loading, but I can't see it adding any paths other than the directory where the fabfile lives prior to trying to perform the import (and only if it is not already on `sys.path`).

Would it be possible to see what `sys.path` contains at the top of the fabfile?

**Comment by anentropic** [comment]
amazingly 2 years later I can still reproduce this :)

quite possibly the problem is some weird misconfiguration on my server, or an old version of virtualenv or something

I'm hosting on WebFaction. This is what my `sys.path` looks like if I print it before modifying at the top of the fabfile:
```
['/home/anentropic/webapps/django__1_4/myproj', '/home/anentropic/virtualenvs/myproj/bin', '/home/anentropic/lib/python2.7/setuptools-0.6c11-py2.7.egg', '/home/anentropic/lib/python2.7/pip-1.0-py2.7.egg', '/home/anentropic/lib/python2.7/sorl_thumbnail-11.05.1-py2.7.egg', '/home/anentropic/lib/python2.7/django_denorm-0.2.0-py2.7.egg', '/home/anentropic/lib/python2.7/distribute-0.6.10-py2.7.egg', '/home/anentropic/lib/python2.7/URLObject-0.5-py2.7.egg', '/home/anentropic/lib/python2.7/simplejson-2.1.5-py2.7-linux-i686.egg', '/home/anentropic/lib/python2.7/bunch-1.0.0-py2.7.egg', '/home/anentropic/lib/python2.7/django_notification-0.2a1.dev4-py2.7.egg', '/home/anentropic/lib/python2.7/django_storages-1.2a-py2.7.egg', '/home/anentropic/lib/python2.7/satchless-2011.9.pre-py2.7.egg', '/home/anentropic/lib/python2.7', '/home/anentropic/virtualenvs/myproj/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', '/home/anentropic/virtualenvs/myproj/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg', '/home/anentropic/virtualenvs/myproj/src/ebaysync', '/home/anentropic/virtualenvs/myproj/lib/python27.zip', '/home/anentropic/virtualenvs/myproj/lib/python2.7', '/home/anentropic/virtualenvs/myproj/lib/python2.7/plat-linux2', '/home/anentropic/virtualenvs/myproj/lib/python2.7/lib-tk', '/home/anentropic/virtualenvs/myproj/lib/python2.7/lib-old', '/home/anentropic/virtualenvs/myproj/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/home/anentropic/virtualenvs/myproj/lib/python2.7/site-packages', '/home/anentropic/webapps/django__1_4/lib/python2.7']
```

so the problem is that the virtualenv site-packages is almost at the bottom of the list, behind a bunch of stuff from the system user python2.7

if I run `python fabfile.py` I have exactly the same problem

now, I am stuck using old virtualenv 1.10.0 since anything newer clashes with the old setuptools 0.6c11 ..and this is in the system root python (which on webfaction is shared with other users) and I can't upgrade it

related: https://github.com/fabric/fabric/issues/1207#issuecomment-142403783

anyway it doesn't happen locally so I think problem is related to the messed up situation on my webfaction host

**Comment by kaaveland** [comment]
Okay, I'm not sure that issue is fixable from within fabric.

If wonder if maybe you're able to run `pip install --upgrade virtualenv setuptools` in your virtualenv and make a new one from that (don't know if this is supported) ?
