### ISSUE TITLE
decorators._wrap_as_new always overrides the class of a task

### ISSUE THREAD

**Issue by termie** [fabric/fabric#1035]
https://github.com/fabric/fabric/blob/master/fabric/decorators.py#L43

In the scenario where you subclass tasks.Task to override a call (in this case get_hosts), when you try to use that subclass all other decorators will keep changing your class back to a WrappedCallableTask.

It seems like, the conditional there should possibly say 'if not isinstance...' or alternatively have a place to set the task class factory somewhere.

Here's the code that is triggering this, https://gist.github.com/termie/7817384

This behavior means my overloaded task decorator has to be the last decorator in the chain every time

**Comment by bitprophet** [comment]
Sad that I never even so much as responded to a ticket filed by termie :( sorry! If this hasn't been tweaked since then (likely) and is still an active problem, please comment and will reopen. (Though likely this will be sidestepped in v2 which redoes a lot of the task-class related junk.)
