### ISSUE TITLE
Remote processes designed to use the entire terminal widith will wrap becuase of the output prefix

### ISSUE THREAD

**Issue by andersrein** [fabric/fabric#1043]
When running processes like yum (red hat package manager) on remote system which uses the entire width of the terminal as progress bar, the lines will wrap because the output of the host puts the output prefix  "[host] out:" in front of the output.

**Comment by kaaveland** [comment]
You can use this idea to work around this:
```python
def do_thing():
    with api.settings(output_prefix=False):
        api.run('echo hello')
```
```
fab do_thing
[X] Executing task 'do_thing'
[X] run: echo hello
hello


Done.
```
While it would be convenient with some shortcut here, I'm not sure fabric should be guessing whether you want this behaviour or not, so I think maybe this one could be closed.

**Comment by andersrein** [comment]
I was think more that the proper solution was to send to the remote system that the terminal width is equal to the local terminal width minus the length of the prefix. I was not suggesting that the prefix would be automatically disabled.

**Comment by kaaveland** [comment]
That might be an option, maybe you want to take a stab at it? We'd have to account for `output_prefix=False`, but it looks doable since `stty` seems fairly standard. We'd probably need to handle windows differently though.

**Comment by andersrein** [comment]
This is not really important for me anymore. My original bug report was 2 years ago and I no longer work with fabric so I probably won't spend any time fixing this. Sorry.

**Comment by kaaveland** [comment]
No worries, thanks for the input.
