### ISSUE TITLE
Inbuilt support for history of deployment? 

### ISSUE THREAD

**Issue by VarunBatraIT** [fabric/fabric#1048]
My use case is to have a history of deployment so that if something goes wrong I can immediately switch to different version which was working.

Something like:

https://github.com/CodeMeme/Phingistrano#deployhistory

**Comment by kaaveland** [comment]
I'd say this is outside the scope of fabric. 

It's very specific to deployment, but fabric is more general purpose than that. I use it for many one-off tasks that I need to execute on many servers. It'd be incredibly difficult to implement this robustly without making choices that fabric shouldn't make for its users. Eg. on teams with multiple people deploying, you'd need to store the versions somewhere on the server. Maybe you'd have to worry about concurrent deployments, so perhaps a single file might not be enough etc.

In a more specific scenario, it is easy enough to do this by making your deploy task append f. ex. the timestamp, version, git-hash or what have you into a known file on the server. Or to not delete the applications you deploy and rather upgrade by pointing a symlink. Fabric gives you the tools to solve this easily in many different ways without making any choices that restrict you and that's probably a good place to be.

**Comment by bitprophet** [comment]
Thanks for the feedback, @VarunBatraIT! Unfortunately, what @kaaveland said stands - Fabric is lower level than this, it is used *for* deploys semi often but that is only one of many use cases.

That said, there are other libs out there built on top of Fabric that help with deploy related concerns and one of them may already implement this or be amenable to doing so. I'd look around :)
