### ISSUE TITLE
Python 3.3 support

### ISSUE THREAD

**Issue by pashinin** [fabric/fabric#1050]
As I understood it's not working with Python 3.3 yet. Maybe you can add this support now?

Dependencies:
  `rudolf` - rewritten for python3 - https://github.com/pashinin/rudolf
  `paramiko` - https://github.com/paramiko/paramiko/pull/236

Now have following problems - https://travis-ci.org/pashinin/fabric/builds/17479924

```
Traceback (most recent call last):
File "/home/travis/build/pashinin/fabric/fabric/operations.py", line 408, in put
   mode, local_is_path, temp_dir)
File "/home/travis/build/pashinin/fabric/fabric/sftp.py", line 234, in put
   rattrs = putter(local_path, remote_path)
File "/home/travis/virtualenv/python3.2/src/paramiko/paramiko/sftp_client.py", line 611, in put
   return self.putfo(fl, remotepath, os.stat(localpath).st_size, callback, confirm)
File "/home/travis/virtualenv/python3.2/src/paramiko/paramiko/sftp_client.py", line 578, in putfo
   raise IOError('size mismatch in put! %d != %d' % (s.st_size, size))
IOError: size mismatch in put! 0 != 4
```

**Comment by foxxyz** [comment]
+1! Hope this is close to release!

@pashinin Excellent job on the temporary fork, seems to be executing our tasks just fine.

**Comment by v6** [comment]
Is there a way I can download the fork as a package, or add it as a dev dependency in my requirements.txt file?

**Comment by foxxyz** [comment]
@v6 Here's an example of how added it as a dependency to our requirements.txt file:

```
-e git+git@github.com:pashinin/fabric.git@6783d2f7ad7a449c97cd1ee0df9a2dbc29422fce#egg=Fabric
```

**Comment by v6** [comment]
Cool. I'm hoping to use it with python-vagrant.

**Comment by aronysidoro** [comment]
@v6 or @foxxyz does that work for Python3?

**Comment by 9gix** [comment]
:+1:

**Comment by dan-blanchard** [comment]
> I may use this and other Python 3 related branches when porting chunks of code that don't need a rewrite, but they won't get merged as-is. Thanks!

@bitprophet As many users (such as myself) are just using the fork @pashinin put together, is there any way you could just merge his changes in?  It seems strange to put off Python 3 compatibility till 2.0 when there's a fork that is already Python 3 compatible.

**Comment by troygrosfield** [comment]
I agree with @dan-blanchard.  Many of us have been [waiting quite a long time](https://twitter.com/pyfabric/status/421439766677438464) for "fabric 2.0" which is understandable since open source isn't a full time job for any of us.  However, if there's an alternative that's ready to go then why not leverage it?

People talk about using pyinvoke however, when you go to the main doc page it reads:

> Warning
> While fully usable, Invoke is still pre-1.0 software and has no backwards compatibility guarantees until the 1.0 release occurs! Please make sure to read the changelog carefully anytime you upgrade!

Which prevents me from using it at all. The other issue is there aren't really good alternatives that do what fab does in the python community.  I'm in big support of getting the python 3 branch merged in!

**Comment by v6** [comment]
// , What do you think it'd take to get it sponsored by some companies?

**Comment by troygrosfield** [comment]
Could open up a [kickstarter](https://www.kickstarter.com) project and get it crowd funded, but that would also require @bitprophet to be onboard...

**Comment by v6** [comment]
// , Pfft. Kickstarters are for consumers. Lern ye marketings?

**Comment by troygrosfield** [comment]
@v6 see http://www.django-rest-framework.org/topics/kickstarter-announcement/

**Comment by v6** [comment]
Well, lern ME marketings.

It's been a while since I have felt so happy for correction, Mr. Grosfield.

Wow.

**Comment by aronysidoro** [comment]
@v6 and @troygrosfield there is another site that you could use, Indiegogo.  Here's the link:

https://www.indiegogo.com/


JK... you guys are funny! just had to make light :-)

**Comment by eedeebee** [comment]
I agree with @dan-blanchard too.

**Comment by eirnym** [comment]
I agree with @dan-blanchard  too. :+1:

**Comment by bitprophet** [comment]
Please keep in mind that just because it appears to work in one fork for one use case, does not mean there's no cost to merging. For example, Paramiko recently-ish migrated to 2+3 and months later we're still finding subtle-but-dangerous bugs - it was a severe hit to stability.

Given that Fabric 1 is near EOL and stability is more important than ever, such a change isn't something I am in a huge rush to do. I'm also hoping that the early-adopter folks who want Python 3 will be more willing to give Fabric 2 a shot once it comes out.

This issue is also more exacerbated in projects with spotty test coverage - Fabric's isn't horrible but it's nowhere near comprehensive, and it not being written in a testable fashion means ever getting there is highly unlikely. (Another reason why 2.x is happening.)

**Comment by v6** [comment]
Didn't know that there was a plan for Fabric 2.

**Comment by bitprophet** [comment]
I linked it up above, but I'll link it again more obviously - the fabric roadmap! http://www.fabfile.org/roadmap.html

**Comment by krzysztofp** [comment]
so what's the status here?

**Comment by akaariai** [comment]
I created a branch that passes all tests on Python 3.4. I haven't tested it much in real world usage, but at least basics seem to work OK. Branch at https://github.com/akaariai/fabric/tree/py34 (based on https://github.com/pashinin/fabric/tree/p33).

If there is interest I am willing to work to get it merged into Fabric. I think there is some hope to keep the changes extremely conservative when it comes to not breaking anything in Python2.

**Comment by troygrosfield** [comment]
:+1:

**Comment by glynjackson** [comment]
:+1:  from me :) Fabric is now the only package I use without Python 3 support!

**Comment by akaariai** [comment]
I think I have a bit more work to do, it seems a lot of tests are still disabled by doing a file rename test_foobar -> tes2t_foobar. So, there might actually be still a lot to do.

**Comment by grigi** [comment]
@akaariai What is the chance you think you could release your branch as fabric-py3 on pypi?
@pashinin made it clear he is not going to merge the py3 work into the current fabric, so I'm hoping he doesn't have an issue with it in the short term? Once fabric2 is out we can move all move off fabric-py3?

**Comment by pashinin** [comment]
@grigi I hope my code was useful for some of you, now make it all better (I'm not working on it anymore)

**Comment by grigi** [comment]
@pashinin I'm using it as-is. It works for all my use cases, just want it pushed to pypi to make it easier to use.

**Comment by hjwp** [comment]
@bitprophet -- is there any way we can help with the "official" fabric 2 ?

**Comment by philipn** [comment]
@bitprophet and other core maintainers here: is the current fabric 2 development happening off Github?  If so, is it possible it could be moved here under a development branch?  There are many folks, such as myself, for whom this is the only remaining python 2 package in our infrastructure, and would happily run and improve a dangerously unstable invoke-based fabric rewrite.

**Comment by glynjackson** [comment]
+1 @philipn comment

**Comment by jmagnusson** [comment]
I'd also be willing to try out Fabric 2, if it's in any shape to be tested.

**Comment by kegan** [comment]
+1 @philipn comment.

**Comment by hjwp** [comment]
‎I actually had a dream about Fabric2 being released the other night. Seriously. The announcement email had a crazy embedded comic with a futuristic dinosaur whale thing...

**Comment by bbirand** [comment]
:+1:

**Comment by bitmonk** [comment]
@grigi it sounds like @akaariai still has some concerns with the way the tests pass, maybe it wouldn't be wise to imply to the world that a working and supported python3 fabric exists.  Those of us looped in here can all fork and pin to install from github, though I'm eager to see a fabric that is Invoke-based @bitprophet ! :)

**Comment by bitprophet** [comment]
@bitmonk still working on it actively! an alpha will be out by EOM, for really reals.

Also, I forgot one can lock issues now, so I'm gonna do that here (though I will try and remember to post a note when that alpha goes out, for anybody not following twitter/mailing list/main repo updates).
