### ISSUE TITLE
Error Handling during run, documentation or design change

### ISSUE THREAD

**Issue by acscott** [fabric/fabric#1051]
I'm using fabric 1.8 (python 2.7)  as a Library instead of the fabfile.

When I test for a return code from the return value using this call, python throws an error when there's a network error since its a NetworkError object.  

Maybe in the documentation it could be mentioned to test the return type before reutrn_code?

           with settings(host_string=host, user=USER, 
                         key_filename=KEYFILE, warn_only=True):
              results = run(cmd)

Traceback (most recent call last):
  File "backup.py", line 169, in <module>
    main()
  File "backup.py", line 60, in main
    checkDiskSpace(host,mount_database_disk,THRESHOLD_DISK_USE)
  File "backup.py", line 121, in checkDiskSpace
    if not results.return_code:
AttributeError: type object 'NetworkError' has no attribute 'return_code'

**Comment by bitprophet** [comment]
This doesn't seem right, the current version of `run()` should only ever be returning `_AttributeString` objects, regardless of library vs CLI usage. Closing as can't-reproduce.
