### ISSUE TITLE
fabric/io.py:input_loop busy waiting eats CPU

### ISSUE THREAD

**Issue by mjog** [fabric/fabric#1074]
The implementation of fabric/io.py:input_loop leaves a fair bit to be desired:

1. The select() call has a timeout of 0.0, effectively busy waiting on user input.
2. No attempt is made to use poll/epoll or kqueue/kevent where supported

The resulting busy waiting means that fab sits using a lot more CPU than it really should when a connection is open.

The former is an easy fix, in input_loop():
```
-            r, w, x = select([sys.stdin], [], [], 0.0)
+            r, w, x = select([sys.stdin,chan], [chan], [])
```
This ensures that if any input or output on the SSH connection makes select return, thus freeing up the loop to check chan.exit_status_ready() while waiting forever for user input.

The latter is a bit more involved, but simply means adding checks for functional poll(), epoll(), etc and using the best one found, rather than select().

**Comment by bitprophet** [comment]
99% sure this has changed in the interim to use an 0.1 or 0.01 or similar (& controllable) sleep timer.
