### ISSUE TITLE
Parallel per hosts, serial per single host

### ISSUE THREAD

**Issue by vlastv** [fabric/fabric#1075]
I have very simple script:

```python
from fabric.api import env, execute, parallel

env.hosts = ['web1', 'web2']


def task1():
    pass


def task2():
    pass


@parallel
def deploy():
    execute(task1)
    execute(task2)
```

I expect that it will work in the following sequence:

1. deploy on web1, web2
2. task1 on web1
3. task1 on web2
4. task2 on web1
5. task2 on web2

Ie running tasks should be consistent within a single host, but parallels between all hosts.

But here's what I get in reality:
```
$ fab deploy
[web1] Executing task 'deploy'
[web2] Executing task 'deploy'
[web1] Executing task 'task1'
[web2] Executing task 'task1'
[web1] Executing task 'task1'
[web2] Executing task 'task1'
[web1] Executing task 'task2'
[web2] Executing task 'task2'
[web1] Executing task 'task2'
[web2] Executing task 'task2'

Done.
```
Moreover, that is not what I expected. So also a number of suspicious perform the same task.

What am I doing wrong?

**Comment by kaaveland** [comment]
There's a pretty good explanation of the execution model here on this page and I linked directly to the page concerning how `execute()` works: http://docs.fabfile.org/en/1.10/usage/execution.html#intelligently-executing-tasks-with-execute

In particular, the red warning box explains why you're getting so many calls.

You are asking fabric to run your deploy task in parallell to both your hosts. Deploy consists of executing two other tasks. That can't possibly result in the sequence of actions you expect, by the time the code inside `deploy` runs, fabric has already made parallel processes. 

I think, what you want to do would be something like this:
```python

def task1():
    pass

def task2():
    pass

@parallel
def deploy():
     upload_or_something()
```
And invoke saying `fab deploy task1 task2`. Another option would be to structure it something like this:

```python
# same tasks as before + one more

@runs_once
def supertask():
    with settings(hosts=['web1', 'web2']):
        execute(deploy)
        execute(task1)
        execute(task2)
```
These will both give you the sequence of events you expect. The reason why the last one works is that there is no host-list associated with `supertask`, so it isn't run once per host. But there has to be a host-list for `deploy`, `task1` and `task2` to work.

**Comment by kaaveland** [comment]
This can probably be closed (although there's probably better suggestions on how to do this, but that sort of looks like mailing list / stackoverflow and not issues). Long term, it might be a good idea to issue a warning with the relevant doc-link on nested executes like this, I can't imagine it is common to want the behaviour it exhibits by default.

**Comment by bitprophet** [comment]
FTR, handling nested multi-host executions is a super high level problem for this solution domain.

I've been thinking about whether it makes sense to try and detect accidental instances of this scenario (aka "multiplicative" execution) in v2 where the overall model should be much cleaner...but even then, there's likely no great heuristic to tell "newbie made a mistake" apart from "advanced user doing crazy stuff on purpose".

If a non awful heuristic can be found, a warning (as @kaaveland notes) may be the best solution: make sure newbies see it and that advanced users have the ability to turn it (and only it, not other warnings) off.
