### ISSUE TITLE
Ability to name fabfile.py => Fabfile

### ISSUE THREAD

**Issue by bsandrow** [fabric/fabric#1122]
Is there anything preventing this change? I'm willing to make the changes to the import code to allow the `fabfile.py` to be named `Fabfile` (e.g. use `imp.load_source` rather than `__import__`). I just don't want to waste my time if there are good reasons not to go this way (or strong opinions that would prevent such a Pull Request from being accepted).

I've taken a quick look at the import code, and I don't think that there are any major blockages to the change. It looks like `imp.load_source` is deprecated in Python3, but still works as of Python 3.3.5 and [will eventually have a replacement in `importlib`](http://bugs.python.org/msg158086).

Why? Well, this is a standard naming convention for build-type files (e.g. `Makefile`, `Rakefile`, `Dockerfile`, `Vagrantfile`, `Gruntfile`, etc). It makes sense (to me at least) that Fabric have the ability to follow this convention as well.

**Comment by mattvonrocketstein** [comment]
Any word on this?

**Comment by bitprophet** [comment]
The groundwork for this exists in 2.x, as Invoke allows user-configurable default task-collection names: http://docs.pyinvoke.org/en/1.1/concepts/loading.html#configuring-loading

However there are a couple drawbacks which still exist; I'm spitballing here but the gist should be accurate:

- The biggest problem is simply that task loading is couched as "use the Python import system", which…doesn't like loading files which do not end in `.py`! (IIRC this was the case in 1.x as well, I don't remember if/when we ever used literal `exec`, but it's been a while)
  - This should be work-around-able by subclassing Loader to taste, all of the importing stuff ought to be self-contained therein. I'm hoping there aren't other parts of the code which care overmuch about importing vs just having a module object in hand.
  - Then one could specify that subclass in a custom Program instance, though you'd end up having to overwrite the default-installed `fab` with a pointer to that custom Program if you really wanted it to "be `fab`". (Or simply install as some other local binary name, which is what most folks do when they need custom program behavior.)
- A smaller one is that some of the config system is predicated on knowing where the task collection is, causing a bit of a chicken/egg situation when it comes to configuring the load process on a per-project manner (though configuring it at the system or user level should work fine).

I'm going to close this for now as "users who seriously care now have some avenues open to them", but not going to lock or anything:

- If a whole bunch of folks show up really wanting the `Blahfile`-with-no-suffix style, then we can reconsider whether core should support it natively somehow, though I'm skeptical that it'd be worthwhile
- If my above spitballing has serious issues (i.e. if the code makes unnecessary assumptions about importing vs whatever's needed to load a non `.py` file) I'd be fine considering such things as fixable bugs; the intent of the 2.x/invoke line is to empower users to do things without core having to merge every single new idea or functionality. So if the classes we're publishing don't suffice, they need fixing.
