### ISSUE TITLE
Setting Shell_Env before running prefix

### ISSUE THREAD

**Issue by warsamebashir** [fabric/fabric#1135]
I would like to run and set my shell_env before the execution of the prefix. It looks like my shell env is never set in the example below:

````python

with shell_env(ENV1="TEST"):
    with prefix(". myapp"):
          run("echo $ENV2")
````

I expected my shell_env to be set but my prefix runs first. I know this because the prefix commands uses the environment variables and will prompt for them if not set?

**Comment by bitprophet** [comment]
Yea offhand I don't see how this is anything other than an oversight in the implementation of `shell_env`. And since it's just sugar, it shouldn't seriously break things for anybody in a way they cannot fix themselves.

**Comment by bitprophet** [comment]
Closing to roll into #1241, thanks @cmattoon!
