### ISSUE TITLE
Allow for pre-connection hooks

### ISSUE THREAD

**Issue by ronelliott** [fabric/fabric#1142]
A way to run code before a connection is created would allow fabric to be more easily integrated into configurations using port knocking / fwknop.

**Comment by bitprophet** [comment]
As of 2.0 this could be done in userland by subclassing `Connection` and extending `Connection.open`, so at a basic API/object level, this is "done". An off the cuff example:

``` python
```

In terms of integrating user-created subclasses into the parts of Fabric core which instantiate Connections automatically (now and in the future as we port more of v1), that's still pending, but would probably not be too difficult & has precedent elsewhere in the codebase. I don't have time to hunt down the ticket(s) for that feature but as it's orthogonal, this can be closed now I believe.
