### ISSUE TITLE
Hanging fabric

### ISSUE THREAD

**Issue by ghost** [fabric/fabric#1162]
I am new to fabric and I am running into sporadic hanging issue with fabric. Sometimes it hangs on a certain run command, other times it's OK, then hangs on another run command, I have yet to run through the whole fabfile successfully. I have tried upgrading and downgrading fabric and the paramiko libraries, but I have had no success.  I have run the commands manually outside of fabric and they seem to work just fine and I have searched the internet already, but have not found anything that solved my issue.

Current Environment:

Running fabric on a ubuntu box running version 12.0.4, connecting to AIX (unix) hosts.

Fabric Version Info:

Fabric 1.9.0
Paramiko 1.14.0

My FabFile:

import logging
logging.basicConfig(level=logging.DEBUG)

from fabric.api import *
from fabric.contrib.files import exists

env.roledefs = {
   'DEVSIT':['cd200','cd015','cd006','cd004']
}

env.warn_only = True

env.user = 'santosa'
env.key_filename = '/root/.ssh/id_rsa'

def start_middleware():
    run('/usr/local/bin/sudo -iu wasadm /ops/scripts/was/startwas.sh')
    run('/usr/local/bin/sudo -iu webadm /ops/scripts/was/startwas.sh')
    run('/usr/local/bin/sudo -iu webadm /ops/scripts/webadm/startce.sh')
    run('/usr/local/bin/sudo -iu fnsw /ops/scripts/webadm/startpe.sh')
    run('/usr/local/bin/sudo -iu wmadmin /ops/scripts/webmethods/wmdev/start_dev.sh')

Command I am running:

fab --show=debug -R DEVSIT start_middleware

Some output from command:

DEBUG:paramiko.transport:[chan 11] EOF sent (11)

Warning: run() received nonzero return code 1 while executing '/usr/local/bin/sudo -iu all_adm /swift/alliance/rls/bin/saa_bootstrap start'!

None

[cdsd200] run: /bin/bash -l -c "/usr/local/bin/sudo -iu all_adm /swift/alliance/rls/bin/saa_system --start operational"
DEBUG:paramiko.transport:[chan 12] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 12] Max packet out: 32768 bytes
INFO:paramiko.transport:Secsh channel 12 opened.
DEBUG:paramiko.transport:[chan 12] Sesch channel 12 request ok
DEBUG:paramiko.transport:[chan 12] Sesch channel 12 request ok
[cdsd200] out: sudo: unknown user: all_adm
[cdsd200] out: DEBUG:paramiko.transport:[chan 12] EOF received (12)
DEBUG:paramiko.transport:[chan 12] EOF sent (12)
sudo: unable to initialize policy plugin
[cdsd200] out:

Warning: run() received nonzero return code 1 while executing '/usr/local/bin/sudo -iu all_adm /swift/alliance/rls/bin/saa_system --start operational'!

None

[cdsd200] run: /bin/bash -l -c "/usr/local/bin/sudo -iu wmadmin /ops/scripts/webmethods/wmdev/start_dev.sh"
DEBUG:paramiko.transport:[chan 13] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 13] Max packet out: 32768 bytes
INFO:paramiko.transport:Secsh channel 13 opened.
DEBUG:paramiko.transport:[chan 13] Sesch channel 13 request ok

This time it got stuck on "[cdsd200] run: /bin/bash -l -c "/usr/local/bin/sudo -iu wmadmin /ops/scripts/webmethods/wmdev/start_dev.sh" but sometimes it passes this and gets stuck somewhere else.

**Comment by birchb1024** [comment]
Hi,

We're seeing the same thing. Running fabric Fabric 1.9.0 Paramiko 1.14.0 on Centos6.6 connecting to AIX 7.1. The AIX end hangs when we have ```shell=False```. We see a lot of zombie sshd processes with pty. One curious thing, it works sometimes, but rarely.
The cure for us was to use:

    run("command", shell=False, pty=False)

**Comment by birchb1024** [comment]
However doing the same thing from paramiko directly works fine.
Code below. So it's a Fabric bug somewhere.....

```python
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

for machine in ['linuxbox', 'hpuxbox', 'aixbox']:
    ssh.connect(machine, username='me', timeout=5)
    stdin, stdout, stderr = ssh.exec_command('uname -a', get_pty=False)
    print stdout.read()
    print stderr.read()
```

**Comment by birchb1024** [comment]
Still have the same issue.  Python 2.6.6, Fabric 1.10.1, Paramiko 1.15.2, RedHat 6.6 to AIX 7.1.  Another workaround is to add a sleep after the command:

```run('/some/command arg ; /bin/sleep 1')```

Which would indicate it's a timing issue in Fabric.
