### ISSUE TITLE
fabric.context_managers.hide 'status' does not hide "Done."

### ISSUE THREAD

**Issue by HelloGrayson** [fabric/fabric#1163]
You would expect the following command not to have "Done." in the end.

``` python
from fabric.api import task
from fabric.context_managers import hide

@task
def some_command():
    with hide('status'):
        print "hi!"
```

Instead you have to do the following to get it to work correctly:

``` python
import fabric
from fabric.api import task

@task
def some_command():
    fabric.state.output.status = False
    print "hi!"
```

This is less than ideal.

**Comment by clayg** [comment]
I assumed this would be the answer, but it's not immediately expected - probably everyone tries to hide the `status` messages *inside* the task only to discover `Done.` is still printed.

So what's the recommended solution?

Obviously running `fab my_task --hide status` prevents `Done.` from being printed - is there anyway to get up in global state early enough to prevent the output?
