### ISSUE TITLE
Use Proper Exceptions, not sys.exit()

### ISSUE THREAD

**Issue by TaylorSMarks** [fabric/fabric#1181]
Fabric currently offers two possibilities for error handling:
1 - You can set it to "warn only", where they'll print out a statement and not give the user's code any proper way of handling it (one would have to create their own sys.out to catch the message, then decipher it to decide what to do).
2 - You can leave it on the default settings, where it uses sys.exit() which isn't a proper exception (deriving from Exception) but instead an unrelated special exception (derived from BaseException) which really shouldn't be used in this case.

Neither is even slightly Pythonic. Create proper exception types and throw those. If an exception occurs, believe it or not, I want it to be able to handle it, not to either ignore and log it or ignore it and crash.

As a work around, I have to instead catch SystemExit, which really should only be used with some kind of end-user consent (IE, the user typed exit() into the interactive prompt, or was given a raw_input with a choice to end the program and they decided that they wanted to do so), and really shouldn't ever need to be caught.

**Comment by longquanzheng** [comment]
+1
