### ISSUE TITLE
Please don't rewrite fabric for version 2.0/python 3

### ISSUE THREAD

**Issue by joekiller** [fabric/fabric#1185]
I've read that fabric 2.0 might be a ground up rewrite and I hope this isn't quite true.  I do understand the virtues of many arguments ie:
- http://blog.codinghorror.com/when-understanding-means-rewriting/
- http://onstartups.com/tabid/3339/bid/2596/Why-You-Should-Almost-Never-Rewrite-Your-Software.aspx
- and of course: http://www.joelonsoftware.com/articles/fog0000000069.html

I believe you got paramiko going without a rewrite but could be mistaken.  I guess all I'm saying is consider all the edge cases that have been fixed over time and if a rewrite can really encapsulate it versus is the core code absolutely broken.  I know that boto successfully updated to support 2.7 and 3 at the same time.

It may be best to just run the tests in python 3 and see what breaks first and go from there.  

Anyway, I just wanted to register my concern.

**Comment by rodrigc** [comment]
If you want to try Fabric with Python 3, you may want to look at this fork:
https://github.com/fabric/fabric/issues/1378

It does seem to work.  @bitprophet is not accepting these changes though, due to the Fabric 2.0 rewrite.
