### ISSUE TITLE
lcd not working on Windows (when pointing to different volume)

### ISSUE THREAD

**Issue by jamespacileo** [fabric/fabric#1199]
from fabric.api import lcd, local, env

    with lcd("E:/"):
        print env.lcwd
        # print E:/
        local("dir")
        # points to current folder in C:/

Pointing to same drive works fine though.

**Comment by kaaveland** [comment]
Never commented back, but some research (and testing this on an old windows machine I found lying around) suggests that the magic words to first go to the correct drive in cmd.exe would be:
```
E:
cd wherever
```

**Comment by gtback** [comment]
You can also use `cd /d E:`
