### ISSUE TITLE
Unable to use fabric after enabling Multi factor auth SSH

### ISSUE THREAD

**Issue by owais** [fabric/fabric#1202]
We've enabled multi-factor auth using google-authenticator library on our ssh. Ever since fabric has not been able to log into the servers. 

The desired behaviour is for fabric to ask us for the token every time it logs into the server but it just keeps sitting there.

Using ssh:

```
>>> ssh myuser@myserver
Authenticated with partial success.
Verification code: 
```

After entering the code, ssh drops us in the server shell.

Using fabric:

```
>> fab myserver deploy
[localhost] Executing task 'staging'
[staging.thevetted.net] Executing task 'deploy'
[staging.thevetted.net] Executing task 'update_code'
[staging.thevetted.net] run: git fetch origin
No handlers could be found for logger "paramiko.transport"
```

and then fabric hangs in there indefinitely. My guess is that ssh asks for the token there but fabric fails to show that prompt to the user and keep waiting.

**Comment by bitprophet** [comment]
This works-for-me when using the functionality in Paramiko from merging paramiko/paramiko#467 - as long as my pubkey is working OK via Fabric, Paramiko bubbles up a prompt for the keyboard-interactive 2FA step, and it seems to Just Work™.
