### ISSUE TITLE
should allow case insensitive match in fabric.contrib.files.contains()

### ISSUE THREAD

**Issue by xoul** [fabric/fabric#1203]
Hi,
maybe fabric.contrib.files.contains() within fabric/contrib/files.py should allow case insensitive match.

Since contains() uses egrep, where should be a way to pass it a "-i". 
Maybe a case_insensitive defaulting to false can be added:

fabric.contrib.files.contains(filename, text, exact=False, use_sudo=False, escape=True, shell=False, case_insensitive=False)

**Comment by bitprophet** [comment]
Rolling into #1240
