### ISSUE TITLE
sudo commands (e.g. /etc/init.d/networking restart) can hang if TCP session resets (due to duplicate IP address)

### ISSUE THREAD

**Issue by stannous** [fabric/fabric#1205]
Hello,

(Using Fabric 1.8.3 and paramiko 1.10.1 on debian wheezy linux 3.2.60-1 machines.)

We have a case where we were getting tests just hanging on "sudo" commands (mostly /etc/init.d/networking restart).  Granted, it may seem foolish to do a networking restart when you are running your tests over eth0 but it's usually not a problem because the fabric/paramiko session (and channel)  keeps working just fine.   

But when there happens to be a duplicate IP address on the LAN, the device under test's
eth0 interface comes up, handles getting its IP address via DHCP just fine. It then ARPs for the device it was talking to (where we run our nose tests that use fabric) and receives an ARP response.    

It then receives another ARP response (from the duplicate IP)
with a different MAC address.  Once this happens, the server running
the test (presumably, the debian linux (v 3.2.60-1) sends a TCP reset packet
to the device under test and this gets TCP reset sent back in response.

While all these TCP resets are exchanged, the originating fabric session sudo command just
hangs.   I added some debug statements to the "while True:" loop in operations.py
and it simply prints out a timestamp continuously increasing (the sleep timer there
is the default 0.01 seconds).

My question is this: shouldn't fabric somehow know that the underlying (paramiko?) 
ssh session is broken when the TCP resets get exchanged?   It seems to keep 
spinning in the while:True loop.     I realize this is a corner case and the duplicate IP 
address should be removed.....but, one would expect the sudo command to produce an
error (like "Socket error...lost connection" or something...not just hang).

I initiate the test by cutting and pasting the following:
(keep in mind you have to have a second server with the same IP address
as the server running this test....the "dut1" below is on the same LAN.)
Everything works just fine...it's just the presence of a duplicate IP device
on the LAN that hangs the sudo command (service networking restart) 
where an ARP is involved that effects the underlying TCP session:

ipython

hosts = "testid@dut1"
import fabric
from fabric.operations import run, sudo
from fabric.tasks import execute
from fabric.context_managers import hide
from fabric.context_managers import settings

reload = lambda: sudo('/etc/init.d/networking restart')
mydate = lambda: sudo('date')
execute(mydate, hosts=hosts)

this next command will hang indefinitely if there is a duplicate IP address 

execute(reload, hosts=hosts)

even the following doesn't seem to help as we still get 
the command to hang and no retries or timeouts occur
with settings(hide(timeout=10, connection_attempts=5):
     execute(_date, hosts=hosts)

**Comment by rudeb0t** [comment]
+1 for this. I have a command which does network restart:

```
sudo('systemctl restart network')
```

Command hangs and never finishes, networking is damaged and I had to reboot via IPMI to get it back online. I can use SSH and then issue the same command without any problems though.

**Comment by kaaveland** [comment]
I can reproduce this quite easily. I run a long-running command (such as `while true; do sleep 1; echo hi; done`), then I go off from VPN/network so that I no longer have access to the server. paramiko does not raise any errors in this case, instead we hang in `fabric.io.OutputLooper.loop` on `bytelist = self.read_func(self.read_size)`. This eventually goes into `paramiko.buffered_pipe.BufferedPipe.read` but I'm not sure where this goes wrong (I'm not at all familiar with paramiko). Either way, I don't think it is right to attempt to solve this in fabric-land.

**Comment by kaaveland** [comment]
I think this looks like https://github.com/paramiko/paramiko/issues/515

**Comment by kaaveland** [comment]
OTOH if I do this with just a plain socket from socket.py, it hangs forever in `recv()` after I kill my VPN connection. This is probably a different problem seeing as `TCP RST` packets will never reach me, whereas in the description above `TCP RST` packets should arrive just fine. Completely not sure here.

**Comment by stannous** [comment]
No longer interested.
