### ISSUE TITLE
Imports, ImportError and sys.path

### ISSUE THREAD

**Issue by mixman** [fabric/fabric#1207]
I ran into an ImportError due different PYTHONPATH's, decided to look into the matter, and wanted your input on expectations -- should the last case work with Fabric, or is it user responsibility to mend paths? Example code in https://github.com/mixman/fabpath (checkout; 'bash maybe.bash') and output:

#### fabfile.py
```
from fabric.api import task

@task
def hello():
    from project.idea import Implementation
```

#### bash maybe.bash
```
No ImportError due 'python -m' adding the current directory (='') to sys.path:
python -m fabric hello

Done.

No ImportError because we add current path to sys.path using PYTHONPATH
PYTHONPATH= fab hello

Done.

No ImportError, because directory *of script being run* is automatically added to sys.path
python hello.py

ImportError follows during *task execution* because current directory is not in sys.path.
The current directory is not in sys.path, as 'fab' is the script being run, and its path is there.
The import would work outside the function. Only affects runtime imports.
fab hello
Traceback (most recent call last):
  File "/opt/fabpath/venv/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/opt/fabpath/venv/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/opt/fabpath/venv/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/opt/fabpath/fabfile.py", line 5, in hello
    from project.idea import Implementation
ImportError: No module named project.idea
```

References: #1004

**Comment by deronnax** [comment]
I ran into it, and that's very annoying. When is supposed to come version 2 ?

**Comment by bitprophet** [comment]
At present the Invoke loader (which will load fabfiles in Fabric 2) does add the parent directory of the tasks file to `sys.path` and *does not* remove it afterwards, so we should be good once 2.0 hits the streets. (It is in development right now.)

Furthermore, the loading system is set up to be more replaceable/swappable, so it will be possible to have different loading "behaviors" if users need it.

**Comment by morgante** [comment]
Is there even a temporary workaround for this?

As of now, it's making it impossible to work with non-core packages and Fabric.

**Comment by bitprophet** [comment]
That seems pretty unlikely, @morgante, as myself and many others routinely import non-stdlib packages into fabfile code on recent versions of Fab. There might be something specific in your environment that's exacerbating things though :(

**Comment by morgante** [comment]
@bitprophet But are those packages globally installed or inside a virtualenv?

I did find a work around though, by adding this to my fabfile:
```
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), ".venv/lib/python3.4/site-packages"))
```
