### ISSUE TITLE
Fabric 2.0 Development Branch?

### ISSUE THREAD

**Issue by FlipperPA** [fabric/fabric#1224]
I scanned through the issues, and didn't see anything, but I'm on a tiny screen so sorry if this is a dupe.

Any chance we can get a fabric-2.0-dev branch pushed to GitHub? Our team would like to pitch in on helping convert to Python 3. We've done this for several other packages as well.

**Comment by rodrigc** [comment]
@FlipperPA: If you want to try Fabric-1.10 under Python 3, then
use this fork:

https://github.com/fabric/fabric/issues/1378

I've tried it and it works.
The patches in this fork are not being accepted
by @bitprophet because they break compatibility with
Pytho 2.5, and also because Fabric 2.0 (which is a major rewrite)
will support Python 3.

However, if you are in a bind and need to try existing Fabric
under Python 3, try the above fork.

**Comment by lgunsch** [comment]
Is there any updates on a 2.x branch? I'd like to start helping out if possible, and begin using Fabric on Python 3 projects.

**Comment by FlipperPA** [comment]
I've been using invoke and paramiko together which have served my needs in a Python 3 world. Have you checked them out? http://www.pyinvoke.org/ It seems that bitprophet was moving in this direction, but I won't speak for him.

**Comment by rodrigc** [comment]
@lgunsch @FlipperPA If you want to use Fabric with Python 3, then you should use the Fabric3 port by @mathiasertl : https://pypi.python.org/pypi/Fabric3

**Comment by lgunsch** [comment]
I have used Invoke on a few Python 3 projects already for simple tasks. I was going to try out Fabric 2 for more of a continuous-deployment solution.

**Comment by bitprophet** [comment]
Still working exclusively on Fabric 2 related stuff on my OSS days (as usual, much of the work is in Invoke itself). Really hoping to get the alpha out sooner instead of later, at long last. Been using it in bits & pieces at my dayjob!

**Comment by toabi** [comment]
@bitprophet Do you have a time estimate for a Fabric 2 Alpha release?

**Comment by bitprophet** [comment]
@toabi I've been using it even more at work lately and my "required for alpha" todo list has been shrinking rapidly. I'm clearly Bad at Estimates™ but I've been hoping to take the wraps off this month sometime. Time will tell.
