### ISSUE TITLE
Add an option to sudo with a login shell

### ISSUE THREAD

**Issue by gauravjuvekar** [fabric/fabric#1248]
Add an option to `sudo -i ...`

Usecase

````
Remote users: admin <-- sshed to by fabric
                |
                V
             sudo to 
                |
                V
            djangouser
````
Where djangouser hosts all django apps in virtualenvs

Hence, it's necessary to get a login shell to djangouser since it is easier to work with virtual envs this way.

This also addresses #1013 

-------
This could probably implemented with a `login_shell` option to sudo and a `with settings(login_shell=True):` wrapper

Example #1247

**Comment by bitprophet** [comment]
There's a bunch of open tickets about this type of thing, can you search and link some of them? I think some of them may even be PRs.

**Comment by gauravjuvekar** [comment]
Related
#503 
Weakly related
#60 
Mostly unrelated
#848

**Comment by ploxiln** [comment]
I think you could use the sudo_prefix setting to achieve this
http://docs.fabfile.org/en/1.12/usage/env.html#sudo-prefix

```python
env.sudo_prefix = "sudo -S -p '%(sudo_prompt)s' -i " % env
```

**Comment by bitprophet** [comment]
Think we can close this in favor of the others linked.
