### ISSUE TITLE
passing agruments through execute does not work

### ISSUE THREAD

**Issue by ror6ax** [fabric/fabric#1256]
```
def sometask(arument):
    pass
def job(taskname=None):
    env.hosts = open('hosts_file', 'r').readlines()
    execute(taskname)
```

When running `fab job:sometask:argument` I get `Fatal error: 'sometask:argument' is not callable or a valid task name`.

Please advice or confirm so I would work on a patch.
Thanks.

**Comment by ror6ax** [comment]
@bitprophet Can you please specify if this was in the design in the first place?

**Comment by ror6ax** [comment]
Hi, any update on this?

**Comment by bitprophet** [comment]
You may need to re-read the CLI docs more closely, there should only be one colon, and if you want to pass args into the being-executed task you need to mirror them in the top level task (or just use splats), e.g.:

``` python
def job(taskname=None, *args):
    execute(taskname, *args)
```

then if called like this, for example:

```
$ fab job:mytaskname,someargvalue
```

would be the equivalent of doing this:

``` python
mytaskname('someargvalue')
```

If you need more help after this, please see IRC or the mailing list, those will get more people helping you faster. Thanks!

**Comment by ror6ax** [comment]
Thanks for help!
