### ISSUE TITLE
Add build dependency check

### ISSUE THREAD

**Issue by coolplay** [fabric/fabric#1259]
Fabric is a wonderful tool for task execution and deployment. I am just wondering if it is possible to add some build tool functionality, like ``Program('hello.c')`` in Scons. Thus I do not need to compile up-to-date executables again and again.

**Comment by bitprophet** [comment]
I'd put any feedback you have into pyinvoke/invoke#100 which is where this kind of thing will go if we do decide to implement it. (Invoke is the "local tasks / build functionality" component of fabric 2.x.) Thanks!
