### ISSUE TITLE
 "env.key_filename" not work

### ISSUE THREAD

**Issue by csin2009** [fabric/fabric#1268]
from fabric import *
from fabric.api import *

env.host_string = '192.168.1.100'
env.key_filename = "~/.ssh/id_rsa"

@task
def check_cinstall():
    run("uname -a")
execute(check_cinstall)

the output is ：

$python fabfile.py
[192.168.1.100] run: uname -a
[192.168.1.100] Login password for 'root': 

why need input password， can i do something to Skip the input password...  

$fab --version

Fabric 1.10.1
Paramiko 1.15.2

$cat /etc/redhat-release 
CentOS release 6.3 (Final)

$uname -r 
2.6.32-279.el6.x86_64

$python --version
Python 2.6.6

**Comment by bitprophet** [comment]
If it's not clearly a bug, please ask the mailing list first, thanks!
