### ISSUE TITLE
Depend on a release of Paramiko

### ISSUE THREAD

**Issue by gdmello** [fabric/fabric#1275]
Hi,

Since, yesterday, fabric has failed on our team city builds, with this error -

```python
 Traceback (most recent call last):
  File "/usr/local/bin/fab", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
 pkg_resources.DistributionNotFound: ecdsa
```
Since we have no explicit dependency on ecdsa, I looked into fabrics requirements and was surprised to see fabric depends on a development version of Paramiko (which depends on ecdsa as I later found out). It would be really helpful to have fabric depend on a released version of Paramiko as opposed to the master.

Is there a plan for this?

Thanks!

**Comment by kbrownlees** [comment]
The packaged version of fabric depends on a released paramiko (from setup.py):
```
if sys.version_info[:2] < (2, 6):
    install_requires=['paramiko>=1.10,<1.13']
else:
    install_requires=['paramiko>=1.10']
```
the requirements.txt states:
> # These requirements are for DEVELOPMENT ONLY!

I assume there is some history which would explain why it is setup like this..

**Comment by gdmello** [comment]
Good spot @kbrownlees !
I'll close the issue.
