### ISSUE TITLE
Additional roledefs keys beyond 'hosts' not loading into env

### ISSUE THREAD

**Issue by fxer** [fabric/fabric#1276]
This snippet from [the docs](http://docs.fabfile.org/en/latest/usage/execution.html) doesn't make the example keys 'foo' available to the user via env, only the 'hosts' key is subsequently loaded by Fabric (into env.hosts)
```
from fabric.api import env

env.roledefs = {
    'web': {
        'hosts': ['www1', 'www2', 'www3'],
        'foo': 'bar'
    },
    'dns': {
        'hosts': ['ns1', 'ns2'],
        'foo': 'baz'
    }
}
```
Documented further on [this stackoverlow question](http://stackoverflow.com/questions/25813995/fabric-env-roledefs-not-acting-as-expected)

**Comment by henryon** [comment]
you can use below example as configure file , then add some  internal function to handle  fabfiles.py

like: list.db
interface|ip|password|role....
hope it will work for you.

**Comment by lundberg** [comment]
There are several env keys used by fabric to determine which host(s) to connect to for each session, i.e. roles, effective_roles, hosts, host_string. And of course decorators as well.

That said, the roledefs is only a name mapping for grouping hosts, not necessary merged into env.hosts.

Defining the roledefs as a dict helps you organize other custom settings, next to hosts, that are role specific. You can access them via full env path, i.e. env.roledefs.web.foo

**Comment by fxer** [comment]
env.roledefs.web.foo produces the error: `AttributeError: 'dict' object has no attribute 'web'`

I mean you could access it like a regular dict, env.roledefs['web']['foo'] but then I don't see why this functionality exists at all in Fabric, it's just a plain dict. It seems like this feature was implemented for a more useful reason?

**Comment by lundberg** [comment]
Sorry, you're right, you have to access it like you say. 

Currently theres no other reason than allowing you to group more role settings next to hosts.
But, when milestone 1.11 is released and #1092 exists, then it makes it more sense.

Also #1088 is part of 1.11 which is similar to what your describing/expecting. But I haven't found a nice way, as i said, to implement merging of roledefs yet. Only proof-of-cocept in fork using "ugly" deep monkey-patching.

**Comment by fxer** [comment]
Ah alright that makes, I was beating my head against the wall thinking I was missing something :) Those referenced issue numbers look like they will help quite a bit whenever they roll. Thanks Jonas!

**Comment by chaimpeck** [comment]
This is confusing and I think it should be noted in the documentation that these additional variables are not accessible outside of the roledefs.

**Comment by wang178743010** [comment]
what

**Comment by kynan** [comment]
@bitprophet Why has this been closed? The behavior of additional roledef keys hasn't changed, so is this a "won't fix"?
