### ISSUE TITLE
Install error on Android when using 'pip install' .

### ISSUE THREAD

**Issue by nethomas1968** [fabric/fabric#1278]
"pip install pycrypto" fails on my Android phone.
I have Python2.7 installed, along with Twisted module, and Kivy.

But, Twisted wants to use Crypto stuff, hence wanting to install PyCrypto.
But, it won't install, error is:

raise RuntimeError("chmod error")
at line 273 in cache/build/PyCrypto/setup.py .

Any ideas?

Regards

Nick

**Comment by bitprophet** [comment]
Have you asked the PyCrypto folks about this? From the info present it doesn't seem like it's a problem on Fabric or Paramiko's end. I've never really encountered anybody using these tools on Android but it doesn't mean it shouldn't work, necessarily.

Please comment if you find something that indicates this is on Fabric's end and we can reopen :) thanks!
