### ISSUE TITLE
`abort()` with `output.stderr = True` still ignore the error output

### ISSUE THREAD

**Issue by dreampuf** [fabric/fabric#1284]
https://github.com/fabric/fabric/blob/master/fabric/utils.py#L347

```
    if func is abort:
        if stdout and not fabric.state.output.stdout:
            message += _format_error_output("Standard output", stdout)
        if stderr and not fabric.state.output.stderr:
            message += _format_error_output("Standard error", stderr)
```

Is this by design ?

**Comment by bitprophet** [comment]
Unless I am missing your question, you may be misunderstanding what this code does. It makes sure that in the event of an abort, if the user was configuring Fabric to hide an IO stream, said IO stream is printed explicitly as part of the abort process.

This way, no matter how the output settings were configured, stdout and stderr always get printed somehow, during an abort.
