### ISSUE TITLE
Monitor files for change and execute tasks using inotify (like inotifywait)

### ISSUE THREAD

**Issue by FedericoCeratto** [fabric/fabric#1295]
It would be handy if fabric had a helper to detect file changes (typically source code files being written/closed) and execute tasks in a loop (e.g. run unit tests, compile, deploy...)

A simple library like inotifyx should do the trick.

**Comment by FedericoCeratto** [comment]
Here's a simple example:
https://gist.github.com/FedericoCeratto/29cea5478e67908b6e2d

**Comment by bitprophet** [comment]
I feel like this is probably feature creep, I certainly wouldn't want to require something like `watchdog` (which is platform-agnostic; inotifyx seems Linux only?) and it feels like it'd be pretty easy for users to write their own 'meta' watch tasks and distribute those using normal Python package channels.

That said, I could see us potentially adding a contrib-style such function to the `patchwork` lib once it becomes a real thing post Fabric 2.x.

**Comment by FedericoCeratto** [comment]
Reacting to file changes seems to be relatively common in build/deploy tools - however - I agree with you: I wouldn't add a hard dependency on any library. The function could simply detect if it can run and print out a warning message otherwise.

**Comment by bitprophet** [comment]
This could also tie in with pyinvoke/invoke#100, insofar as both sort of want a generic api for "should a task run". (Though, not identical, that ticket is "somebody explicitly told me to run - should I really?" and this is "trigger runs based on criteria, with no explicit human request besides whatever started a watcher".)

**Comment by bitprophet** [comment]
I put a basic example of this sort of thing into an Invocations module (split out from a per-project tasks file), https://github.com/pyinvoke/invocations/blob/master/invocations/watch.py in the recentish past. Folks should submit ideas or PRs for this functionality over in that repo from now on :) (Re: Fabric, this means it'd be primarily useful once v2 is in the wild, or for folks who only need the Invoke side of things.)
