### ISSUE TITLE
Naming Collision with Twitter Fabric

### ISSUE THREAD

**Issue by baweaver** [fabric/fabric#1299]
https://get.fabric.io/

Apparently Twitter didn't do their due diligence in naming things. This is going to cause some nasty headaches later.

**Comment by bitprophet** [comment]
Yes, I noticed this. sadly there's nothing we can do about it, especially since we have significant prior art :( Please do comment if you had specific thoughts, but it's still not worth "rebranding" given our brand is strong within the namespace of Python projects :)

**Comment by baweaver** [comment]
Yeah, honestly I think these companies should be doing their homework more. Google did it with Go, Apple with Swift.

The only saving grace on this one is that they're completely different platforms :/

I'm trying to get Twitter to answer on that one but I've gotten radio silence so far.

**Comment by bitprophet** [comment]
I doubt they're interested in a dialogue; first, the "different problem domains / platforms / namespaces" argument is technically valid, and also, they're a big company which has clearly put technical/marketing/etc hours into the name, and we're "just" a volunteer project. Doesn't usually work out for the latter party in a dispute.

Really appreciate you reaching out to them though, let me know if you need anything from me.
