### ISSUE TITLE
stderr and stdout incorrectly combined when pty=True

### ISSUE THREAD

**Issue by Semyazz** [fabric/fabric#1322]
I'm using the following settings to execute commands on the remote machine

    run("cat /xyz", pty=True, combine_stderr=False)

and as a result I see

    ExitCode: 1
    Failed: True
    Succeeded: False
    stderr: 
    stdout: cat: /xyz: No such file or directory

Is there a way to make it work? With `pty=False` everything works fine, but I need `pty=True` to make sudo work on some machines where I cannot modify the configuration. Is it possible to correctly split `stderr` and `stdout` when `pty` is set to `True`?

**Comment by fgimian** [comment]
To be honest, I don't believe this is possible.  Happy for others to chime in though :smile:

**Comment by bitprophet** [comment]
They are, in fact, *correctly* combined when pty=True :( ptys - generally, not just for us - specifically exhibit a single output stream. See http://docs.fabfile.org/en/1.10/usage/interactivity.html?highlight=pty#combining-the-two e.g.:

> As a final note, keep in mind that use of pseudo-terminals effectively implies combining stdout and stderr – in much the same way as the combine_stderr setting does. This is because a terminal device naturally sends both stdout and stderr to the same place – the user’s display – thus making it impossible to differentiate between them.
