### ISSUE TITLE
Doc enhancement for fabric.operations.get mode kwarg

### ISSUE THREAD

**Issue by mjmare** [fabric/fabric#1325]
The docs indicate that "Alternately, you may use the mode kwarg to specify an exact mode, in the same vein as os.chmod or the Unix chmod command."
The docs should point out that a four-digit mode mask must be provided. Three-digit mask or letter mask (like u+x) are not allowed or yield the wrong result, whereas the chmod command does allow these

**Comment by bitprophet** [comment]
Sounds like maybe we want to just drop the "or the Unix chmod command" part, since `os.chmod` does seem to only accept the 4-digit numeric value. Sound good?

**Comment by mjmare** [comment]
That's OK, though you might want to indicate that a 4-digit value is expected. Maybe with an example.

**Comment by bitprophet** [comment]
Fair.
