### ISSUE TITLE
Documentation - Fabric 8 beginners guide

### ISSUE THREAD

**Issue by raghunila** [fabric/fabric#1328]
Hello Fabric 8 dev,
My apologies, since i didn't find any forms where I can ask below question.
Is there any book or material that mention step by step instruction to create container, profile, feature and modules. And How all these work together?

thanks in advance,

**Comment by jbub** [comment]
Hello i think you are in the wrong repository :) Maybe you wanted https://github.com/fabric8io/fabric8 ?
