### ISSUE TITLE
fabric hangs while excuting remote bash script

### ISSUE THREAD

**Issue by eromoe** [fabric/fabric#1330]
I have a bash script named `ssadmin.sh`, it manages another script `sscounter.sh` .
I am using fabric to excute `ssadmin.sh`.

Without `pty=False`:

```
def ts1():
    with settings(warn_only=True):
        run("chmod 775 %s" % 'ssadmin.sh')
        run("%s start" % 'ssadmin.sh')

```

`sscounter.sh` even can not start, but cmd would not be hanged:

```
root@ubuntu-1404:~# /mithril/scripts/ss-bash/ssadmin.sh status
ssserver not running
sscounter.sh not running
```

with `pty=False`:

```
def ts1():
    with settings(warn_only=True):
        run("chmod 775 %s" % 'ssadmin.sh')
        run("%s start" % 'ssadmin.sh', pty=False)
```
 ```
root@ubuntu-1404:~# /mithril/scripts/ss-bash/ssadmin.sh status
ssserver not running
10670 ?        S      0:00 /bin/bash /mithril/scripts/ss-bash/sscounter.sh
sscounter.sh is running
```
sscounter.sh started, but cmd hangs:

```
E:\[Sync]\project\walbk\fab>fab ts1
[192.168.1.181] Executing task 'ts1'
[192.168.1.181] run: chmod 775 /mithril/scripts/ss-bash/ssadmin.sh
[192.168.1.181] run: /mithril/scripts/ss-bash/ssadmin.sh start
[192.168.1.181] out: stdin: is not a tty
[192.168.1.181] out:  9915 ?        S      0:00 /bin/bash /mithril/scripts/ss-bash/sscounter.sh
[192.168.1.181] out: sscounter.sh鍚姩涓?..
[192.168.1.181] out: 10670 ?        S      0:00 /bin/bash /mithril/scripts/ss-bash/sscounter.sh
[192.168.1.181] out: sscounter.sh宸插惎鍔?
[192.168.1.181] out:                 (hang at here)
```

**Comment by hardikdangar** [comment]
can you share contents of ssadmin.sh script ? Also can you tell your purpose of your fab script. i may be able to tell you better way to do it.

**Comment by eromoe** [comment]
ssadmin.sh is in https://github.com/hellofwy/ss-bash
I am using this script to control a sock5 proxy service `shadowsocks`.
My purpose is to setup a `shadowsocks` service in a new VPS by one line fabric magic command.

**Comment by kaaveland** [comment]
I'm not sure I can see a nice way for fabric to not hang here. As far as I can tell, it is waiting for output from the remote host that never arrives.
