### ISSUE TITLE
SSH connection via Fabric does not behave as per manual SSH connection

### ISSUE THREAD

**Issue by carn1x** [fabric/fabric#1331]
I have a remote server, say `1.2.3.4` which is running a docker container that is serving SSHD mapped to port 49222 on the docker host, so to connect to it manually I would do:

`workstation$ ssh 1.2.3.4 -t "ssh root@localhost -p 49222"` and arrive at the docker container SSH command prompt `root@f383b4f71eeb:~#`

If I run a fabric command which triggers `run('ssh root@localhost -p 49222')` then I instead am asked for the root password. However it does not accept the root password which I know to be correct, so I suspect  the password prompt is originating from the host and not the docker container.

**Comment by pauleveritt** [comment]
Try putting this:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

...in your script and see if it complains with this:

```
ERROR:paramiko.transport:Exception: Incompatible ssh peer (no acceptable kex algorithm)
```

If so, then your problem is  http://goo.gl/VOnb7X

**Comment by carn1x** [comment]
Thanks, but no cigar. Instead the problem was that I needed to set:

```
env.forward_agent = True
```
