### ISSUE TITLE
Enable configuration of banner_timeout

### ISSUE THREAD

**Issue by pgroudas** [fabric/fabric#1342]
Hello,

We have a number of hosts that we automate with fabric, that are occasionally under a lot of load (so much so that ssh banner is not very responsive), and the default 15 second timeout may fail.

Now that paramiko supports customizing this, I'd like to add support for fabric to do the same.  Should I just have HostConnectionCache.connect() read from something like `env.ssh_banner_timeout` and if its not None pass it through to the call to client.connect?

I'm happy to do this myself, I just want to ensure that that is an okay way to plumb configuration.

https://github.com/fabric/fabric/blob/master/fabric/network.py#L381
https://github.com/paramiko/paramiko/pull/362
https://github.com/fabric/fabric/issues/710

**Comment by bitprophet** [comment]
That sounds like a reasonable approach to me offhand, @pgroudas. I'd just make the setting `banner_timeout`, no point having the `ssh_` prefix IMHO.

**Comment by bitprophet** [comment]
Rolling into PR
