### ISSUE TITLE
trailing whitespace in ssh user leads to bad ssh connection

### ISSUE THREAD

**Issue by twomice** [fabric/fabric#1346]
This is similar to #305 and #619, which relate to the ssh host, whereas this relates to ssh user.

# Summary:
A trailing space in the ssh user will be passed on to the ssh connection process, leading to a failed connection attempt.  This is true for trailing spaces in the User value for a host in .ssh/config, leading to the confusing situation in which `ssh example.com` connects properly, but `fab mytask -H example.com` fails.

# To reproduce
ssh-agent is running with my key for the remote server, as you'll see in the results of the `ssh` command below.

```
$ cat fabfile
from fabric.api import *
env.use_ssh_config = True

@task
def test_fab():
    run('pwd')
$ cat ~/.ssh/config
Host mie
  Hostname A.B.C.D # redacted IP address
  # note the trailing whitespace on the next line:
  User allen 
$ ssh mie
Last login: Thu Jun 25 14:38:13 2015 from W.X.Y.Z
allen@mie:~$ exit
logout
Connection to A.B.C.D closed.
$ fab test_fab -H mie
[mie] Executing task 'test_fab'
[mie] run: pwd
[mie] Passphrase for private key: 
```

If I remove the trailing space from the User value in .ssh/config, there's no problem connecting with fabric:
```
$ cat ~/.ssh/config
Host mie
  Hostname A.B.C.D # redacted IP address
  # No more trailing whitespace on the next line:
  User allen
$ ssh mie
Last login: Thu Jun 25 14:38:13 2015 from W.X.Y.Z
allen@mie:~$ exit
logout
Connection to A.B.C.D closed.
$ fab test_fab -H mie
[mie] Executing task 'test_fab'
[mie] run: pwd
[mie] out: /home/allen
[mie] out: 


Done.
```

I also tried adding `env.user = "allen"` to fabfile.py, allowing for a successful connection. But changing that to `env.user = "allen "` results in the same type of failure shown above. 

Perhaps adding a trailing space inside the quotations when setting env.user is "asking for trouble" in that it should be fairly obvious and will also fail consistently.  Trailing spaces in .ssh/config, however, are not as obvious and will also not fail when connecting directly with `ssh`.

**Comment by bitprophet** [comment]
Thanks for the report!

**Comment by bitprophet** [comment]
This actually might need fixing in Paramiko but we'll figure that out when we get to this.

**Comment by abednarik** [comment]
HI @bitprophet  I send a simple pull requests that should fix this issue using strip().

**Comment by bitprophet** [comment]
See https://github.com/fabric/fabric/pull/1399#issuecomment-206691552 - tl;dr upgrade Paramiko once its version 1.13.5 is released (as it includes https://github.com/paramiko/paramiko/issues/499) and this should be fixed, regardless of Fabric version.
