### ISSUE TITLE
Parallel execution : share a variable

### ISSUE THREAD

**Issue by 9263** [fabric/fabric#1356]
Hello,

I am working on a tool which use Fabric.

I use the execute function like that :
  execute(my_function, a_shared_var, hosts=servers)

a_shared_var is modify in my_function.

All is ok when my_function is not run in Parallel mode, but with @parallel a_shared_var duplicate into differents forks and impossible to share the information.

Have you got any idea, how can I have a_shared_var between all my hosts and when is back to main a_shared_var must be up to date with all modifications ?

I am thinking about write into a file in my_function, because I have not other idea...

Thanks,

**Comment by 9263** [comment]
I solved my problem. Using a multiprocessing Queue. Before running the execute function, I start a thread which have to read into the Queue. And into my_function I have a producers which put messages into the Queue.

**Comment by bitprophet** [comment]
That's how the internals do it as well, yup.
