### ISSUE TITLE
Exception subclasses should not be shown in "fab -l"

### ISSUE THREAD

**Issue by mattvonrocketstein** [fabric/fabric#1365]
To reproduce, create a fabfile.py with contents "class Foo(Exception): pass", then "fab -l" will list it as an available command.  

I suppose this happens because callable(Foo) is True, but since using an Exception as a fabric command is nonsense, I would expect this to generate an error like "Fatal error: Fabfile didn't contain any commands!" just like if I had a fabfile consisting only of contents "Foo=[]", 

For real fabfiles, this clutters up the namespace and it's annoying to have to do the "from module import SomeException as _SomeException" workaround.

**Comment by bitprophet** [comment]
Gross. Thanks for the catch.

**Comment by mattvonrocketstein** [comment]
No problem.  Since we agree it's a bug now, I'll volunteer to create a patch.

**Comment by bitprophet** [comment]
Rolling into PR.
