### ISSUE TITLE
Unable to do multiple hop ssh

### ISSUE THREAD

**Issue by zahidajaz** [fabric/fabric#1366]
Hi All
I have a use case where i have host -> server1 and server2.
I connect to from host to server1 via fabric(key_filename=xyz and forward_agent = True) and need to run scp(put) command on server1 to server2. It gives error permission denied , when i put ssh-agent off on host. but works when i add private key to ssh agent.

Requirement is without adding private key to ssh-agent i need to get above use case done.

**Comment by zahidajaz** [comment]
Any updates on this Jeff.

**Comment by ploxiln** [comment]
The private key needs to be added to the ssh-agent which has a socket forwarded to server1, so scp on that machine can use the agent to make use of the private key to access server2. Fundamentally, some ssh-agent is required.

Theoretically, you could add a complex feature to fabric/paramiko, such that this was a special temporary ssh-agent instance, with the desired key added to it. Alternatively, you could make a wrapper script that does that: setting up a new ssh-agent, running fab, cleaning up the ssh-agent.

**Comment by bitprophet** [comment]
@ploxiln has it; this is a fundamental limitation of SSH and not a bug. Not sure why I didn't respond with that earlier, sorry @zahidajaz :(

Yes, we could presumably add a high level hack to make temporary/focused agent exposure possible, but the core issue of exposing a credential socket to the first remote system would remain, so if this is a policy constraint on the user's end, it's still a violation.

(Arguably this could fall under "fab/paramiko should support `IdentitiesOnly`", which would be aces, but I think that's kinda tangential.)
