### ISSUE TITLE
Need support of non-SSH way to contact a rsync remote server 

### ISSUE THREAD

**Issue by huntzhan** [fabric/fabric#1369]
I've discovered that currently [`fabric/contrib/project.py`][1] supports only SSH way to contact a remote server, which might not fulfill my requirement, in such case I could merely contact a remote server through TCP protocol.

It seems that fabric is strongly bound with SSH, do you guys consider supporting other kinds of protocols? Is that appropriate to make a pull request implementing TCP support for  [`fabric/contrib/project.py`][1]?

[1]: https://github.com/fabric/fabric/blob/master/fabric/contrib/project.py

**Comment by bitprophet** [comment]
Upcoming project reorganization means this will either be implementable as a swappable backend class in 2.0, or - more likely - as a "truly contrib" PR on the 'patchwork' repo (which right now is 1.0 oriented unfortunately).

So - +1 on the idea but please don't do any work on it just yet as it would be invalidated pretty soon. Stay tuned to Twitter/mailing list/etc for news on that stuff. Thanks!
