### ISSUE TITLE
Bug in sed when scaping quotes 

### ISSUE THREAD

**Issue by bittecnologia** [fabric/fabric#1376]
Hi, today, with Fabric 1.10.2, I have exacly this issue here https://github.com/fabric/fabric/pull/567

I need to change the postgresql conf file

       sed(filename='/etc/postgresql/9.3/main/postgresql.conf',
                              before="#listen_addresses = 'localhost' ",
                              after="listen_addresses = '*' ", 
                              use_sudo=True)

 The error

        out: bash: -c: line 1: syntax error: unexpected end of file

        Requested: sed -i.bak -r -e 's/#listen_addresses = \'localhost\' /listen_addresses = \'*\'/g'      "$(echo /etc/postgresql/9.3/main/postgresql.conf)"
        Executed: sudo -S -p 'sudo password:'  sed -i.bak -r -e 's/#listen_addresses = \'localhost\'  /listen_addresses = \'*\'/g' "$(echo /etc/postgresql/9.3/main/postgresql.conf)"

How can I make it works?

**Comment by bitprophet** [comment]
The best solution when these "tweak it via sed" approaches don't work, is usually to keep a copy of the full postgresql.conf in your local repo and just upload it wholesale (possibly using `upload_template`). The escaping is pretty thorny and hard to fix for 100% of use cases :(

**Comment by Russell-Jones** [comment]
FWIW, '\'' and '"'"' are two ways to quote single quotes inside single quotes. Adding a $ at the start also works (with bash). So I think in sed() in fabric/contrib/files.py
```
context = {
        'script': r"$'%ss/%s/%s/%sg'" % (limit, before, after, flags),
        'filename': _expand_path(filename),
        'backup': backup
    }
```
would work with newer versions of bash. It doesn't work with csh or tcsh, though.

( see http://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings )
