### ISSUE TITLE
`with settings(prompts = ...)` has no effect on local()

### ISSUE THREAD

**Issue by fillest** [fabric/fabric#1377]
Hello!
Do you have any plans for changing `local` behavior to use `settings` (particularly `prompts `)? Or will it remain a thin wrapper for `subprocess.call`?
It would be much more convinient than calling `run`/`sudo` to localhost (which requires creating extra ssh key and so on).

**Comment by bitprophet** [comment]
This sounds like the same question #98 has been asking (for years, sob).

2.0 will have a significantly more powerful `local` (you can actually see its current state in Invoke, which is where it lives, http://docs.pyinvoke.org/en/0.11.1/api/runners.html#invoke.runners.Runner.run) which will be completely on par with `run`/`sudo` in terms of functionality/configuration/etc. (The only differences remaining will be where `run`/`sudo` have *additional* configuration specifically relating to SSH things.)

Thanks!

**Comment by fillest** [comment]
Aah, yeah, sorry, I've searched through the issues but very briefly just for keywords.

Great news! Looking forward to 2.0. Thanks for the awesome work.
