### ISSUE TITLE
Can't get List of followers in Twitter using Fabric Android

### ISSUE THREAD

**Issue by app2naklabs** [fabric/fabric#1380]
I am using [Fabric sdk for Twitter][1]. In this I am able to make login request as it's described in its document. Now I wan't to get list of follower of logged in user and show in `RecycleView` with follower name and profile image. I have tried various solutions like:

 

    private void getFollowersdReq(long userID) {
            showProgressDialog();
    
    
            JsonObjectRequest getRegisterReq = new JsonObjectRequest(Request.Method.GET,
                    "https://api.twitter.com/1.1/followers/list.json?cursor=-1&&skip_status=true&include_user_entities=false&user_id=" + userID, null,
                    new Response.Listener<JSONObject>() {
    
                        @Override
                        public void onResponse(JSONObject response) {
                            LogUtils.LOGD("Server Response", response.toString());
                            hideProgressDialog();
                        }
                    }, new Response.ErrorListener() {
    
                @Override
                public void onErrorResponse(VolleyError error) {
                    VolleyLog.d("server Error",
                            "Error: " + error.getMessage());
                    Toast.makeText(getActivity(),
                            "Error:" + error.getMessage(), Toast.LENGTH_LONG).show();
                    hideProgressDialog();
                }
            }) {
    
                /**
                 * Passing some request headers
                 * */
                @Override
                public Map<String, String> getHeaders() throws AuthFailureError {
                    HashMap<String, String> headers = new HashMap<String, String>();
                    headers.put("Content-Type", "application/json");
                    headers.put("Accept", "application/json");
                    return headers;
                }
    
            };
    
            // Adding request to request queue
            AppController.getInstance().addToRequestQueue(getRegisterReq, new SignpostUrlStack(twitterToken, secret));
    
            // Cancelling request
            // ApplicationController.getInstance().getRequestQueue().cancelAll(tag_json_obj);
        }

In above code I am calling [Twitter API][2] to get list of followers but in this I am getting error message

    {
        "errors": [
            {
                "code": 215,
                "message": "Bad Authentication data."
            }
        ]
    }

Also I have tried 

    class MyTwitterApiClient extends TwitterApiClient {
            public MyTwitterApiClient(TwitterSession session) {
                super(session);
            }
    
            public CustomService getCustomService() {
                return getService(CustomService.class);
            }
    
            public UsersService getUsersService() {
                return getService(UsersService.class);
            }
        }
    
        interface CustomService {
            @GET("/1.1/followers/list.json")
            void show(@Query("user_id") Long userId,
                      @Query("screen_name") String var,
                      @Query("skip_status") Boolean var1,
                      @Query("include_user_entities") Boolean var2,
                      @Query("count") Integer var3, Callback<User> cb);
        }
    
        interface UsersService {
            @GET("/1.1/users/show.json")
            void show(@Query("user_id") Long userId,
                      @Query("screen_name") String screenName,
                      @Query("include_entities") Boolean includeEntities,
                      Callback<User> cb);
        }

Called this class like:

    new MyTwitterApiClient(session).getCustomService().show(userID, null, true, true, 100, new Callback<User>() {
                @Override
                public void success(Result<User> result) {
                    LogUtils.LOGI("Get success",result.toString());
                }
    
                @Override
                public void failure(TwitterException e) {
                    hideProgressDialog();
                }
            });

By this method also I am not able to get desired output.

  [1]: https://docs.fabric.io/android/twitter/twitter.html
  [2]: https://dev.twitter.com/rest/reference/get/followers/list

**Comment by bitprophet** [comment]
I think you have the wrong Fabric, please read this repo's description ;)
