### ISSUE TITLE
shell_env fails when using csh

### ISSUE THREAD

**Issue by dgloe** [fabric/fabric#1386]
On Fabric 1.8.0 and python 2.7.9 shell_env fails with csh since it tries to use export instead of setenv.

    dgloe@flubber-elogin1:~> cat fabrictest.py
    import fabric.api
    
    fabric.api.env.shell = '/usr/bin/csh -c'
    fabric.api.env.host_string = 'localhost'
    
    with fabric.api.shell_env(TEST='asdf'):
        fabric.api.run('echo $TEST')
    dgloe@flubber-elogin1:~> python fabrictest.py
    [localhost] run: echo $TEST
    [localhost] Login password for 'dgloe':
    [localhost] out: export: Command not found.
    [localhost] out:
    
    
    Fatal error: run() received nonzero return code 1 while executing!
    
    Requested: echo $TEST
    Executed: /usr/bin/csh -c "export TEST=\"asdf\" && echo \$TEST"
    
    Aborting.

**Comment by mradziej** [comment]
I had similar problems and found a fix: You need to set ``backslash_quote`` in csh. See pull request #1483 . Feedback welcome.

**Comment by bitprophet** [comment]
Thanks @mradziej - rolling into the doc change in #1483.
