### ISSUE TITLE
prompts is not supporting callable or regex

### ISSUE THREAD

**Issue by riccardodivirgilio** [fabric/fabric#1394]
env.prompts right now is just a dictionary with a set of strings that needs to match exactly the prompt.
this is a problem when the message is generated and contains something dynamic like: "are you sure you want to accept fingerprint ... ... ... from server ....?".
In this case there is no way to match the message, and a dictionary is not enough.
why don't we support a callable over the prompt or a regex?

thanks

**Comment by bitprophet** [comment]
Thanks for the feedback! There are plans for an improved 'expect'-like prompt/response system in 2.0. There should be tickets out there, though I can't find the exact one.

**Comment by cyberbra1n** [comment]
Is this functionality available now? I still struggle finding the way to solve this 'dynamic' prompts thing.
