### ISSUE TITLE
Unable to execute commands on remote server.

### ISSUE THREAD

**Issue by shankarh79** [fabric/fabric#1396]
I am trying to run a basic script as given below.
from fabric.api import *

env.host_string = "10.2.3.4"
env.user = "admin"

env.shell = "/bin/sh -c"

def host_type():
    run('uptime')
    
I am getting the following output on console.
$ fab host_type
[10.2.3.4] run: uptime
[10.2.3.4] out: /bin/sh -c "uptime": cannot open
[10.2.3.4] out: 

Fatal error: run() received nonzero return code 255 while executing!

Requested: uptime
Executed: /bin/sh -c "uptime"

Aborting.
Disconnecting from 10.2.3.4 .... done.

When I login to the machine 10.2.3.4 and try executing the command it works.
/bin/sh -c "uptime"
 14:09:51 up 21:11, load average: 0.12, 0.11, 0.08

**Comment by bitprophet** [comment]
Please hit up the mailing list or IRC for help, the issue tracker is for bugs/features only :) thanks!
