### ISSUE TITLE
How about role-specific user definition?

### ISSUE THREAD

**Issue by wonderbeyond** [fabric/fabric#1397]
Assume `roledefs` as belows:

```python
env.user = 'root'

env.roledefs = {
    'web': {
        'hosts': [
            '0.0.0.110',
            '0.0.0.101',
        ],
        'user': 'webapps',
    },

    'nginx': {
        'hosts': [
            '0.0.0.6',
            '0.0.0.7',
        ],
    },
}
```

I want specific roles could use specific ssh-login user as default.
Further on, we can think  of one role item in `roledefs` a conjunction of `host/port/user/password`.

Thank you!

**Comment by bitprophet** [comment]
Intelligent per-host/per-role variable customization is planned for v2.
