### ISSUE TITLE
Recursive put() and get()

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#140]
### Description

The current functionality of put and get are limited by only being able to place files in existing dirctories, and further (because of glob limitations), dont support deep recursion. This is fairly annoying for deployments, so I suggest using a module that implements scp-like behavior via paramiko. Here is one I found http://bazaar.launchpad.net/~jbardin/paramiko/paramiko_scp/annotate/500?file_id=scp.py-20081117202350-5q0ozjv6zz9ww66y-1 .

put() and get() could just become thin wrappers for this module (with all the fabric goodness in state-keeping).

---

Originally submitted by **Erich Heine** ([sophacles](https://github.com/sophacles)) on **2010-02-06** at **01:59pm EST**
### Relations
- Related to #121: Make put() more flexible re: file modes
- Related to #156: put() will try to chmod, even though this is not always possible. There is no way to turn this off
- Related to #61: Extend `cd` to work for get/put
- Related to #226: Update test server to handle sftp
- Related to #79: Optional host prefix for get
- Duplicated by #28: Allow put-style globbing with get
- Related to #217: Allow file handling methods (put/get/etc) to handle file-like objects and/or StringIO
- Related to #245: Consider breaking out the cd() behavior of local into lcd()
- Related to #274: See if it makes sense to have get/put return values
- Related to #279: Prune recursive kwarg from get()/put()
- Related to #2: Make `put` sudo-able

---

Closed as _Done_ on **2011-02-25** at **10:08pm EST**

**Comment by lkdmid** [comment]
I'm not seeing any documentation for "Make `put` sudo-able" and the Fabric 1.x syntax of `use_sudo=True` is invalid. Any pointers please?
