### ISSUE TITLE
background color tag not working in svg file

### ISSUE THREAD

**Issue by apurvacp** [fabric/fabric#1401]
This is my canvas design. i saved it in SVG.

![cdcanvas](https://cloud.githubusercontent.com/assets/15886780/11209675/a7eb75a8-8d48-11e5-87da-a904d05da661.png).

But when i open it in inkscape tool background color become null.
![inkscapecd](https://cloud.githubusercontent.com/assets/15886780/11209739/161ead2e-8d49-11e5-8891-9542b2ee2cc2.png)

this is my svg data:

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="415" height="415" style="background-color: #9b9e46" xml:space="preserve">
<desc>Created with Fabric.js 1.5.0</desc>
<defs></defs>	<g transform="translate(198.5 294.23)">

<text font-family="Arial" font-size="24" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #c43525; fill-rule: nonzero; opacity: 1;" ><tspan x="-40" y="5.3904" fill="#c43525">cd data</tspan></text>
	</g>
<circle cx="0" cy="0" r="38.5" style="stroke: red; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #ffffff; fill-rule: nonzero; opacity: 1;" transform="translate(207.5 207.5) "/>
</svg>

in browser while i am opening  this showing perfectly with background color.  
pls let me know how to get canvas background color in svg file.

**Comment by bitprophet** [comment]
I believe you have the wrong project :(
