### ISSUE TITLE
Frontpage example fails 

### ISSUE THREAD

**Issue by nitrocode** [fabric/fabric#1404]
Manually remoting to my server:

    $ ssh root@10.59.4.60
    root@ubuntu1204:~$ uname -s
    Linux

Running fab:

    $ cat fabfile.py
    from fabric.api import run
    def host_type():
        run('uname -s')

    $ fab -u root -H 10.59.4.60 host_type
    [10.59.4.60] Executing task 'host_type'
    [10.59.4.60] run: uname -s
    [10.59.4.60] Login password for 'root': 
    [10.59.4.60] out: Linux
    [10.59.4.60] out: 
    
    
    Done.
    Disconnecting from 10.59.4.60... done.

Versions:

    $ fab --version
    Fabric 1.10.2
    Paramiko 1.10.1

    $ python --version
    Python 2.7.6

Am I doing something wrong?

**Comment by gtback** [comment]
Hi, @nitrocode!

What are you expecting to see? The output you give contains the line:

```[10.59.4.60] out: Linux```

(the example at http://www.fabfile.org/ uses `-H localhost,linuxbox`, so it runs on two different machines)

**Comment by nitrocode** [comment]
Ah. I don't know why I didn't see that. Too much coffee...

Thanks.
