### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by richardasaurus** [fabric/fabric#1407]
When will this support python 3?

**Comment by Russell-Jones** [comment]
It won't, fabric 2 will.

**Comment by richardasaurus** [comment]
When is fabric 2 going to be released?

**Comment by Russell-Jones** [comment]
No date is set. See http://www.fabfile.org/roadmap.html

**Comment by richardasaurus** [comment]
That's a shame, it blocks both my personal and work projects from upgrading to 3.

**Comment by tiggreen** [comment]
+1 for py3k support.

**Comment by Russell-Jones** [comment]
@tigreen AIUI, that's just not going to happen in the main project for 1.x... there are some forks with Py3 support IIRC. Try searching the bug tracker and mailing lists.

**Comment by bitprophet** [comment]
I'm really curious why @richardasaurus didn't search the tracker for "Python 3" :( there's a bunch of other, closed tickets with lots of links to the roadmap etc.

**Comment by richardasaurus** [comment]
@bitprophet Because when you close a ticket it no longer appears the default search results. So you might as well leave one open :+1: 

Here's a fork which may function for anyone looking: https://github.com/mathiasertl/fabric/

**Comment by bitprophet** [comment]
Grump, wonder when Github started doing that - did not used the be the case. Thanks, Github :(

**Comment by nicktimko** [comment]
There was a post in September that said 2.0 alpha would be out by "the end of the month", but alas, nothing. Is the fork being kept super-seekret for a reason? If you're anxious about people dumping issues and PR's on you, they could be disabled in another GH repo while things are still in major flux. Showing *something* would go a long way in alleviating Netscape 6 fears.
