### ISSUE TITLE
Doc for `put` doesn't specify behavior when remote_file already exists

### ISSUE THREAD

**Issue by chris-martin** [fabric/fabric#1408]
Does it overwrite? Does it fail?

**Comment by kaaveland** [comment]
Hey,

We'll try to get the doc updated here. `put` will overwrite files if they're already present.

**Comment by jennaliu** [comment]
put doesn't overwrite the file that already exists. It would just hang there without giving any errors. Specifically it hangs at:
> /home/junlanvm/.virtualenvs/fabric/local/lib/python2.7/site-packages/fabric/sftp.py(290)put()
-> sudo("mv \"%s\" \"%s\"" % (remote_path, target_path))
If I execute this command directly in the script, it would prompt for overwrite. Changing it to 
-> sudo("mv -f \"%s\" \"%s\"" % (remote_path, target_path))
would make it work.

The VM that I deploy to runs CentOS 6.7
