### ISSUE TITLE
Hang when making connections to FQDN and 'localhost' in the same test run.

### ISSUE THREAD

**Issue by cjw296** [fabric/fabric#1409]
This is for @mathiasertl, but I figured @bitprophet might also be interested so logging here...

So, I'm using https://github.com/mathiasertl/fabric/ to get Fabric working under Python 3.
I've found that I need the following package-level teardown to prevent the test run hanging during interpreter shutdown:

```
def teardown_package(self):
    # prevent hang on shutdown
    from fabric.state import connections
    for key in tuple(connections):
        del connections[key]
```

This hang doesn't occur using the same codebase under Python 2. Thought it might be worth a headsup when preparing for the 2.0 release...

**Comment by bitprophet** [comment]
Version 2 is a near total rewrite so I'm guessing this won't apply, but thanks for noting it on the record!
