### ISSUE TITLE
Broken SSH session causes fabric to hang

### ISSUE THREAD

**Issue by ldelossa** [fabric/fabric#1420]
I'm writing a bootstrap script in which I 

launch a vm, 
get the MAC address from 'virsh dumpxml' 
arp for the DCHP given address of the machine
SSH into this dhcp'd machine
set new IP address info
restart networking

At the restart of the network service, fabric hangs. I understand I broke the initial SSH session, but is there anyway to gracefully handle this, being that I intended to do so? 

Also I tried to set my timeout to 1 second, and catch the failure, but fabric just hangs infinitely.

**Comment by kaaveland** [comment]
I think this is a case of https://github.com/fabric/fabric/issues/1205 which I believe comes from paramiko. I can’t think of any good workaround for this, you’ll want to interrupt the thread that is hung somehow. I’m not sure what a good way to do this is — maybe you can schedule sigalarm before you go to the code that you know will hang and try to “unhang” the thread there? https://docs.python.org/2/library/signal.html#signal.alarm
