### ISSUE TITLE
fab command will execute a fabfile in parent directory (possible security issue)

### ISSUE THREAD

**Issue by robvdl** [fabric/fabric#1432]
This behaviour just seems plain weird to me, if fabric doesn't find a fabfile.py in the current directory, but finds one in the parent directory, it just goes ahead and tries to execute it.

I think this is pretty bad and could potentially lead to security issues, not only that, but it seems that fabric will just keep looking up a directory, and up, and up, etc. until it finds a fabfile.py.

**Comment by kaaveland** [comment]
As far as I know, this is intended behaviour. Can you shed some light on what sort of security issues this leads to?

**Comment by robvdl** [comment]
I was just thinking if someone managed to get a fabfile installed in / it could be a problem, but then I guess you have bigger problems because your system would be compromised.  I just found the behaviour very strange.

**Comment by kaaveland** [comment]
I'm not sure it is a good idea to change this unless we can come up with some good reasons why this is not safe. Users probably rely on this feature. I used to have a bunch of deeply nested repositories with configuration for several servers, it was nice to be able to work on a configuration file deep inside the structure and `fab deploy` without having to go back to the root of the repository.

**Comment by gtback** [comment]
I rely on this behavior. As @kaaveland mentioned, it's convenient when you're deep in directory hierarchies. Other use cases (besides deployment) include building documentation and running tests.

**Comment by ploxiln** [comment]
This is also how git works, looking for a `.git/config` which can contain aliases with arbitrary commands, and other tools as well. Parent directories being under your control, or safe, is assumed.

**Comment by bitprophet** [comment]
I missed this earlier, sorry about that. As stated by all the other folks, this is absolutely intended/expected behavior.

FWIW Fabric 2 will more cleanly expose the algorithm(s) used to seek & load fabfiles (i.e. https://github.com/pyinvoke/invoke/blob/684407959abfac291a8d53413e120fb6975f6c42/invoke/loader.py) so users like @robvdl who don't want the behavior can more readily change or disable it.

For now though, closing as invalid/working-as-expected. Thanks!
