### ISSUE TITLE
sudo("reboot") hangs against local KVM

### ISSUE THREAD

**Issue by GregorioDiStefano** [fabric/fabric#1444]
Running `sudo("reboot")` against my local KVM hangs forever.
However, changing the command to: `sudo("reboot 2>/dev/null >/dev/null &")` works fine.

Running the exact same code, with `sudo("reboot")` against VirtualBox VMs does not reproduce this bug.

This is happening under: 
Fabric 1.10.2
Paramiko 1.16.0

**Comment by GregorioDiStefano** [comment]
Ill add some more useful logs here in a bit.

**Comment by bitprophet** [comment]
#1488 is same issue & has more info in it, let's merge 'em. Closing this one. Thanks!
