### ISSUE TITLE
Using rsa ca based ssh authentication, fab repeatedly asks for password (even when given a correct one)

### ISSUE THREAD

**Issue by VoittajaTomi** [fabric/fabric#1445]
I have server public rsa certificate in ~/.ssh/id_rsa-cert.pub and can connect without a password using ssh. When using fabric I get prompted for the password, but the password is still not accepted.

fabfile:

``` python
from fabric.api import *
from fabric import *

def host_type():
  run("uname -s")
```

command line:

```
fab -i ~/.ssh/id_rsa -H user@server host_type
```

result:

```
[user@server] Executing task 'host_type'
[user@server] run: uname -s
[user@server] Login password for 'user': 
[user@server] Login password for 'user': 
[user@server] Login password for 'user': 
```

**Comment by kaaveland** [comment]
Can you put:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
At the top of your file and run this again (to investigate what paramiko does in this case) ?

**Comment by KarimJedda** [comment]
I started debugging a docker-swarm networking issue, and now I'm debugging this.
 
@kaaveland I have the same issue, paramiko logs some BS about "DEBUG:paramiko.transport:Switch to new keys ...", which when googled shows that nobody has an effing clue what it could be.

**Comment by ploxiln** [comment]
Paramiko, which is what fabric uses for the ssh connection, does not yet support client auth key certificates.

see https://github.com/paramiko/paramiko/pull/1042 and https://github.com/paramiko/paramiko/pull/531
