### ISSUE TITLE
Doc bug: positional arguments for `put()` are not documented

### ISSUE THREAD

**Issue by markstos** [fabric/fabric#1452]
The positional arguments for `put()` are only documented as "*args*".  Examples are shown like this:

    put('bin/project.zip', '/tmp/project.zip')

But it is never explicitly mentioned what the first and second positional arguments are for. 

I would presume that the first positional argument is `local_path` and the second one is `remote_path`, but this is never stated. 

Explicitly updating the documented signature from `*args` to something more explicit would be helpful, since `*args` would describe *every* function that takes positional arguments.

**Comment by bitprophet** [comment]
I think this falls under #103. Thought we had at least *some* magic sauce between "just `@wraps`" and "use `decorator.decorator`" (which is what #103 suggests) but I'm not seeing much, either on the `@needs_host` decorator masking `put`/`get` or on the public decorators (which get more love).

There may be newer tickets too, e.g. I have a faint memory of some workarounds possibly breaking down in recent history. No time to dig further. If you run across such tickets, please do link them to #103 and we can continue discussion there. Thank you!
