### ISSUE TITLE
ssh interact by send() and recv()

### ISSUE THREAD

**Issue by mungayree** [fabric/fabric#1465]
Since Fabric is based over paramiko and has very simple api. Can it be enhanced to interact with remote process started on ssh ? Similar to robot-framework has API to write/read_until based over paramiko.

e.g most of switches support ssh connections, but weird prompts.

This can be enhanced in case a user wants to start a mini process on one appliance and local system to send commands.

I failed to find any documentation if this can already be achieved in docs.fabfile.org

**Comment by mungayree** [comment]
nice to have with open_shell(): interact()

**Comment by kaaveland** [comment]
Can you be a little bit more specific? I'm not sure exactly which feature you want -- do you want to send stuff to `stdin` of the remote process?

**Comment by mungayree** [comment]
Yes you are right. Is there any API to connect to such virtual appliance with ssh-process having weird interactive shells and prompts ?

How can fabric interact with these processes ?

e.g. i have small VM simulating a switch. Once you ssh you are having prompt 'switch-> ' . fabfile.py need to feed commands thereafter on the prompt. command can be "do link down" or "deploy images from tftp". 

I tried below code, but it does not work -

 @task
 taskA():
      with settings(prompts={'switch-> ' : 'deploy img.bin' }):
          run('save image')

**Comment by ploxiln** [comment]
you may have to use "pexpect" instead of fabric. see slightly related #1448

**Comment by bitprophet** [comment]
Pexpect can work for this, there's also an `env.prompts` setting for very basic call-and-response that may or may not work in your case. Version 2 will offer something that lets you do more pexpect-y things, as well.

**Comment by mungayree** [comment]
Sure. Will wait and test v2.
