### ISSUE TITLE
HostConnectionCache does not seem to be utilized

### ISSUE THREAD

**Issue by stardude900** [fabric/fabric#1466]
This code:

```
    host =      run('hostname')
    os_version = run('cat //etc/redhat-release')
    uptime =    run('uptime')
    ip_addr =   run('hostname --all-ip-addresses')
```

Creates four separate connections to each host in env.hosts.  The way I interpret the documentation it should be transparently reusing the HostConnectionCache to reuse the previous connection.

**Comment by kaaveland** [comment]
Can you paste your complete fabfile and tell us how you invoked it? I tried to verify this by inserting some logging into `network.py` (see `def connect()` where actual connections are created), but with my minimal example, fabric only creates one connection per host and reuses it for all 4 of the `run` invocations.

**Comment by stardude900** [comment]
I'm verifying it by checking the last output on an SL6 and CentOS 7.2
machines.  I'm running it by using an embedded execute command.

from fabric.api import run, task, execute, runs_once, env, sudo,
settings, hide, hosts
from fabric.network import HostConnectionCache, disconnect_all
import base64, time
import cProfile
# import Log_in

env.skip_bad_hosts = True
env.abort_on_prompts = False


def workhorse():
    host = run('hostname')
    os_version = run('cat //etc/redhat-release')
    uptime = run('uptime')
    ip_addr = run('hostname -I')
    CPU = run('nproc')

    for i in uptime.split():
        if 'average' in i:
            x = uptime.index(i)
            x = uptime[x:].replace('average:', '')
            load = x

    uptime = uptime.replace(',', '')
    uptime = uptime.split()[2:4]
    uptime = ' '.join(uptime).replace(',', ' ')
    # print(load)

    if 'users' in uptime:
        uptime = uptime.split('  ')
        print(uptime)

    def netstat():
        x = sudo('sudo netstat -tlnp | awk \'{print $7}\'')
        x = ''.join(x)
        x = x.split()
        q = ''
        for i in x:
            if 'Address' in i:
                continue
            for letter in i:
                if letter.isdigit():
                    continue
                if '/' in letter:
                    continue
                if '-' in letter:
                    continue
                else:
                    q += letter
            q += '\n'
        q = set(q.split())
        q = list(q)
        q.insert(0, host)
        q.insert(1, os_version)
        q.insert(2, uptime)
        q.insert(3, ip_addr)
        q.insert(4, CPU)
        return q


    # load = ' '.join(load)
    services = (''.join(i) for i in netstat()[4:])
    # print('Hostname:', host,
    #       '\nOS Version: ', os_version,
    #       '\nUptime: ', uptime,
    #       '\nLoad: ', load,
    #       '\nIP: ', ip_addr,
    #       '\nServices: ', ' '.join(services))
    # print('----------------------')

    return host, os_version, uptime, load, ip_addr, CPU


@hosts(['testvm1'])
@task
@runs_once
def set_hosts():
    with settings(warn_only=True):
        env.hosts = 'logankvm'
        with hide('running', 'status', 'warnings'):
            try:
                results = execute(workhorse)
                for key, value in results.items():
                    print(key, value)
                return results
            except SystemExit:
                pass
            # results = list[results]

set_hosts()
# Code execution timing
start_time = time.time()
# cProfile.run('execute(set_hosts)', 'stuff.profile')
print("\n--- %s seconds ---" % (time.time() - start_time))


# Ensures all connections have been closed
disconnect_all()


Regards,
Logan

**Comment by kaaveland** [comment]
I suspect the problem is that you're nesting `execute` calls, see http://docs.fabfile.org/en/1.11/usage/execution.html#intelligently-executing-tasks-with-execute

I'll see if I can find the time to double-check this, but I'm almost positive that this is the problem. Instead of invoking `execute(workhorse)` in your `@task`, try just calling it directly (as you're already in the `execute` context) ?

**Comment by stardude900** [comment]
I could very well be missing something obvious, but in the interests of
simplifying it a great deal I mostly copied what is in the docs you linked
and still have the same result.

I've executed it directly from the IDE (PyCharm) as well as from
commandline as fab go -f <file> with similar results.

from fabric.api import task, execute, run, runs_once, env
from fabric.network import disconnect_all

@task
def workhorse():
    # host = run('hostname')
    # os_vers = run('cat /etc/redhat-release')
    return run('hostname'), run('cat /etc/redhat-release')

@task
@runs_once
def go():
    env.hosts = 'logankvm'
    results = execute(workhorse)
    return results


Regards,
Logan

**Comment by kaaveland** [comment]
I must be misunderstanding this issue. Using your example from the last comment, I get this result:

```bash
$ fab -f issue_1466.py go
[first-server] Executing task 'go'
[first-server] Executing task 'workhorse'
[first-server] run: hostname
Create new connection to user@first-server:22
[first-server] out: alt-daled
[first-server] out:

[first-server] run: cat /etc/redhat-release
[first-server] out: CentOS release 6.7 (Final)
[first-server] out:

[second-server] Executing task 'workhorse'
[second-server] run: hostname
Create new connection to user@second-server:22
[second-server] out: alt-dayos
[second-server] out:

[second-server] run: cat /etc/redhat-release
[second-server] out: CentOS release 6.7 (Final)
[second-server] out:

Done.
Disconnecting from first-server... done.
Disconnecting from second-server... done.
```

As far as I can tell, only one connection is created to each server (I added a print in the function that creates new connections) and the tasks run only once per server. Is that different from what you expect? What is the expected behaviour?

**Comment by stardude900** [comment]
Ah, I see how we're getting mixed up.  I'm verifying it based on what the
machine I'm logging into is reporting

To see what I'm referring to, log into the machine you're connecting to,
first and second server and run sudo last and see how many times it logged
into the machine.

Regards,
Logan

**Comment by kaaveland** [comment]
I tailed `/var/log/secure` (CentOS 6.5) and only saw one session open/close on each server. Maybe what you're observing is that fabric is creating a new shell for each `run` ? As far as I can tell, there's only one ssh session.

**Comment by stardude900** [comment]
Actually I bet that's exactly what it's doing

**Comment by bitprophet** [comment]
Yes, there's one discrete shell/login session for each `run()`, no way around that since it maps to an SSH `exec` channel request.
