### ISSUE TITLE
Archieve failed due to "error: Fabric: Info.plist Error"

### ISSUE THREAD

**Issue by WXGBridgeQ** [fabric/fabric#1476]
```
error: Fabric: Info.plist Error

Unable to process Info.plist at path /xxxx/Info.plist
This could be a timing issue, make sure the Fabric run script build phase is the last build phase and no other scripts have moved Starbucks.app from the location Xcode generated it.

** ARCHIVE FAILED **
```

it only happens when I set CONFIGURATION_BUILD_DIR=xxxx with my xcodebuild command, seems fabric find the incorrect path, I just want to know how to fix it.

**Comment by kaaveland** [comment]
This looks apple-specific, are you sure you're reporting to the correct fabric project ?

**Comment by WXGBridgeQ** [comment]
sorry for the mistake

**Comment by Leonif** [comment]
How did you fix it?

**Comment by tnurdinov** [comment]
> How did you fix it?

Here is the fix
https://fabric.io/kits/ios/crashlytics/install
