### ISSUE TITLE
Fabric detailed help command (fab -d) broken for parallel and other custom decorators

### ISSUE THREAD

**Issue by adt123** [fabric/fabric#1481]
Given the following two python functions,
```python
@roles('role_name')
@task
@parallel
def my_func_1(x=5,hello='world'):
   """ my first function """
   pass

@roles('role_name')
@task
def my_func_2(x=5,hello='world'):
   """ my second function """
   pass
```
the command `fab -d my_func_1` does not return the arguments,
```
Displaying detailed information for task 'my_func_1':
    my first function
    Arguments:
```
whereas the command `fab -d my_func_2` does return the arguments
```
Displaying detailed information for task 'my_func_2':
    my second function
    Arguments: x=5, hello='world'
```
It seems as though `argspec` is not returning the correct arguments to a function when the `parallel` decorator is applied.
Furthermore, the same issue with `argspec` occurs when using other decorators on a function, as per http://stackoverflow.com/questions/12558505/preserve-argspec-when-decorating and http://stackoverflow.com/questions/3972290/how-can-i-get-the-argument-spec-on-a-decorated-function

**Comment by bitprophet** [comment]
Looks like #1406, rolling into that. Thanks!
