### ISSUE TITLE
docs.unwrap_tasks does not properly unwrap multiple decorators

### ISSUE THREAD

**Issue by SwampFalc** [fabric/fabric#1485]
While the docs.unwrap_tasks functions works fine for a single task decorator, it fails to properly unwrap when there's both task and roles: the arguments become (\*args, \*\*kwargs) instead of whatever is defined.

I managed to cobble together something that works at first sight for me:

  ```python
if isinstance(obj, WrappedCallableTask):
    f = obj.wrapped
    while hasattr(f, 'wrapped'):
        f = f.wrapped
    setattr(module, obj.name, f)
    set_tasks.append(obj.name)
    f.func_name = obj.name
```
However, this is apparently sensitive to the order in which the decorators are applied.

```
@roles()
@task
def func(arg1):
```
is correctly unwrapped

```
@task
@roles()
def func(arg1):
```
is not correctly unwrapped and retains the \*args, \*\*kwargs signature.

So I'm hoping someone with better knowledge of the fabric internals can improve on this...

**Comment by bitprophet** [comment]
I think this falls under the longstanding #103. Thanks for the report though! (Yes - it's something of a pain which is why it's gone unfixed.)
