### ISSUE TITLE
fabric std output to file

### ISSUE THREAD

**Issue by kaushalshriyan** [fabric/fabric#1487]
Hi,

My fabric python script is here 

######################################################
from fabric.api import *

env.hosts = ['192.168.1.215','192.168.1.168','192.168.1.99']

def checkconn():
    run('w')
def checkdisk():
    run('df -hT --total')
######################################################

$fab checkconn should write to a file in the local system instead of stdout on the console.  For example output of "w" command run on the remote server should be written to a file locally.

Any help will be highly appreciable

Regards,

Kaushal

**Comment by bitprophet** [comment]
Please read [the API docs](http://docs.fabfile.org/en/1.11/api/core/operations.html#fabric.operations.run) - `run` returns all the remote command's output and you can then save it to a file as you desire, such as using the `open` Python builtin.

For more help please see our mailing list. Thanks!
