### ISSUE TITLE
Login to one machine from another

### ISSUE THREAD

**Issue by roshu10** [fabric/fabric#1489]
Hi, 

I just started with Fabric.

I have seen many post about executing commands in multiple host.

I have a problem, where i need to login to multiple machine

for eg:

For case like this :

login to machine2 from machine1, then login to machine3 from machine2 and run some command.

machine1 -> machine2 -> machine3

How can we do this ?

Thanks for any help !!

**Comment by bitprophet** [comment]
Take a look at the [gateway setting](http://docs.fabfile.org/en/1.11/usage/env.html#gateway), if you don't actually need to execute commands on `machine2` (this is commonly known as a gateway, jump box, bastion, etc).

For further help, please ask the mailing list: http://www.fabfile.org/contact.html#mailing-list - you'll get more responses there. Thanks!
