### ISSUE TITLE
Allow overriding default 5s post-'reboot' sleep in operations.reboot()

### ISSUE THREAD

**Issue by linfenghuaster** [fabric/fabric#1493]
In some cases, a host may not stop network service in 5 seconds, such as many services should be shutdown,  but the reboot api try to reconnect the host,  then it report the host reboot success in wrong.

`
(sudo if use_sudo else run)(command)
        # Try to make sure we don't slip in before pre-reboot lockdown
        time.sleep(5)
`

**Comment by bitprophet** [comment]
The code above what you posted should make reconnecting pretty graceful, trying a number of times w/ a timeout each time: https://github.com/fabric/fabric/blob/097c224a5402e9469ac9a2685d0fa1e7f5d0a5bd/fabric/operations.py#L1272-L1283

If you're on a version predating that code, I'd recommend upgrading; if you're already on such a version, I'd be interested in details re: how it is breaking for you. Happy to reopen if that is the case. Thanks!

**Comment by linfenghuaster** [comment]
Sorry，I think it can not solve my problems. Such as a hypervisor which has 10 vms,  when rebooted, it must shutdown the vms firstly,  this will cost more than 5 seconds, but the fabric will attempt to reconnect the host after 5 seconds, the fabric assumed that it must failed, but the host  just shutdown the vms but not shutdown itself,  so it think the host(hypervisor) finished reboot process in 5 seconds. In a word, the fabric think the network service will be close in 5 seconds, but not in some times.

**Comment by bitprophet** [comment]
I see what you mean - the problem is that the host is taking >5s to shut off networking pre-reboot, because it has a heavier network-shutdown procedure than the average web host. Thanks for the clarification.

Changing it to be "wait until the connection is actually broken" might be tricky; I think a much easier change would be to expose that 5s as a keyword argument, having it hardcoded like that is silly. I'll add this to a release milestone and do that sometime.

**Comment by linfenghuaster** [comment]
Since the waiting time is uncertain, a method is required to determine the waiting time, either by the reboot  api or by the user. In my opinion, changing the reboot api is better as I do in my project,  because the user just need to  call the api rather than determining the waiting time everywhere pre-reboot.

**Comment by linfenghuaster** [comment]
Since the waiting time is uncertain, in my opinion, changing the reboot api is better as I do in my project, because the user just need to call the api rather than determining the waiting time based on historical data or analysis.

**Comment by kaplanlior** [comment]
A suggested fix ( I can send a PR if needed):

```
diff --git a/fabric/operations.py b/fabric/operations.py
index 98e612a..6146f1f 100644
--- a/fabric/operations.py
+++ b/fabric/operations.py
@@ -1243,7 +1243,7 @@ def local(command, capture=False, shell=None):
 
 
 @needs_host
-def reboot(wait=120, command='reboot', use_sudo=True):
+def reboot(wait=120, command='reboot', use_sudo=True, timeout=5):
     """
     Reboot the remote system.
 
@@ -1271,8 +1271,6 @@ def reboot(wait=120, command='reboot', use_sudo=True):
         Added ``use_sudo`` as a kwarg. Maintained old functionality by setting
         the default value to True.
     """
-    # Shorter timeout for a more granular cycle than the default.
-    timeout = 5
     # Use 'wait' as max total wait time
     attempts = int(round(float(wait) / float(timeout)))
     # Don't bleed settings, since this is supposed to be self-contained.
@@ -1285,7 +1283,7 @@ def reboot(wait=120, command='reboot', use_sudo=True):
     ):
         (sudo if use_sudo else run)(command)
         # Try to make sure we don't slip in before pre-reboot lockdown
-        time.sleep(5)
+        time.sleep(timeout)
         # This is actually an internal-ish API call, but users can simply drop
         # it in real fabfile use -- the next run/sudo/put/get/etc call will
         # automatically trigger a reconnect.
```

**Comment by kaplanlior** [comment]
@bitprophet Can you the comment above ?

**Comment by bitprophet** [comment]
Seems reasonable!

**Comment by edbrannin** [comment]
(Looks like this can be closed?)
