### ISSUE TITLE
OpenSSH over windows support

### ISSUE THREAD

**Issue by Sahloul** [fabric/fabric#1496]
In the exists functon, the `test -e` command is used, however it does not exist in windows. Moreover, path expansion does not support cross platforms.

I proposed [here](https://github.com/fabric/fabric/pull/1495/files) a simple modification to depend on `stat` command which is provided in the Win32 GNU commands.

The only concern is **how to differentiate between Windows and *NIX**?
I chose to call `ver` command, which exists on windows machines.

**Comment by bitprophet** [comment]
No real need to make two tickets, let's keep discussion in the PR, thanks!
