### ISSUE TITLE
Add missing release tags

### ISSUE THREAD

**Issue by johnjohndoe** [fabric/fabric#1499]
I just installed version 1.12.0 via _pip_. Here on GitHub I cannot find a release tag for the version. Please add the missing tags and push them:

```
git checkout abc123
git tag -a "1.12.0." -m "Brief summary of the changes."
git push --tags origin
```

**Comment by bitprophet** [comment]
Having serious deja vu here, must have made the same mistake I did on...paramiko? probably?

Thanks for the idiot check :)

```
» gps --tags
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:fabric/fabric.git
 * [new tag]         1.10.4 -> 1.10.4
 * [new tag]         1.11.2 -> 1.11.2
 * [new tag]         1.12.0 -> 1.12.0
```
