### ISSUE TITLE
Incorrect Format

### ISSUE THREAD

**Issue by cquenx** [fabric/fabric#1500]
I am working on xCode8.0  beta 4

After following all the steps here https://fabric.io/kits/ios/twitterkit/install
and building the project it says 

> error: couldn't parse contents of '/projectName/project/Info.plist': The data couldn’t be read because it isn’t in the correct format.

[info.plist.txt](https://github.com/fabric/fabric/files/410862/info.plist.txt)
info.plist attached

**Comment by bitprophet** [comment]
This fabric isn't that fabric :)
