### ISSUE TITLE
[Feature] - Subscript/Supscript

### ISSUE THREAD

**Issue by terrancesnyder** [fabric/fabric#1504]
All,

The company I work for deals heavily with graphic rendering and text layout of printed products and digital ones. The fabric library is fantastic, but we've run into a desire to scale and we'd like to open a bounty on fabricjs core to allow richer dynamic iText editing that support sub-script and sup-script.

We're open to many possible solutions but at the end of the day the solution needs to accomplish the following:

- The ability to change a selection of character text to sub-script or sup-script. For example rendering 1.00 as 1<sup>00</sup>.
- The solution needs to use the standard measureText(...) functions as we have overridden them to ensure kerning support via openType.js. Your solution need to be concerned with kerning support.

Here are some helpful links to get you started:

An example "poor guy/gals" superscript/subscript
- https://forum.processing.org/two/discussion/6367/primitive-superscript-subscript-text-rendering

A simple video on what subscript and supscript means
- https://www.youtube.com/watch?v=4boHA5wo5e0

Validation of work:

Modification of the http://fabricjs.com/test/misc/itext.html page with a button that shows "sub-script" and "sup-script" and the ability to select character ranges and subscript and sup-script them.

**Comment by bitprophet** [comment]
You've got the wrong repository! :)
