### ISSUE TITLE
Make fabfile print() statements controllable via output controls

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#151]
### Description

Right now, user `print` statements are completely untouched by the output control mechanisms -- they cannot be easily hidden by higher-up code, and when #57 is implemented, they would not get logged either.

This is annoying, especially when one wants to start retaining serious control over fabfile output -- `print` cuts right through top level `hide` statements, but it's not acceptable to have the lower level output removed entirely -- sometimes you do want it.

I don't think we can do this with the builtin `print` statement, aside from dicking around with `sys.stdout` (but how -- no way I can think of to replace sys.stdout with something that will know whether its incoming writes are from `print` or from something else...right?) so it'd probably be best to just create a function to "replace" print, e.g.:
- `output`
- `out`
- `puts` (lol Ruby)
- `prntln` (or some abbrev like `pr` or `prnt`.)

This function would eventually call `print` or `sys.stdout.write`, but would check `fabric.state.output` for permission, just as `output_thread` does now for remote stdout/stderr, or how `abort`/`warn` behave.

The output level for this type of output might be called `user` or similar -- `output` is already taken, it's an alias for stdout and friends (and naturally, this level of output would be included in `output` since it's not an abort/warning/etc.)

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2010-03-19** at **01:31pm EDT**
### Relations
- Related to #57: Support full logging to file
- Related to #101: ANSI Color support

---

Closed as _Done_ on **2010-09-06** at **02:08am EDT**

**Comment by DylanYoung** [comment]
Might it not be better to allow the "output level" as an argument to `puts`.  It's quite a bit less useful to show/hide *everything* versus being able to label what gets shown and hidden.  Arbitrary levels could even be allowed. 

Anywho just a thought; maybe this is already addressed in v2
