### ISSUE TITLE
How to get stdout/stderr when fabric.tasks.execute

### ISSUE THREAD

**Issue by yyh-graphsql** [fabric/fabric#1511]
I want to use fabric.tasks.execute to run commands, but I cannot find a way to get the commands' output. Is there any method I can try to get the output?

**Comment by bitprophet** [comment]
There's no direct correlation between a task and stdout/stderr, stdout/stderr only maps to `run`/`sudo` calls. Your task needs to collate any such data and `return` it like any other function might, then it'll show up in the return value of `execute` (see its API docs for details on that format, should be a dict whose values are those per-task-exec return values) :)
