### ISSUE TITLE
fabric.api.run remove leading and trailing whitespace from output

### ISSUE THREAD

**Issue by serg2014** [fabric/fabric#1512]
```
>>> fabric.version.VERSION
(1, 12, 0, 'final', 0)
>>> a=fabric.api.run("echo -e ' \n \n 1 \n'")
[localhost] run: echo -e '

 1
'
[localhost] out:
[localhost] out:
[localhost] out:  1
[localhost] out:
[localhost] out:

>>> a
'1'
>>> a.stdout
'1'
```

The problem in this line https://github.com/fabric/fabric/blob/master/fabric/operations.py#L839

**Comment by bitprophet** [comment]
Thanks for the report! Unfortunately, this has been the behavior since before 1.0 so changing it now would be backwards incompatible. 2.0 will not do any stripping, however!
