### ISSUE TITLE
Always showing password prompt and cannot pass.

### ISSUE THREAD

**Issue by kxxoling** [fabric/fabric#1513]
I have a simple ``fabfile.py``:

```
from fabric.api import *

env.hosts = ['localhost']

def hello():
    run('pwd')
```

It's OK on my Mac with OS X 10.11.6 installed but always prompting my password to run command, and won't disappear after I entered right password on my Ubuntu computer:

```
$ fab hello
[localhost] Executing task 'hello'
[localhost] run: pwd
[localhost] Login password for 'windrunner':
[localhost] Login password for 'windrunner':
[localhost] Login password for 'windrunner':
```

This won't disappear no matter I set ``password``, ``use_ssh_config``, ``key_filename`` or ``username``. I also changed several versions of Fabric, it's always there. So I think this might be the incapability with my system:

```sh
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu Yakkety Yak (development branch)"
```

**Comment by bitprophet** [comment]
How exactly is your Ubuntu system's sshd set up to authorize you? It might be configured to disallow password logins & only allow SSH keys, for example. The password prompt in Fabric sometimes comes up when other auth problems happen, it's a long-standing problem.

Can you `ssh localhost` on the Ubuntu system ok? Are you using an SSH agent? Other details like that would be helpful.

**Comment by kxxoling** [comment]
@bitprophet ``ssh localhost`` returns ``Permission denied (publickey).`` I may changed my key before. Also, password login through SSH is forbidden for security.

So is that why it always prompts password? I think it's better to throw an error.

**Comment by bitprophet** [comment]
Yea, eventually we'll update Paramiko (the underlying lib throwing the ambiguous errors) to be more granular, now that we maintain it too. I found our old ticket about this - #85.

**Comment by kxxoling** [comment]
@bitprophet Thanks for your help! :)
