### ISSUE TITLE
sudo() function adding undesirable options

### ISSUE THREAD

**Issue by satoshi** [fabric/fabric#1515]
Hi,

My workplace has restrictions around getting shell as root:
```
$ sudo -l
Matching Defaults entries for username on this host:
    env_keep+=SSH_AUTH_SOCK

User username may run the following commands on this host:
    (root) ALL, !/bin/sh, !/bin/csh, !/bin/ksh, !/bin/bash, !/bin/zsh, !/bin/tcsh, !/bin/jsh, !/bin/pfcsh, !/bin/pfksh, !/bin/pfsh, !/sbin/jsh, !/bin/dash, !/bin/su, (ALL,
    !root) ALL
```
I can run sudo commands just fine, as long as I don't specify the shell:
```
[username@hostname ~]$ sudo ls -la
[sudo] password for username: 
total 128
drwx------    4 username username  4096 Oct  3 05:01 .
drwxr-xr-x 1417 root  root  36864 Sep 30 20:05 ..
-rw-------    1 username username 38188 Oct  3 05:13 .bash_history
-rw-r--r--    1 username username    18 Mar 15  2016 .bash_logout
-rw-r--r--    1 username username   176 Mar 15  2016 .bash_profile
-rw-r--r--    1 username username   124 Mar 15  2016 .bashrc
```
So, let's try through Fabric:
```
from fabric.api import sudo

def sudo_cmd(cmd):
    sudo(cmd)

[username@username-machine ~]$ fab sudo_cmd:'ls -la' -H hostname.somedomain.com
[hostname.somedomain.com] Executing task 'sudo_cmd'
[hostname.somedomain.com] sudo: ls -la
[hostname.somedomain.com] out: sudo password: 

[hostname.somedomain.com] out: Sorry, user username is not allowed to execute '/bin/bash -l -c ls -la' as root on hostname.somedomain.com.
[hostname.somedomain.com] out: 


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: ls -la
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "ls -la"

Aborting.
Disconnecting from hostname.somedomain.com... done.
```
Alas, because Fabric by default prepends /bin/bash -l, suddenly the command doesn't work anymore.  Let's see if I can override that:
```
[username@username-machine ~]$ fab sudo_cmd:'ls -la' -H hostname.somedomain.com -s ''
[hostname.somedomain.com] Executing task 'sudo_cmd'
[hostname.somedomain.com] sudo: ls -la
[hostname.somedomain.com] out: sudo password: 

[hostname.somedomain.com] out: sudo: ls -la: command not found
[hostname.somedomain.com] out: 


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: ls -la
Executed: sudo -S -p 'sudo password:'   "ls -la"

Aborting.
Disconnecting from hostname.somedomain.com... done.
```
This time, it is failing because "ls -la" is double-quoted.  It would have worked fine if the command looked like:
```
sudo -S -p 'sudo password:'   ls -la
```
but I don't know how to get rid of the double quotes, as it is coming in as one-argument from the command line.  Is there a way to get around this issue?  Thanks in advance, as I'm trying to use Fabric instead of looking for a different solution with 1/10th of the feature set.

**Comment by ploxiln** [comment]
`sudo()` also supports most of the options for `run()`, see http://docs.fabfile.org/en/1.12/api/core/operations.html#fabric.operations.run - try adding `shell=False`

```python
sudo("ls -la", shell=False)
```

**Comment by satoshi** [comment]
@ploxiln: thanks for your response.  I'll give it a try and report back here.

**Comment by bitprophet** [comment]
Try setting `env.use_shell = False` (any of the usual option-setting approaches work here, it's a normal option) - looks like that will do away with all of the shell wrapping junk including the double-quotes.

Closing as "nothing to fix" but leaving convo open. ✨

**Comment by satoshi** [comment]
@bitprophet: Thanks for chiming in.  I'm finding that use_shell = False in .fabricrc isn't working, presumably because I am using Fabric 1.6.2.  However, passing in shell = False into the function call did the trick.  Thanks folks for quick responses on this issue.
