### ISSUE TITLE
Fabric compile error: required Info.plist value not found

### ISSUE THREAD

**Issue by Amindv1** [fabric/fabric#1517]
Hi!

I'm trying to build my project but every time I build it I get this error:

```
2016-10-06 15:54:14.090 uploadDSYM[36684:1854760] Fabric.framework/run 1.6 (203)
2016-10-06 15:54:14.097 uploadDSYM[36684:1854760] Launched uploader in validation mode
error: Fabric: Required Info.plist Value Not Found

A CFBundleIdentifier value in your Info.plist is required. Please confirm this value is present in /Users/Amin/Library/Developer/Xcode/DerivedData/BPD-mobile-ahgawajhinuvlfbiyrfyzuqqhqld/Build/Products/Release-iphonesimulator/BPD-mobile.app/Info.plist 
```
I really don't know what's going on. I've checked my info.plist file and there is a NSDictionary titled as Fabric with the API key. I've also tried uninstalling and reinstalling fabric and crashlytics but hat didn't work either. I've installed everything via cocoapods. I also have the most up to date versions (fabric 1.6.9, crashlytics 3.8.2). Any ideas as to why this is causing my project not to compile? If you need more information just ask.

Thanks!

**Comment by Amindv1** [comment]
I also want to mention that Fabric is the last thing that runs in Build Phases. So that's not the issue either.

**Comment by ploxiln** [comment]
that's a totally different "Fabric", it's not related to this project
https://cocoapods.org/?q=fabric
