### ISSUE TITLE
ed25519 type keys not yet supported by Fabric?

### ISSUE THREAD

**Issue by latgarf** [fabric/fabric#1521]
When RSA keys are used, all works fine. When ed25519 key is used instead, the remote server prompts for a password. Is this because ed25519 key support has not yet been implemented in Fabric?

**Comment by bitprophet** [comment]
It's because it's not implemented yet in Paramiko, which is where Fabric gets all of its crypto/SSH support from. Please follow paramiko/paramiko#325.
