### ISSUE TITLE
stderr becomes stdout, is this due to warn_only?

### ISSUE THREAD

**Issue by SwampFalc** [fabric/fabric#1524]
So, I'm building a slightly complex system based on invoke and fabric, with invoke tasks that use fabric as a library in order to call invoke tasks on remote systems.

On the remote system, I have an invoke task that I have tested: if it succeeds, output is sent to stdout, if it fails, output is sent to stderr.

On the local system, I have this invoke task (abridged version):

```python
@invoke.task
def setup_snapshot(ctx, device, size='10G'):
    snapshot = '/usr/local/bin/invoke -r /root fedbackup.setup_snapshot'

    with fabric.quiet():
        result =fabric.execute(
            fabric.run,
            snapshot,
            host=xenhost
        )
    result = result[xenhost]

    print result.stdout or 'stdout'
    print result.stderr or 'stderr'
```

This gives the following output:

```
Logical volume "srv-fhq-file-swap-snapshot" already exists in volume group "vg01"
stderr
```

Which proves that what the remote command sent out on stderr, ends up in the stdout of the result of the fabric.execute call.

For completeness purposes, here's result.__dict__:

```
{'succeeded': False,
'return_code': 5,
'failed': True,
'command': '/usr/local/bin/invoke -r /root fedbackup.setup_snapshot /dev/vg01/srv-fhq-file-swap 10G', 
'stderr': '',
'real_command': '/bin/bash -l -c "/usr/local/bin/invoke -r /root fedbackup.setup_snapshot /dev/vg01/srv-fhq-file-swap 10G"'}
```

I see two possible reasons:

1) quiet() implies warn_only=True, which could be responsible for this. If this is the case, however, I found no trace of this in the documentation...
2) this is due to me giving fabric.run as the first argument to fabric.execute (in order to avoid having to define a separate function)

If it's 1 and it's working as designed, fine, I just need to know I can rely on that.

**Comment by ploxiln** [comment]
the "combine_stderr" setting is True by default in Fabric:
http://docs.fabfile.org/en/1.12/usage/interactivity.html#crossing-the-streams

**Comment by SwampFalc** [comment]
Thanks for pointing me in the right direction; I will close this issue.
