### ISSUE TITLE
OS X Yosemite “sed: illegal option -- r” fatal error

### ISSUE THREAD

**Issue by doflink** [fabric/fabric#1526]
I'm using fabric to deploy a system on MAC. However, I got the following issue.
> [localhost] out: sed: illegal option -- r
[localhost] out: usage: sed script [-Ealn] [-i extension] [file ...]
[localhost] out:        sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
[localhost] out:

> Fatal error: run() received nonzero return code 1 while executing!

The configuration of the machine:
MAC OS: OS X Yosemite
version 10.10.2
Fabric 1.10.2
Paramiko 1.15.2
Python 2.7.10

**Comment by bitprophet** [comment]
Rolling into PR discussion.

**Comment by itBrujo** [comment]
just use 'sed -E' instead 'sed -r'

**Comment by ayobamiseun** [comment]
how do you fix this on vscode
