### ISSUE TITLE
Switch to a different crypto library, as it looks like PyCrypto is no longer maintained.

### ISSUE THREAD

**Issue by dougthor42** [fabric/fabric#1540]
It looks like PyCrypto is no longer maintained (last commit June 20, 2014).

Might I suggest [Cryptography]( https://cryptography.io/en/latest/)? I haven't done the research to see if it has everything you need, but it's definitely maintained and well regarded.

Also, I don't know if you're locked it to PyCrypto because of other dependencies. If so, let me know and I'll go bug them to change :smile:.

**Comment by ploxiln** [comment]
fabric 1.13.1 supports Cryptography instead of PyCrypto (by using paramiko 2.x) see #1461

**Comment by dougthor42** [comment]
Whoops, looks like you guys already did this in !1461. Sorry!

Thanks,

**Comment by dougthor42** [comment]
@ploxiln You just beat me to the punch!
