### ISSUE TITLE
how to use db2 through fabric

### ISSUE THREAD

**Issue by charleshood** [fabric/fabric#1544]
I use the db2 command in my fabfile, while it says db2 : not found. I want to know if it can not use db2 command in fabric.

**Comment by bitprophet** [comment]
Fabric is "just Python" so if you can answer the question "how can I use db2 in a regular Python script?", you've then answered it for Fabric :) I personally have no idea as I've never used db2, but I'm sure Google knows - good luck!

**Comment by charleshood** [comment]
NONONO, I want to use fabric to to connect to the remote database from the remote hosts, not the compute what I run the fabric job.
