### ISSUE TITLE
Fabric does connect but not execute the commands

### ISSUE THREAD

**Issue by asciireign** [fabric/fabric#1546]
I try to use fabric to connect to a router and gather information this way. But it opens the connection and then does nothing until i kill it with crtl+c

I works fine when i try to connect to one of our linux servers

fab --version
Fabric 1.12.0
Paramiko 1.17.2

Fabfile:

```
from fabric.api import env, run, sudo, parallel, execute
import logging
logging.basicConfig(level=logging.DEBUG)
env.user="admin"
env.password="pass"
env.skip_bad_hosts=True
def Uptime():
        run("echo 'EchoOutput'")
        run('uptime')
```

Shell Output:
> root@management-linux:~/scripts/fabric/Fog# fab Uptime -H "192.168.1.1"
> [192.168.1.1] Executing task 'Uptime'
> [192.168.1.1] run: echo 'EchoOutput'
> DEBUG:paramiko.transport:starting thread (client mode): 0xf4a150L
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_1.17.2
> DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_5.5
> INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_5.5)
> DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'arcfour'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'arcfour'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
> DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
> DEBUG:paramiko.transport:MAC agreed: hmac-md5
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.1.1: 2f837fea4a75139b050f7dfdf2daa9f3
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out: Welcome to Router 2012/09/14 00:00:00
> [192.168.1.1] out: systemname is TheRouter
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out: TheRouter:> DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
> DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
keeps on looping the last debug message until i hit crtl+c

Also tryed the following parameters without a change in behaviour:
 --no-pty --abort-on-prompts -I

**Comment by asciireign** [comment]
i can manually input commands while it is connected that way and the router recognizes them.
when i send "exit" it goes to the next task, which is "uptime" in my case.

> [192.168.1.1] out: TheRouter:>exit
> [192.168.1.1] out: DEBUG:paramiko.transport:[chan 0] EOF received (0)
> DEBUG:paramiko.transport:[chan 0] EOF sent (0)
> 
> 
> [192.168.1.1 run: uptime
> DEBUG:paramiko.transport:[chan 1] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 1] Max packet out: 32768 bytes
> DEBUG:paramiko.transport:Secsh channel 1 opened.
> DEBUG:paramiko.transport:[chan 1] Sesch channel 1 request ok
> DEBUG:paramiko.transport:[chan 1] Sesch channel 1 request ok
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out: Welcome to Router 2012/09/14 00:00:00
> [192.168.1.1] out: systemname is TheRouter
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out:
> [192.168.1.1] out: TheRouter:> DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
> DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"

**Comment by ploxiln** [comment]
Your router is not a normal plain unix system on the other side of the ssh connection, it is a specialized command line interface with some built-in commands. I think you need to use something like "expect" to detect the prompt and issue commands.

Fabric uses the shell `/bin/bash` to run commands, by default. I'm guessing your router command line interface does not have direct access to real executables like /bin/bash. You can disable usage of the shell, see http://docs.fabfile.org/en/1.13/api/core/operations.html#fabric.operations.run

The bigger problem is how Fabric tracks execution of the command on the other side of the ssh connection, and waiting for it to finish. It appears the router does not have an ssh server which is as fully functional as a linux/unix system ssh server (e.g. `unhandled channel request "keepalive@openssh.com"`). It doesn't allow to run arbitrary executables on the other side, it only runs the special router command-line interface, automatically.

**Comment by asciireign** [comment]
Thank you for your advice i changed my fabfile to:
```
def BintecUptime():
        sleep(10)
        with settings(prompts={'TheRouter:> ': 'uptime',TheRouter:system> ': 'exit'}):
                run("echo 'hello'")
```
which seams like kind of a dirty hack, but it executes as meant to.

anyone has experience with this kind of setup?

is there a way to maybe use fabric to open the session, wait 5 seconds, send the desired command, wait 5 seconds, send the 'exit' command (which seems to close the session successfully)?

i would like to use it in parallel mode later.

**Comment by bitprophet** [comment]
There's not usually a lot we can do on our end for this sort of appliance based setup (as per @ploxiln ) so closing as "cantfix" but feel free to keep posting if you find useful workarounds.
