### ISSUE TITLE
Support for Fabric tasks methods defined in a class?

### ISSUE THREAD

**Issue by blindenvy** [fabric/fabric#1547]
It would be nice if you could define Fabric tasks as methods in a class instead of just as module level functions. This class-based approach provides the benefits of inheritance and method overriding.

We have several fabric scripts that violate the DRY principal, class based definitions using inheritance would solve this issue nicely. 

Is this a feature that people see as worth while or should this issue be solved differently via existing capabilities?

**Comment by bitprophet** [comment]
Can't find an existing ticket for this but it's been a feature request for years and years. Thanks for articulating it though :)

Best I can find is that it's currently being tracked for 2.0 under the Invoke project: pyinvoke/invoke#347

**Comment by bitprophet** [comment]
Ah yea, that ticket even mentions the one here - #573
