### ISSUE TITLE
No way to force disconnect/reconnect

### ISSUE THREAD

**Issue by benjolitz** [fabric/fabric#1556]
Consider the following case:

```
@task
def setup():
    # ... install docker blah blah
   sudo('usermod -aG docker someuser')

@task
def download_images():
    run('docker pull ubuntu')
```

If you run it via `fab setup download_images`, you will find that it will fail with the error that the user does not have permission to use docker. Upon retrying with `fab download_images`, it works perfectly.

Despite searching the documentation, I've not been able to see a "force reconnection with new session".

**Comment by ploxiln** [comment]
I was inspired by [reboot()](https://github.com/fabric/fabric/blob/1.13.1/fabric/operations.py#L1246) to use `connections.connect(env.host_string)`

```
from fabric.api import task, run, sudo, env
from fabric.state import connections

@task
def addgroup(group):
    sudo("gpasswd -a '%s' '%s'" % (env.user, group))
    connections.connect(env.host_string)

@task
def listgroups():
    run("groups")
```

```
$ fab -H ubuntu@devbox listgroups addgroup:games listgroups
[ubuntu@devbox] Executing task 'listgroups'
[ubuntu@devbox] run: groups
[ubuntu@devbox] out: ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd
[ubuntu@devbox] out: 

[ubuntu@devbox] Executing task 'addgroup'
[ubuntu@devbox] sudo: gpasswd -a 'ubuntu' 'games'
[ubuntu@devbox] out: Adding user ubuntu to group games
[ubuntu@devbox] out: 

[ubuntu@devbox] Executing task 'listgroups'
[ubuntu@devbox] run: groups
[ubuntu@devbox] out: ubuntu adm dialout cdrom floppy sudo audio dip video plugdev games netdev lxd
[ubuntu@devbox] out: 
```

**Comment by benjolitz** [comment]
Surprisingly nonintuitive but that will do it. That works due to the singleton connections instance being a dict-like https://github.com/fabric/fabric/blob/39e6c4d8c0e6db064fd42af18291e15372b42f03/fabric/network.py#L150-L151

Thanks.

**Comment by bitprophet** [comment]
There's also `network.disconnect_all` which is a convenience shortcut for clearing the connection cache (thus forcing reconnects afterwards).
