### ISSUE TITLE
Interaction with remote terminal program

### ISSUE THREAD

**Issue by sixsixtrample** [fabric/fabric#1565]
I am trying to connect to a remote server via ssh, login to a remote program, automate commands from within that program, exit the program, and close the connection.

Currently I can ssh to the machine, and login to the program, but execution stops here because Fabric seems to be looking for a return code from **run** that is not coming back:

`
#assume I am connected to the server

**run('command to log in to program')**

- command prompt would now change from '$' to 'PROG1>'
- I would like **run** to operate in the exact same way as it did before logging in to remote program, but this command:

**run('execute PROG1 thing')**

is never run because the previous **run** command did not return successfully. It stopped before showing the 'PROG1>' prompt
`

Does Fabric have any way to interact with a remote program that is not based on a specific prompt, but continues to send commands as normal until told to stop? I am essentially looking for functionality similar to pExpect's **sendLine** and **expect**. I want to send something, and expect something that may or may not include a newline.

With Paramiko and Fabric debugging on, there is nothing returned, it just hangs after:

**run('command to log in to program')**

**Comment by ploxiln** [comment]
sounds like #1546

**Comment by bitprophet** [comment]
Yea this sounds like ye olde "we're just not set up to deal with nonstandard not-really-a-shell environments", unfortunately. Once 2.x comes out it'll include a more flexible, more expect-y functionality (http://docs.pyinvoke.org/en/latest/concepts/watchers.html basically, except that it'll probably grow to be more mature later) that is probably our best bet for this sort of thing.

The core problem of these remote systems not having clean SSH protocol level per-command sessions (with distinct return/exit values and return of control to caller) will remain, but that's also something the more structured code in 2.x might be able to deal with eventually (e.g. a subclassed Runner that attempts to ignore exit code functionality in favor of detecting when e.g. a remote prompt has changed).

**Comment by sixsixtrample** [comment]
Thanks for the info! I'll look forward to trying it in 2.0.
