### ISSUE TITLE
skipping editor while executing the remote command

### ISSUE THREAD

**Issue by roshu10** [fabric/fabric#1568]
Hi guys,

We are manually doing git pull on 20+ servers.

once the git pull gets completed, it will open some log message in nano editor.

I'm trying to automate the above process.

But the problem is with log messages opening in editor.

Is there any way to skip that part using fabric ?

**Comment by ploxiln** [comment]
This is a git thing. Possibly see http://stackoverflow.com/questions/12752288/git-merge-doesnt-use-default-merge-message-opens-editor-with-default-message#12752379
