### ISSUE TITLE
env.shell is ignored?

### ISSUE THREAD

**Issue by MoeMorox** [fabric/fabric#1575]
Hi there,

I'm trying to deploy my web project with fabric.
I've set `env.shell = '/bin/bash -c'` and I get some weird behaviour:
`run('echo $0')` returns `tcsh`, the default shell on the server.
Later I'm running a git command, which sometimes fails and then says `out: /bin/bash: line 1:  3314 Killed`. This really irritates me, does fabric use the env.shell selectively?
I tried (as suggested in docs) with ssh itself: `ssh user@host "/bin/bash -l -c \"echo $0\""` and it returns `bash` as expected.
Is this normal or am I doing something wrong/missing something?

Thanks for your work BTW!

**Comment by ploxiln** [comment]
The problem could be server-configuration specific. Here's a more detailed way to see what's happening:

```python
from fabric.api import env, task, run, puts

@task
def test():
    print_subtree = "pstree -a | grep -B4 -A1 pstree"

    run(print_subtree)
    env.shell = "/bin/dash -c"
    run(print_subtree)
```

I specified the "dash" shell to differ from the default bash (for my server). But it looks like it works:

```
$ fab --show=debug -H testdeploy03.ec2.st-av.net test
Using fabfile '/Users/pierce/scratch/fabwork/fabfile.py'
Commands to run: test
Parallel tasks now using pool size of 1
[testdeploy03.ec2.st-av.net] Executing task 'test'
[testdeploy03.ec2.st-av.net] run: /bin/bash -l -c "pstree -a | grep -B4 -A1 pstree"
[testdeploy03.ec2.st-av.net] out:   |   `-{rs:main Q:Reg}
[testdeploy03.ec2.st-av.net] out:   |-sshd -D
[testdeploy03.ec2.st-av.net] out:   |   `-sshd 
[testdeploy03.ec2.st-av.net] out:   |       `-sshd  
[testdeploy03.ec2.st-av.net] out:   |           `-bash -l -c pstree -a | grep -B4 -A1 pstree
[testdeploy03.ec2.st-av.net] out:   |               |-grep -B4 -A1 pstree
[testdeploy03.ec2.st-av.net] out:   |               `-pstree -a
[testdeploy03.ec2.st-av.net] out:   |-systemd --user
[testdeploy03.ec2.st-av.net] out: 

[testdeploy03.ec2.st-av.net] run: /bin/dash -c "pstree -a | grep -B4 -A1 pstree"
[testdeploy03.ec2.st-av.net] out:   |   `-{rs:main Q:Reg}
[testdeploy03.ec2.st-av.net] out:   |-sshd -D
[testdeploy03.ec2.st-av.net] out:   |   `-sshd 
[testdeploy03.ec2.st-av.net] out:   |       `-sshd  
[testdeploy03.ec2.st-av.net] out:   |           `-dash -c pstree -a | grep -B4 -A1 pstree
[testdeploy03.ec2.st-av.net] out:   |               |-grep -B4 -A1 pstree
[testdeploy03.ec2.st-av.net] out:   |               `-pstree -a
[testdeploy03.ec2.st-av.net] out:   |-systemd --user
[testdeploy03.ec2.st-av.net] out: 


Done.
Disconnecting from testdeploy03.ec2.st-av.net... done.
```

**Comment by MoeMorox** [comment]
Well, the server doesn't even have ps installed not to mention pstree..
However I just tested, when logged in via ssh in tcsh running `/bin/bash -c "echo \$0"` also returns -tcsh, so it really seems they have a really weird configuration.

Thanks for the super fast reply!

**Comment by MoeMorox** [comment]
Sorry for the inconvenience, I just saw this:
`/bin/bash -c "echo $0"` -> `-tcsh`
_but_
`/bin/bash -c 'echo $0'` -> `/bin/bash`

Is it possible to change the double quotes to single ones?

**Comment by ploxiln** [comment]
Fabric escapes commands to run in the shell where appropriate. `--show=debug` will show you:

```
$ fab --show=debug -H testdeploy03.ec2.st-av.net test
Using fabfile '/Users/pierce/scratch/fabwork/fabfile.py'
Commands to run: test
Parallel tasks now using pool size of 1
[testdeploy03.ec2.st-av.net] Executing task 'test'
[testdeploy03.ec2.st-av.net] run: /bin/dash -c "echo \$0"
[testdeploy03.ec2.st-av.net] out: /bin/dash
...
```

So, it seems the command run on the other side of the ssh connection is obligated to run under the default/login shell of the user. Fabric seems to exec the desired shell wrapper under that, given the actual command string as an argument. I think my process tree output from above is a bit misleading, because the default/login shell was temporarily in it, but that process was replaced by `env.shell` with an "exec", before pstree printed out.

The problem for your case could be that the escaping is not completely compatible with tcsh. You might be able to change your default/login shell with `chsh`. Failing that, your best bet may be to set `env.use_shell = False` and use correct syntax / escaping for having all your commands run directly by tcsh.

**Comment by MoeMorox** [comment]
`chsh` isn't available either but `env.use_shell = False` does the trick.
Thanks for your time and effort and have a nice day!
