### ISSUE TITLE
singleton env cause problem where used as lib in concurrent situations?

### ISSUE THREAD

**Issue by wingyiu** [fabric/fabric#1579]
i would like to use fabric lib mode in devops web platform, i want to know will the singleton `env` cause problem where used as lib in concurrent situations?

**Comment by bitprophet** [comment]
Yes, it can definitely cause threading issues, which is why our parallel feature uses `multiprocessing`, and why version 2 (alpha soon) does away with it entirely (allowing threads and anything else one might want).
