### ISSUE TITLE
Bash shellshock fix breaks environment parsing/passing

### ISSUE THREAD

**Issue by MarkAhlstrom** [fabric/fabric#1582]
Using the SLES build of fabric in SP2, our python scripts using the fabric library.  To reproduce: 

On a recent build of bash, export a function with declare -x -f NAME and then run the fabric based connection to the remote.  Passing the environment variables results in the following error:
/bin/bash: -c: line 0: unexpected EOF while looking for matching ``'
/bin/bash: -c: line 2: syntax error: unexpected end of file

My local patch was to add the following into the _prefix_env_vars function in operations.py just before updating the env_vars
```python
    # Strip bash functions to account for bash changes with regards to the shellshock bug
    for key,value in env.shell_env.items():
        if key.startswith('BASH_FUNC_'):
            del env.shell_env[key]
```
This still leaves the limitation that exported bash functions are not exported to the remote.

I can submit a pull request when I get some extra time.

**Comment by ploxiln** [comment]
This does not happen for me.

I didn't think that local environment variables were passed across to the remote system by default. How are you passing them? On the other side, they are limited by sshd's `AcceptEnv` config setting.

```
$ somefunc() {
> echo bash function ran
> }
[pierce@plo-pro fabwork]$ somefunc
bash function ran
[pierce@plo-pro fabwork]$ declare -x -f somefunc
[pierce@plo-pro fabwork]$ env | grep BASH
BASHRC_NUM_CORES=2
BASHRC_UNAMESTR=Darwin
BASH_FUNC_somefunc%%=() {  echo bash function ran
[pierce@plo-pro fabwork]$ bash -c somefunc
bash function ran
[pierce@plo-pro fabwork]$ fab -H testdeploy05.ec2.st-av.net test
[testdeploy05.ec2.st-av.net] Executing task 'test'
[testdeploy05.ec2.st-av.net] run: env
[testdeploy05.ec2.st-av.net] out: XDG_SESSION_ID=18317
[testdeploy05.ec2.st-av.net] out: SHELL=/bin/bash
[testdeploy05.ec2.st-av.net] out: TERM=vt100
[testdeploy05.ec2.st-av.net] out: SSH_CLIENT=158.106.212.130 3108 22
[testdeploy05.ec2.st-av.net] out: SSH_TTY=/dev/pts/0
[testdeploy05.ec2.st-av.net] out: USER=pierce
[testdeploy05.ec2.st-av.net] out: PATH=/home/pierce/bin:/home/pierce/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
[testdeploy05.ec2.st-av.net] out: MAIL=/var/mail/pierce
[testdeploy05.ec2.st-av.net] out: PWD=/home/pierce
[testdeploy05.ec2.st-av.net] out: LANG=en_US.UTF-8
[testdeploy05.ec2.st-av.net] out: HOME=/home/pierce
[testdeploy05.ec2.st-av.net] out: SHLVL=2
[testdeploy05.ec2.st-av.net] out: LOGNAME=pierce
[testdeploy05.ec2.st-av.net] out: SSH_CONNECTION=158.106.212.130 3108 172.31.47.190 22
[testdeploy05.ec2.st-av.net] out: XDG_RUNTIME_DIR=/run/user/1003
[testdeploy05.ec2.st-av.net] out: _=/usr/bin/env
[testdeploy05.ec2.st-av.net] out: 


Done.
Disconnecting from testdeploy05.ec2.st-av.net... done.
```

**Comment by MarkAhlstrom** [comment]
We are passing the environment variables. That's what that portion of operations.py does at least, prefixing the command with the environment variables. It's possible there is also a difference in function syntax.

Our function is essentially:
----
func() {
    eval `cmd bash $*`
}

That's consistently getting parsed with the trailing \n, which breaks the command line.

We're adding the environment to the context manager like so (managers is the var for context managers):

managers.append(shell_env(**outenv))

We add escapes to the special characters in the environment producing outenv so that setting them on the other side works as expected.

Only other main differences is that we exercise all of this through a python script calling the libraries directly. This worked on previous versions of bash.

**Comment by ploxiln** [comment]
I see, [fabric.context_managers.shell_env](http://docs.fabfile.org/en/1.13/api/core/context_managers.html#fabric.context_managers.shell_env), I wasn't aware of that feature.

It's worth clarifying that this is only a problem if you gather all environment variables, and add them all to some commands with this context manager, and you export some bash functions. Honestly, those are both generally bad ideas.

The proper fix would be to fix the escaping. The best work-around is for you to filter out the problematic variables before passing them to the context manager.

**Comment by MarkAhlstrom** [comment]
It seems that documentation of that limitation would be helpful, since I can see attempting to export a bash function as something someone may want to do.

Adding basically the entire environment is a requirement of our use case.
