### ISSUE TITLE
Netapp Cluster Mode deployment automation

### ISSUE THREAD

**Issue by metro1234** [fabric/fabric#1585]
Hi Team,

I am implementing Netapp ontap Clustermode deployment automation using fabric.

Still now I have not seen any issues I have implemented half of my code, but still i need get confirmation with you folks that it is recommended to use Fabric for deployment automation and Fabric is tested with Netapp ontap cluster mode OS.

Please help

**Comment by ploxiln** [comment]
I am not familiar with "Netapp ontap Cluster mode OS", but I'm pretty sure Fabric is not tested against it. If it's not a real unix-like shell environment (with real binaries and such), it may not work, see #1546
