### ISSUE TITLE
env.timeout has no effect on paramiko's client.connect(timeout=xxx), ends up prompting user for password after "paramiko.SSHException: No existing session"

### ISSUE THREAD

**Issue by albertferras** [fabric/fabric#1600]
Hi, I have a process which launches many fabric tasks in parallel to multiple servers (>50 per host) and everything ends up failing because paramiko raises an exception "paramiko.SSHException: No existing session" which fabric tries to handle by prompting the user for password. This prompt is raised on every process and I have abort_on_prompts=True because it's an automated process.
This works perfectly if number of parallel fab executions is reduced to <10. I've already modified sshd_config's MaxSessions and MaxStartups with no luck.

After digging into fabric and paramiko's sourcecode, this is what I've found:

1 - Fabfile calls paramiko.client.SSHClient.connect here https://github.com/fabric/fabric/blob/master/fabric/network.py#L481 with timeout=10 (default)
2 - Paramiko calls `Transport.get_remote_server_key` here https://github.com/paramiko/paramiko/blob/master/paramiko/client.py#L342
3 - get_remote_server_key raises 'No existing session' here: 
https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L661 .

The reason for this is because Transport.start_client() timed out and no exception was raised (for whatever reason, self.active is kept as True). The reason for which it times out is because the remote machine is very busy at 100% cpu
After this, fabric does not do any kind of check to see if the connection is correct or we've timed out.

What I would expect here is Fabric notices about something being wrong and retry the connection (without prompting user for password) because it just timed out, not failed on authenticating. 

From what I've seen, paramiko always raises `SSHException('No existing session')` everytime it thinks the start_client failed. Maybe it would be a good idea to parse this specific error message here https://github.com/fabric/fabric/blob/master/fabric/network.py#L499 and go directly to retry reconnecting without prompting for password/

Workaround:
Changing env.timeout to a higher value fixes the problem (`No existing session` exception disappears).

*Reproducing the issue*:
Previously added local machine's root pubkey to remote machine's authorized_keys.

fabfile.py:
```
from fabric.api import (env, local, run, lcd, cd, prefix, get, put, settings, roles,
                        task, execute, parallel, abort)
import paramiko
import logging
logging.getLogger('paramiko').setLevel(logging.DEBUG)
logging.getLogger('paramiko.client').setLevel(logging.DEBUG)
logging.getLogger('paramiko.transport').setLevel(logging.DEBUG)
paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)

env.pty = False
env.shell = '/bin/bash -c'
env.abort_on_prompts = True
env.use_ssh_config = True
env.combine_stderr = True
env.user = 'root'
env.keepalive = 15
env.connection_attempts = 10

@task
def test():
    run('echo "1"')
    run('sleep 10')
    run('echo "2"')
```

test.sh:
```
#!/bin/bash

for run in {1..100}
do
  fab -f fabfile.py test -H othermachine &
done
wait
```

**Comment by bitprophet** [comment]
Either #1475 or #1347 should probably solve this.
