### ISSUE TITLE
fabric 2 connection does not the password arg 

### ISSUE THREAD

**Issue by pint12** [fabric/fabric#1604]
in fabric 1 i could directly put the password in the settings context .
it seems that in fabric 2 there is no way to put the direct password in the connection .

**Comment by bitprophet** [comment]
@pint12 You should be able to use the `connect_kwargs` `Connection` init param for this, e.g. `cxn = Connection(user='foo', connect_kwargs={'password': 'mypass'})` ought to work similarly to Fabric 1 re: submission of password auth.

**Comment by pint12** [comment]
tried as you suggested and hot this err 


from fabric import connection


with connection.Connection(host="user@host", connect_kwargs={"password": "password"} ) as c :
    r = c.run('pwd')
    print r

AttributeError: 'Channel' object has no attribute 'update_environment'

**Comment by pint12** [comment]
Plz reopen issue

**Comment by bitprophet** [comment]
@pint12 You're probably on a too-old Paramiko version, you need to be on, IIRC, 1.18+ or 2.1+.

**Comment by pint12** [comment]
thanks @bitprophet  it works now .  i think you should add the  praimko to the requirement file. 
i was sure it is their so i didn't bothered to  check. :+1: 

BTW 
 how  can i set fabric and fabric2 to work in prallel on **windows** i was trying to set the 
env_wants_v2 = os.environ.get('PACKAGE_AS_FABRIC2', **True**)
but it didnt work

**Comment by bitprophet** [comment]
Hm, Paramiko is in Fabric 2's `setup.py` and does say it requires `>=2.1`, so actually not sure how you ended up with an older version!

Afraid I don't know how Windows handles environment variables, I would assume they appear in `os.environ` as on Unix, but really not sure. I looked in Python's docs and found [this page](https://docs.python.org/2/using/windows.html#excursus-setting-environment-variables) which makes it seem like you can do something like `set PACKAGE_AS_FABRIC2;C:\path\to\pip install`, but I can't test that myself.

**Comment by pint12** [comment]
what should be the value of PACKAGE_AS_FABRIC2 ? 
i thought it is a Boolean value ....

**Comment by bitprophet** [comment]
It can be anything that isn't the empty string, so it can be `"1"` or `"yes"` or anything!
