### ISSUE TITLE
Make it easier to set password auth in v2

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#1605]
## Background

Right now, password auth (vs key auth) is a bit stinky, to wit:

- You have to use `Connection(connect_kwargs={'password': 'mypass'})`, period, right now - there is no prompting, etc.
  - Though you can use the configuration system; but that still doesn't work great when you really want runtime, one-time, non plaintext, password entry.
- `connect_kwargs` is not very visible in the docs (it's not in the tutorial or even in the body of the Connect docstring; only in the `__init__` apidoc), which makes the above not-great
- It's not even possible to set `connect_kwargs` easily in the non-lib/pure-cli use case, because `__init__` is called on your behalf by `FabExecutor`. It's possible to modify the `Connection` object given as the task context, from inside the task and before you try calling `run`/etc, but that's a grody antipattern.

## Solution(s)

- Seems best to reinstate v1's password prompt in some fashion, in core, that occurs somewhere between `Program` and `Executor`.
- v1's lazy behavior has always been pretty crummy so it should definitely happen up front, like `fab -I` in v1, and therefore opt-in.
- It'd be nice to detect the situation of "no keys + no password = auth error" and highlight to the user that they may have wanted to supply the password or the prompt-me-plz flag, because right now they'll just get Paramiko's semi obtuse auth error if they are talking to eg a brand new system with no keypair set up.

**Comment by bitprophet** [comment]
This is mostly solved now! 2.0 released with a `--prompt-for-login-password` (plus similar for passphrase and sudo password, latter inherited from Invoke) which matches v1's similar option for up-front prompting.

So if users don't want to use the config system (including environment vars) this is the proper way to enter such info at runtime.

Improved detection of "missing" auth will be its own thing and largely dependent on an upcoming Paramiko feature-add.

**Comment by DylanYoung** [comment]
@bitprophet Any chance of making this a config option?  is a bit a annoying to type it everytime...  I can do up a PR if it would be welcome.

**Comment by bitprophet** [comment]
@DylanYoung Using `connect_kwargs.password` should work for that. See https://docs.fabfile.org/en/2.4/concepts/configuration.html?highlight=connect_kwargs#new-default-values-defined-by-fabric

**Comment by DylanYoung** [comment]
That's great! Thanks.  I'll do up a PR for you if i can make the time.   

The issue with doing it manually, which i did try,  is that even if a flag like `--help` is passed, it'll still unnecessarily prompt for the password.

**Comment by bitprophet** [comment]
That seems like an arguably unrelated bug (but it's also an odd one, I just peeped the code both here and in Invoke and it doesn't look it should call getpass if you did pass --help. I'm probably not digging deep enough.) At any rate, yes please file a PR if you can, and @ me w/ a link to this issue so I remember this discussion :)

**Comment by DylanYoung** [comment]
Oh sorry for the confusion.  I mean, if I try to manually hook in and prompt the user for their password, there's no way for me to do it conditionally based on the `--help` flag (without hacking `sys.argv` or overriding the entire `Program` object) or something ugly like that.  Maybe I could make a new executor class, but I'm not sure where I would hook in, so it seems like it would be valuable as a config option.  No issue with the current `cli` option though. It works as intended and the password is bypassed with `--help`.
