### ISSUE TITLE
env.hosts not updated when subsequent parallell tasks are run

### ISSUE THREAD

**Issue by WimRoose** [fabric/fabric#1608]
Hi All

I've noticed something weird when executing parallell tasks in serial: env.hosts is not updated, and second task is executed on same hosts as first task. Some code:

```
def _setEnvHosts(machine_type=None, keep_alive_priority=100):
	servers = config.get_machines(machine_type, keep_alive_priority)
	for server in servers:
		env.hosts.append(server.host)
		env.passwords[server.host + ':22'] = server.password 
```
```
@parallel
def _getFootprint(command, timeout=10):
	# ignore errors by offline hosts
	logger.info("Getting (%s) footprint of %s" % (command, env.host))
	env.skip_bad_hosts = True
	with hide('output'):
		# ignore exit codes > 0
		with settings(warn_only=True):
			try:
				footPrint = run(command, timeout=timeout)
				with open(config.path_to_footprints + command + env.host +'.log', 'w') as file:
					file.write(footPrint)
			except CommandTimeout as e:
				logger.error("_getFootprint command on host %s timed out!" % env.host)
```
```
execute(_getFootprint, command='ps aux', timeout=5, hosts=_setEnvHosts(keep_alive_priority = 15))
# env.hosts=[]
execute(_getFootprint, command='smbstatus', timeout=5, hosts=_setEnvHosts(machine_type='sambaserver'))

```
Second command is executed on same hosts as first. When I put env.hosts=[] between them, all's fine. It started going weird when adding the CommandTimeout exception - though I don't know if it has anything to do with it.

**Comment by ploxiln** [comment]
When you write `hosts=_setEnvHosts(...)` that's misleading. Your function `_setEnvHosts()` is not returning a host list, it is setting a global host list, and returning `None`. It would be equivalent to just do

```python
_setEnvHosts(machine_type='sambaserver')
execute(_getFootprint, command='smbstatus', timeout=5)
```

Your function `_setEnvHosts()` just appends to the global list of hosts, it does not replace it. That's why the second command runs on the same hosts as the first.

**Comment by WimRoose** [comment]
Hi @ploxiln 

That's kind of obvious indeed. Should have noticed that myself..

Thanks anyway!
