### ISSUE TITLE
Question: Is Fabric support Multistage ssh via different account ?

### ISSUE THREAD

**Issue by kizuka-sst** [fabric/fabric#1612]
* local -> gw -> target
* gw account: user1/pass1
* target account: user2/pass2

This environment, Can I use Fabric via multistage ssh access ?
Please teach me how (example code etc...).

I can't use ssh key-based access.
Thanks.

**Comment by ploxiln** [comment]
Yes. See http://docs.fabfile.org/en/1.13/usage/env.html#gateway

You can specify the username in front of the hostname, like:

```
fab --gateway=user1@gw-server -H user2@target-server taskname
```

You can also specify gateway in the fabfile, like

```python
from fabric.api import env, task, run

env.gateway = "user1@gw-server"

@task
def taskname():
    run("uptime")
```

Fabric will prompt you for each password needed, if you don't use key-based access.

**Comment by kizuka-sst** [comment]
@ploxiln Thank you very much.
This is point host_string and env.gateway include "user@" strings.

**Comment by ocswor** [comment]
@ploxiln  I have  another question
local -> gw -> target
gw account: user1/sshconfig     sshconfig in local 
target account: user2/sshconfig sshconfig in gateway

how to run task on the target  ?
