### ISSUE TITLE
README says Group should receive a list of strings while the current implementation expects *args

### ISSUE THREAD

**Issue by seocam** [fabric/fabric#1620]
V2 README file says:

```python

Group(['web1', 'web2', 'db1']).run('df -h')
``` 

While the current implementation requires:

```python

Group('web1', 'web2', 'db1').run('df -h')
``` 

I'm aware that the `run` method is not implemented in the Group class so none of those would work anyway.

**Comment by bitprophet** [comment]
I feel like somebody mentioned this at PyCon sprints but we all forgot about it. Will go change that now. Thanks!

**Comment by bitprophet** [comment]
Love when a two line README format fix triggers about a day's worth of futzing because you noticed, oh, the client library your code is based on got a li'l refactor the other week. And broke things. All fixed now ![](http://i.somethingawful.com/forumsystem/emoticons/emot-toot.gif)
