### ISSUE TITLE
`sudo_prompt` echoes the password

### ISSUE THREAD

**Issue by varunagrawal** [fabric/fabric#1622]
I am on python 2.7.12 running on Ubuntu 16.04. I have Fabric 1.13 installed.

The bug is that when I run a `sudo()` operation, the `sudo_prompt` password is echoed back to me in plaintext.

Here is a simple piece of code to reproduce:

```python
from __future__ import with_statement
from fabric.api import task, run, sudo, env
from fabric.contrib.console import confirm
import getpass

env.password = getpass.getpass("Password: ")
env.sudo_prompt = env.password
env.hosts = ["test_host"]
env.user = "username"

def list_contents(username="$USER"):
    sudo("ls")
```

My output is:

```shell
[minsky5.cc.gatech.edu] Executing task 'add_docker_user'
[minsky5.cc.gatech.edu] sudo: ls
[minsky5.cc.gatech.edu] out: <Password123>
[minsky5.cc.gatech.edu] out: index.html  index.html.1  index.html.2	jupyterhub  __pycache__  scribbler.tar	test_site.py
[minsky5.cc.gatech.edu] out: 
```

**Comment by bitprophet** [comment]
`env.sudo_prompt` isn't the password, though! It's literally the sudo _prompt_ text. You should normally never need to touch it. This ought to work fine if you simply remove the `env.sudo_prompt = env.password` line.

**Comment by varunagrawal** [comment]
`sudo_prompt` is what gets filled for `sudo -S`. Shouldn't it be sudo_password?

**Comment by bitprophet** [comment]
Not quite, it's what gets filled for `sudo -p`, i.e, what prompt text sudo should display to the "user" (in this case, that's Fabric, which now knows what to look for in the remote stdout/err so it can autofill your password.)

The actual literal password comes from `env.password` (or, if you've set it, `env.sudo_password`).

**Comment by varunagrawal** [comment]
I tried filling in `env.sudo_password` but the script still prompts me for a password on the remote server to perform the sudo operation. That doesn't seem to align with what the documentation says.

**Comment by marthjod** [comment]
I see the same behavior as @varunagrawal, i.e. getting an (initial) sudo password prompt even though `env.sudo_password` is pre-filled.

**Comment by bitprophet** [comment]
I can't replicate that on my end, @marthjod, a trivial fabfile which looks like this, works fine:

``` python
from fabric.api import task, env
@task
def wat():
    env.sudo_password = 'mypass'
    sudo("whoami")
```

Output is:

```
» fab -H host wat               
[host] Executing task 'wat'     
[host] sudo: whoami             
[host] out: sudo password:      
[host] out: root                
[host] out:                     
                                     
                                     
Done.                                
Disconnecting from localhost... done.
```

Confirmed that in this test case, `env.password` is `None`.

**Comment by varunagrawal** [comment]
@bitprophet can you please check if you're using the same version of Python and Fabric as I am? I would like to eliminate any false positives.

**Comment by bitprophet** [comment]
2.7.12 and Fabric master, which at the moment resembles the 1.13.2 release + some doc-only changes.

**Comment by varunagrawal** [comment]
Okay, I just checked with your version and I changed `sudo_prompt` to `sudo_password`, and everything seems to work great! Even the docs have the correct information so this bug is no longer valid.

Thank you very much for you time and patience @bitprophet. Hope to see Fabric for Python3 out soon. :slightly_smiling_face:
