### ISSUE TITLE
Fabric Run Hanging

### ISSUE THREAD

**Issue by gabrielschickling** [fabric/fabric#1623]
I'm having issues with my script hanging on a run command and was wondering a way to get around it, i searched tons of forums and documentation and still have not come up with the solution.

To give context i'm working on a script that configures Ubiquiti Edgerouters

the problem is , part of my script deletes the interface port that i'm currently plugged into, so when i run the command to commit changes the run command just hangs.

I tried using the timeout feature but that closes the script completely, is there a way to timeout a run command and then continue on in the script?

Thanks,

**Comment by ploxiln** [comment]
Try putting the run-with-timeout in a try-catch block.

**Comment by bitprophet** [comment]
Yup, you should be able to catch an exception on timeout and try again, as with any other Python code :)

The exception might have to be really broad, like `SystemExit`, which is unfortunate, but if you keep it limited to just around a specific `run` call or two...maybe not so bad :D
