### ISSUE TITLE
Text move to right after increasee font size in fabirc js canvas

### ISSUE THREAD

**Issue by rbissa** [fabric/fabric#1624]
I am drawing a wedding card using fabric js on canvas in magento, i have facing a strange problem when i open canvas in iphone the large font move to right but in other browser it works fine. I checked in browserstack and other simulator but it only problem in iphone actual device. I am just going to attach both screenshot of iphone and chrome browser, if anyone have any solution please comment. 

Chrome image in this "Lachla" text showing in center : https://i.stack.imgur.com/fTaEB.png

iPhone image in this "Lachla" text showing in right : https://i.stack.imgur.com/EZKHB.png 

so after every letter increase text align to right by font size only in iphone.

**Comment by ploxiln** [comment]
This is not a github repo for https://get.fabric.io/ - you have found the wrong "fabric".
