### ISSUE TITLE
password + google 2-factor failing (Fabric 1.13.2 + paramiko 2.2.1)

### ISSUE THREAD

**Issue by kevinwaddle** [fabric/fabric#1625]
We are setting up some servers to add google's 2-factor auth. This is now working with straight ssh logins. The sshd servers are not going to be set up to require using key based auth.

After issuing a Fabric command I am first asked for "Passphrase for private key:", then it loops on "Login password for 'user':"

I found issue #1202 and the corresponding paramiko/paramiko#467 changes that were added to address problems with Fabric and 2-factor auth. But it seems to be focused on pubkey + 2-factor only?

Should there be an expectation of password + 2-factor auth being workable with Fabric at this time?

Thanks!

**Comment by ploxiln** [comment]
what you want is https://github.com/paramiko/paramiko/pull/914

**Comment by kevinwaddle** [comment]
Yes. I want this merged in and released.

**Comment by kevinwaddle** [comment]
So I am trying again with this pull request (paramiko/paramiko#914) rebased against current origin/master and installed into my virtualenv with `python setup.py develop`. I see the same prompts and behavior.

> After issuing a Fabric command I am first asked for "Passphrase for private key:", then it loops on "Login password for 'user':"
