### ISSUE TITLE
 Problem env.hosts add ip

### ISSUE THREAD

**Issue by pierreousset** [fabric/fabric#1627]
Hello we add hosts in our env.hosts with env.hosts.extend (extend) but when we launch a command ex: ls
It does not find me ip
No hosts found. Please specify (single) host string for connection:

Est il possible de rajouter des ip en cours ?
Thank you in advance

**Comment by ploxiln** [comment]
Can you provide a minimal self-contained `fabfile.py` showing this behavior?

**Comment by pierreousset** [comment]
Thank you very much I just found the error is a ereur my share
