### ISSUE TITLE
how not to let fabric api to wait for execution completion?

### ISSUE THREAD

**Issue by thinksabin** [fabric/fabric#1628]
Hi,
sorry this must be the dumb question. But I am facing some issue regarding the running the task through fabric api.

i am using:
execute(getattr(fabfile, 'copy_run_patch'), patch_file)

to run the task mentioned in copy_run_patch. Copy_run_patch uses the run() to initiation bash script that does installation and changes in the target machine and it takes 2-3 hours for that. Until installation is done all i get is "message:Installation is in progress."

is there any way, i can execute the task in the remote target machine and dont wait for it to complete and move on ?? I just need to trigger the bash script and move on without caring about its success or failure.

thanks

**Comment by ploxiln** [comment]
see http://www.fabfile.org/faq.html#why-can-t-i-run-programs-in-the-background-with-it-makes-fabric-hang
