### ISSUE TITLE
`sudo` with `cd` context manager

### ISSUE THREAD

**Issue by ambsw-technology** [fabric/fabric#1630]
I'm having issues mixing the `cd` context manager with `sudo`.  Specifically, the following code:

    with cd('$HOME/{}'.format(release)):
         sudo('./configure')
         sudo('make')
         sudo('make install')

is producing the following error:

> [172.24.0.10] out: sudo: cd: command not found
> ...
> Requested: ./configure
> Executed: sudo -S -p 'sudo password:'  cd $HOME/openssh-7.3p1 && ./configure

I tried `shell=False` to see if it would move the sudo to the internal command, but that didn't help.

**Comment by ploxiln** [comment]
Try with `shell=True` (maybe shell is defaulting to False because env.use_shell was set to False?) - it will form commands like `sudo bash -l -c "cd $HOME/openssh-7.3p1 && ./configure"`

**Comment by ambsw-technology** [comment]
That fixed it. As far as I can tell, we're not changing any defaults so I'm not clear why this isn't working "out of the box".

**Comment by ambsw-technology** [comment]
We had a wrapper to deal with some other issue (I think backtick escaping) so I've sorted out the issue.
