### ISSUE TITLE
fabric.api.get do not get the remote file mode

### ISSUE THREAD

**Issue by pysnow530** [fabric/fabric#1633]
When I download a executable file(0755) using `fabric.api.get()` from the remote server, the result file's mode is 0644. The executable flag is lost.

Maybe I lost an option? Or how could reserve the remote file mode?

**Comment by bitprophet** [comment]
No, you're not wrong, `get` does not seem to have its own version of `put(mirror_local_mode=True)`. Thanks for the catch!

For what it's worth, you can of course use `os.chmod` to work around this in the meantime.

**Comment by nikshepsvn** [comment]
@bitprophet is this still open? this would be my first open source contribution!

**Comment by ploxiln** [comment]
looks like someone recently made an attempt at this in #1649

**Comment by nikshepsvn** [comment]
is this still open? would love to give this a shot! can someone give me an idea of how to start off?

**Comment by adrianyi** [comment]
it appears someone already implemented this, you can see how he did it [here](https://github.com/fabric/fabric/pull/1649/commits/bb08697452e801258f213412af777e023d94b756)

**Comment by AdamDonna** [comment]
This appears implemented with https://github.com/fabric/fabric/pull/1649. Can we mark this as closed so new devs looking for "Low hanging fruit" don't get mislead?

**Comment by pysnow530** [comment]
Thanks for reminding, @AdamDonna , closed!

**Comment by pysnow530** [comment]
Thanks for reminding, @AdamDonna , closed.
