### ISSUE TITLE
How to reboot with parallel

### ISSUE THREAD

**Issue by 631068264** [fabric/fabric#1635]
```
@task()
@hosts(host)
@parallel
def init():
    do sth .......
    sudo('reboot')

```
And when one of server execute reboot the fab session was closed so other server can't continue

**Comment by ploxiln** [comment]
Have you tried [fabric.operations.reboot](http://docs.fabfile.org/en/1.13/api/core/operations.html?highlight=reboot#fabric.operations.reboot)?
(and see also #1488)
