### ISSUE TITLE
How to ignore ansible SSH authenticity checking?

### ISSUE THREAD

**Issue by 631068264** [fabric/fabric#1636]
```
GATHERING FACTS ***************************************************************
The authenticity of host 'xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx)' can't be established.
RSA key fingerprint is xx:yy:zz:....
Are you sure you want to continue connecting (yes/no)?
```
My task was aborted by this problem

**Comment by ploxiln** [comment]
You appear to be using Ansible, not Fabric.

**Comment by ploxiln** [comment]
To clarify: both ansible and fabric use https://github.com/paramiko/paramiko - ansible does not use fabric. So this is the wrong repo to ask this question in.

Paramiko can have different "missing host key policies" plugged in. This is not one of the ones included in paramiko. So this is completely within the realm of Ansible. (I think ansible might be able to use the openssh client directly too, and this looks a lot like output from openssh.)

**Comment by bitprophet** [comment]
Also, FWIW, Fabric defaults to auto-adding previously-unseen hosts to one's known_hosts file (i.e. it selects Paramiko's `AutoAddPolicy` as mentioned above) unless one turns that behavior off. So if one was using vanilla Fabric this sort of prompt should not typically appear.
