### ISSUE TITLE
Multiple items in a @roles, how to get current index?

### ISSUE THREAD

**Issue by avoidik** [fabric/fabric#1641]
Let's define simple task:
```
@task
@roles("a","b")
def deploy_task():
  run('hostname')
```

How to get current role position from array? `env.effective_roles` returns whole array, without index. Right now I'm using approach provided below, but is there are any simpler way?
```
def get_current_role():
    for role in env.roledefs.keys():
        if env.host_string in env.roledefs[role]['hosts']:
            return role
    return None
```

**Comment by bitprophet** [comment]
I don't think there's a better way at present, the roles machinery is relatively simplistic & wasn't set up for this kind of introspection. Seems likely that a post-2.0 feature release might make this more reasonable though. Going to close this as "non-actionable" but I'm sure if other folks run across it & have found different workarounds, they'll share. Thanks!
