### ISSUE TITLE
frabric2 fails on windows

### ISSUE THREAD

**Issue by wyamyy** [fabric/fabric#1647]
D:\my_tool\fabric>fab
Traceback (most recent call last):
  File "C:\Python27\Scripts\fab-script.py", line 11, in <module>
    load_entry_point('fabric==2.0.0', 'console_scripts', 'fab')()
  File "C:\Python27\lib\site-packages\invoke\program.py", line 274, in run
    self.create_config()
  File "build\bdist.win32\egg\fabric\main.py", line 74, in create_config
  File "C:\Python27\lib\site-packages\invoke\config.py", line 109, in __getattr_
_
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'load_base_conf_files'

Valid keys: []

Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_dat
a', 'global_defaults', 'load_collection', 'load_defaults', 'load_overrides', 'lo
ad_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system',
 'load_user', 'merge', 'paths', 'pop', 'popitem', 'prefix', 'set_project_locatio
n', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']

**Comment by bitprophet** [comment]
Can you post the output of `fabric -V` (assuming that works w/o an exception; it probably will) and `pip list` (or equivalent for however you manage Python packages)? That does not look like a Windows specific error, but the latest `invoke` release and the HEAD of fabric `v2` branch together, seem to work fine, so I wonder if you have an older Invoke version. (Should be 0.20-ish.)

**Comment by wyamyy** [comment]
It's invoke-0.20.3 before. And "fab -V" works after I installed invoke-0.20.4. 
D:\2_CBS\tool_in_dev>fab -V
Fabric 2.0.0
Paramiko 2.2.1
Invoke 0.20.4

But my fabfile.py doesn't work, even like this:
from fabric import * 
    
def hello():
    print( "world" )

**Comment by ploxiln** [comment]
fabric v2 has some big changes: http://docs.fabfile.org/en/v2/upgrading.html#cli-tasks

**Comment by bitprophet** [comment]
@wyamyy Yup the 0.20.3 -> 0.20.4 Invoke change was what I was looking for, so that was the cause of your first problem :) As for the second, see above, there are a lot of changes so see the upgrade docs! Thanks.
