### ISSUE TITLE
`execute()` hangs on big hosts list

### ISSUE THREAD

**Issue by arossert** [fabric/fabric#1650]
I'm using `execute()` to run a task on a big hosts list (~20K) and export a report on all servers.

It seems that all the tasks being executed but the `execute()` function never returns and the main `fab` process won't finish.

After examination, it seems that there are some `fab` jobs (`ps -ef | grep fab`) that didn't close.
I'm using the latest 1.13.2 release, this is my configuration:
```
# Fabric settings
class FabricException(Exception):
    pass

env.abort_exception = FabricException
env.warn_only = True
env.skip_bad_hosts = True
env.abort_on_prompts = False
env.disable_known_hosts = True
env.command_timeout = 10
env.timeout = 10
```

- Is something wrong with my configuration?
- Is 20K servers list to big for fabric to handle?

**Comment by bitprophet** [comment]
20K seems like a lot, but as with any software, there's no technical "limits" to what Fabric itself can do, it comes down to the system you're running it on. (For example I know of places which successfully manage fleets of, say, 10K without any problem - it just takes a while!)

Are you using parallel mode in any fashion? Snippet implies no, but you mention finding stale "fab jobs" in the ps table, which implies you're spawning local subprocesses. That can make a big difference re: what to look into first.

**Comment by arossert** [comment]
@bitprophet thanks for the quick response.
I am using parallel mode with `poolsize=50`

This is how I'm using the script:
`fabfile.py`

```
@parallel(pool_size=50)
def monitor_func():
    ....
    return stat

@task
@runs_once
def monitor():
    res = execute(monitor_func)
    [process res dict]
```
Running:
`fab monitor`

I'm using a big server for that:
Ubuntu 14.04, 48 cores, 256GB memory

I have added logging to file on entering/exiting in monitor_func(), I executed this on 10000 servers (out of 28126) and I see 10000 enters and 9999 exists, so one of the commands is still running.
I have set a timeout so I don't understand why it is not closing it after the time has passed.

**Comment by bitprophet** [comment]
OK, that's what I guessed (parallel). There are unfortunately many reasons why child subprocesses could end up not exiting cleanly; one way to make sure you're not seeing already-solved hanging-at-end-of-session problems is to be on the latest Paramiko version so I'd double check that.

I'd also just doublecheck the resource consumption of your master process near the middle or end of the run, in case it is still somehow eating all your RAM (for example).

**Comment by arossert** [comment]
I have the latest Paramiko version (2.2.1).
As far as I can see none of the `fab` processes eating the machine resources, do you have any other idea how to check this?
Can I force the job to close after a timeout?
Maybe there is another way to gather stats on the run beside using `execute`?

**Comment by arossert** [comment]
I have managed to find the issue, t appears that it is the same server that is hanging.
I'm using multiple `run` statements on each server and for some weird reason, only on that server it hangs on the second `run` statement, it does not matter what is the statement, some as simple as:
```
run("date")
run("date")
```
This is the output:
```
[server] run: date
[server] out: Sun Aug 27 03:12:58 PDT 2017
[server] out:
```
And it hangs here forever

What can be the issue? (I have tried timeout in the `run` statement but with the same results )

**Comment by bitprophet** [comment]
Yea, that's pretty bizarre. Sadly it is a big class of rare and hard to troubleshoot problem for this library  (specifically for Paramiko.)

We recently merged a patch to Paramiko that is in this rough sphere of things; it is a long shot, but it's possible it will help in your situation: https://github.com/paramiko/paramiko/pull/1041

If you're capable of grabbing the unreleased master of Paramiko, please try that out; otherwise I plan to release it this week or next.

**Comment by bitprophet** [comment]
FTR I'm going to mark this as "almost surely a Paramiko issue" and close it, but discussion can continue.
