### ISSUE TITLE
Cannot set hosts then use run in a task

### ISSUE THREAD

**Issue by jackric** [fabric/fabric#1657]
Fabric task semantics surprise me: the operations are not associative. Given the below fabfile.py:

```python
from fabric.api import env, run

def set_a_host():
    env.hosts = ["my_server"]

def run_bare():
    run("id")

def run_with_host():
    env.hosts = ["my_server"]
    run("id")
```

`fab set_a_host run_bare` works correctly
`fab run_with_host` results in a prompt: `No hosts found. Please specify (single) host string for connection`

This is very annoying - is there a good reason for this behaviour?

**Comment by ploxiln** [comment]
The task `run_with_host()` runs on the list of hosts as it is defined before the task starts.

You can achieve what you want with the hosts decorator http://docs.fabfile.org/en/1.13/api/core/decorators.html#fabric.decorators.hosts

```python
@hosts("my-server")
def run_with_host():
    run("id")
```

**Comment by bitprophet** [comment]
See also the general docs on how roles/hosts/tasks interoperate with each other: http://docs.fabfile.org/en/1.13/usage/execution.html
