### ISSUE TITLE
fabric - ssh-process having weird prompt shells

### ISSUE THREAD

**Issue by mungayree** [fabric/fabric#1658]
Since fabric is based on paramiko, is there any API to connect to virtual appliance with ssh-process having weird prompt shells ?

How can fabric automate-jobs with processes acting as such shells.

e.g. VM acting as switch having prompt 'switch-> ' when login is done over ssh. 
fabfile.py need to feed commands thereafter. once such command is to deploy images over tftpboots. The VM provides both telnet/ssh interface with user/password)

I tried below code, but it does not work -

 ```
@task
 taskA():
      with settings(prompts={'switch-> ' : 'bringkickstart img.bin' }):
          run('save image')
```

**Comment by ploxiln** [comment]
Fabric is not designed to work with such appliances, sorry. see #1546 and you might try using pexpect https://pexpect.readthedocs.io/en/stable/api/pxssh.html
