### ISSUE TITLE
fabric cannot read /etc/ssh/ssh_config

### ISSUE THREAD

**Issue by pysnow530** [fabric/fabric#1660]
I found fabric couldn't parse `/etc/ssh/ssh_config` when I use `use_ssh_config` option.
Is there a gentle workaround? Or would it be supported?

**Comment by bitprophet** [comment]
Fabric 2 will support this out of the box; in 1.x the best you can do is to explicitly specify it via the "ssh config path" config option: http://docs.fabfile.org/en/1.13/usage/env.html#ssh-config-path

But as you might expect, this means it will stop reading your personal config in `~/.ssh/config`.

Again, Fabric 2 (in alpha) does the "right" thing here and loads up both configs, merging them together.

**Comment by pysnow530** [comment]
Ok, thanks!
