### ISSUE TITLE
Fabric2. I don't understand how I can get "host"

### ISSUE THREAD

**Issue by rpisarev** [fabric/fabric#1663]
E.g. for fabric1 I had

```
[192.168.0.36] run: uname -a
[192.168.0.36] out: Linux *.cloudlinux.com 3.10.0-714.10.2.lve1.4.59.el7.x86_64 #1 SMP Thu Aug 3 06:26:01 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[192.168.0.36] out:
```

But on the other hand, for fabric2 (I used warn=True, echo=True) I had only:
```
uname -a
Linux *.cloudlinux.com 3.10.0-714.10.2.lve1.4.59.el7.x86_64 #1 SMP Thu Aug 3 06:26:01 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Is it possible return back interface? Because I have multi process application and that output makes impossible to debug my app.

**Comment by bitprophet** [comment]
There's currently no 'prefix', which is what you're referring to. The current ticket for this is https://github.com/pyinvoke/invoke/issues/15 - basically, the idea is that we'll find a non terrible way to log non-interactive stdout/err via an actual logging module, then use said logging module's built-in log line formatting to inject things like hostname.

You could possibly work around it for now by doing something with the `out_stream` and `err_stream` arguments to `run()`, making your own lightweight file-like objects that write to stdout/err but prefix each line with the hostname. (We could also, _maybe_, provide a built-in helper like this that would be a close analogue to the Fabric 1 prefix behavior. Not sure though, logging would be much more flexible.)

**Comment by rpisarev** [comment]
Ok. Then I would try to add a prefix that would look good for me. And we will discuss patch.

**Comment by rpisarev** [comment]
Actually, 'run' string is patched easily by monkey-patch

```
-          print("\033[1;37m{0}\033[0m".format(command))
+          print("\033[1;37m[{0}] run: {1}\033[0m".format(self.context.host, command))
```

**Comment by gitaarik** [comment]
For now I worked around this like this:

```
def run(host, command):
    
    result = host.run(command, hide=True, echo=False)
    output = result.stdout or result.stderr
    
    print(
        f"[{host.host}] {result.command}\n"
        f"{output}"
    )
```

So instead of `c.run('ls')` I do `run(c, 'ls')`

**Comment by mattrobenolt** [comment]
To add a slightly nicer imo workaround, I just did this by extending the `fabric.connection:Connection` and overriding `run/sudo` and providing my own `{out,err}_stream` to provide a prefix and colors. This all around felt nice since we could customize a lot of the output. Here's a snippet from my solution:

```python
import io
from fabric.connection import Connection as FabConnection


class coloredstream:
    def __init__(self, prefix, err=False):
        self.prefix = prefix
        self.buffer = None
        self.err = err

    def write(self, data):
        if self.buffer is None or self.buffer.closed:
            self.buffer = io.StringIO()
        self.buffer.write(data)

    def flush(self):
        if self.buffer is None or self.buffer.closed:
            return

        for line in self.buffer.getvalue().splitlines():
            click.secho(
                f"[{self.prefix}]: {line}", fg="red" if self.err else None, err=self.err
            )
        self.buffer.close()


class Connection(FabConnection):
    def run(self, command, **kwargs):
        return self._fancy_run("run", command, **kwargs)

    def sudo(self, command, **kwargs):
        return self._fancy_run("sudo", command, **kwargs)

    def streams(self, prefix):
        return coloredstream(prefix, err=False), coloredstream(prefix, err=True)

    def _fancy_run(self, method, command, **kwargs):
        out_stream, err_stream = self.streams(self.host)

        sudo = "[sudo] " if method == "sudo" else ""
        out_stream.write(click.style(f"+ {sudo}{command}", bold=True) + "\n")

        rv = getattr(super(), method)(
            command, echo=False, out_stream=out_stream, err_stream=err_stream, **kwargs
        )

        (out_stream if rv.exited == 0 else err_stream).write(
            f"Command exited with status {rv.exited}\n"
        )
        out_stream.flush()
        err_stream.flush()
```

From here, you can use `SerialGroup.from_connections()` instead of the default initializer so we can wrap with our custom `Connection`.

So ends up looking something like:

```python
def make_group(hosts, parallel=False):
    return (ThreadingGroup if parallel else SerialGroup).from_connections(
        [Connection(host) for host in hosts]
    )
```

```python
g = make_group(['a', 'b'], parallel=True)
g.run('hostname')
```

I think overall doing this gave a bit more flexibility for say, printing the whole `stderr` in red, printing the exit status, and printing the command ala `bash +x` always, etc. It took a bit of understanding of the plumbing, but worked well for me.
