### ISSUE TITLE
Running fab with sudo results in unexpected env.user

### ISSUE THREAD

**Issue by gncs** [fabric/fabric#1665]
Let's assume I have the following fabric file (`test.py`):

```Python
from fabric.api import env, run

# Fabfile load time
print "Load time: %r" % env.user

def mytask():
    # Task runtime
    print "Runtime env.user: %r" % env.user
    print "Runtime env.host_string: %r" % env.host_string
    run("whoami")
```

When I run this as `gncs` user
```Bash
/bin/fab -f test.py -H localhost mytask
```
 I get the following (expected) output:
```Bash
Load time: 'gncs'
[localhost] Executing task 'mytask'
Runtime env.user: 'gncs'
Runtime env.host_string: 'localhost'
[localhost] run: whoami
[localhost] out: gncs
[localhost] out: 


Done.
Disconnecting from localhost... done.
```

However, if I run with `sudo`, i.e., `sudo /bin/fab -f test.py -H localhost mytask` I get (I hit Ctrl+C when it asks for the password):
```Bash
Load time: 'gncs'
[localhost] Executing task 'mytask'
Runtime env.user: 'gncs'
Runtime env.host_string: 'localhost'
[localhost] run: whoami
[localhost] Login password for 'gncs': 
Stopped.
```

Is this expected?
In addition, I discovered that I get the same behaviour if I run `sudo su` and then `/bin/fab -f test.py -H localhost mytask`. Interestingly, I get the desired output if I run `sudo su -`:

```Bash
Load time: 'root'
[localhost] Executing task 'mytask'
Runtime env.user: 'root'
Runtime env.host_string: 'localhost'
[localhost] run: whoami
[localhost] out: root
[localhost] out: 


Done.
Disconnecting from localhost... done.
```

Details:
```Bash
Fabric 1.13.2
Paramiko 1.16.1
```
on `CentOS Linux release 7.4.1708 (Core)`

**Comment by ploxiln** [comment]
Interestingly, I can't reproduce in macOS 10.12 or ubuntu-16.04. But this sounds like the difference between the "uid" and the "euid": https://stackoverflow.com/questions/27669950/difference-between-euid-and-uid

You can get an effect similar to `su -` with just sudo: `sudo --login ...`

**Comment by bitprophet** [comment]
Yea `su -` does some additional stuff behind the scenes compared to regular `sudo` or `su`, regarding effective user, so I think @ploxiln is onto something there. I don't think this is really a Fabric-level issue but more of an OS-level one.

For what it's worth the default value of `env.user` comes out of [the getpass module](https://github.com/fabric/fabric/blob/ecb588b788cfea5d2becc6957ad12e8c78042a38/fabric/state.py#L38) at the moment.

Re: workarounds, if you're happy doing things at module-load time, you could always simply `env.user = some.other.os.level.method()` if you find something in the stdlib that gives the answer you're expecting, e.g. `os.geteuid`.

**Comment by gncs** [comment]
I asked for help on [StackExchange](https://unix.stackexchange.com/questions/393361/environment-user-and-username-in-centos-7) and apparently the behavior of `sudo` changed.
In addition, I learned that `getpass` uses environment variables which is causing the problem here.

To resolve this issue, I overwrite the `user` variable in my fabfile like so:
```Python
...
import os
import pwd

env.user = pwd.getpwuid(os.getuid()).pw_name
...
```
