### ISSUE TITLE
Fabric doesn't distribute the new version of the app, although it seems to believe that it does

### ISSUE THREAD

**Issue by dianatkh** [fabric/fabric#1668]
Fabric screen shows that that it Distributed the version has been Accepted by beta-testers, no emails actually reach our inboxes. 

In general, the app sending notifications is often hit-and -miss, so we have to connect 3 email addresses, hoping that at least 1 of them will get the email (when it was still working)

**Comment by ploxiln** [comment]
This is not a github repo for https://get.fabric.io/
You have found the wrong Fabric.
