### ISSUE TITLE
Allow multiple -H/--hosts options

### ISSUE THREAD

**Issue by sylr** [fabric/fabric#1669]
Hi,

In order to be able to use bash brace expansion relatively easily with Fabric it would be nice that fabric options allow multiple occurrences of -H/--hosts, i.e. :

```
fab -f pwet.py "-H myhost"{00..10} apt_get_upgrade
```

Which would expand to :

```
fab -f pwet.py -H myhost00 -H myhost01 -H myhost02 -H myhost03 -H myhost04 -H myhost05 -H myhost06 -H myhost07 -H myhost08 -H myhost09 -H myhost10 apt_get_upgrade
```

Here a working but most probably very dirty attempt to make that append: https://github.com/sylr/fabric/commit/4dbdada10273bde8cc34215b08465452c2b4dd57

Regards.

**Comment by ploxiln** [comment]
try `fab --hosts=$(echo myhost{00..10} | tr ' ' ',') ...`

**Comment by bitprophet** [comment]
There's some other open issues for similar ideas, I can't find them offhand but I distinctly remember them (at least one has links to a potential sub-library we could use as well). Similar to your idea, uses square or curly bracket expansion. So I'm going to close this as a duplicate, but thanks for the suggestion regardless!

@ploxiln is also correct that your shell almost surely has a lot of utility in this space as well, which is one reason we haven't landed any features around this yet.

**Comment by sylr** [comment]
@bitprophet it's possible that you are referring to this https://github.com/graphite-project/graphite-web/issues/1510#issuecomment-213336851

@ploxiln solution would indeed work but goal here is to make it easy to write.

**Comment by ploxiln** [comment]
I happen to have a task in my fabfile which is like this:

```python
@task
@serial
@hosts('virtual')
def H(name):
    """Add target host by short name"""
    hostname = expand_and_misc_stuff(name)
    env.hosts.append(hostname)
```

You can use it like `fab H:myhost01 H:myhost02 task` or even `fab H:myhost{01,02} task`

(it does need to be before the other "real" tasks on the command line)
