### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mharmuth** [fabric/fabric#1673]
I'm running an automated build with Gitlab CI using fabric for generating an artifact. Everything worked fine until today. Now I get an error while installing fabric:

https://gist.github.com/mharmuth/3ebfb8688de5a3a1cf9f29b9725e1d3a

Nothing was changed. I compared the version with an older build that worked and even the pip and fabric versions are the same.

**Comment by ploxiln** [comment]
> Failed to build cffi

> No package 'libffi' found

> c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory

Clearly it's libffi/cffi that changed. Perhaps your base image used to have them pre-installed, but no longer. And python cffi needs a package called something like "python-dev" installed in order to compile.

**Comment by ploxiln** [comment]
Probably a bit more helpful: what really changed was the "cryptography" dependency, that has had significant updates in the past few months, including significant updates to its dependencies/requirements.

**Comment by mharmuth** [comment]
Thanks for this tip. That was what I needed ;)
I added libffi6 and python-dev as dependencies and now the build is running again!
