### ISSUE TITLE
Missing enum34 dependency (ImportError: No module named enum)

### ISSUE THREAD

**Issue by walterdolce** [fabric/fabric#1675]
Hi all.

I installed fabric `1.14.0` and when I issued a `fab -h` I got the following:

```
Traceback (most recent call last):
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/paramiko/transport.py", line 34, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 12, in <module>
    from cryptography.exceptions import (
  File "/Users/a_user/.local/share/virtualenvs/fabric_tasks-kENjJPUz/lib/python2.7/site-packages/cryptography/exceptions.py", line 7, in <module>
    from enum import Enum
ImportError: No module named enum

There was a problem importing our SSH library (see traceback above).
Please make sure all dependencies are installed and importable.
```

I googled a little bit and after adding the `enum34` to my `Pipfile` it solved the problem.

This looks like it's a hard dependency for fabric. Should this not be defined in the `requirements.txt` file?

If so, I'm more than happy to quickly PR this. Thank you!

**Comment by bitprophet** [comment]
Notice how we're not actually importing it - `cryptography` is!

Their setup.py _should_ have caused your pip to grab `enum34` explicitly, e.g. this is how Cryptography 2.0.3 does it: https://github.com/pyca/cryptography/blob/87a6dcae8a527d6e0b5c8feabfa768cd8fa6e264/setup.py#L43-L44

Not sure what went wrong on your end. More details about your specific platform / Python version / Cryptography version / output of install/upgrade command / etc, might yield a clue?

Gonna close for now as "hasn't been a big problem for other folks / probably a fluke" but not locking or anything :)

**Comment by walterdolce** [comment]
Thanks @bitprophet for the reply. 

This is running onna macOS with Python 2.7 installed by default. With pip installed. With pipsi installed via pip. With pipenv installed via pipsi. With fabric installed via pipenv.

**Comment by bitprophet** [comment]
If you're able to reliably reproduce this (eg by nuking the local pipenv virtualenv and then recreating it and installing fabric again) I'd be really interested in the output of the fabric install command - ideally with verbose flags enabled, not sure what pipenv has for those as I don't use it yet. Equivalent of `pip -vv install fabric`, basically.

Not sure if this represents a pipenv bug/quirk or some strange confluence between pipsi, pipenv and pip, but again, a normal vanilla pip install ought to execute Cryptography's `setup.py`, which should notice you're on Python <3.4, and should spit out `enum34` in its `install_requires`. (I do wonder if this continues to hold true for wheels, though...)

**Comment by walterdolce** [comment]
Thanks @bitprophet. Indeed, installing `fabric` as you suggested does not create this problem. I can simply `fab -h` without issues. This makes me think something's not right in `pipenv` then. I shall open an issue there.

**Comment by bitprophet** [comment]
(Quick update from abovelinked ticket, this does sound like it was an already-patched pipenv bug.)
