### ISSUE TITLE
ImportError: cannot import name Connection

### ISSUE THREAD

**Issue by RaidoS** [fabric/fabric#1685]
I`m the trying to run Fabric with password watchers from the [docs](http://docs.fabfile.org/en/stable/getting_started.html#run-commands-via-connections-and-run)

`from fabric import Connection`
`from fabric.connection import Connection`
both of them raises ImportError

Fabric==1.14.0
paramiko==2.4.0
invoke==0.21.0

Are there docs or Fabric version issues?

**Comment by ploxiln** [comment]
Those docs you are reading are for Fabric-2 which does not have a stable release yet. The docs for Fabric 1.x are here: http://docs.fabfile.org/en/1.14/

**Comment by RaidoS** [comment]
@ploxiln thx a lot. a mark **stable** not about this case ^^

**Comment by bitprophet** [comment]
Whoa, that's odd. @RaidoS how did you end up on the `stable` docs version exactly? The root domain (docs.fabfile.org) dumps you out on the "real" latest-stable which is currently `/en/1.14/`.

Guessing you clicked on the `stable` link in the RTD widget on bottom right? I'll have to see why that's being picked up. Thanks for the report!

**Comment by bitprophet** [comment]
OK, yea, no idea why RTD picked that up but it did have a 'stable' version entry pointing to the v2 branch. Unchecked it and seems gone from the widget now 👍
