### ISSUE TITLE
Can't update to Fabric 2

### ISSUE THREAD

**Issue by revolter** [fabric/fabric#1692]
The [Upgrading from Fabric 1.x](http://docs.fabfile.org/en/stable/upgrading.html?highlight=cd#upgrading-piecemeal) page says that there is a version 2 of the `fabric` package, but the latest version is [`1.14.0`](https://pypi.python.org/pypi/Fabric/1.14.0) and that there is a `fabric2` package, but it can't be installed:

```
pip install fabric2
Collecting fabric2
  Could not find a version that satisfies the requirement fabric2 (from versions: )
No matching distribution found for fabric2
```

**Comment by ploxiln** [comment]
fabric2 is not on pypi

http://bitprophet.org/blog/2017/04/17/fabric-2-alpha-beta
#1672

**Comment by revolter** [comment]
Shouldn't this information be in the README instead of a blog post?

**Comment by revolter** [comment]
Also, it highly contradicts with

> The v2 branch can optionally be installed as fabric2 if one wants to use it alongside Fabric 1 for an easier upgrade

which sounds like `fabric2` can be installed, and it contains the `v2` branch.

**Comment by ploxiln** [comment]
Well, what it means is, fabric contains a v2 branch, and you can checkout that branch and install it as "fabric" or as "fabric2"

**Comment by revolter** [comment]
I didn't know that you can change the installed module name so it differs from the official one, and I guess that I'm not the only one. What I was trying to say is that adding this information in the README and making them clearer might prevent others from creating duplicate issues here.

**Comment by bitprophet** [comment]
Argh, I don't know why RTD keeps republishing that 'stable' page, v2 is _not_ stable yet :( which is doubtless why you're so confused! Gonna take another look at removing that part of the docs.

**Comment by bitprophet** [comment]
OK, it was no longer marked as building, but that was insufficient to nuke it from the published cache. Just 'cleaned' it and it's gone now.

For the official roadmap, see http://www.fabfile.org/roadmap.html#invoke-fabric-2-x-and-patchwork!

**Comment by revolter** [comment]
1. Even if version 2 is not final, migrating to its alpha/beta version seemed to be helped by that page, or migration shouldn't be done yet?
2. Are there any alpha/beta/not stable docs for the new version as it is for the current version, with the obvious warning of possible breaking changes?
3. Is it possible to know a RC or stable release of the version 2 of this?
