### ISSUE TITLE
append duplicating lines

### ISSUE THREAD

**Issue by bl4ckmesa** [fabric/fabric#1694]
I'm struggling with this crontab entry:

> from fabric.contrib.files import append
> heapdump_line = "  2-59/5  *  *  *  * root    for file in `ls /mnt/data/heapdump/*.hprof 2>/dev/null`; do mv $file ${file}_`date --reference $file '+\%Y\%m\%d\%H\%M'`; done"
> append("/etc/crontab", heapdump_line, use_sudo=True)`

It will append this line identically multiple times.  Is there something with quotes/other special characters I'm missing?  It certainly looks like I expect in the crontab; it just keeps duplicating.

**Comment by ploxiln** [comment]
What is your exact version of Fabric? see also #1559 and #1599

**Comment by bl4ckmesa** [comment]
aperture:docker aaronr$ fab --version
Fabric 1.10.2
Paramiko 1.16.0

**Comment by ploxiln** [comment]
If you update to Fabric 1.12.2 or later, I think this will work better for you.

**Comment by bl4ckmesa** [comment]
You are correct, upgrading to 1.14.0 took care of it.  Thanks!
