### ISSUE TITLE
unable to use ssh key_filename with gevent

### ISSUE THREAD

**Issue by grapemix** [fabric/fabric#1701]
Hi,

We've been using this lib quite a while, it works perfectly. Thanks for providing this awesome lib. Recently, we decided to switch to gevent together with fabric3. And we found out that we are unable to assign the ssh private key programatically as we used to. Our app need to use different ssh private key to connect to different machine on the fly.

Here is the to demo, hope it can save you guys sometime:

```
# Comment these two lines if you need to use fabric's ssl cert
#from gevent import monkey
#monkey.patch_all(thread=False)

import logging

logging.basicConfig()
paramiko_logger = logging.getLogger("paramiko.transport")
paramiko_logger.disabled = True

import datetime
from fabric.api import run
from fabric.api import settings as fabSettings
import os

formData = {
  "ip": "YOUR_IP",
  "username": "SSH_USERNAME",
  "keyRelPath": "~/.ssh/SSH_PRIVATE_KEY_NAME"
}

def test():
  with fabSettings(
      host_string=formData["ip"],
      user=formData["username"],
      key_filename=os.path.expanduser(formData["keyRelPath"])
      ):
    run("ls")

test()
```

Github just doesn't preserve space in the code....

And we are using:
Fabric3==1.13.1.post1
paramiko==2.3.1

**Comment by ploxiln** [comment]
you can use triple-backticks on their own lines for code quoting, like so:

    ```
    your code here:
        with indent
    ```

Note that this project does not maintain Fabric3 and does not test with gevent. Your best bet is to debug this yourself, try to identify root cause, and submit a pull request for a small appropriate fix. It is unlikely that someone else will do this.
