### ISSUE TITLE
Command works through open_shell but not run (Javascript shell)

### ISSUE THREAD

**Issue by Phxntxm** [fabric/fabric#1720]
My test code is this:
```
from fabric.api import *
env.host_string = "[redacted]"
env.user = "[redacted]"
env.password = "[redacted]"
env.output_prefix = False

cmd = """
var testImport = importCommands(".");
println(testImport);
println(typeof test);
"""

run(cmd, shell=False)
open_shell(cmd)
```
And output is this:
```
[host] run: 
var testImport = importCommands(".");
println(testImport);
println(typeof test);

JavaScript Shell

Type help(); for more information
true
undefined

JavaScript Shell
Type help(); for more information
shell[1]> 
shell[1]> var testImport = importCommands(".");
shell[1]> println(testImport);
true
shell[1]> println(typeof test);
function
shell[1]>
```

importCommands imports files in the directory as functions, and there is indeed a test file (as it can be found in the open_shell output). I'm blanking on what's going wrong here, as even when using this in `run` it returns true, meaning it should be successful. On top of that, if I run `help()` it shows that `test` as well as everything else that should be imported now exists, but it's still undefined and I can't use them.

Using `open_shell` works, but it's a workaround as this is not meant to be interactive and output handling is much more annoying with it as opposed to using run. Additionally error handling is annoying, because if I throw a `quit` on the end of it, it then "functions like run" but that means I also have to handle any errors before the `quit`, etc.....point is, I'd like to use run instead of this funky workaround, but I don't know what's going wrong, it doesn't make sense to me.

**Comment by fruch** [comment]
@bitprophet `open_shell` was nice, any thoughts on a direction to implement it on fabric 2 ?

**Comment by bitprophet** [comment]
@Phxntxm @fruch funny timing on closing this; Fabric 2 is getting `Connection.shell()` in the next feature release (work's already done and just needs some test fixes). In case it's still relevant in any way 🙃

**Comment by Phxntxm** [comment]
Good to know in the future, thank you! I no longer work at the job we had using that however which is why I closed it, after going through some of my old issues lol
