### ISSUE TITLE
Roadmap / progress update for Fabric 2?

### ISSUE THREAD

**Issue by SamuelMarks** [fabric/fabric#1727]
What's the news on Fabric 2? - Haven't seen anything this year, or really heard anything apart from:
http://www.fabfile.org/roadmap.html
http://bitprophet.org/blog/2017/04/17/fabric-2-alpha-beta/

Been creating all sorts of neat little packages and Fabric wrappers over at [github/offscale](/offscale).

Want to support Python 2.7+ and Python 3; but your TODO list was long, so was planning on waiting until you're closer to feature parity (mostly just need: custom context managers, `shell_env`, `cd`, `exists`).

Can you provide an update on Fabric 2? - Thanks.

**Comment by bitprophet** [comment]
I'm wrapping up some dayjob work (related to the Spectre/Meltdown security explosion earlier this year) and have gotten signoff to spend most of April sprinting on Fabric 2 so I can finally, at long last, have it done by this year's PyCon in May.

So expect to start seeing movement again real soon now.

**Comment by ssbarnea** [comment]
I am quite curious why [adding support for Python 3 bug](https://github.com/fabric/fabric/issues/1617) was closed and locked? Clearly the fix was not implemented and also prevents others from adding links to the [fabric3 fork that apparently works with python3](https://pypi.python.org/pypi/Fabric3).

**Comment by bitprophet** [comment]
Python 3 support is coming in v2; after the extreme hassle and instability of porting another old codebase to Python 3 (Paramiko) I judged it not worth trying to do it for Fabric 1, when Fabric 2 was already in development and natively/from-the-start a hybrid codebase.

(I did not anticipate Fabric 2 taking this long to come out, clearly. Hopefully moot very soon now!)
