### ISSUE TITLE
Question: How to run task on target throngh jumper by different account ?

### ISSUE THREAD

**Issue by ocswor** [fabric/fabric#1736]
local -> gw -> target
gw account: user1/sshconfig sshconfig in local
target account: user2/sshconfig sshconfig in gateway

how to run task on the target ?

I try like below,but don't work

from fabric.api import *
import os
env.use_ssh_config = True
env.gateway = 'alyjumper'

env.host_string = 'algorithm@alg-service001'

def list_dir():
    run('ls')

list_dir()

**Comment by mchwalisz** [comment]
I see you are using fabric1 syntax. Consider switching to fabric2, to motivate you, look at http://docs.fabfile.org/en/2.0/concepts/networking.html#proxyjump It solves your particular use case.

**Comment by ocswor** [comment]
@mchwalisz Thanks
