### ISSUE TITLE
Page for updating to version 2 is not exist

### ISSUE THREAD

**Issue by sergiusnick** [fabric/fabric#1742]
In README there is a reference to page for upgrading to version 2 (http://www.fabfile.org/en/latest/upgrading.html), but this page does not exist

**Comment by rpkilby** [comment]
Hi @sergiusnick. The link was just fixed in c135ce7b6777fa313e9a2c37824f3fdc72f49566. The correct link is http://docs.fabfile.org/en/latest/upgrading.html
