### ISSUE TITLE
local example seems needed

### ISSUE THREAD

**Issue by JaminShanti** [fabric/fabric#1747]
do you have a local example, now that the command was moved, api to Connections?  Multiple sites has the uptime example in fabric 1.4.  One or two examples of running local commands would be helpful. Thank you.

**Comment by bossjones** [comment]
Hi @JaminShanti ,

I was able to get the `local` command working in this following block of code. Note I am new to the 2.0 api changes, and basically going through the exercise of converting old fab tasks from 1.x -> 2.x.

```
from fabric import Connection
from invoke import task, Exit
from invocations.console import confirm

@task
def log_local(c):
    """[Run journalctl -f on localhost]

    Arguments:
        c {[Connection]} -- [Explicit initial context argument, whose value will be a Connection object at runtime.]
    """
    c.local('journalctl -f')
```

From there, all I need to do is run the command as follows: `fab -H localhost log-local`

Hope that helps.

**Comment by bitprophet** [comment]
@JaminShanti See @bossjones' useful example above (thanks!!) and also see the upgrading document, such as this particular set of subsections around the run/local/sudo functions (which are now methods): http://docs.fabfile.org/en/latest/upgrading.html#id7

There's also a bigger example of porting a sample fabfile, at the bottom of that document.
