### ISSUE TITLE
CI auto-cancellation

### ISSUE THREAD

**Issue by rpkilby** [fabric/fabric#1757]
https://blog.travis-ci.com/2017-09-21-default-auto-cancellation would be nice to have for PRs.

**Comment by bitprophet** [comment]
I haven't had time to keep up with all the awesome Travis has been putting out...thanks! Will go nudge this for my repos.

**Comment by bitprophet** [comment]
Oh, seems either I already did, or they did it for everybody, since it appears to be set (both branches and PRs) on all my projects already! Let me know if this seems somehow not the case.
