### ISSUE TITLE
Upgrade doc should mention underscore-to-hypen changes

### ISSUE THREAD

**Issue by vkurup** [fabric/fabric#1758]
Underscores in function names get converted to dashes in command line task names. This should probably be mentioned in the [upgrade document](http://docs.fabfile.org/en/latest/upgrading.html)

```
$ grep load_infrastructure fabfile.py 
def load_infrastructure(c):
$ fab2 -l
Available tasks:

  load-infrastructure
```

**Comment by bossjones** [comment]
@vkurup good catch, made a quick PR: https://github.com/fabric/fabric/pull/1760
