### ISSUE TITLE
V2: how to migrate to patchwork.files?

### ISSUE THREAD

**Issue by mjmare** [fabric/fabric#1764]
I'm a bit at a loss as to how to use pathwork.files. It seems that the first parameter is the connection and must be provided. The second is a 'runner' which is provided automatically(?). Other args are method specific.
However 
```
exists(c, 'test.txt')
```
fails with:
```
AttributeError: 'Result' object has no attribute 'succeeded'
```
What is the proper usage pattern?

**Comment by mjmare** [comment]
It seems that there is a bug in patchwork.files: replacing 'succeeded' with 'ok' fixes it. The calling procedure is indeed: exists(c, 'test.txt')

**Comment by bitprophet** [comment]
A fix for this got merged recently, please make sure you're on latest master of Patchwork. Thanks!

**Comment by mjmare** [comment]
That was quick ;-) Thx.

**Comment by bitprophet** [comment]
It's linked in the upgrading doc under the 'contrib' section: http://docs.fabfile.org/en/2.0/upgrading.html#contrib

Was there someplace else you were expecting it to be? (Honest question!) We're still dealing with a lot of growth pains after the release so I'm sure the docs could use a shakeup, but it is there in at least the one spot :)

**Comment by acdha** [comment]
From my perspective the “still in an essentially alpha state” note was a bit off putting but the real question was just docs for patchwork – Fabric has great docs but right now if you follow that link you basically have to read the source to confirm any details about a function's existence or signature.

**Comment by mjmare** [comment]
Patchwork contains useful stuff, mentioning it only in the upgrade docs doesn't do it justice. It should be part of the fabric docs to prevent a, uhh, patchwork of docs. See issue https://github.com/fabric/fabric/issues/1776
