### ISSUE TITLE
unable to use functions with underline in their names

### ISSUE THREAD

**Issue by mehdipourfar** [fabric/fabric#1770]
auto_dash_names in tasks config should be false by default.

**Comment by bitprophet** [comment]
"should be" is rather strong, don't you think? it's not like we didn't think about this when we put the dashed name stuff in place. There's also a little thing called backwards compatibility to think about...

That said I've been wanting to make this not an issue for a while and I just wrote it down over in pyinvoke/invoke#529. Please follow there for updates - thanks!

**Comment by mehdipourfar** [comment]
I think underscore is more backward compatible because I always executed fab commands with the exact function names. Am I wrong?

**Comment by bitprophet** [comment]
I meant backwards compatible _with 2.0_, which itself is of course not backwards compatible with 1.0.

I'm planning to put out a 3.0 at some point (not 7 years from now), but the idea is not to break backwards compat _too_ often 😁
