### ISSUE TITLE
ThreadingGroup does not implement get function

### ISSUE THREAD

**Issue by JensRantil** [fabric/fabric#1774]
See https://github.com/fabric/fabric/blob/master/fabric/group.py#L163. `get` function raises `NotImplementedError` in inherited `Group`. This likely fixes #1712.

**Comment by bitprophet** [comment]
Yea, none of the Group subclasses actually implemented `get`, I think I've already axed it temporarily from the docs. Also, is this missing a link or a PR? "this likely fixes" implies such but...no patch!
