### ISSUE TITLE
Emulate lcd in Fabric2?

### ISSUE THREAD

**Issue by mjmare** [fabric/fabric#1775]
I tried to emulate a fabric1 snippet in fabric2 (F2):

```
    with lcd(f'{env.frontend.src}'):
        local('quasar build')
```
(FYI quasar is a node CLI script to build the javascript frontend)

Since there is no lcd equivalent in F2 I tried using connection.prefix:
```
with c.prefix('cd ../melder_webapp'): 
    c.local('quasar build')
```
This fails with the message:
```
env: node: No such file or directory
```
Trying to find the root cause I then tried:
```
c.local(f'cd ../melder_webapp && quasar build', echo=True)
```
same error. 
When I try the command "cd ../melder_webapp && quasar build" manually on the command line, it works fine.

**Comment by bitprophet** [comment]
I'd double check other things like the subprocess' CWD and PATH and so forth; maybe just run `"env"` and compare to `env`'s output in your interactive shell. The actual `&&` should work fine so it's possible something else is tripping you up.

**Comment by bitprophet** [comment]
Going to close as "probably not actionable", outside of the already known thing where we need to implement a real local-oriented `with cd`. Feel free to keep commenting though.

**Comment by bitprophet** [comment]
Actually you're probably hitting a related issue re: env being straight up discarded, see https://github.com/fabric/fabric/issues/1744#issuecomment-391181327
