### ISSUE TITLE
Highlight patchwork and invocations in Fabric's top level docs

### ISSUE THREAD

**Issue by mjmare** [fabric/fabric#1776]
Obviously in Fabric2 great pains went into producing a well designed framework of reusable libraries: fabric builds on pyinvoke. Both libs are extended with patchwork en invocations respectively. fabric and invoke come with well written docs. 
However for a regular user it is hard to get an overall mental picture of what is where. A feature could be in any of the four libs.
If the docs cannot be combined, the newcomer or casual user (like myself ;-) would be well served by more extensive usage examples.

**Comment by bitprophet** [comment]
This is definitely something we want to work on! WE're focusing on getting some big missing features out the door first, then once the code itself is more usable we'll work on enhancing the docs.

**Comment by bitprophet** [comment]
Trying this out in various places in the docs, nothing fits perfectly so I gotta make a judgement call re: where fab, inv, invocations and patchwork are best mentioned.

- Putting mention of all 4 in the README, when only 2 are truly required for use, feels like it could be throwing newbies too much at once.
  - "Oh man this is so complicated! 4 libraries just to run a single command?!?! Fuck this I'm going elsewhere". 😢 
- Conversely, having that high level view is useful and burying mention of it in the FAQs or a conceptual doc _also_ doesn't feel right – per this ticket's OP, it just delays the inevitable or leads to users never coming across the optional libs even when those libs would fit their use case.
- An argument for delaying this is that invocations and patchwork are still rougher than the core libs, across a few axes (understanding which functions should live where, given #98; the general quality and test coverage is still lacking; etc).
  - And funneling users at them only to generate more questions whose answers are "sorry! still working on that" doesn't feel good.
  - But neither does hiding them, of course.

Anyway, that's enough overthinking a plate of beans. I guess in the end putting it "out there" and in the README is the best route. Anyone who was gonna be turned off by it is both A) likely to still be turned off by it even if they understand 2 of the libs are optional, and B) probably going to be a bit of a support vampire anyways 😐 .

**Comment by bitprophet** [comment]
Close-via-commit-message still problematic, I see -_-
