### ISSUE TITLE
fabric2 not work on ssh config with -H.

### ISSUE THREAD

**Issue by hackrole** [fabric/fabric#1778]
I have a ssh config for hostname test list below:
```ssh-config
Host test
     HostName 1.1.1.1
     User test
     IdentityFile file
```
the following code will work.
```python
from fabric.connetion import Connection
c = Connection("test")
c.run("name -a")
```
while the following will not.
```python
from invoke import task
@task
def name(ctx):
      ctx.run('uname -a')
# fab -H test name
```
it is confused.

**Comment by snahor** [comment]
What version are you using? It works on 2.1.3 and 2.0.1.

**Comment by hackrole** [comment]
sorry, It seems like my mistake. it works now. I cannot reproduce it.

what I got was I run `fab -H test get_uname` it raise cannot connnect to my alias.
