### ISSUE TITLE
Connection.sudo in python REPL doesn't quite work...

### ISSUE THREAD

**Issue by SwampFalc** [fabric/fabric#1779]
```
$ python
>>> from fabric2 import Connection
>>> c = Connection('myserver')
>>> c.sudo('ps -ef')
[sudo] password: mypaSorry, try again.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-4>", line 2, in sudo
  File "/usr/local/lib/python2.7/dist-packages/fabric2/connection.py", line 24, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric2/connection.py", line 588, in sudo
    return self._sudo(runner, command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/context.py", line 220, in _sudo
    raise_from(error, None)
  File "/usr/local/lib/python2.7/dist-packages/invoke/vendor/six.py", line 718, in raise_from
    raise value
invoke.exceptions.AuthFailure: The password submitted to prompt '[sudo] password: ' was rejected.

```
So basically what happens is that I get asked for my password, I start typing and what I type is echoed on screen and then after one single second it just cuts off.

That's not enough time to type any sort of secure password, plus of course, echoing it on screen is a big no-no.

Now, of course, this is obviously not the designed way of doing all this, so I wouldn't necessarily call this a bug. But maybe this could be improved upon a bit anyway, at some point in the future?

**Comment by chiganov** [comment]
I have the same problem.
I use python3.6, zsh, tmux, ubuntu16.04

**Comment by ploxiln** [comment]
In this case of not using the `fab` tool, you'll need to query the sudo password with your own python code (e.g. `import getpass; pass = getpass.getpass()`) and then set it in the invoke config or pass it to the sudo method (e.g. `c.sudo("ps -ef", password=pass)`)

**Comment by chiganov** [comment]
It worked for me if I use the key ```--prompt-for-sudo-password``` then run fab. This helped to get around the problem.

**Comment by bitprophet** [comment]
If you want to manually respond to the sudo prompt, just use `run("sudo ps")`. `sudo` is explicitly for the case where you want the system automatically responding to the prompts on your behalf. I bet the docs could be clarified about this.

**Comment by bitprophet** [comment]
Added a note to Invoke's docs around this, pyinvoke/invoke@da7f448bbddfe470c25484f329025218ae3cc331

**Comment by bitprophet** [comment]
Also, to be clear, @chiganov is 100% correct - as soon as you find yourself entering the sudo password >1 time per session, you probably do want to just use `sudo()` + `--prompt-for-sudo-password` (or go with @ploxiln's suggestion if you want to handle your own prompting or config.)
