### ISSUE TITLE
outline a basic fabric 1 cli/task setup in fabric 2

### ISSUE THREAD

**Issue by benzkji** [fabric/fabric#1781]
the docs mention the `fab` tool, but it's usage is not so clear - I guess that normally nobody will use the `-H` option, but create some kind of `fabconf.py`, create groups in there, and then...somehow get those into the `c` parameter of each of the tasks. this is really basic in fabric 1, through env.

Please forgive if I missed this in the docs! I read them ;-)

**Comment by bitprophet** [comment]
That functionality is still being worked on, so you didn't miss any docs! Please follow #4 :)
