### ISSUE TITLE
Request: get/put multiple files

### ISSUE THREAD

**Issue by SwampFalc** [fabric/fabric#1784]
Any chance we could have a get/put that could work with a folder and recursively get/put?
I mean, obviously I can do the recursion and all myself, but it feels like this is a not-uncommon use case that would be best served by a standard solution...

**Comment by bitprophet** [comment]
This is covered by our upgrading-from-v1 docs: http://docs.fabfile.org/en/latest/upgrading.html#file-transfer - see the item about recursive multi-file transfer.

I could see us _maybe_ adding a lightweight wrapper around an archive->upload->unpack workflow (which would, while still nontrivial, likely have a smaller bug surface area). But it's not something I can personally prioritize right now. Everyone's got slightly different needs here and it's not _that_ hard to implement to your specific tastes locally.

There's also the (still having some kinks worked out, tho most were tackled in a recent bugfix) rsync helper in patchwork: http://fabric-patchwork.readthedocs.io/en/latest/api/transfers.html#patchwork.transfers.rsync - that's arguably your best bet right now depending on use case.
