### ISSUE TITLE
Working with roles in v2

### ISSUE THREAD

**Issue by muhammedabad** [fabric/fabric#1786]
From what I can see, the `@roles` functionality that was present in v1 is currently not available in v2.

Is there any alternative way to work around this for now ? My issue lies in performing tasks on `x` number of hosts that are categorised by type. `x` could change quite often and I would naturally prefer to update a dictionary with a new hostname than change a number of fab commands throughout my CI script.

Is the only option (at the moment) to use the `-H` flag  and pass a list of hostnames in ?

**Comment by bitprophet** [comment]
At the moment, yea, 2.0 is still kinda in technology-preview mode so it lacks some core stuff like roles. They're entirely lacking besides creating your own `Group` objects within your tasks (or, for example, setting them up with pre-tasks and assigning them as config values, then referencing them in the 'main' tasks.) That's the only obvious workaround at present.

See https://github.com/fabric/fabric/issues/1594 for the issue tracking how to move forward with something filling the roles use case in v2. Thanks!
