### ISSUE TITLE
ssh agent lost when issues ssh/rsync in connection

### ISSUE THREAD

**Issue by kmike82** [fabric/fabric#1787]
when trying to ssh or issue an rsync on connections, self._agent seems is lost

this is easily tested:
```
from fabric import Connection

conn = Connection("myhost")
conn.run('ssh localhost "echo hello"') 
```

this raises the exception in the paramiko agent.py: AuthenticationExemptionL Unable to connect to SSH agent

**Comment by bitprophet** [comment]
I think this just means you want to set `forward_agent=True` when creating your Connection - give that a shot!
