### ISSUE TITLE
Context.cd fails with Context.sudo

### ISSUE THREAD

**Issue by schober-ch** [fabric/fabric#1790]
Hi, I'm trying to upgrade an old fabric1 fabfile to the new API and I find many strange things.. 

```
def test(c):
    with c.cd("/home/user/blabla"):
        c.sudo("ln -s file1 sym1", user="user") 
```
will give the chained command:

`cd /home/user/blabla && ln -s file1 sym1`

but, as this is wrapped in sudo, the executed command will give an error:

`sudo: cd: command not found` 

since cd is not a command (but a builtin) and not executable by sudo...

In my opinion, the documentation here is wrong

> Any calls to run, sudo, within the wrapped block will implicitly have a string similar to "cd <path> && " prefixed in order to give the sense that there is actually statefulness involved.

Same applies for `context.prefix` if used with `source` or `.` to activate a python virtual environment (without virtualenvwrapper-helper).

Aside from being wrong in the documentation, how would one solve these use-cases? The only thing I can imagine right now is something like:

```
def test(c):
    with c.cd("/home/user/blabla"):
         c.run("sudo -u user ln -s file1 sym1")
```

In general, I seem to be putting back a ton of explicit stuff to get my old fabric1 file working with fabric2, making everything less readable than before (at best).. Perhaps fabric2 is solving a different problem than fabric1 did and I'm now using the wrong tool?

**Comment by kg4lod** [comment]
I also ran into this issue today while migrating.

**Comment by bitprophet** [comment]
See pyinvoke/invoke#459 - thanks!

**Comment by autoscatto** [comment]
ugly but: (≖__≖)

` 
cwds, conn.command_cwds = conn.command_cwds, []
conn.sudo(cmd)
conn.command_cwds = cwds
`
works
