### ISSUE TITLE
local can not use local env in fabric2.1.3

### ISSUE THREAD

**Issue by ipfans** [fabric/fabric#1792]
## System
MacOSX 10.13.4

## Version
fabric 2.1.3+Python3.6.4

## Sample Code
```python
with Connection('aaa', user='aaa') as c:
    c.local('go build')
```

## What I want to see?

No error outputs.

## What I saw?

c.local can not read $GOPATH or $GOROOT on current terminal session, so complied failed.

**Comment by ploxiln** [comment]
https://github.com/fabric/fabric/issues/1744#issuecomment-388864529

**Comment by ipfans** [comment]
@ploxiln thx bro

use `replace_env=False` works fine.
