### ISSUE TITLE
Support GSS-API authentication if ssh_config mentioned it.

### ISSUE THREAD

**Issue by Xeite** [fabric/fabric#1794]
Now, I found fabric does not pass GSS-API related options at all to Paramiko even if the options in ssh_config exists.

Although user can pass the related parameter using `connect_kwargs` now, I think it's better to pass minimal required parameters to avoid users' misunderstanding. (At least 'gss_auth: True')

**Comment by bitprophet** [comment]
Let's roll this into the PR.
