### ISSUE TITLE
Can't upload binary with MacOs Fabric App - Archive Distribution Error -9

### ISSUE THREAD

**Issue by crpr** [fabric/fabric#1797]
Today i started having this error when trying to upload an iOS binary to Fabric.

"Could not save the release notes. The operation couldn't be completed. (HTTP error 500)."

I tried with and without release notes and it always fails.

My internet connection is stable and without problems.

Thanks.

**Comment by ploxiln** [comment]
This is not the repo for https://get.fabric.io/ - this is a different Fabric, a python library.
