### ISSUE TITLE
"su -" problem

### ISSUE THREAD

**Issue by gamba47** [fabric/fabric#1798]
Hi guys, i have some debian servers with a normal user and need to use "su -" to change to root.

What can i do to make it work? i was reading a lot but i can't root access.

I need to put some files on root folders and execute commands like we do with "sudo"

Thanks for any post for read.

best regards.

gamba47

**Comment by gamba47** [comment]
I will close this and look in other places.

Sorry.

**Comment by XuCcc** [comment]
> I will close this and look in other places.
> 
> Sorry.

@gamba47 

Hey, i met the same problem like u.I want to check my root's password is correct or not.Some normal user of Debian does't have sudo command.

I try this method in http://docs.fabfile.org/en/2.4/getting-started.html#superuser-privileges-via-auto-response.However i met some other problems in https://github.com/fabric/fabric/issues/1880

Is there any good idea?
