### ISSUE TITLE
"run" does not carry env vars in arguments

### ISSUE THREAD

**Issue by poquirion** [fabric/fabric#1799]
```
$ run("echo $FOO", env{"FOO"="bar"})
```
returns nothing, with replace_env=True OR =False

While 
```
$ local("echo $FOO", env{"FOO"="bar"})
bar
```
Work as expected.

**Comment by poquirion** [comment]
... I am running  "fabric":"2.1.3" under python 3.6

**Comment by bitprophet** [comment]
This is a security design choice, see `replace_env` here - http://docs.fabfile.org/en/2.1/concepts/configuration.html#overrides-of-invoke-level-defaults

(and, if you read that page, you'll see you can simply set `replace_env=False` in `run` to get the same behavior as in `local` - but beware that this is a security risk!)
