### ISSUE TITLE
AttributeError: 'SerialGroup' object has no attribute 'put'

### ISSUE THREAD

**Issue by 26huitailang** [fabric/fabric#1800]
I follow the [official tutorial](http://docs.fabfile.org/en/2.1/getting-started.html#bringing-it-all-together). Try to upload and unpack the file to several servers but got this problem. And I `dir(pool)`, there is no attribute named `put`.

**Comment by bitprophet** [comment]
Apologies, that specific feature is still pending, we hope to get it out in an early feature release. See #1810. Thanks!

**Comment by mapio** [comment]
Pending since one year? Take at least the time to remove it from the getting started docs!

**Comment by andrewebdev** [comment]
End of 2020 and still not implemented.

Maybe this should _not_ be mentioned in the tutorial or documents if it's not available? It creates a false sense of capabilities and results in people chasing tails.
