### ISSUE TITLE
Feature request: sudo parameter to c.get() and c.put()

### ISSUE THREAD

**Issue by ChaoticMind** [fabric/fabric#1802]
Unlike fabric1's get() and put() functions, the [`get()`](http://docs.fabfile.org/en/2.1/api/transfer.html#fabric.transfer.Transfer.get) and [`put()`](http://docs.fabfile.org/en/2.1/api/transfer.html#fabric.transfer.Transfer.put) methods provided by [`Connection()`](http://docs.fabfile.org/en/2.1/api/connection.html) don't [yet?] support a `sudo` (or `use_sudo`) parameter.

Would be great to have that supported again!

As a quick workaround, one can use:
```python
def sudo_put(c, local, remote, **kwargs):
    tmp_file = "/tmp/tmp_fabric_put_file"
    c.put(local, tmp_file, **kwargs)
    c.sudo("mv {} {}".format(tmp_file, remote))

```

**Comment by bitprophet** [comment]
This is covered by our upgrading-from-v1 docs: http://docs.fabfile.org/en/latest/upgrading.html#file-transfer – look in that section for mention of 'sudo'. Thanks!
