### ISSUE TITLE
no auth credentials when wrapping docker push cmd

### ISSUE THREAD

**Issue by Mokubyow** [fabric/fabric#1803]
After migrating to Fabric 2.0 my simple fab command to run a docker push doesn't work anymore. For some reason, the shell doesn't know I'm logged in. When I run the shell command outside Fabric it works fine. Any ideas what is going on?

```
@task
def push(c, tag):    
    c.run(f'docker push docker.company.com/app:{tag}')


The push refers to repository [docker.company.com/app]
f76a30813b1d: Preparing
1ead8c68efa3: Preparing
17b534c85a5f: Preparing
53d8d2a2e6ab: Preparing
0b7cd459baf0: Preparing
ddd403bcae47: Preparing
1f127cc5b31e: Preparing
b09178215597: Preparing
62345e64388b: Preparing
1f127cc5b31e: Waiting
ddd403bcae47: Waiting
62345e64388b: Waiting
b09178215597: Waiting
014cf8bfcb2d: Preparing
014cf8bfcb2d: Waiting
no basic auth credentials
```

**Comment by bitprophet** [comment]
Can you post the code from v1 that you're using? There are a few possible things that could be going on here and I want to avoid working off any bad assumptions. I'm wondering if this is as simple as confusion between `run` and `local` (e.g. where `c` is a regular Invoke context obj, `run` is a local shell; but where `c` is a Fabric connection obj, `run` executes remotely).

**Comment by Mokubyow** [comment]
sure thing here is the v1 code:

```
def push(tag='latest'):
    local(f'docker push docker.company.com/app:{tag}')
```

**Comment by bitprophet** [comment]
Wondering if this is another permutation of #1752 - if docker is relying on env vars for its config or auth, that would cause this. Please try changing your v2 code to `c.run(f"docker ...", replace_env=False)` and see if that makes it work?

**Comment by Mokubyow** [comment]
@bitprophet adding `replace_env=False` does resolve the issue.

**Comment by bitprophet** [comment]
Thanks! I'm going to close this as a sub-case of that linked issue, please follow it if interested. Once fixed this issue should effectively go away - `Context.run()` / `Connection.local()` will default to `replace_env=False`.
