### ISSUE TITLE
Sudo context and/or decorator

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#181]
### Description

I wonder if it is technically possible but I'd like to set the "run with sudo" globally by using context or decorator. Or more precise, I'd like to drop the sudo parameter from _all_ the functions, just because it is needed there for consistency.

So, instead of making functions/extensions like (more concrete examples: http://docs.fabfile.org/0.9.1/api/contrib/files.html):

```
# CURRENTLY

dosomething(param1, param2, use_sudo=True)
dosomething2(param1, use_sudo=True)

# INSTEAD

with sudo:
   dosomething(param1, param2)
   dosomething(param1, param2)
```

And then the low-level function would/wouldn't automatically use the sudo, according to given context. Additionally this could be set via decorator. 

This would make easier, not to worry about providing sudo parameter is all the places, preferably in right order.

---

Originally submitted by ***\* ([jmu](https://github.com/jmu)) on **2010-06-20** at **12:19pm EDT**
### Relations
- Duplicates #25: Update "use_sudo to be "via" or similar

---

Closed as _Duplicate_ on **2010-06-20** at **07:44pm EDT**

**Comment by WoLpH** [comment]
Little bit late to the party and not a full solution but could still be useful for people right now. I've worked around the limitation using the following (very hacky) method:

```python
import contextlib
from fabric import api

def sudo_context(user=None):
    user = user or api.env.sudo_user

    run = api.run
    try:
        # Temporarily monkeypatch api.run to use api.sudo instead
        api.run = api.sudo
        yield
    finally:
        api.run = run
