### ISSUE TITLE
Allow definition of hosts in project config file

### ISSUE THREAD

**Issue by notsimon** [fabric/fabric#1813]
Hi,

I would like to define a default hosts list in a *fabric.yml* along my *fabfile.py*.

After a few minutes of digging into Invoke and Fabric, it seems to me that `FabExecutor` should use a `hosts` config item [instead of](https://github.com/fabric/fabric/blob/2.0/fabric/executor.py#L15) `self.core[0].args.hosts.value`. This config item would then be overridden in the [update_config](https://github.com/fabric/fabric/blob/2.0/fabric/main.py#L98) method of `FabProgram`.

Did I miss something ? Is it already possible ? If not, I can work on a PR.

**Comment by notsimon** [comment]
Should I open a PR for the commit above ?

**Comment by bitprophet** [comment]
Hi, please see #4! This is something that needs active feature development and is under discussion, we're hoping to get something basic implemented for 2.1 or 2.2.
