### ISSUE TITLE
Script hangs while using Fabric's Connection.run() in the background

### ISSUE THREAD

**Issue by mpenning** [fabric/fabric#1815]
Overview
---

I'm trying to use python fabric to run an ssh command as root on a remote server.

The command: `nohup ./foo &`

`foo` is expected to command run for several days.  I must be able to disassociate `foo` from fabric's remote ssh session, and put `foo` in the background.

The [Fabric FAQ](http://www.fabfile.org/faq.html) says you should use something like `screen` or `tmux` when you run your fabric script (which runs the backgrounded command).  I tried that, but my fabric script still hung.  `foo` is not hanging.

Question
---
How do I use fabric to run this command on a remote server without the script hanging: `nohup ./foo &`

Details
---

This is my script:

```python
#!/bin/sh
# Credit: https://unix.stackexchange.com/a/20895/6766
if "true" : '''\'
    then
    exec "/nfs/it/network_python/$OSREL/bin/python" "$0" "$@"
    exit 127
fi
'''

import os

from fabric import Connection

assert os.geteuid()==0, "ERROR: Must run as root"

for host in ['host1.foo.local', 'host2.foo.local']:
    # Make an ssh connection to the host...
    conn = Connection(host)
    result = conn.run('nohup ./foo &')  # The script always hangs at this line
```

I always open a `tmux` session to run the aforementioned script in; even doing so, the script hangs when I get to `conn.run()`, above.

I'm running the script on a vanilla CentOS 6.5 VM; it runs under python 2.7.10 and fabric 2.1.

If you google this problem, you'll naturally see my [stackoverflow question](https://stackoverflow.com/q/51071839/667301) on the same subject.

**Comment by bitprophet** [comment]
Please reread that FAQ, especially if you had issues with `screen` too!

The remote process and shell _must_ exit for Fabric's local end to continue executing, and most of the time `nohup` doesn't do the trick. `screen` should, but you have to make sure you invoke it in a manner that truly backgrounds the process instead of (as is its default behavior) attaching immediately to the foreground.

For example, `screen -d -m ./foo` should do what you want. Here's an example just using `sleep`:

```
# Sanity check that a quick SSH session works fine
» python -c "from fabric import Connection; c = Connection('localhost'); c.run('whoami')"                                  
jforcier                                                                                                                   
# Run screen in detach-immediately mode, with a 60s sleep
» python -c "from fabric import Connection; c = Connection('localhost'); c.run('screen -d -m sleep 60'); print('All done')"
All done               
# Because I hit localhost I can just quickly check that the detached proc is running                                                                                                    
» pgrep -l sleep                                                                                                           
24064 sleep                                                                                                                
# And I can ask screen about its session list
» screen -list                                                                                                             
There is a screen on:                                                                                                      
        24061..tachi    (Detached)                                                                                         
1 Socket in /var/folders/yx/399vybz54g1269vjzbw5h_5c0000gn/T/.screen.                                                                                                           
```

In that setup you can, for example, reattach to the detached session with `screen -r`.

For more, please consult screen's docs 😁
