### ISSUE TITLE
Fabric2: Download information while using Connection.get

### ISSUE THREAD

**Issue by Kireeti-K** [fabric/fabric#1818]
Hi!!

I just switched to fab2 from 1.0, strangely I no more see the download info or the file size of my db. I am using connection class to connect to my host and doing a get on the connection. Is there something wrong I am doing or should I directly use the Transfer?, 

Thanks

**Comment by bitprophet** [comment]
You're not doing anything wrong, the 2.x put/get calls are lacking some things from 1.x. We need to re-solve the problems of output/logging (https://github.com/pyinvoke/invoke/issues/15) and actually-solve exposing async progress info to the logger and to users generally (#394). Please follow those for details - thanks! Feel free to stick with the 1.x line until we iron this out, 2.0 needs some feature releases to get up to par.
