### ISSUE TITLE
Fabric 2 - Execute task from external files

### ISSUE THREAD

**Issue by bonimd** [fabric/fabric#1820]
Hi,

I'm using Fabric to build a set of tasks to manage my servers. 
I'm trying to separate these tasks in Collections, in this way:
```
fab -H aws --list
Available tasks:
  deploy.build-revision
  deploy.generate
  deploy.push-image
  docker.exec
  docker.kill
  docker.ps
  docker.restart
  mysql.dump
  mysql.list-databases

```
This collections are splitted in files with this structure:

```
project/
├── config.py
├── fabfile.py
├── lib
│      └──utils.py
├── task_collections
│   ├── deploy
│   │   ├── __init__.py
│   │   └── tasks.py
│   ├── docker
│   │   ├── __init__.py
│   │   └── tasks.py
.....

```
Every directory name within task_collections is used as a Collection name and every task inside tasks.py will be owned by this collection:

```
for root, dirs, files in os.walk(CURRENT_PATH + '/task_collections/'):
    for file in files:
        if file == 'tasks.py':
            collection_name = os.path.basename(root)
            module_name = "task_collections.%s.tasks" % (collection_name)
            ns.add_collection(Collection.from_module(sys.modules[module_name], name=collection_name))
```
Now I would like to reuse tasks and call them from other tasks. Im able to do it when both tasks are in the same tasks.py file, but I can't when not.
For example when I execute deploy.generate-build, i need to run docker.exec  which is in other file.
Is it possible to do this?

Thanks.

**Comment by bitprophet** [comment]
At a high level I think this would be helped by the unresolved missing feature of "call other tasks from Python without literally calling their functions", which is https://github.com/pyinvoke/invoke/issues/170

However, I'm not 100% sure I grok the exact problem here; you're dynamically building a collection, basically aping how v1 worked in that regard, which should be fine. However, `Collection.from_module` explicitly *does not* "crawl" imported objects -- meaning that you *should* be able to do things like:

``` python
```

**Comment by bonimd** [comment]
Thank you for your answer.

I was looking for a more native way like the one you describe at first.
But you are right, calling them as functions works totally fine and solves the problem.
