### ISSUE TITLE
Shell input is broken after running script

### ISSUE THREAD

**Issue by sinwoobang** [fabric/fabric#1829]
Hello. I've used various commands using Fabric.
But sometimes, Shell input is broken after running script.

![2018-07-18 3 50 04](https://user-images.githubusercontent.com/6701124/42864753-76d0d170-8aa2-11e8-999c-b0a771a56bdd.png)

Looking at the screenshot, can't see any inputs in the shell.
I entered `return command` many times but It didn't work.

I've tried to reproduce it and it normally worked while running scripts that have short results like `git fetch` or `git reset`.
But It didn't work after doing something that have long results like `pip install -r requirements.txt`.

Do you have any idea?

**Comment by sinwoobang** [comment]
@bitprophet Thank you for reply.

It is impossible to write the exact code but the part where the error occurs is written like..
```python
group = ThreadingGroup('host1', 'host2', 'host3')
group.run('pip install -r requirements.txt')
```

Thanks :)

**Comment by bitprophet** [comment]
Thanks @sinwoobang - I was indeed mostly looking to see if you were using `ThreadingGroup`. This definitely sounds like #1812 - please subscribe to that ticket for updates! 👍
