### ISSUE TITLE
Fab CLI doesn't find collections if run from venv

### ISSUE THREAD

**Issue by ciarancourtney** [fabric/fabric#1830]
Works:

1. Install fab globally via pip `sudo pip install fabric`
2. create fabfile.py as per tutorial
3. `fab --list` works

Doesn't work

1. Install fab into a virtualenv `python -m venv venv && venv/bin/pip install fabric`
2. create fabfile.py as per tutorial
3. `venv/bin/fab --list` raises `No tasks found in collection 'fabfile'!` Moving fabfile.py into `venv/bin` and chdir to there works

**Comment by ciarancourtney** [comment]
Nevermind, misunderstood docs http://docs.fabfile.org/en/2.2/cli.html?highlight=__init__.py#seeking-loading-tasks

**Comment by tomieq** [comment]
@ciarancourtney what was the case? I've read docs 3 times already and still can't figure out what I'm doing wrong. I understand the docs exactly the same as you in the first post.
I did touch fabfile.py with hello() func content and `fab --list` cannot see it. Tried with `chmod a+x` on fabfile but it didn't help... Some advice would be nice

**Comment by ciarancourtney** [comment]
> @ciarancourtney what was the case? I've read docs 3 times already and still can't figure out what I'm doing wrong. I understand the docs exactly the same as you in the first post.
> I did touch fabfile.py with hello() func content and `fab --list` cannot see it. Tried with `chmod a+x` on fabfile but it didn't help... Some advice would be nice

I can't remember my original problem, it was dumb anyway, probably a typo in `fabfile.py` or leaving out the `@task` decorator.

Try it again as per http://docs.fabfile.org/en/2.2/getting-started.html#addendum-the-fab-command-line-tool

Try with `--debug` arg as well
