### ISSUE TITLE
Tasks don't work as expected

### ISSUE THREAD

**Issue by FUNNYDMAN** [fabric/fabric#1833]
Hello. I started using fabric not so long ago. And I've found some problems. Can you explain/review it?
Fabric 2.2.0
Paramiko 2.4.1
Invoke 1.1.0

### 1
from fabric import Connection, Config

REMOTE_HOST = 'tele'
c = Config(overrides={"sudo": {"password": 'somepassword'}})

conn = Connection(REMOTE_HOST, config=c)
def some():
    conn.sudo("echo 'hello'")
some()
After typing fab in console I'm getting '[sudo] password:' message, after that I get the result and core options if I would just type fab --help

### 2
The put doesn't work if remote path needs root permissions
#conn the same as above
def some():
    conn.put("app.py", "/etc/nginx/app.py")

### 3
Tasks functionality
Why can't just create and configurate Coonnection and after send it as argument to task?
like this:
conn = Connection(REMOTE_HOST, config=c)

@task
def some(conn):
    conn.sudo('echo "hello"')
### 4 
I think docs need more real examples

**Comment by FUNNYDMAN** [comment]
Thanks! it works

**Comment by bitprophet** [comment]
While inquirer looks real neat, I do want to note that there's a built-in `--prompt-for-login-password` (plus same for sudo and key passphrases) arguments which do a basic version of the same thing, prompting up front for sensitive info.

Re: item 2, that's an outstanding semi-missing feature for now.

Item 3, you can absolutely do that if you want, the point of us exposing Connection and friends is so you have that option! :) (I'm still working on a 'nice' way to take an 'outer' context like that from a 'local' task, and use it when creating a Connection, but for now you can just: `cxn = Connection("host", config=c.config)`)

Item 4: we agree and hope to get more examples up later! Thanks.

**Comment by KantiCodes** [comment]
As far as I understood the docs, it should be the Fabric wrapping the Invoke, but here it's clearly the other way around.

@davidjmemmett  Could you also help me out to understand it here?
