### ISSUE TITLE
How to execute task on localhost ?

### ISSUE THREAD

**Issue by bussiere** [fabric/fabric#1836]
Sorry but i have hard time to understand how to execute task locally : 

> from fabric2 import Connection
> cbis = Connection.local()
> with cbis.cd('/home/bussiere/Workspace/Stack/Event/'):
>     cbis.run('git add .')

but i have this error :

> TypeError: local() missing 1 required positional argument: 'self'

https://stackoverflow.com/questions/51573657/self-error-when-launching-a-local-command-with-fabric2#51573693

Thanks

**Comment by bachirelkhoury** [comment]
Per docs:
http://docs.fabfile.org/en/2.2/getting-started.html?highlight=local

> Anything that isn’t specific to remote systems tends to live in Invoke, and it is often used standalone by programmers who don’t need any remote functionality.
Fabric users will frequently import Invoke objects, in cases where Fabric itself has no need to subclass or otherwise modify what Invoke provides.



You would use Invoke like so:
```
from invoke import task

@task
def gitadd(c):
    c.run('cd /home/bussiere/Workspace/Stack/Event/ && git add .')

```
Then you can call that from the command line with:

```invoke gitadd```

**Comment by bitprophet** [comment]
@bachirelkhoury has it! thanks :)

To add: if @bussiere _did_ have some remote connection using `fabric.Connection` (e.g. `c = Connection('my.remote.server')`), he could still have run local commands via that object, by doing `c.local("git add .")`. `Connection.local` is just another command running method; it's not a constructor or anything :)

**Comment by nafanz** [comment]
I constantly get confused with this, so I decided to leave a simple example without functions and tasks. 
I hope it will be useful to someone.

```
from invoke import run

run('pwd')
```
