### ISSUE TITLE
Unable to connect on neetwork

### ISSUE THREAD

**Issue by evknz** [fabric/fabric#1839]
I did everything I found on internet about proxy settings for Fabric Android Studio Plugin and nothing seems to workout. 

<img width="410" alt="screen shot 2018-08-02 at 15 50 51" src="https://user-images.githubusercontent.com/4521822/43604353-eda84dc6-966b-11e8-8dea-bbd4df8cf1e6.png">

I already have setted the proxy credentials on vmoptions file but it didn't resolve.

Any help?

**Comment by bitprophet** [comment]
Hello! I'm afraid you've got the wrong repo; you seem to be looking for https://get.fabric.io/ ? This is a totally separate (and older) project. Thanks!
