### ISSUE TITLE
Get() not working correctly when wrapped with cd()

### ISSUE THREAD

**Issue by stefan-wegener** [fabric/fabric#1840]
My environment is: Python 2.7.9 and Fabric Version: 2.2.2.

When using
`
with c.cd('/etc/openvpn/easy-rsa2/keys'):
    c.get('<some-name>', 'test')
` 
I am getting: IO error: [Errno 2] No such file

But when using
`
 c.get('/etc/openvpn/easy-rsa2/keys/<some-name>', 'test')
`
the file gets downloaded as expected.

I also checked if the cd is working correctly by:
`
with c.cd('/etc/openvpn/easy-rsa2/keys'):
    c.run('ls -al')
`
And I am getting the contents of the folder as expected. 

Is it intended that Fabric does not support the usage of cd with get? (Version 1 was supporting it, as this problem is currently appearing during my migration from version 1 to 2)

**Comment by bitprophet** [comment]
Not intended, this is a bug / missing port, please follow #1752 for updates! Thanks :)
