### ISSUE TITLE
Local commands don't get $PATH by default

### ISSUE THREAD

**Issue by lahwaacz** [fabric/fabric#1841]
Consider this simple `fabfile.py`:

```python
import os
from fabric import task, Connection

@task(hosts=["local"])
def foo(c):
    c.local("env")
    c.local("echo")
    c.local("which ls", env=os.environ)
    c.local("which ls")
```

Running `fab foo` with fabric 2.2.1 gives this:
```
PWD=/home/lahwaacz
SHLVL=1
_=/usr/bin/env

/usr/bin/ls
which: no ls in ((null))
```

So there is no `$PATH` in the execution environment, or most other variables for that matter.

Note that the [documentation for local](http://docs.fabfile.org/en/latest/api/connection.html#fabric.connection.Connection.local) says that it is just a wrapper around `invoke.run`. But the [documentation for invoke.run](http://docs.pyinvoke.org/en/latest/api/runners.html#invoke.runners.Runner.run) says:

> env (dict) – 
> By default, subprocesses recieve a copy of Invoke’s own environment (i.e. os.environ).

Clearly this is not the case when invoked through the fabric's wrapper so I think there is a bug...

**Comment by ploxiln** [comment]
#1744 mentions a work-around

**Comment by gilesbrown** [comment]
> #1744 mentions a work-around

That work-around does not support the context stuff to allow you to do a 
```python
with c.cd('/some/dir'):
    local("some_command_on_path")
```
Am I missing something?  (It is quite likely.)
