### ISSUE TITLE
Fabric2: hostname prefix missing from stdout

### ISSUE THREAD

**Issue by ciarancourtney** [fabric/fabric#1844]
Apologizes if this is covered elsewhere, but I couldn't find any mention in the docs.

In fabric1 (actually fabric3 fork in my usage) the output had the current hostname in the gutter, prepended in brackets before the output like

    [hostname1] op done.
    [hostname2] op done.
    ....

This seems to be missing from fabric2 as an option

**Comment by bitprophet** [comment]
This is covered by our upgrading-from-v1 docs: http://docs.fabfile.org/en/latest/upgrading.html – look for 'output_prefix'. Thanks!

**Comment by pudong7163** [comment]
It seems that the fabric 2 project is in a maintenance mode. I guess we won't get this feature in the "near" future?

**Comment by michitaro** [comment]
This code is helpful in most cases for me.

```python
from fabric import SerialGroup

for cxn in SerialGroup('da12', 'da13'):
   cxn.run('date | sed "s/^/[$(hostname)] /g"')
```

```
[da12] Sat May 27 07:52:09 JST 2023
[da13] Sat May 27 07:52:10 JST 2023
```
