### ISSUE TITLE
Need guardrails re: recursion in ProxyJump chained Connections

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#1850]
Moving https://github.com/pyinvoke/invoke/issues/564 over here - @acdha is getting recursion errors on line 331 of latest public release, which is where we create new Connection objects from ProxyJump in SSH configs: https://github.com/fabric/fabric/blob/4b1a2ab33af2682f20832bc91f9d20d800989f0b/fabric/connection.py#L316-L331

Chris, can you share your (sanitized) `~/.ssh/config`, as well as the actual CLI invocation you're using to arrive at the traceback? This functionality has been tested in a basic sense so I'm guessing there might be an angle to your setup that is either a legit mistake on your part (in which case we still need some sort of detection/exception guardrail) or a bug on my end (99.9% possible) re: some edge case.

**Comment by bitprophet** [comment]
As you can see in that snippet, we don't currently persist config objects from the outer to inner Connections, but right now that _should probably_ only matter if one was trying to avoid loading SSH configs entirely.

**Comment by bitprophet** [comment]
Perfect, that makes a lot of sense, should be fixable (might need to be on the Paramiko side, depending...)

Also, re: why disabling SSH config loading didn't help - see above - we don't persist our own config which means the gateways will go back to loading SSH configs. I might as well fix that while I'm in here...

**Comment by bitprophet** [comment]
Suspect it probably does need to be fixed here; I'm assuming SSH config files should still represent their literal contents & not try to be "smart", meaning that we should get this:

- You do `fab -H somehost.tld` or equivalent
- We get a Connection for `somehost.tld`
- Its SSH config is derived as having `ProxyJump bastion-host.tld` due to the wildcard (Paramiko level logic)
- Connection sees this, generates gateway Connection object for `bastion-host.tld`
- That loads its own SSH config, which will have both `ProxyCommand none` and `ProxyJump bastion-host.tld`
- We then need to detect that we should not be using the `ProxyJump` because its target is ourselves.
  - Needs care re: fully qualified such strings, but presumably `ProxyJump user@host.tld` should still be considered a distinct jump target than just `ProxyJump host.tld`... 🤔 

@acdha I'm also curious about the `ProxyCommand none`, is that disabling some other `ProxyCommand` not visible in your snippet? It seems like it shouldn't be relevant here otherwise.

**Comment by bitprophet** [comment]
Cool, fixing #1852 gets my test for this bug failing as anticipated. On to the fix.

**Comment by bitprophet** [comment]
Another thing I am punting on is when somebody REALLY goofs up and does something like `Connection("user@host:123", gateway="user@host:123")`, which would technically be a similar class of error.

Anyway, I got my tests to pass, so this should be good now? Will be out in a bugfix release soon™.

**Comment by acdha** [comment]
Thanks!
