### ISSUE TITLE
fab no password/passphrase prompt when executing a task

### ISSUE THREAD

**Issue by sam-dieck** [fabric/fabric#1853]
When executing a task using 
`fab -H host task`
it'll fail immediately with "Authentication failed", without prompting for any login password/passphrase.
If i add the --prompt-for-password or --prompt-for-passphrase arguments, it'll properly prompt me for either and the task executes fine.

This seems to be a different behavior as fabric1, and seems logical to me that if no password/passphrase has been provided, it should prompt you with it.

Is this the intended 2.x behavior? or am I missing something?

Thanks
Sam

**Comment by ploxiln** [comment]
This is intentional: http://www.fabfile.org/upgrading.html#upgrading-general

**Comment by sam-dieck** [comment]
I see, thanks, I'll look deeper into the new configuration system.
