### ISSUE TITLE
Can't find any way to forward env variables in Fabric 2

### ISSUE THREAD

**Issue by nicolas-van** [fabric/fabric#1869]
The title speaks for itself. I just can't find any possibility to send env vars to a remote computer. Example:

```
from fabric import task

@task
def test(c):
   c.run('echo hello $WORLD', env={'WORLD': 'world'})
```
```
fab -H myserver test
# hello
```

Please, just give me a hint because I can't find anything in the doc about that.

Fabric version: 2.3.1

**Comment by mengjuleu** [comment]
A workaround solution: you might create use a command to set env var of the remote server.

```
from fabric import task

@task
def test(c):
    c.run('WORLD='world'')
    c.run('echo hello $WORLD')

**Comment by bitprophet** [comment]
This is a known bug, see #1752.

**Comment by SharkFourSix** [comment]
> A workaround solution: you might create use a command to set env var of the remote server.
> 
> ```
> from fabric import task
> 
> @task
> def test(c):
>     c.run('WORLD='world'')
>     c.run('echo hello $WORLD')
> ```

This may not be ideal for sending sensitive pieces of data such as passwords and the like because they'll be recorded in bash history

**Comment by cariaso** [comment]
`  c.config.run.env = {
            'VAR1':'val1',
            'VAR2':'val2',
            }
    c.run(f'printenv')
`
seems to work
