### ISSUE TITLE
connection.run(git clone -b .......) doesn't work in fabric 2.4.0

### ISSUE THREAD

**Issue by peshmerge** [fabric/fabric#1883]
Hi, 

I try to clone a repo from bitbucket using fabric 2.4.0 with the following command:
```
from fabric import Connection as connection

with connection(host=HOST, user=USER) as c:
     c.run('git clone -b development git@bitbucket.org:REPO production')
```
But the command doesn't clone and it doesn't show any error. So it seems it runs successfully, but that's not true because it's doesn't clone! 

When I replace `c.run()` with `run` from `invoke` library it works perfectly. I import run from invoke using 
 `from invoke import run` 
so the working code looks like this:
```
    with connection(host=HOST, user=USER) as c:
        with cd('/var/www/MY_DIR/releases'):
            c.run('git clone -b development git@bitbucket.org:REPO production')
```
`cd` is imported from `from invoke.util import cd`

It's worth mentioning that the bitbucket repo is big, about 1.5 GB, but I think that mustn't matter, right?!

Does anyone has an idea why it happens?

**Comment by schwahue** [comment]
Hi @peshmerge , have you determined what was the possible cause for this since?

**Comment by peshmerge** [comment]
Hi @schwahue sorry, I don't remember anymore!
