### ISSUE TITLE
`cd` context manager seems not work with `sudo`

### ISSUE THREAD

**Issue by klahnakoski** [fabric/fabric#1884]
This is not working; the command sent to the server is invalid.

```python
conn=Connection(**my_config)
with conn.cd("/home/ubuntu/temp"):
    sudo("rm -fr ~/.cache/pip")
```

Actually, the `with` block has a number of `run()` commands, along with this one `sudo()`, and I removed them for simplicity.

**Comment by bitprophet** [comment]
This probably falls under https://github.com/pyinvoke/invoke/issues/459 - please follow that for updates.
