### ISSUE TITLE
Add option: skip password prompting upon failure

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#189]
### Description

Some use cases exist where a user would rather abort than be prompted in the case where their stored password is incorrect. Currently there's no option for this; the behavior to reprompt forever is hard coded.

Should be simple enough to add a new CLI flag + env var, something like `--no-reprompt`, to allow configuration of this behavior.

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2010-07-13** at **04:44pm EDT**
### Relations
- Related to #8: Allow skipping of "bad" host connections
- Duplicated by #53: Add command-line option to abort if input is needed
- Duplicated by #357: Ability to disable password prompt for library usage

---

Closed as _Done_ on **2011-06-21** at **06:55pm EDT**

**Comment by Maka7veli** [comment]
well this is to abort and exit the script after passwd failure, but how to tell the script to skip passwd failure and move to the next IP???
