### ISSUE TITLE
Date picker text field sub component

### ISSUE THREAD

**Issue by maximus12793** [fabric/fabric#1895]
![datepicker1](https://user-images.githubusercontent.com/8516155/47585020-09fc4800-d911-11e8-8821-e47cfc18d9b9.png)

OWA would like a text-field that can be used in sync with the mini calendar. Ex: User can either type in the text form or select a date from the mini cal and both are kept in sync. The main use case being that if the calendar is always displayed we may want a text display of the selected time but currently the only text field creates a new mini cal popout.  @micahgodbolt

**Comment by davidjmemmett** [comment]
I think you’ve got the wrong project

**Comment by micahgodbolt** [comment]
Office ui fabric react

**Comment by davidjmemmett** [comment]
Triaging before I was a member of this project! Closing :)
