### ISSUE TITLE
Question: Why cant I just .close() ?

### ISSUE THREAD

**Issue by Krogsager** [fabric/fabric#1902]
I connect with fabric as
```result = Connection(endpoint, connect_kwargs={'password': config.PASSWORD}).run('uname -a', hide=True)```
But I can't close it with ```Connection.close()``` because it requires self, which I don't have.
So I just get 
> TypeError:  close() missing 1 required positional argument: 'self'

Any work-around?

**Comment by ploxiln** [comment]
```python
conn = Connection(...)
result = conn.run(...)
conn.close()
```

**Comment by Krogsager** [comment]
Fabulous. Of course.
