### ISSUE TITLE
Add support for Paramiko exec_command's 'timeout' kwarg

### ISSUE THREAD

**Issue by yvwulei** [fabric/fabric#1922]
How to use command_timeout in fabric2.4

Thanks first.

**Comment by bitprophet** [comment]
This has been an in-code TODO for a while: https://github.com/fabric/fabric/blob/e9939d68b734935f0c98d98817912ad7c698238f/fabric/runners.py#L30-L31

The "real" ticket for this is at the command-runner (Invoke) layer: https://github.com/pyinvoke/invoke/issues/539

The code Fabric's level of things needs to be tickling, in Paramiko, is: https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/client.py#L463

**Comment by bitprophet** [comment]
See #539 / #645

**Comment by mcouthon** [comment]
After reading pyinvoke/invoke#539, I see that this was solved in `invoke`, but AFAICT, the code in fabric's master branch still [does not pass](https://github.com/fabric/fabric/blob/master/fabric/runners.py#L58) the timeout param to `command_exec`. 
Does this mean that this ability is only available when running fabric through the CLI?
