### ISSUE TITLE
run local

### ISSUE THREAD

**Issue by janezj** [fabric/fabric#1933]
Running a  local command is not intuitive. In the following example, there are four examples. Last two versions are using the current environment and this is the intuitive and expected behavior (the same as the old local function). The local(replace_env = False) from version 1.xx should be returned in some intuitive way. I have plenty of old scripts I would like to port to version 2.+ and local is a major pain.

``` python
f -e env

@task
def env(c):
    c.run('env | wc -l')
    # 3
    c.run('env | wc -l', replace_env = True)
    # 3
    c.run('env | wc -l', env = os.environ)
    # 82
    c.run('env | wc -l', replace_env = False)
    # 82

```

**Comment by bitprophet** [comment]
Didn't see this until after I made #2027 - let's roll it into there. This is indeed a huge pain in the rear.
