### ISSUE TITLE
how get host list  on ThreadingGroup with fabirc2.

### ISSUE THREAD

**Issue by swimmingchar** [fabric/fabric#1940]
Hello, in that format, you can pass the list of hosts to the Threading Group of fabirc2?
eg:
 use list?
hosts=["host1","host2"]
from fabric2 import ThreadingGroup as Group
pool = Group(hosts).run(cmd, hide=True)

**Comment by 4linuxfun** [comment]
The Group class init code:
···
    def __init__(self, *hosts, **kwargs):
        """
        Create a group of connections from one or more shorthand host strings.

        See `.Connection` for details on the format of these strings - they
        will be used as the first positional argument of `.Connection`
        constructors.

        Any keyword arguments given will be forwarded directly to those
        `.Connection` constructors as well. For example, to get a serially
        executing group object that connects to ``admin@host1``,
        ``admin@host2`` and ``admin@host3``, and forwards your SSH agent too::

            group = SerialGroup(
                "host1", "host2", "host3", user="admin", forward_agent=True,
            )

        .. versionchanged:: 2.3
            Added ``**kwargs`` (was previously only ``*hosts``).
        """
        # TODO: #563, #388 (could be here or higher up in Program area)
        self.extend([Connection(host, **kwargs) for host in hosts])
···

**Comment by swimmingchar** [comment]
Sorry, maybe I'm not very clear. I mean, if I have several hosts, do I need to use tuples to bring these IP into the SerialGroup function instead of writing them out one by one?

**Comment by swimmingchar** [comment]
Also, if I use SerialGroup, how do I close the connection manually after the operation is completed instead of waiting for it to automatically close the connection?

**Comment by zhazhalaila** [comment]
Group receive *args argument, if your parameter type is list, please use `*list`.
```python
hosts = ["host1", "host2"]
from fabric2 import ThreadingGroup as Group
pool = Group(*hosts).run(cmd, hide=True)
```

**Comment by davidjmemmett** [comment]
Closing issue due to age - please re-open a new issue using the provided template if necessary.
