### ISSUE TITLE
var = ssh.sudo('').stdout output goes both in "var" and in stdout

### ISSUE THREAD

**Issue by emanuele-leopardi** [fabric/fabric#1965]
Code

```python

ssh = Connection(ip)
var = ssh.sudo('docker run --rm --net=host cassandra:3.0.16 nodetool tablestats').stdout
```
I expect the output of this command to be just in "var" but it also outputs it on my terminal too.

**Comment by unixo** [comment]
Try:

`var = ssh.sudo('docker run --rm --net=host cassandra:3.0.16 nodetool tablestats', hide=True).stdout`
