### ISSUE TITLE
how to modify hosts list with tasks with fabric2?

### ISSUE THREAD

**Issue by elapouya** [fabric/fabric#1966]
With fabric 1.x I have a fabfile about like this :

```
from fabric.api import env

def prod():
    env.hosts += ['1.2.3.4']

def integ():
    env.hosts += ['2.3.4.5']

def doit():
    env.user = 'root'
    - do some stuff here -
```
By this way, I am able to specify my targets : to execute doit() for integration, I can do :

`fab integ doit`

for integration and production, I can do :

`fab integ prod doit`

With fabric2, I can see there is no more api and one have to use Connection object but, I cannot see where I can change the current SerialGroup to add some hosts on-the-fly.

How can I port this code to fabric2 ??

**Comment by elapouya** [comment]
After debugging, I discovered that all "call" objects to each host have already been created before their execution : There is no use to modify a hosts list inside a tasks, the games are already set. 
Nevertheless I found a workaround, one can do something like this : 

```
from fabric import task, SerialGroup
hosts_to_process = []

@task
def prod(c):
    global hosts_to_process
    hosts_to_process += ['1.2.3.4']

@task
def integ(c):
    global hosts_to_process
    hosts_to_process += ['2.3.4.5']

@task
def doit(c):
    if not hasattr(c,'host'):
        group = SerialGroup(*hosts_to_process)
        for c in group:
            doit(c)
    else:
        env.user = 'root'
        - do some stuff here -

```

By this way, one can now do one of the following : 

```
fab integ doit
fab integ prod doit
fab -H 3.4.5.6 doit

```

**Comment by lkdmid** [comment]
Any thoughts on using the `@task(hosts=group)` decorator as opposed to adding the conditional to all your tasks? Looking for an answer to this: https://stackoverflow.com/questions/63902049/taskhosts-yields-context-but-h-yields-connection
