### ISSUE TITLE
Fabric can't connect to SSH server while ssh command works fine

### ISSUE THREAD

**Issue by mikew** [fabric/fabric#1972]
I'm trying to get a tool that uses Fabric working, and am running into some strange behaviour.

- `api.env.host_string` doesn't set the username correctly
- even with setting `api.env.user`, it's asking for a password, despite SSH keys existing and `ssh` working without a password.

This is with the 1.x branch, so if that's not supported anymore, apologies and this can be closed.

I'm using this simple task to test:

```python
# test.py

from fabric import api
from fabric.tasks import execute

def main():
    api.run('ls')

api.env.host_string = 'b3cmd@motryx.ag:2224'
execute(main)
```

And running it in docker with:

```sh
docker run --rm -it --volume "$PWD:/app" --volume "$HOME/.ssh:/root/.ssh" python:2 bash
pip install 'fabric<2.0'
cd /app
python test.py
```

Which gives

```
[b3cmd@motryx.ag:2224] run: ls
[b3cmd@motryx.ag:2224] Login password for 'root': 
```

Where did root come from? If I set `api.env.user` to `b3cmd`, it displays said username, but it still asks for a password when it shouldn't.

When I just run the command via ssh, everything works fine. This is run in the same Docker container:

```sh
ssh -p 2224 b3cmd@motryx.ag ls /
app
bin
dev
etc
home
lib
linuxrc
media
mnt
opt
proc
root
run
sbin
sys
tmp
usr
var
```

**Comment by mikew** [comment]
Sorry, I accidentally hit enter well before finishing writing.

**Comment by ploxiln** [comment]
I suggest using `--show=debug` and enabling parmiko debug logging, see https://www.fabfile.org/troubleshooting.html

this is probably related to paramiko and ssh key type support and selection, not sure where that "root" comes from though (thus the debug)

for what it's worth, I happen to maintain a fabric-1.x fork: https://github.com/ploxiln/fab-classic

**Comment by mikew** [comment]
Thanks for the pointer, it does seem to be the key itself. Tried an ancient key I have and it worked.

The output from pramiko wasn't super helpful. Diffing the working and not working runs, instead of outputting `Login password for 'root':` it just reports it working:

```
DEBUG:paramiko.transport:Trying discovered key e012522637c49f2e83d434a3f37d66d7 in /root/.ssh/id_rsa
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
```

And cheers on the fork! Am checking it out now

**Comment by ploxiln** [comment]
I suspect your new key is an rsa key using the "new openssh format", see
https://github.com/paramiko/paramiko/issues/1313
https://github.com/paramiko/paramiko/pull/1343

**Comment by mikew** [comment]
Perfect. Those issues also explain why the same bad key worked when it was added to my ssh-agent. Thanks again.
