### ISSUE TITLE
fabric 2 could not run “screen” command on remote as fabric 1 can

### ISSUE THREAD

**Issue by NickEm** [fabric/fabric#1974]
I have created issue with questions on [stackoverflow](https://stackoverflow.com/questions/56019514/fabric-2-issue-running-screen-command-on-remote) with all the details provided. I think most of the people look there for answer at first.

**Comment by yarikoptic** [comment]
it would have been nice if issue and details were provided here... that link (https://stackoverflow.com/questions/56019514/fabric-2-issue-running-screen-command-on-remote) seems to be 404 now, so cannot tell if I am experiencing the same problem as you did, but unlikely -- for me with fabric 2.5.0 screen starts just fine (well - I enter via bash and then start screen) but there are some oddities.
