### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by breisig** [fabric/fabric#1975]
Is this project dead? I haven't seen a commit in over 6+ months and the issue tracker is filling up with more and more issues.

**Comment by mwoss** [comment]
Sadly Fabric has only one true maintainer and according to his github status he's not available atm ;//

**Comment by LKI** [comment]
:( feels bad.
Is there any alternative for fabric?

**Comment by mwoss** [comment]
@LKI Could be overkill in some situations but Saltstack and Ansible are good alternatives.

**Comment by slippers** [comment]
fabric is a great project. invoke was a good move and has had recent updates. everybody needs a break from their monsters:)
should we ask what motivates @bitprophet ?

**Comment by makhomed** [comment]
Probably situation with this project described in the article http://antirez.com/news/129

See also personal site of Jeff Forcier http://bitprophet.org/ for more details.

**Comment by 4linuxfun** [comment]
fabric is a great project.

**Comment by bitprophet** [comment]
Been underwater due to job hunt/switch/start/moving. Back on things now! Thanks for your concern and patience 👍
