### ISSUE TITLE
Can't put a directory to remote

### ISSUE THREAD

**Issue by namewhat** [fabric/fabric#1977]

**Comment by Acowboyz** [comment]
I have same issue.

I trace the code of fabric 1.x, there is put_dir function.

will this feature be implemented on fabric 2.x?

**Comment by nafanz** [comment]
Yes, I miss this feature too.

For myself, I solved it this way.

```
nginx_server = SerialGroup(
    credentials.nginx,
    user='root'
)

nginx_directories = [
    '/etc/nginx/sites-enabled',
    '/etc/nginx/sites-available'
]

for dir in nginx_directories:
    dir_ls = nginx_server.run(f'ls {dir}', hide=True)
    for connection, result in dir_ls.items():
        output_stdout = result.stdout.split("\n")
        for i in output_stdout:
            try:
                nginx_server.get(f'{dir}/{i}')
            except exceptions.GroupException:
                pass
```

But so far I can’t figure out how to get files in different folders so that if the names match, they don’t replace each other.

**Comment by davidjmemmett** [comment]
Hi,

As per the [Upgrading from 1.x](https://www.fabfile.org/upgrading.html#file-transfer) guide, this feature has been removed from fabric v2. Please see the appropriate entry below.

> **Feature**: Recursive multi-file transfer (e.g. `put(a_directory)` uploads entire directory and all its contents)
> **Status**: Removed
> **Notes**: This was another one of the buggiest parts of v1, and over time it became clear that its maintenance burden far outweighed the fact that it was poorly reinventing `rsync` and/or the use of archival file tools like ye olde `tar`+`gzip`.
> 
> For one potential workaround, see the `rsync` function in [patchwork](https://github.com/fabric/patchwork).

Cheers,
David
