### ISSUE TITLE
AttributeError: 'SerialGroup' object has no attribute 'put'

### ISSUE THREAD

**Issue by eromoe** [fabric/fabric#1980]
fabric  is  2.4.0

From document  http://docs.fabfile.org/en/2.4/getting-started.html#bringing-it-all-together : 
```
from fabric import SerialGroup as Group
pool = Group('web1', 'web2', 'web3')
pool.put('myfiles.tgz', '/opt/mydata')
pool.run('tar -C /opt/mydata -xzvf /opt/mydata/myfiles.tgz')
```

I have checked that `SerialGroup` do have no attribute put

**Comment by coreaut** [comment]
@eromoe you are wrong, read the documentation again. It does not say that SerialGroup has a put function.


This is what the Documentation says:

```python
for connection in Group('web1', 'web2', 'web3'):
    connection.put('myfiles.tgz', '/opt/mydata')
```

**Comment by coreaut** [comment]
@bitprophet
Hello Sir, I think you can close this one.

Off Topic: do you accept contributions for the documentation?

**Comment by eromoe** [comment]
I think it need change
> You could use multiple *Group* method calls to do this:
to 
> You could use multiple *Connection* method calls to do this:

and only retain `pool.put('myfiles.tgz', '/opt/mydata')`  instead of full wrong example .

Put that sort of code would cause confusion if someone's English is not good . 
For example, I didn't quite understand  `That approach falls short as soon as logic becomes necessary ` meaning at first glance , I just saw 

> *Group* method calls to do this:  `  . 
> ```
> ...
> pool.put
> ...
> ```

**Comment by coreaut** [comment]
@eromoe 
Hello Sir, I'm sorry. 
Seems I should read the documentation again. Yes you're right. There is a error in the documentation.

```python
pool.put('myfiles.tgz', '/opt/mydata')
```
It's wrong, yes.
One would expect Group to have those functions but they are not there yet. You can contribute code if you want to change this.
bitprophet is more ore less alone on this project, afaik.

So you could reopen this and change the title to show the documentation is wrong.
