### ISSUE TITLE
Fabric 1.X: Documentation shows only *args, **kwargs in function signature

### ISSUE THREAD

**Issue by henniss** [fabric/fabric#1986]
The documentation for Fabric 1.X used to correctly display function signatures. However, some time ago it began displaying only `*args, **kwargs` for certain (decorated?) functions:

1.5.0:

![image](https://user-images.githubusercontent.com/17056237/59884466-47648880-936d-11e9-9305-9faf8018b553.png)

[1.12.1](http://docs.fabfile.org/en/1.12.1/api/core/operations.html):

![image](https://user-images.githubusercontent.com/17056237/59884894-6adc0300-936e-11e9-9341-29327771edd6.png)

I know 1.X isn't a priority now, since 2.0 has been out for over a year, but thought I should report this anyway, since we haven't found the time to migrate and I imagine others are in the same boat.

**Comment by ploxiln** [comment]
hmm that's odd.

in the short term you could look at https://ploxiln.github.io/fab-classic/api/core/operations.html

**Comment by bitprophet** [comment]
Interestingly, the "live" 1.5 docs also show the problem: http://docs.fabfile.org/en/1.5/api/core/operations.html

Annoyingly this has been an issue at least once or twice in the past and I'm not sure why/when it reverted. Will take a quick look in case it's an easy fix.

EDIT: as I could've guessed, it happened way back when we first switched the site from the old single doc site to the (new at the time) Paramiko/Invoke style split doc sites. For whatever reason the old unwrap code did not get ported.

**Comment by bitprophet** [comment]
I no longer have useful branch markers for 1.5-1.9 but those are so ancient I'm not going to worry. 1.10-1.14 just got the fix & docs subsites are rebuilding now.

**Comment by bitprophet** [comment]
Confirmed that eg http://docs.fabfile.org/en/1.14/api/core/operations.html was previously rendering the splat-args version and is now rendering the fixed version. Thanks for reporting this!!
