### ISSUE TITLE
Unknown exception: X962

### ISSUE THREAD

**Issue by weisong82** [fabric/fabric#1994]
demo runs ok on A computer, but failed on B computer. both use miniconda 3.6
`c = Connection(
    "{username}@{ip}:{port}".format(
        username="root",
        ip='xx',
        port=22,
    ),
    connect_kwargs=args,
)
result = c.run('uname -s')`

Unknown exception: X962
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/root/miniconda3/lib/python3.6/site-packages/paramiko/transport.py", line 2199, in _negotiate_keys
    self.kex_engine.start_kex()
  File "/root/miniconda3/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 42, in start_kex
    serialization.Encoding.X962,
  File "/root/miniconda3/lib/python3.6/enum.py", line 324, in __getattr__
    raise AttributeError(name) from None
AttributeError: X962

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-dff755a1b44c> in <module>()
----> 1 result = c.run('uname -s')
      2 c.create_session()

<decorator-gen-3> in run(self, command, **kwargs)

~/miniconda3/lib/python3.6/site-packages/fabric/connection.py in opens(method, self, *args, **kwargs)
     27 @decorator
     28 def opens(method, self, *args, **kwargs):
---> 29     self.open()
     30     return method(self, *args, **kwargs)
     31 

~/miniconda3/lib/python3.6/site-packages/fabric/connection.py in open(self)
    613             del kwargs["key_filename"]
    614         # Actually connect!
--> 615         self.client.connect(**kwargs)
    616         self.transport = self.client.get_transport()
    617 

~/miniconda3/lib/python3.6/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase, disabled_algorithms)
    404             sec_opts.key_types = [keytype] + other_types
    405 
--> 406         t.start_client(timeout=timeout)
    407 
    408         # If GSS-API Key Exchange is performed we are not required to check the

~/miniconda3/lib/python3.6/site-packages/paramiko/transport.py in start_client(self, event, timeout)
    658                 e = self.get_exception()
    659                 if e is not None:
--> 660                     raise e
    661                 raise SSHException("Negotiation failed.")
    662             if event.is_set() or (

~/miniconda3/lib/python3.6/site-packages/paramiko/transport.py in run(self)
   2081                             self._send_message(error_msg)
   2082                         else:
-> 2083                             self._handler_table[ptype](self, m)
   2084                     elif ptype in self._channel_handler_table:
   2085                         chanid = m.get_int()

~/miniconda3/lib/python3.6/site-packages/paramiko/transport.py in _negotiate_keys(self, m)
   2197             self._send_kex_init()
   2198         self._parse_kex_init(m)
-> 2199         self.kex_engine.start_kex()
   2200 
   2201     def _check_banner(self):

~/miniconda3/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py in start_kex(self)
     40         m.add_string(
     41             self.Q_C.public_bytes(
---> 42                 serialization.Encoding.X962,
     43                 serialization.PublicFormat.UncompressedPoint,
     44             )

~/miniconda3/lib/python3.6/enum.py in __getattr__(cls, name)
    322             return cls._member_map_[name]
    323         except KeyError:
--> 324             raise AttributeError(name) from None
    325 
    326     def __getitem__(cls, name):

AttributeError: X962

**Comment by ploxiln** [comment]
`Serialization.Encoding.X962` was added in cryptography-2.5 - you are using an older version of cryptography along with a newer version of paramiko. (Paramiko's setup.py should prevent this, if pip was used to install it.) To fix, upgrade cryptography, or downgrade paramiko.

**Comment by neoluu** [comment]
Hi,

I have the same problem suddenly. I've updated cryptography to 2.7 but did not resolve.

Python 3.6.5
Fabric 2.5.0
paramiko 2.6.0
cryptography 2.7 (was 2.2)
