### ISSUE TITLE
Make `put` sudo-able

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#2]
### Description

Right now, `put` can only write remote files as the logging-in user, which is problematic when one needs to write to locations owned by root or another user.

Paramiko's SFTP API doesn't support any sort of sudo functionality (though I rather doubt the SFTP protocol in general supports this anyways) so this will need to be implemented as a call to the current `put` behavior, plus a `sudo('mv')`.

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2009-07-20** at **04:56pm EDT**
### Relations
- Related to #140: Recursive put() and get()
- Related to #257: Add a convenience chown-ing kwarg to put()?

---

Closed as _Done_ on **2010-11-14** at **09:02pm EST**

**Comment by minhaz1** [comment]
Is there any way to make `put` support `shell=False` and `use_sudo=True`. For example the `sudo()` supports `shell=False` but there doesn't seem to be a way to do it with put. In my use case, my user can execute sudo commands, but cannot get a sudo shell (for security auditing purposes).

**Comment by lkdmid** [comment]
I'm not seeing any documentation for "Make `put` sudo-able" and the Fabric 1.x syntax of `use_sudo=True` is invalid. Any pointers please?
