### ISSUE TITLE
AttributeError: 'str' object has no attribute 'extend' when using custom connect_kwargs and key_filename option

### ISSUE THREAD

**Issue by joeydumont** [fabric/fabric#2007]
When using a custom `connect_kwargs` with a `key_filename` option, like so:

```python
    config = fabric.config.Config()
    print("Connecting with ssh/config")
    with fabric.Connection(
        host=instancePrivateIp,
        user='ec2-user',
        config=config,
        connect_kwargs={
            "key_filename": keyFileName,
        }) as c_instance:
```
I get an `AttributeError`:

```python
  File "/home/dumontj/Projects/ami-builder/ami_builder/customization.py", line 26, in do_bash_customization
    "key_filename": keyFileName,
  File "/home/dumontj/.local/share/virtualenvs/ami-builder-jbdgQc96/lib/python3.7/site-packages/fabric/connection.py", line 450, in __init__
    self.connect_kwargs = self.resolve_connect_kwargs(connect_kwargs)
  File "/home/dumontj/.local/share/virtualenvs/ami-builder-jbdgQc96/lib/python3.7/site-packages/fabric/connection.py", line 490, in resolve_connect_kwargs
    connect_kwargs["key_filename"].extend(
AttributeError: 'str' object has no attribute 'extend'
```

The documentation specifies that `key_filename` should be given as a string, but I found that it works if you actually give it a list:

```python
    with fabric.Connection(
        host=instancePrivateIp,
        user='ec2-user',
        config=config,
        connect_kwargs={
            "key_filename": [keyFileName,],
        }) as c_instance:
```

If this is the wanted syntax, I can update the documentation through a PR (see https://github.com/fabric/fabric/blob/2.0/fabric/connection.py#L234). Otherwise I could change `fabric/connection.py` to check whether there is already an entry, then transform it into a list if necessary.

**Comment by boweevil** [comment]
I'm seeing the same issue on 2.5.  However, using a list works.

**Comment by adq** [comment]
Same problem. Looks like it could be a silly bug to be, so pinning to 2.4.0 till we hear more from upstream.

**Comment by m4g005** [comment]
I get the same problem when host is set to a DNS name. When set to an IP, the exception doesn't occur.
E.g.:
```
{'host': '127.0.0.1', 'user': 'MyUser', 'connect_kwargs': {'key_filename': '/Users/MyUser/.ssh/MyPem.pem'}} # <- Works
{'host': 'some.dns.name', 'user': 'MyUser', 'connect_kwargs': {'key_filename': '/Users/MyUser/.ssh/MyPem.pem'}} # <- Doesn't work
```

**Comment by BISMIFATHIMANASAR** [comment]
face_caches[self.face_img_paths[i].stem] = faces
AttributeError: 'str' object has no attribute 'stem'
 i got this error. can anyone suggest me a solution

**Comment by danmichaelo** [comment]
Someone else made a PR to change the docs, but not merged yet: #2014

**Comment by fmors** [comment]
This happens to me as well... and also, I think it would be important to be able to set if I only want to connect using the key_filename provided, instead of using the ssh_config info.

**Comment by laver0ck** [comment]
It is an error in docs. `key_filename` expects a list.

```
c = Connection(
    host="hostname",
    user="admin",
    connect_kwargs={
        "key_filename": ["/home/myuser/.ssh/private.key"],
    },
)
```

**Comment by vardhmanandroid2015** [comment]
Providing key file name within list worked.. Thanks  
@laver0ck for pointing this...

**Comment by bdmorin** [comment]
Documentation is still wrong, what an infuriating waste of 2 hours. lol

**Comment by vardhmanandroid2015** [comment]
i know it is quite frustrating but it is an open source so we need to be little patient with such issues.... Is there anything I can do to update document so others will not get frustrated with this......

**Comment by bitprophet** [comment]
2.7.1 is out with the fix!
