### ISSUE TITLE
docker-compose exec can't find docker executable

### ISSUE THREAD

**Issue by zoh48gz04** [fabric/fabric#2013]
Hi there,

I'm currently porting fab1 scripts to v2.
When trying to execute a command via `docker-compose exec` in `c.local()` I get the following error:
```
Couldn't find `docker` binary. You might need to install Docker:

https://docs.docker.com/engine/installation/mac/
```

The docker binary is in the PATH and executable from within `c.local`:

```
@task
def test(c):
  c.local('echo $PATH')
  c.local('/usr/local/bin/docker ps')
  c.local('docker-compose exec php php test.php')
```

results in

```
$ fab2 test
/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                      NAMES
e89ab2360f88        jwilder/nginx-proxy        "/app/docker-entrypo…"   9 months ago        Up 3 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy
Couldn't find `docker` binary. You might need to install Docker:

https://docs.docker.com/engine/installation/mac/
```

Does anyone have an idea what's going on here?

Thanks and best regards!

**Comment by Synkied** [comment]
Hi @zoh48gz04!
Does running the docker-compose command works on your machine, outside of fabric's script?

**Comment by zoh48gz04** [comment]
Hi @Synkied 

yes it does perfectly!

**Comment by zoh48gz04** [comment]
This is really weird, other `docker-compose` commands are working perfectly.
The problem is just docker-compose exec.

**Comment by zoh48gz04** [comment]
Got it working by using `replace_env=False` and the `docker-compose exec -T` flag.
