### ISSUE TITLE
Status of the project? Dead or alive? Need a hand?

### ISSUE THREAD

**Issue by im-n1** [fabric/fabric#2019]
Hey I  use fabric since 1.0 version and it's really good. But from what I see now - 332 issues, 33 pull requests - it seems like it's dying.

This is really cool project that has almost no alternatives. Ansible aims for imdempotency and is "config files" oriented. It would be really pity if this would die. Think about this for a second.

Since I use this project for so long maybe I can help with some merge requests at least. I guess other folks would help me as well. Do you think it's still possible to gain some momentum here and don't fall into black hole of abandoned projects?

**Comment by zhan9san** [comment]
We look forward to reactivating this project, thanks

**Comment by bitprophet** [comment]
Still alive, 2019 just sucks. Will be looking to find people I can trust to help with triage in 2020.

**Comment by im-n1** [comment]
I guess you can trust us. The community. But maybe some of us might switch to Ansible...
