### ISSUE TITLE
How to alway echo executed commands, also for manually created connections

### ISSUE THREAD

**Issue by justinc1** [fabric/fabric#2032]
I have fabfile which I run with `fab -e ...`. This shows the executed commands.

In fabfile additional connection to a VM is created (`cvm = fabric.Connection(vm_ip)`). I was not able to set `echo` parameter as `connect_kwargs`. How to enable echo also for the `cvm` connection?

**Comment by justinc1** [comment]
I think it will work if I subclass `fabric.Connection` and override the default `run` method to always set `echo`. But it does sound as overkill.

**Comment by gitaarik** [comment]
You set configuration on a `Connection` object like this:

```
from fabric.config import Config


config = Config(overrides={
    'run': {
        'echo': True
    }
})

c = Connection('myhost', config=config)
c.run('ls')
```

**Comment by justinc1** [comment]
Thank you @gitaarik , that does the job.
