### ISSUE TITLE
Fabric 2 - Output the host the command is running on

### ISSUE THREAD

**Issue by gitaarik** [fabric/fabric#2035]
Fabric 1 prints the host the command is running on, in front of the command that is run.

In Fabric 2, I managed to enable showing the command that is run by configuring the connection like this:

```python
from fabric.config import Config
from fabric import SerialGroup as Group


config = Config(overrides={
    'run': {
        'echo': True
    }
})

c = Group('host1', 'host2', 'host3', config=config)
c.run('ls')
```

But still the host the command is running on is not shown. That would be very handy because if there are errors, I know which host I should fix, in case I have multiple hosts.

Is there a way to add this to the output?

**Comment by ploxiln** [comment]
I think the answer is "no" and the issue is tracked here: https://github.com/pyinvoke/invoke/issues/15

**Comment by ploxiln** [comment]
see also #1663

**Comment by gitaarik** [comment]
I'm continuing the discussion on pyinvoke/invoke#15
