### ISSUE TITLE
Error reading input error when using put() method on local mounted directory

### ISSUE THREAD

**Issue by alexanderdevm** [fabric/fabric#2036]
When transferring a file using fabric put from a mounted folder to a remote server then `Error reading input:[Errno 13] Permission denied` is shown.

```
local_path = '/mnt/content/file.txt'
remote_path = '/tmp/'

ssh = Connection(host=host, user=user,
                              connect_kwargs={"password": password})

res = ssh.put(local_path, remote_path)

res -> Error reading input:[Errno 13] Permission denied
```

The file can be scp'd normally using scp command or using paramiko.
Mounted forlder/file permissions are `rwxr-xr-x 1 root root`

Is there a way to get fabric put to transfer the file?

**Comment by ploxiln** [comment]
I think you have to specify remote filename too, like

```
remote_path = '/tmp/file.txt'
```

**Comment by alexanderdevm** [comment]
yes, that fixed.
