### ISSUE TITLE
Environment variable is not passed onto a remote command

### ISSUE THREAD

**Issue by exhuma** [fabric/fabric#2043]
Considering how basic this feature is, I assume that I am doing something wrong here, but on the off-chance that this really is a bug, here is my current observed behaviour (simplified to a minimal example):

```
from fabric import Connection
from invoke import task


@task
def hello(ctx):
    conn = Connection('localhost')
    conn.run('export', env={'FOO': 'BAR'})
```

And on the shell:

```
$ ./env/bin/fab hello
/home/users/malbert/work/tmp/env/lib/python3.5/site-packages/invoke/loader.py:3: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/users/malbert/work/tmp/env/lib/python3.5/site-packages/invoke/tasks.py:153: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  spec = inspect.getargspec(func)
export
HOME=/home/users/malbert
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LOGNAME=malbert
MAIL=/var/mail/malbert
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
SHELL=/bin/zsh
SSH_CLIENT='127.0.0.1 46992 22'
SSH_CONNECTION='127.0.0.1 46992 127.0.0.1 22'
USER=malbert
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_ID=64949
```

As you can see, the environment variable `FOO` does not appear in the output but I would expect it to be.

I also tried with `replace_env=True`, but that didn't help either.

The reason why I am creating the `Connection` instance inside a task is because in the real task showing this behaviour dynamically creates connections to different hosts, so the overall structure is the same as this simplified example.

I did not try using a "real" fabric-task instead of an invoke-task though.

**Comment by ploxiln** [comment]
see #2011

**Comment by exhuma** [comment]
Thanks. :)
