### ISSUE TITLE
Archive Packaging Error: -10 

### ISSUE THREAD

**Issue by bhavin3116** [fabric/fabric#2045]
Having issue while uploading build via Fabric.

Error 
Archive Packaging Error: -10
Could not export the entitlements and resource rules from existing application signature. 

<img width="318" alt="Screen Shot 2019-12-30 at 4 49 03 PM" src="https://user-images.githubusercontent.com/29137795/71630402-c1a17f80-2bd0-11ea-8eda-95cf24abc5cf.png">

Already tried this ..
https://stackoverflow.com/questions/46366599/fabric-archive-packaging-error-6?rq=1

**Comment by ploxiln** [comment]
You have found the wrong fabric - this project is not related to https://get.fabric.io/
