### ISSUE TITLE
Having trouble with Connection config

### ISSUE THREAD

**Issue by WinstonN** [fabric/fabric#2048]
Hi, 

I apologise if I missed this in the docs somewhere, if I did, please point me in the right direction

I have this code
```
for host in context.host:
        c = Connection(host)
        c.run('uname -a')
``` 

in my ~/.ssh/config I have some config which allows me to simply do
```
ssh ip.add.re.ss
```
which gets me into my hosts, via a bastion gateway

When I run the code in fabric, I get connection timeout. 
My question is, can you please help me to figure out how to add this connection config? Can you show me a real example, which would help me to build on top of?

# non issue related
I loved fabric 1. fabric 2 is strange, difficult, sparsely documented to the point where it's non usable. 
It was really an eye opener for me to come from fabric 1 and dive into fabric 2, and I often wonder why a developer would do something like this. Why take something that is loved, and has the ability to challenge all the big guns out there, and build something completely often lacking features (like roles, for example)
It's neither here, nor there, but I am your perfect use case. And if I cannot make this work, you have a bigger problem on your hands....
Not, a rant, just honest feedback <3

**Comment by ploxiln** [comment]
The relevant docs for loading ssh config files is: http://docs.fabfile.org/en/2.5/concepts/configuration.html#ssh-config

Please share your exact fabric and paramiko versions, and also share a couple sample sections from your ssh config, with ip addresses redacted if you like, to e.g. "1.1.1.1", "2.2.2.2". paramiko is what actually loads your ssh config, and it doesn't support all directives/features (but a fair bit was added very recently, in paramiko-2.7.0)

**Comment by WinstonN** [comment]
Hi @ploxiln, sure

```
fabric            2.5.0
paramiko          2.7.1
```

ssh config looks like
```
# Somewhere, over the rainbow
# foo
Host bastion.foo.rainbow
  HostName 1.1.1.1
    IdentityFile ~/.ssh/unicorn.key
    User unicorn
    ForwardAgent yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

# bar
Host bastion.bar.rainbow
  HostName 2.2.2.2
    IdentityFile ~/.ssh/unicorn.key
    User unicorn
    ForwardAgent yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

# Proxy Commands
# foo
Host 10.1.*.*
  ProxyCommand ssh -e none %r@bastion.foo.rainbow -W %h:%p
  ForwardAgent yes
  User unicorn
  IdentityFile ~/.ssh/unicorn.key
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

# bar
Host 10.2.*.*
  ProxyCommand ssh -e none %r@bastion.bar.rainbow -W %h:%p
  ForwardAgent yes
  User unicorn
  IdentityFile ~/.ssh/unicorn.key
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
``` 

I then do, ssh 10.1.1.1 or ssh 10.2.1.1 and i'm in

**Comment by ploxiln** [comment]
hmm ... looks to me like it should work. two things to look into:
  * enable debug logging for paramiko with `logging.basicConfig(level=logging.DEBUG)`
  * just after starting the script, see if/how the ProxyCommand is running with something like `ps ax | grep ssh`

**Comment by ploxiln** [comment]
`Include` is not supported. There's an attempt here: https://github.com/paramiko/paramiko/pull/1194

**Comment by WinstonN** [comment]
@ploxiln 

Thank you so much 
Mmm, breaks my heart to say it, but I think fabric2 is maybe not for me. That PR was raised 23 Apr 2018 (2 years ago)

All the best with the project
