### ISSUE TITLE
Tasks with underscores in names don't work

### ISSUE THREAD

**Issue by lucadealfaro** [fabric/fabric#2059]
```
@task
def is_working(c):
    print("Yes, it works")
```

```
$ fab is_working
No idea what 'is_working' is!
```

**Comment by miso-belica** [comment]
Hi, you need to use `fab is-working`. Fabric translates the naming convention from Python to CLI for you 😉 I think it is possible to turn off. It's somewhere in the documentation if you really insist on underscores.

**Comment by lucadealfaro** [comment]
Great, thanks!  I did not know that.  No problem, I just wish it also changed all the "t" into "p" and vice versa, it would make just as much sense, and I would get to write "pup-file" instead of "put_file", which is clearly more fun... ;-)

**Comment by miso-belica** [comment]
@lucadealfaro You can read more in the documentation http://docs.pyinvoke.org/en/stable/concepts/namespaces.html#dashes-vs-underscores

**Comment by PhiOfX** [comment]
It is not great practice to modify user choices by default without at least some warning. Dashes and underscores are visually close and people may spend hours pulling their hair (I did) of why something doesn't work (especially with the migration for fabric 2). I would recommend either auto_dash_names: true by default, or if the CLI dash convention is so important to print some warning on screen when processing a task with underscores.

**Comment by somnath-binary** [comment]
It only took me a full day, a few clumps of hair, and most of my patience. On the bright side, I’m saving on haircuts for the next few weeks!
