### ISSUE TITLE
paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted

### ISSUE THREAD

**Issue by chrisbarry** [fabric/fabric#2077]
I'm not sure if this is the right place for this, but I'm having a lot of problems using fabric to connect to an AWS server using their key format? Is there a problem with their pem files?

paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted 

The key is not encrypted.

**Comment by zhan9san** [comment]
Hi
Which version do you use? And how do you use it? Could you please provide some code?

The following code work well(Version: 2.5.0).
```
from fabric import Connection
c = Connection('x.x.x.x', user='ec2-user', connect_kwargs={"key_filename": "/Users/x/aws/ue1.pem"})
c.run('hostname')
```

**Comment by chrisbarry** [comment]
So, the problem was I was setting half my connection information inside the fabfile

c = Connection(
host='......',
user='......',
port=22,
connect_kwargs={
"key_filename": "...
}
)

And doing half on the command line

fab -i ../devops/keys/******.pem -H place-server.com deploy

When in actual fact, you could just do it all from the command line, and just needed to add username@server-hostname to the command

fab -i ../devops/keys/******.pem -H username@place-server.com deploy

I'm not sure if putting all the information inside the fabfile would make the problem go away in the other direction, but it seems like I've been getting confused by putting half the information in two places, and perhaps those places don't merge.

Infact, it seems like the in file connection is just entirely ignored, as I commented it out entirely, did everything from the command line, and everything worked. Which makes sense, but I was very used to fabric 1

**Comment by BenSturmfels** [comment]
For what it's worth, this "private key file is encrypted" error popped up when I'd specified a completely wrong host string with two "@" symbols eg. "user@@example.com". This is a bit misleading since the error was nothing to do with private keys.

**Comment by davidjmemmett** [comment]
Hi @chrisbarry, if this is still an issue, can you please send a code snippet which isn't working?

**Comment by davidjmemmett** [comment]
I've just realised that this is quite an old issue. I'll close it off for now.
