### ISSUE TITLE
do you need help?

### ISSUE THREAD

**Issue by anarcat** [fabric/fabric#2079]
Hi!

I am really enthusiastic about this project. It has helped me tremendously in automating some processes that were hard to automate with Ansible (because too custom) or Puppet (because too ad-hoc). I want to use this project in the long term so I'm hoping I can contribute back with patches and reviews.

Unfortunately, it seems a lot of pull requests and issues are unanswered here. Do you need help?

I see that your (@bitprophet) GH status is currently "Focused on features & crit bugfixes, no time for triage rn", but there's no one else with access to the Invoke and Fabric projects on GitHub, which makes me worried about the proverbial "bus factor" on top of short-term maintenance concerns.

At the very least, here, #1960 should just be merged to unbreak the test suite. I think that qualifies as a "crit bugfix". :)

Anyways, this is an offer for help. I understand that free software projects, in general, are done on a best-effort basis, and I don't expect you to just jump up to attention because I am excited about your project. And particularly now, with the health situation, I would totally understand if this project would take a back seat. 

And that's why I'm offering help. :) I'm happy to do some triage of the issue queue and provide patches for critical problems that come up, or as much involvement as you can allow or require. I understand that other collaborators here might be available to provide support and triage and it might be helpful to give them access too (thinking of redkrieg on irc for example).

Thanks for your hard work and this awesome project!

**Comment by eagleamon** [comment]
Hi, really glad this project exists as well, would be happy to help too!

**Comment by daringer** [comment]
had the same thought, count me in, happy to support. 
I would vote for an issues clean-up & prioritization first. 
@anarcat any irc/matrix/... to connect other fabric-users and ppl willing to support?

**Comment by anarcat** [comment]
>  @anarcat any irc/matrix/... to connect other fabric-users and ppl willing to support?

there's #fabric on freenode already...

**Comment by eagleamon** [comment]
I missed that point, great thanks !

**Comment by dbsxdbsx** [comment]
Do you know how to using fabric to connect remote windows machine?  I never work it out.

**Comment by anarcat** [comment]
> Do you know how to using fabric to connect remote windows machine? I never work it out. It just always stuck there, then showing an error after several seconds.

I don't think it's the right place to ask that question, sorry. :)

**Comment by rb1193** [comment]
Also a big fan of this project and willing and able to contribute time to it, at least while I'm stuck at home with no job (likely to be the case for a while). For me fabric hits the sweet spot between the directness and terseness of bash scripting and the power and configurability of Ansible/Puppet etc., great for solo devs/small teams

**Comment by bitprophet** [comment]
http://bitprophet.org/blog/2020/07/02/help-wanted/ !!
