### ISSUE TITLE
Mining Level issue

### ISSUE THREAD

**Issue by inklesspen1scripter** [fabric/fabric#2081]
Minecraft version: 20w17a
gradle-properties:
`minecraft_version=20w17a
yarn_mappings=20w17a+build.3
loader_version=0.8.2+build.194

#Fabric api
fabric_version=0.6.2+build.327-1.16

# Mod Properties
	mod_version = 1.0.0
	maven_group = net.fabricmc
	archives_base_name = fabric-example-mod`

Creating block:
`public static final Block BLOCK = new Block(FabricBlockSettings.of(Material.STONE)
.hardness(1.5f)
.breakByTool(FabricToolTags.PICKAXES, 1)
.build());`

and registering:
`Registry.register(Registry.BLOCK, new Identifier("inklesstest", "testblock"), BLOCK);
Registry.register(Registry.ITEM, new Identifier("inklesstest", "testblock"), new BlockItem(BLOCK, new Item.Settings().group(ITEM_GROUP)));`

java file is attached
[ExampleMod.txt](https://github.com/fabric/fabric/files/4528648/ExampleMod.txt)

When mining level higher than 0, block cannot be harvested
But when mininglevel is 0, any pickaxe (including wooden) can harvest it

And which code I need to use if this method wrong?

**Comment by ploxiln** [comment]
This repository is not related to https://github.com/FabricMC - this is the wrong "fabric"

**Comment by TehcJS** [comment]
i'm sure @davidjmemmett knows very well what fabric is
you don't have to make it harder for them
