### ISSUE TITLE
Out-of-the-box receipts for deployment

### ISSUE THREAD

**Issue by dbalabka** [fabric/fabric#2094]
I'm newcomer from PHP world and wondering does Fabric provides some out-of-the-box recipes for some common deployment scenarios?

For example, PHP has a great tool Deployer (probably inspired by Fabric and Capistrano) that provides recipes for most common use cases: https://github.com/deployphp/deployer/tree/master/recipe

For example, a recipe that automates directory structure creation and symlink switching for atomic source deployment on the server. Following article describes such an approach:
https://peshmerge.io/how-to-use-fabric-to-deploy-a-flask-web-application/

**Comment by lfglopes** [comment]
This might give you an idea https://github.com/mcuadros/fabric-composer

**Comment by dbalabka** [comment]
@lfglopes thanks. Unfortunately, I have to deploy my python project with PHP tool [Deployer](https://github.com/deployphp/deployer/tree/master/recipe) (that I mentioned above) which is stable and actively develop. I didn't find how it can be solved for Python with Python w/o bikeshedding.

**Comment by davidjmemmett** [comment]
Hi @dbalabka,

I'm not sure what you mean by receipts - fabric writes to stdout & stderr as appropriate whilst executing the tasks.

Could you please provide [some additional information](http://www.contribution-guide.org/) to help us reproduce your issue?


**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the core programming language interpreter/compiler are you using? For example, if it’s a Python project, are you using Python 2.7.3? Python 3.3.1? PyPy 2.0?
- What operating system are you on? Windows? (Vista? 7? 32-bit? 64-bit?) Mac OS X? (10.7.4? 10.9.0?) Linux? (Which distro? Which version of that distro? 32 or 64 bits?) Again, more detail is better.
- Which version or versions of the software are you using? Ideally, you followed the advice above and have ruled out (or verified that the problem exists in) a few different versions.
- How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)
A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.

**Comment by dbalabka** [comment]
@davidjmemmett by this ticket I'm requesting a feature instead of reporting a bug. I'm looking for some collection of ready solutions for common deployment scenarios that can be done with Fabric. Unfortunately, Fabric provides only low level actions. 

As a example I've mentioned Copestrano in Ruby and Deployer in PHP. Both provides solutions to minimize boilerplate code for application deployment along with similar to Fabric lower level API. 

Hope I've succeeded to explain my idea clearly 🙂

**Comment by davidjmemmett** [comment]
Hi @dbalabka,

There are a couple of projects available, [patchwork for fabric](https://fabric-patchwork.readthedocs.io/en/latest/) and [invocations for invoke](https://invocations.readthedocs.io/en/latest/).

I'm still not sure what you're asking about with regards to receipts - do you mean some sort of specially-formatted output or summary?

Cheers,
David

**Comment by dbalabka** [comment]
@davidjmemmett I've already reviewed both projects. Unfortunately, both of them do not provide solution to deploy the projects. 

~~Receipts~~ => recipes. Sorry, it just a mistake. This term is usualy used in some libraries. It defines scripts which implementes best pratices.

**Comment by davidjmemmett** [comment]
In which case, I think this might be worth raising against patchwork or invocations rather than fabric. Fabric provides an API for users to be able to do whatever they want over SSH, rather than providing environment-specific, pre-defined scripts.

I'm closing this issue, but feel free to raise one over at one of the projects listed above. It might also be worth giving specifics of what you're wanting to achieve too.
