### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by jerkstorecaller** [fabric/fabric#2101]
I noticed a while back there hadn't been commits in months, and tons of awaiting PRs. I thought things had just slowed down because the dev is busy, it happens. But just now I looked at @bitprophet 's last commit, changing the copyright year with the message "so it goes out on a cool looking year". Goes out? Is Fabric done? If so I think there should be a notice in the README and/or the website.

**Comment by anarcat** [comment]
this project is not discontinued. it has slowed down, but the maintainer has recognized the problem (see #2079) and is working towards resolving those problems.

if you want to help, it would be welcome, see #2079.

**Comment by jerkstorecaller** [comment]
That's fine. I figured it was something like that. @bitprophet should really put his call for help (http://bitprophet.org/blog/2020/07/02/help-wanted/) at the start of Fabric's README and/or the website. I don't see what benefit there is in posting it as the last comment in a ticket he then closed, and which therefore almost no one will see. :)
