### ISSUE TITLE
How to add multiplex options (ControlMaster etc)

### ISSUE THREAD

**Issue by BoPeng** [fabric/fabric#2103]
I would like to migrate our application from direct use of `ssh` command in `Popen` to fabric. However, we use multiplex options such as

```
-o 'ControlMaster=auto' -o 'ControlPath=.ssh/controlmaster/%r@%h:%p' -o 'ControlPersist=10m'
```
extensively in our application due to frequent visit of remote hosts. I can see from paramiko/paramiko#852 that these options are not supported by paramiko. Is there a way to specify it in frabric, perhaps through `connect_kwargs` of `Connection`?

**Comment by davidjmemmett** [comment]
Hi @BoPeng, the `connect_kwargs` are passed through to paramiko's [SSHClient.connect](http://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.connect) method. Therefore if paramiko doesn't support SSH multiplexing, neither will fabric.

As you've noted, there is already [an open issue in Paramiko](https://github.com/paramiko/paramiko/issues/852) for this, so I'm going to close this issue for now.

Cheers,
David.
