### ISSUE TITLE
Example of Connect() for target machine that is accessed via username & password

### ISSUE THREAD

**Issue by paul-hammant** [fabric/fabric#2117]
From https://www.fabfile.org/ ..

```
result = Connection('web1.example.com')
```

If I try to add username="root", password="myPasswd" (as Paramiko does), Fabric doesn't like that. Can a programatic example of username/password be shown, too please?

**Comment by ploxiln** [comment]
you can specify `user` (not `username`), and the password could be in the `connect_kwargs`
https://docs.fabfile.org/en/2.5/api/connection.html#fabric.connection.Connection.__init__

**Comment by paul-hammant** [comment]
That's it.

```
result = Connection('web1.example.com', user="root",
 connect_kwargs={"password":someWayOfSecurelyGettingPasswordWithoutStoringThatInSourceControl()}).run(...)
```

^ In case someone else is searching for this but can't fid it explicitly in the doco.
