### ISSUE TITLE
dynamic host inventory

### ISSUE THREAD

**Issue by 3c2b2ff5** [fabric/fabric#2118]
Hello,

I would like to do some tasks on some hosts, but I cannot add 3000 hosts to `fabfile.py`, so a dynamic host inventory with a role filter for host groups depending on host names would may do it. is there any way to create a dynamic host inventory from `puppetdb` for instance? 

Thanks

**Comment by davidjmemmett** [comment]
Hi @3c2b2ff5, have you taken a look at the [documentation regarding multiple servers](https://docs.fabfile.org/en/2.5/getting-started.html#multiple-servers)? You would have to write the mechanism for querying puppetdb yourself (though there appears to be one or two Python libraries able to do this).

**Comment by 3c2b2ff5** [comment]
Hi @davidjmemmett, thanks for the reply, I already started to write a script and it looks good so far.
