### ISSUE TITLE
RAM leaking

### ISSUE THREAD

**Issue by JosersRu** [fabric/fabric#2122]

**Comment by ploxiln** [comment]
You've found the wrong GitHub repo. This is not for https://fabricmc.net/ , this is for https://www.fabfile.org/

**Comment by JosersRu** [comment]
> You've found the wrong GitHub repo. This is not for https://fabricmc.net/ , this is for https://www.fabfile.org/

What? why? Everything is correct. I have a minecraft server, not a python library. The server leaking RAM, when there are not even players. This is problem

**Comment by ploxiln** [comment]
It seems I was not clear enough. This _repo_ here is for https://fabfile.org - go ahead and look at the README of this repo. It has nothing to do with Minecraft.
