### ISSUE TITLE
Fabric not opening on Aternos despite adding it previously

### ISSUE THREAD

**Issue by icedcrackerz** [fabric/fabric#2125]
![image](https://user-images.githubusercontent.com/70848570/98453209-a4bdcd00-214e-11eb-9711-df0dcc6a7237.png)
added it mutliple times in the "versions" section and still yet to work.

**Comment by davidjmemmett** [comment]
I think you may have raised this issue against the wrong project. This is fabric, a Python library for SSH automation; you appear to be seeking some Java library relating to the Minecraft game.

Closing issue.
