### ISSUE TITLE
Minecraft Fabric crashes when I open world/server

### ISSUE THREAD

**Issue by Fport1** [fabric/fabric#2141]
[crash-2021-02-14_09.56.54-client.txt](https://github.com/fabric/fabric/files/5977959/crash-2021-02-14_09.56.54-client.txt)

I don't know how to solve this and Minecraft really don't runs as well as I want in Vanilla.

Thaks

**Comment by davidjmemmett** [comment]
Hi Fport1, you've got the wrong project I'm afraid. This is a Python library for automating SSH and has nothing to do with Minecraft, let alone Java. Closing the issue.
