### ISSUE TITLE
Moving from invoke to fabric, tasks executed with Connection.run are executed in --dry-run mode 

### ISSUE THREAD

**Issue by hiphamster** [fabric/fabric#2143]
I'm thinking of upgrading to fabric, so i can leverage its ability to execute commands remotely, but still need to be able to run certain tasks locally (like building docker images and pushing them out to repository). 

my use case:

I have a set of build / deploy tasks, which are currently executed with invoke, and call 'ssh' explicitly inside the command:

~~~python
...
cmd = f'ssh alex@staging docker ps'
# c is Context
c.run(cmd)
~~~

I can create `fabric.Connection` object in my `@task`-decorated method or pass in connection from another task, but then `fab -R` is no longer respected when i use `fabric.Connection.run()` to execute the command. Is there a better way to do this or perhaps my approach is incorrect?

**Comment by davidjmemmett** [comment]
Hi @hiphamster,

Instantiating a new Connection object will create an entirely new configuration, as there is no global configuration in fabric v2:

```python
from fabric import task, Connection

@task
def test(c):
    # this will not run when -R argument is present
    c.run('echo this should not run')
    
    # this is a completely new Connection, with no data taken from
    # arguments, config files etc, therefore this should ignore -R on
    # the command line
    c2 = Connection(host='localhost')
    c2.run('echo this should run')
    
    # this is a completely new Connection, however, we're using the
    # configuration passed in the command line, therefore it should
    # respect the -R argument if passed
    c3 = Connection(host='localhost', config=c.config)
    c3.run('echo this should not run')
```

This outputs:
```
$ fab -R test
echo this should not run
this should run
echo this should not run
```

Does this help?

**Comment by hiphamster** [comment]
@davidjmemmett Yes, this helps. Thank you!

**Comment by hiphamster** [comment]
A followup question 

In the below sample, i update 'run' values in Connection's config with 'run' values from context config. This way
things like '--dry' will be respected by the connection.run. I found the merging process to be somewhat difficult - 
if DataProxy objects are present, merging fails. I don't want to take `c.run.dry` directly, because there may be 
other CLI flags passed in, that's why i did `f_config.load_overrides(data={'run': c.config._config['run']})`. It 
appears to work, but does not look clean.Is there a better way to do this either through merging or by taking CLI 
from sys.argv ?

This is a collection of 'remote' tasks.  

~~~python
     1 from pprint import pformat, pprint
     2
     3 from fabric import Config as FabricConfig
     4 from fabric import Connection
     5
     6 from invoke import task
     7 from invoke.config import merge_dicts
     8
     9
    10 @task
    11 def compose_up(c):
    12     """ Start services
    13     """
    14     c.run('echo "docker-compose up"')
    15
    16
    17 @task
    18 def compose_down(c):
    19     """ Stop services
    20     """
    21     c.run('echo "docker-compose down"')
    22
    23
    24 @task
    25 def verify(c):
    26     """ Verify that the services are running
    27     """
    28     env = c.deployment.get(c.deployment.environment)  # env could be 'staging','prod', or 'dev'
    29
    30     f_config = FabricConfig()
    31
    32     # f_config.update(c.config)
    33     f_config.load_overrides(data={'run': c.config._config['run']})
    34     # f_config.run = c.run
    35
    36     print(pformat(f_config._config, indent=2))
    37
    38     conn = Connection(host=env['host'], config=f_config) 
    39     r = conn.run('docker ps')
    40     # print(r[1])
    41
    42     # print(f'config: {c.config}')
    43     # c.run('echo "docker ps"')
~~~
