### ISSUE TITLE
default branch is still "2.0"

### ISSUE THREAD

**Issue by mogoh** [fabric/fabric#2147]
Looks wrong to me.

**Comment by bitprophet** [comment]
This was an experiment to see if it helped new bugfix PRs to target the 'right place' (in the "fix as far back as a bug applies, then merge forwards" sense). But I haven't done it in any other repos & at this point I don't think it's been any more useful than defaulting to master/main.

Thanks for the nudge. I'll just put it back to master (which will get renamed to main shortly).
