### ISSUE TITLE
How make wrap Fabric into a library?

### ISSUE THREAD

**Issue by KantiCodes** [fabric/fabric#2148]
Using tutorial from [Invoke](http://docs.pyinvoke.org/en/stable/concepts/library.html#reusing-invoke-s-cli-module-as-a-distinct-binary) I managed to make my Invoke program into a library 

part of the setup.py

```
setup(
    name='steinwurf-tasker',
    version=version,
    packages=['tasker'],
    install_requires=['invoke', 'fabric'],
    entry_points={
        'console_scripts': ['sw = tasker.main:program.run']
    }
)
```

Now I wonder if it's possible to do the same with Fabric.

**Comment by davidjmemmett** [comment]
Hi @KantiCodes,

I'm not entirely convinced that this is a valid issue. Closing until further information has been provided.

Cheers,
David
