### ISSUE TITLE
parallel task/function on the same host

### ISSUE THREAD

**Issue by arabnejad** [fabric/fabric#2149]
Hi
with Fabric v1.14
If I want to have parallel execution of a function on the **same/single host**, is that possible to use `@parallel` ?
I already tested these two options:
- if I use threading option, the shared `env` variable can be written by different threads
- if I use pool option, it will stuck on the `run` command , however, `local` works fine

**Comment by davidjmemmett** [comment]
Hi @arabnejad,

If this is part of a new project, I would highly recommend using Python 3 & Fabric 2. It looks as though Fabric v1 will deduplicate the hosts passed in, so passing `-H hostname,hostname` wouldn't work. In Fabric 2, parallel execution is achieved via `ThreadingGroup` (see [the docs](https://docs.fabfile.org/en/2.5/api/group.html) and the example below).

**tasks.py**
```python
from fabric import ThreadingGroup, task

@task
def test(c):
    c = ThreadingGroup('fabrictest@localhost', 'fabrictest@localhost')
    c.run('echo test')
```
Then running `inv test` will output:
```
test
test
```

Cheers,
David

**Comment by arabnejad** [comment]
Hi @davidjmemmett 

Thanks for you suggestion, 
I am working on a software toolkit which uses fabric to submit a large number of jobs to HPC remote servers 
I can see you point here about using Fabric v2.x and use `ThreadingGroup` functionality :) 

let me to explain better my target : 
assume, for a target remote host, we need to prepare a lost of individual folders (which contains files/folders and required job script) and then submit the job to that machine
the main problem is : how can this function (not a `@task`), let's say `job_sub` (to prepare individual folders and submit them) be executed in parallel handled by threads on the same host target (`env.hosts=[fabrictest@localhost]`)

**Comment by davidjmemmett** [comment]
Oh I see, this would probably be better handled by something you deploy to the remote host and run as a service. Something like [Celery](https://docs.celeryproject.org/en/stable/index.html) is probably what you're after.

Cheers,
David

**Comment by davidjmemmett** [comment]
Without wanting to be rude or mean, I think everything you're wanting to do is taken care of in the documentation. If there is an issue you'd like to raise, please feel free re-open this ticket.

Cheers,
David

**Comment by arabnejad** [comment]
Hi @davidjmemmett 

just one more question, due to some develop limitation, I can not use other external library 
is there any version of Fabric support multi-process execution of `run` command, i.e., assume you have
```py
def fun1(.....):
    ...
    fabric.run(.....)
    ...
```
and then you assign this function to process worker in `multiprocessing.pool`
```py
   P = multiprocessing.Pool(....)
   P.apply_async(func=fun1,.....)
```
everything works well, until we reach to `fabric.run` command and code hangs there in all concurrent process
