### ISSUE TITLE
paramiko error EOF in transport thread after validation ok cisco SG350

### ISSUE THREAD

**Issue by aleprrr** [fabric/fabric#2152]
Hi, i have this problem, a cisco SG350, do you know if this model is supported? or if this model return a unexpected message to paramiko before valitation?

thanks

DEB [20210316-17:01:27.024] thr=12  paramiko.transport: starting thread (client mode): 0x61039790L
DEB [20210316-17:01:27.031] thr=12  paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.1
DEB [20210316-17:01:28.011] thr=12  paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.3p1.RL
INF [20210316-17:01:28.011] thr=12  paramiko.transport: Connected (version 2.0, client OpenSSH_7.3p1.RL)
DEB [20210316-17:01:28.512] thr=12  paramiko.transport: kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'chacha20-poly1305@openssh.com'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'chacha20-poly1305@openssh.com'] client mac:[u'hmac-sha1'] server mac:[u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20210316-17:01:28.512] thr=12  paramiko.transport: Kex agreed: diffie-hellman-group-exchange-sha1
DEB [20210316-17:01:28.512] thr=12  paramiko.transport: HostKey agreed: ssh-rsa
DEB [20210316-17:01:28.513] thr=12  paramiko.transport: Cipher agreed: aes128-ctr
DEB [20210316-17:01:28.513] thr=12  paramiko.transport: MAC agreed: hmac-sha1
DEB [20210316-17:01:28.513] thr=12  paramiko.transport: Compression agreed: none
DEB [20210316-17:01:28.987] thr=12  paramiko.transport: Got server p (2048 bits)
DEB [20210316-17:01:29.442] thr=12  paramiko.transport: kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEB [20210316-17:01:29.443] thr=12  paramiko.transport: Switch to new keys ...
DEB [20210316-17:01:29.966] thr=12  paramiko.transport: userauth is OK
INF [20210316-17:01:29.982] thr=12  paramiko.transport: Authentication (password) successful!
DEB [20210316-17:01:33.591] thr=12  paramiko.transport: EOF in transport thread

self.ssh = paramiko.SSHClient()
self.ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
self.ssh.connect(self.cpe_ip, port=22, username=usuario, password=clave, timeout=5)
self.transport = paramiko.Transport((self.cpe_ip, 22))   
here ok!
self.transport.connect(username=usuario, password=clave)   <<<< here timeout

only with this model

switch#sh ver
Active-image: flash://system/images/image1.bin
  Version: 2.3.5.63
  MD5 Digest: 5881484e04bsdccs7c3s87s445e3ab8d
  Date: 20-Aug-2017
  Time: 19:04:55
Inactive-image: flash://system/images/_image1.bin
  Version: 2.3.5.63
  MD5 Digest: 5881484e04bcdcc17c32872445e3ab8d
  Date: 20-Aug-2017
  Time: 19:04:55
switch2fea87#sh system
System Description:                       SG350-10
System Up Time (days,hour:min:sec):       00,04:03:23
System Contact:                           noc
System Name:                              switch
System Location:                          street
System MAC Address:                       x:x:x:x:x:x
System Object ID:                         1.3.6.1.4.1.9.6.1.95.10.3

Unit          Type
---- ----------------------
 1          SG350-10

Unit                Fans Status
----   -------------------------------------
 1           Fans status is N/A

Unit Temperature (Celsius)   Status
---- --------------------- ----------
 1            60               OK

switch#

**Comment by davidjmemmett** [comment]
Hi @aleprrr,

Could you please provide [some additional information](http://www.contribution-guide.org/) to help us reproduce your issue?

In addition, I believe this issue belongs over at [paramiko](https://github.com/paramiko/paramiko), as it doesn't look like you're using fabric from the example you provided.

**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the Python interpreter are you using? Are you using an alternative interpreter such as PyPy?
- What operating system are you using both client & server-side?
- Are you using OpenSSH server or something else?
- Which version or versions of the software are you using?
- How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)
A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.

**Comment by ploxiln** [comment]
please see https://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system
and https://github.com/ktbyers/netmiko

**Comment by davidjmemmett** [comment]
Thanks @ploxiln. Given how this does appear to be a Paramiko issue, I will close this issue in reference to [the FAQ entry](https://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system).

Cheers,
David
