### ISSUE TITLE
fabfile.org: Redirection to TLS does not work

### ISSUE THREAD

**Issue by codethief** [fabric/fabric#2161]
Hi there!

First of all: Thank you for this fantastic project! I was about to write some code to do something very similar the other day but it looks like I no longer have to. :)

Anyway, I followed a link from some blog article to `http://fabfile.org` and did not get redirected to `https://www.fabfile.org`. Instead, the website was served without TLS, which Chrome warned me about. The same thing seems to happen when I enter `http://www.fabfile.org` – no redirection to TLS, either. Meanwhile, `https://fabfile.org` does not seem to work at all.

This might seem like a minor issue but I find it rather critical. At first, my conclusion was that there's no TLS support at all and I ended up being rather wary when it comes to trusting fabric from a security point of view (given that it's based on SSH and everything).

**Comment by bitprophet** [comment]
This is a longstanding deficiency with my VPS setup (it also impacts paramiko and invoke). I'll fix it once I redo that system or give up and move my apex domain to something hosted. Thanks!
