### ISSUE TITLE
Install fails on arm64 (Mac M1, Silicon) due to pynacl issue (via libcffi)

### ISSUE THREAD

**Issue by eblume** [fabric/fabric#2164]
**Due diligence**
I could find no bugs related to this issue on this tracker. Please note that there IS an issue tracked 'upstream' on the PyNACL tracker here: https://github.com/pyca/pynacl/issues/654

**Describe the bug**
`pip install fabric` fails while attempting to install PyNaCl on an arm64 architecture. Please see the above issue (pynacl#654) for an example.

This appears to be an issue where an underlying dependency, `cffi`, as noted in that referenced issue. (https://foss.heptapod.net/pypy/cffi/-/issues/464#note_147550) The CFFI team seems to have decided to explicitly not support arm64 at this time.

**Is there a way to build fabric without pynacl?**

**To Reproduce**
Steps to reproduce the behaviour (please attach a minimal example):
1. Open a non-rosetta2 terminal on an arm64 mac
2. `pip install fabric`

**Expected behaviour**
Pip installs fabric along with its dependencies.

**Environment**
* python 3.9.4
* macOS 11.4 (Big Sur)
* arm64 processor (NOT x86/amd64, and no rosetta2 translation used)
* Details for the fabfile etc. should be irrelevant as this is an installation and build issue.

**Additional context**
My suspicion is that all projects that use `libcffi` are currently broken with this issue on arm64. Because that project has decided not to support arm64 at this time, projects that wish to support arm64 will need to investigate alternative cryptography libraries. I have not investigated the compatibility, but I would suggest taking a look at `cryptography`: https://github.com/pyca/cryptography

**Comment by ploxiln** [comment]
pynacl is a dependency of paramiko, rather than of fabric directly. paramiko already uses cryptography to a large extent, and there is a PR to remove the dependency on pynacl using cryptography relatively recently (compared to when paramiko started using cryptography). https://github.com/paramiko/paramiko/pull/1806

**Comment by eblume** [comment]
Confirmed, this reported issue has been resolved, thanks all.
