### ISSUE TITLE
Recreating 'with lcd' in Fabric 2? 

### ISSUE THREAD

**Issue by mollypabst** [fabric/fabric#2171]
I am trying to recreate this Fabric 1 implementation within Fabric 2: 

```
with lcd("../"):
    local("tar -zcf somefile.tar.gz directory")
    put('somefile.tar.gz','workspace/somefile.tar.gz')
    local("rm somefile.tar.gz")
```

I have viewed previous issues but none have been of use. Is there any way to recreate something similar to this in Fabric 2 since lcd is not supported? I am switching between remote and local so I cannot solely run tasks locally.

**Comment by BenSturmfels** [comment]
Hi @mollypabst, I think what you're after is:

```
c.cd("../"):
    c.local("tar -zcf somefile.tar.gz directory")
    c.put('somefile.tar.gz', 'workspace/somefile.tar.gz')
    c.local("rm somefile.tar.gz")
```
