### ISSUE TITLE
loadSVGFromString  Parse textContent space error

### ISSUE THREAD

**Issue by KayShi** [fabric/fabric#2175]
**Describe the bug**
When I used fabric to parse SVG, I encountered some unexpected problems。
When there are multiple spaces in SVG text, multiple spaces are treated as one space.

Through the analysis of the source code, I found a strange processing logic here.
in /dist/fabric.js
`textContent = textContent.replace(/^\s+|\s+$|\n+/g, '').replace(/\s+/g, ' ');`

I don't quite understand why we should filter multiple spaces into one, which seems to directly affect the original SVG expression

Is this a bug? I sincerely look forward to your answer

**Comment by davidjmemmett** [comment]
You've got the wrong project. Closing issue.
