### ISSUE TITLE
Feature request: add doas support

### ISSUE THREAD

**Issue by hendursaga** [fabric/fabric#2183]
`doas` is an alternative to `sudo` that is more lightweight and (some may argue) secure. It is used by default with OpenBSD, and I use it a lot with my FreeBSD systems. It might be a good idea to refactor out some of the code to be more modular/pluggable.

**Comment by davidjmemmett** [comment]
Hi @hendursaga is there anything stopping you from using this right now? Can you fill out the standard issue template to assist us?

**Comment by davidjmemmett** [comment]
Please feel free to re-open if this issue is still affecting you.
