### ISSUE TITLE
c.sudo puts "[sudo] password:" prompt text instead of the actual password

### ISSUE THREAD

**Issue by ApplePie420** [fabric/fabric#2191]
**Describe the bug**
I have a simple task to run `sudo apt update` but it fails on executing the `sudo` command, entering the `[sudo] password: ` prompt as password, instead of an actual password. Other commands such as `c.sudo("uname -s")` works. Snippet:

```python
@task
def update(c):
    c.sudo("apt-get -y update", echo=True, user="rado", password="rootpwd")
```

**Expected behaviour**
A command `sudo apt-get -y update` will run on remote machine. 

**Environment**
My OS: Windows 10 Pro 20H2, Python 3.8.3, Fabric 2.6.0, Paramiko 2.9.2, Invoke 1.6.0
Host OS: Ubuntu Server 20.04 LTS, fresh installation, *rado* is a sudouser

**Additional context**
Terminal output:
```
sudo -S -p '[sudo] password: ' -H -u rado apt-get -y update
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    update(c)
  File "C:\Python38\lib\site-packages\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "test.py", line 15, in update
    c.sudo('apt-get -y update', echo=True, user="rado", password="rootpwd")
  File "<decorator-gen-4>", line 2, in sudo
  File "C:\Python38\lib\site-packages\fabric\connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "C:\Python38\lib\site-packages\fabric\connection.py", line 737, in sudo
    return self._sudo(self._remote_runner(), command, **kwargs)
  File "C:\Python38\lib\site-packages\invoke\context.py", line 213, in _sudo
    return runner.run(cmd_str, watchers=watchers, **kwargs)
  File "C:\Python38\lib\site-packages\invoke\runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "C:\Python38\lib\site-packages\invoke\runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "C:\Python38\lib\site-packages\invoke\runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "sudo -S -p '[sudo] password: ' -H -u rado apt-get -y update"

Exit code: 100

Stdout: already printed

Stderr: already printed
```

I am very much confused by the `permission denied` lines, since the "rado" user has sudo privileges (can execute the  same command via SSH), and `apt` is not being used (killed it before via SSH, and also can use it that way, so..)
Running it with `c.run("sudo apt-get -y update")` works, but I don't want to answer the prompt 3000x during the whole script execution.

**Comment by davidjmemmett** [comment]
This isn't a fabric; your user doesn't have permission to run `apt update` and that is failing. Closing issue.

**Comment by ApplePie420** [comment]
You are right, my bad, I apologize. I have lived over 7 years in belief, that `sudo` elevates privileges, but actually
> Contrary to popular belief, running sudo does not just run with elevated privileges, it runs at the user root.
(mvndaai, StackOverflow)
Well we learn every day. If anyone has the same problem:
either run the command as a root (which is default, lmao), or add that user to `sudoers` properly (`sudo visudo`). 
Thanks and sorry.
