### ISSUE TITLE
When using a Group, clean way to prevent a single offline host from aborting the whole script?

### ISSUE THREAD

**Issue by jerkstorecaller** [fabric/fabric#2199]
I'm writing a script to run commands on a handful of Linux systems in my lab. When running group commands, the whole script exits as soon as a single system is offline, due to the SSH exception raised. In my case I'd rather keep running the commands for the hosts that are online. I don't see how to make execution continue for these online hosts, short of writing hideous exception-handling code for EVERY group.run call.

```
connection_options_localhost = {'user': 'user',
                    'connect_kwargs': {'password': 'user'}}
localhost = Connection("localhost", **connection_options_localhost)
badhost = Connection("fakefakefake")
localhost2 = Connection("localhost", **connection_options_localhost)
connections=[localhost, badhost, localhost2]

group = ThreadingGroup.from_connections(connections)
group.run("date")
group.run("sleep 10")
group.run("echo ALL GOOD")
```

Result:
```
$ ./fabrictest.py 
Mon 21 Feb 2022 12:29:03 AM EST
Mon 21 Feb 2022 12:29:03 AM EST
Traceback (most recent call last):
  File "./fabrictest.py", line 25, in <module>
    group.run("date")
  File "/home/user/.local/lib/python3.8/site-packages/fabric/group.py", line 119, in run
    return self._do("run", *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/fabric/group.py", line 286, in _do
    raise GroupException(results)
fabric.exceptions.GroupException: {<Connection host=localhost>: <Result cmd='date' exited=0>, <Connection host=fakefakefake>: gaierror(-3, 'Temporary failure in name resolution')}
```

Any advice?

**Comment by davidjmemmett** [comment]
Hi @jerkstorecaller,

I don't believe there is currently anything in fabric that will accommodate ignoring errors for you. You will have to implement your own exception-handling mechanism for now.

Cheers,
David

**Comment by jerkstorecaller** [comment]
What I was struggling to understand is how to process the result uniformly, whether all hosts were online, or 1+ was offline. Like, if a host was offline and it throws an exception, then all the result from the good hosts is discarded as Python takes you straight to the exception, right? Wrong! 

I ended up installing Visual Studio Code and running the script in debug mode, which allowed me to see the contents of objects and understand much better compared to just the doc. (For example GroupException didn't mention the .result member.)

I now understand that even if there's an exception, it won't short-circuit the other parallel runs, it will somehow contain all the results even for the online hosts, not just the error for the offline host. Maybe it's obvious for everyone else but this really surprised me. I even put a 30 second sleep before my command in case it was some timing coincidence.

So we can write this code to fully process group commands uniformly:

```
def print_date(group):
    results = None
    try:
        results = group.run("sleep 30 && date")
    except exceptions.GroupException as e:
        results = e.result    

   #now the results variable has what we want, regardless of the run results

    print("command date was successful on", len(results.succeeded), "hosts")
    for k, v in results.succeeded.items():
        print("date on {} is {}".format(k.host, v.stdout.strip()))

    print("command date failed on", len(results.failed), "hosts")
    for k, v in results.failed.items():
        print(k.host, "error:", v.strerror)

group = ThreadingGroup.from_connections(connections)
print_date(group)
```

output:
```
$ ./fabrictest.py 
Mon 21 Feb 2022 06:25:54 AM EST
Mon 21 Feb 2022 06:25:54 AM EST
Mon 21 Feb 2022 06:25:54 AM EST
command date was successful on 3 hosts
date on 127.0.0.1 is Mon 21 Feb 2022 06:25:54 AM EST
date on 127.0.0.3 is Mon 21 Feb 2022 06:25:54 AM EST
date on 127.0.0.2 is Mon 21 Feb 2022 06:25:54 AM EST
command date failed on 2 hosts
fakehost1 error: Temporary failure in name resolution
fakehost2 error: Temporary failure in name resolution
```

**Comment by davidjmemmett** [comment]
It looks like you're satisfied with the outcome, I will close this issue for now
