### ISSUE TITLE
Where is the full-complete document of 2.7.1 ？

### ISSUE THREAD

**Issue by TaceyWong** [fabric/fabric#2224]
➜  pip show fabric
Name: fabric
Version: 2.7.1
Summary: High level SSH command execution
Home-page: https://fabfile.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: BSD
Location: /home/tacey/anaconda3/lib/python3.9/site-packages
Requires: invoke, paramiko, pathlib2

---

Fabric 、Fabric 2、Fabric 3…… balabala……
An open source project that died because of chaotic version number and documentation

---

**Comment by davidjmemmett** [comment]
An excellent example of a question that could have been answered had you not included snarky comments.

**Comment by goldstar611** [comment]
Fabric3 is a fork and is not the same author as fabric/fabric2.

Keep in mind that Fabric is largely a thin wrapper around [Paramiko](https://paramiko.org/changelog.html) and [Invoke](https://pyinvoke.org/changelog.html)

The changelog has good info in it too, like new features: https://www.fabfile.org/changelog.html
