### ISSUE TITLE
sed: illegal option -- r usage: sed script [-Ealn] [-i extension] [file ...]        sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [fabric/fabric#2225]
Launch Terminal on mac

**Comment by davidjmemmett** [comment]
Hi,

I can only make guesses as to what your issue is relating to. Please open a new issue, filling out the standard issue template with the required details.

Cheers,
David

**Comment by Onyelaudochukwuka** [comment]
I'll do that thanks
