### ISSUE TITLE
Python3.10 incompatibility

### ISSUE THREAD

**Issue by kofra-jg** [fabric/fabric#2229]
**Due diligence**
python3.10 -m pip install Fabric3==1.14.post1
fab --version
from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Describe the bug**
Fabric is not running with Python3.10 after the installation

**To Reproduce**
Steps to reproduce the behaviour (please attach a minimal example):
1. python3.10 -m pip install Fabric3==1.14.post1
2. fab --version

**Comment by kofra-jg** [comment]
We can solve this by changing `from collections.abc import Mapping` to `from collections.abc import Mapping` in the Fabric main file

**Comment by Kanzey** [comment]
Are you sure you are commenting on correct project? Fabric do not use Mapping from collections directly it use one from Invoke.
I think you problem is that you are using deprecated https://github.com/mathiasertl/fabric/
Try using farbric instead of fabric3
