### ISSUE TITLE
Error when using put with a directory

### ISSUE THREAD

**Issue by TheFern2** [fabric/fabric#2240]
Looking at the documentation I can't quite figure out the issue, any idea what I am doing wrong?

```
put(local, remote=None, preserve_mode=True)
```

I am able to put one file, but not a dir.

Works!
```
client.put("tasks/fab.sh")
```

Doesn't work
```
client.put("tasks")
IsADirectoryError: [Errno 21] Is a directory:
```

**Comment by emanuelen5** [comment]
> If a string is given, it should be a path to a local (regular) file (not a directory).

**Comment by TheFern2** [comment]
Ah ok I misunderstood that. I got a bit confused because the scp library put does take a string lol. I'll use a path then. Thanks!
