### ISSUE TITLE
TypeError "Cannot read properties of null (reading 'width')" when using BlendImage mask

### ISSUE THREAD

**Issue by joanned** [fabric/fabric#2251]
**Describe the bug**
I'm trying to use an image to mask another image, but I'm getting this TypeError from `img.applyFilters()`: 
```
TypeError: Cannot read properties of null (reading 'width')
```
in fabric.js I see the error is coming from here:

```
    getCachedTexture: function(uniqueId, textureImageSource) {
      if (this.textureCache[uniqueId]) {
        return this.textureCache[uniqueId];
      }
      else {
        var texture = this.createTexture(
          this.gl, textureImageSource.width, textureImageSource.height, textureImageSource); <--- textureImageSource is null here
        this.textureCache[uniqueId] = texture;
        return texture;
      }
    },
```

**To Reproduce**
erroring from `img.applyFilters()` from the following code:

```
const img = new fabric.Image(imageUrl, {
              left: 0,
              top: 0,
              width: 2000,
              height: 2000
            });
const maskImg = new fabric.Image(maskImageUrl, {
              left: 0,
              top: 0,
              width: 2000,
              height: 2000
            });

              canvasRef.current.add(img);
              canvasRef.current.add(maskImg);

              const maskFilter = new fabric.Image.filters.BlendImage({
                image: maskImg,
                mode: 'mask',
                alpha: 0.5
              });

img.filters?.push(maskFilter);
img.applyFilters(); <-- errors here
```

**Expected behaviour**
No errors. correct masking

**Environment**
- What version of the Python interpreter are you using? Are you using an
alternative interpreter such as PyPy? not sure
- What operating system are you using both client & server-side? Mac OS Monterey
- Are you using OpenSSH server or something else? not sure
- Which version or versions of the software are you using?  "fabric": "5.3.0"
  - Have you already tried the latest release? on latest already
  - Have you, or can you, try some older releases to pin down where the bug
  appeared? have not yet
- How can the developers recreate the bug on their end? If possible, include a
  copy of your code, the command you used to invoke it, and the full output of
  your run (if applicable.) repro steps listed
  - A common tactic is to pare down your code until a simple (but still
  bug-causing) “base case” remains. Not only can this help you identify
  problems which aren’t real bugs, but it means the developer can get to fixing
  the bug faster.

**Comment by davidjmemmett** [comment]
I think you've got the wrong project. Fabric is a Python tool to assist with repetitive SSH tasks.
