### ISSUE TITLE
Connection using custom ssh command for Google Cloud Compute Engine

### ISSUE THREAD

**Issue by micahjsmith** [fabric/fabric#2252]
For hosts on Compute Engine, a developer typically connects using the command [`gcloud compute ssh $INSTANCE_NAME`](https://cloud.google.com/sdk/gcloud/reference/compute/ssh). This takes care of authentication and translation of instance name host name etc.

Is it possible to configure a fabric `Connection` to use this underlying mechanism?

My impression is no, since paramiko is used as opposed to some underlying shell command.

Thanks all

**Comment by davidjmemmett** [comment]
You could always just use invoke on its own, then issue 'c.local("my command here")'

**Comment by davidjmemmett** [comment]
Does this resolve your issue?

**Comment by micahjsmith** [comment]
hey @davidjmemmett , thanks for the response. seems like the answer is "no, fabric doesn't support custom connections". there are definitely workarounds here which I will explore, such as using pure invoke, or connecting to GCP using vanilla ssh after some initial configuration

**Comment by micahjsmith** [comment]
A good workaround for others: run `gcloud compute config-ssh` (https://cloud.google.com/sdk/gcloud/reference/compute/config-ssh) once, then can use normal host names with fabric
