### ISSUE TITLE
Dependency on "decorator" package not captured in v3.0.x

### ISSUE THREAD

**Issue by lrbison** [fabric/fabric#2263]
When installing fabric in a fresh venv, Connection cannot be imported:

```
pip install 'fabric<3.0.0'
python -c 'from fabric import Connection'
```
The above works.  But starting with 3.0.0, (including the recent 3.0.1):

```
pip install 'fabric>=3.0.0'
python -c 'from fabric import Connection'
Traceback (most recent call last):
  File "/home/lrbison/venvC/lib64/python3.7/site-packages/fabric/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lrbison/venvC/lib64/python3.7/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/home/lrbison/venvC/lib64/python3.7/site-packages/fabric/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

**Comment by nelsonq** [comment]
@lrbison Yep, I am getting this error as well.

Looks like It is due to the `invoke` dependency getting upgraded to `2.1.0` which breaks the compatibility.

So I have to downgrade the `invoke` to `2.0.0` for a workaround. 

Looking forward to an official fix.

**Comment by bitprophet** [comment]
Yup this is technically an Invoke level breakage, see https://github.com/pyinvoke/invoke/issues/935 - however I think the correct fix is to make Fabric grow the dependency officially as it was sloppy hygiene to import it via Invoke's vendored copy. I'll commit the fix to master now and it will be out in 3.1 (since it's "sort of" adding a "new" dependency) which is in the works now. Thanks!

**Comment by exhuma** [comment]
Thank you @bitprophet for the quick response

**Comment by bitprophet** [comment]
@exhuma There's nothing in Invoke 2.1 that you would be likely to care a lot about, so in your shoes I would definitely update whatever does your pip installing, to explicitly specify `invoke<2.1` for the time being. I would expect Fabric 3.1 to be out within the next few weeks or so.

**Comment by bitprophet** [comment]
Invocations 3.1 (no relation to Fabric 3.1...I just happened to get new major revs everywhere recently when dropping Python 2 😅) now out, and Fabric main branch now using it to prove this type of issue will be caught by our CI in the future: https://app.circleci.com/pipelines/github/fabric/fabric/191/workflows/8e7ddf2d-8d19-4579-a361-9c2a00e9f9c4/jobs/775

**Comment by Wedge009** [comment]
I confirm installing Fabric 3.1 picks up decorator as part of its dependency chain. Thanks.
