### ISSUE TITLE
`ModuleNotFoundError: No module named 'decorator'` on new fabric install

### ISSUE THREAD

**Issue by ap--** [fabric/fabric#2266]
**Describe the bug**
Installing fabric in a brand new environment is broken.

**To Reproduce**

```shell
❯ python3.11 -m venv venv
❯ source venv/bin/activate
❯ python -m pip install fabric
❯ python -c "from fabric import Connection"
Traceback (most recent call last):
  File "/Users/andreaspoehlmann/Development/fabric-issues/venv/lib/python3.11/site-packages/fabric/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/andreaspoehlmann/Development/fabric-issues/venv/lib/python3.11/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/Users/andreaspoehlmann/Development/fabric-issues/venv/lib/python3.11/site-packages/fabric/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

```

**Environment**

```
❯ python --version
Python 3.11.3

❯ pip freeze
bcrypt==4.0.1
cffi==1.15.1
cryptography==40.0.2
fabric==3.0.1
invoke==2.1.1
paramiko==3.1.0
pycparser==2.21
PyNaCl==1.5.0

```

**Comment by kinocz** [comment]
The problem arises in `invoke`: https://github.com/pyinvoke/invoke/compare/2.0.0..2.1.0#diff-44762232b2a6ad3d7c9be0be73ba1b472f41cb2cb11f23d48daf42c912b0dc7f .

The latest `invoke` is usually resolved because: https://github.com/fabric/fabric/blob/main/setup.py#L66. 

The temporary solution is to make your project depend directly on the `invoke==2.0.0` (2.0.1) or on the `decorator` module directly. Fix for `fabric` seems easy fix to depend directly on `decorator` or require a specific version of `invoke`. That is for the project maintainer to decide.

**Comment by kinocz** [comment]
My bad, the current `master` already depends on `decorator`, so I'd say when `fabric`'s next version is released, it starts working again.

**Comment by ap--** [comment]
Closing because this has been fixed in the newest release

**Comment by SuperMasterBlasterLaser** [comment]
I have installed fabric 3.1.0 version and it still returns:

    ModuleNotFoundError: No module named 'fabric.decorators

This error.

**Comment by Melebius** [comment]
@SuperMasterBlasterLaser The original message in this issue contains `decorator` – there is no `s` in the end. Anyway, you should include _which_ module is importing it in your case, posting the whole traceback is advisable.

**Comment by philipstarkey** [comment]
@SuperMasterBlasterLaser That sounds like your code is expecting fabric v1.x to be installed (or possibly the deprecated and unmaintained [3rd party Python 3 port](https://github.com/mathiasertl/fabric/)). You'll need to update your code to use fabric v3.1.0 if you want to use this version, see: https://www.fabfile.org/upgrading.html#upgrading

**Comment by SuperMasterBlasterLaser** [comment]
@Melebius OMG, I did not see it. I'll try it when I have free time.
