### ISSUE TITLE
why does not  mintty/start work  with connection.run on windows

### ISSUE THREAD

**Issue by tomchon** [fabric/fabric#2278]
**Due diligence**
Please try searching the issue tracker for your problem if you haven't already!
If you find related issues that aren't an exact match, feel free to continue
making a report, and link to those issues.

**Describe the bug**
This is my code,when i use connection, process is not started, 
but when exect with os.system in windows, process starts successfully. 
so i feel confused.
```
from fabric2 import Connection
import winrm
import os
def do_it():

    host = 'win81'
    user = 'administrator'
    password = ''

    # ssh connection
    conn = Connection(host=host, user=user, connect_kwargs={'password': password})

    cmd = "cd  C:/TDengine/ &&  mintty -h never C:/TDengine/taosd.exe && echo 456"
    # cmd = "sc start taosd"
    result = conn.run(cmd, hide=False, warn=False, encoding='utf-8')
    print(result.stdout.strip())
    # os.system(cmd)
if __name__ == '__main__':
    do_it() 
```

**To Reproduce**
repeat code on windows

**Expected behaviour**

**Environment**
linux connect to windows

**Additional context**

**Comment by davidjmemmett** [comment]
I'm afraid we don't provide support with specific applications. If there is an issue with fabric itself, please feel free to raise another issue.
