### ISSUE TITLE
[Feature Request] Task Dependencies 

### ISSUE THREAD

**Issue by Padmanabha025** [fabric/fabric#2285]
Introduce a mechanism for defining task dependencies, allowing users to specify that a task should only run after one or more other tasks have completed.

**Comment by davidjmemmett** [comment]
This also sounds like a problem that a CI/CD tool would solve for you.

**Comment by zodman** [comment]
it's already implemented:


```
@task(pre=[other_task, ], post=[ ...])
def mytask(ctx ...
```
but there is a bug .. https://github.com/fabric/fabric/issues/1968

**Comment by davidjmemmett** [comment]
Okay, if the bug you're impacted by is already raised, I will close this issue.
