### ISSUE TITLE
Fabric 3.2.2 asks for sudo password when executing NOPASSWD command

### ISSUE THREAD

**Issue by nmtitov** [fabric/fabric#2287]
I have configured `sudoers` to let me execute two commands without password:

```
# Allow foobar restart app_server
Cmnd_Alias RESTART = /home/foobar/restart_nginx, /home/foobar/bin/restart_app_server
foobar ALL = NOPASSWD : RESTART
```

When I `ssh` to the server I can execute both commands without password:

```
sudo /home/foobar/bin/restart_app_server
sudo /home/foobar/bin/restart_nginx
```

However when I do the same with Fabric I get the following error:

```
sudo /home/foobar/bin/restart_app_server
sudo /home/foobar/bin/timers_nginx
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required

```

This is what my `fabfile` looks like:

```
    conn = Connection(local_settings.FABRIC_HOST, port=local_settings.FABRIC_PORT)
    conn.run(
        f"sudo /home/foobar/bin/restart_app_server && "
        f"sudo /home/foobar/bin/timers_nginx", echo=True)

```

I tried `shell=False`, tried `sudo(...)` instead of `run(...)`. No difference at all. This issue appeared after updating from Fabric 2.x.x to Fabric 3.x.x. But I can use old Fabric 2.x.x. right now.

Thanks!

**Comment by davidjmemmett** [comment]
Hi,

Could you please fill out the issue template? It's impossible to diagnose an issue without any details.

**Comment by nmtitov** [comment]
> Hi,
> 
> Could you please fill out the issue template? It's impossible to diagnose an issue without any details.

Without any details? You are kidding?

**Comment by davidjmemmett** [comment]
It leaves a lot to be desired. Can you be precise about the setup & what users are being used etc?

**Comment by nmtitov** [comment]
From your empty Github profile history I see that you actually gotta be trolling. I hope you are trolling.

**Comment by davidjmemmett** [comment]
I'll give you a chance to apologise.

**Comment by davidjmemmett** [comment]
@nmtitov I see that you aren't willing to engage constructively, therefore I'm going to close this issue. If you would like to report an issue, please [fill out the issue template](https://github.com/fabric/fabric/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) and please provide as much relevant information as you can.

For future reference: we're all volunteers, we don't get paid to help with these projects. I hope you can adjust your expectations and your manners accordingly.

**Comment by nmtitov** [comment]
@davidjmemmett  🤡
