### ISSUE TITLE
All snake_case task cannot be detected with Fabric 3.2.2 Paramiko 3.4.0 Invoke 2.2.0 Python 3.10.12

### ISSUE THREAD

**Issue by YiHuangDB** [fabric/fabric#2293]
**Describe the bug**
all snake_case task cannot be detected with Fabric 3.2.2 Paramiko 3.4.0 Invoke 2.2.0

**To Reproduce**
Steps to reproduce the behaviour (please attach a minimal example):
1. install Fabric 3.2.2 Paramiko 3.4.0 Invoke 2.2.0
2. code to reproduce
```
# fabfile.py
from fabric import task
@task
def local_deploy(c):
    c.run('echo "Running on localhost local_deploy"')
@task
def deploy(c):
    c.run('echo "Running on localhost deploy"')    
```
```
(.venv) ubuntu@ubuntu-Virtual-Machine:~/pyinvoke$ fab deploy
Running on localhost deploy
(.venv) ubuntu@ubuntu-Virtual-Machine:~/pyinvoke$ fab local_deploy
No idea what 'local_deploy' is!
```
**Expected behaviour**
snake_case task name should be supported

**Environment**

- What version of the Python interpreter are you using? Are you using an
alternative interpreter such as PyPy?
Python 3.10.12
- What operating system are you using both client & server-side?
ubuntu 22.10 cloud image
- Are you using OpenSSH server or something else?
No run locally
- Which version or versions of the software are you using?
Fabric 3.2.2
  - Have you already tried the latest release?
yes

**Comment by davidjmemmett** [comment]
Hi @YiHuangDB,

When invoking tasks using the `fab` and `inv` entry point, underscores are replaced with dashes. Please try `fab local-deploy` instead.

Cheers,
David
