### ISSUE TITLE
Upgrade docs import non-existent modules

### ISSUE THREAD

**Issue by chrisspen** [fabric/fabric#2294]
I'm trying to upgrade an application using Fabric 1 to Fabric 2, so that both coexist.

The [docs](https://www.fabfile.org/upgrading.html#upgrading) state that both the old `fabric` module and `fabric2` module can coexist, but this doesn't seem to be true.

Here's an MRE:

    $ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=22.04
    DISTRIB_CODENAME=jammy
    DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
    $ python3.12 -m venv .env
    $ . .env/bin/activate
    (.env) $ pip install fabric fabric2
    (.env) $ python -c "from fabric.api import env, run"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'fabric.api'

If that doc page were correct, I shouldn't be getting this error.

This [page](https://www.fabfile.org/installing.html#installing-as-fabric2) goes into a little detail about how to install both packages, but not from PyPI.

 Could you please clarify how to install both versions without conflicts?

**Comment by davidjmemmett** [comment]
Hi @chrisspen,

To install fabric v1, you'll need to explicitly specify the version: `python -m pip install fabric\<2`.

Cheers,
David
