### ISSUE TITLE
 fab -c absolute_path_to_fabfile.py is not working

### ISSUE THREAD

**Issue by nexgen** [fabric/fabric#2305]
I'm trying to load tasks from entirely different directory in my computer using:
 fab -c absolute_path_to_fabfile.py

but it says:
Can't find any collection named absolute_path_to_fabfile.py

**Comment by EtsuNDmA** [comment]
Use ` fab --search-root <dir_with_files> --collection <file_with_tasks> <task_to_run>`

https://docs.pyinvoke.org/en/stable/concepts/loading.html?highlight=search-root#configuring-the-loading-process
