### ISSUE TITLE
Can't kill a process correctly

### ISSUE THREAD

**Issue by jvanasco** [fabric/fabric#2309]
I've searched the issues and could not find a similar-enough issue.  An executable example appears below.

I am using Fabric to test some Python scripts/modules during development/maintenance with a goal of CI integration (where this stuff will get wrapped into unittest/nose/etc).   Fabric is already doing some work managing this code, so I'm leveraging it for some integrated testing as well.  The relevant bit here, is that I am just testing to see if these scripts execute without error.

One script uses `input()` to prompt the user to continue. To handle that, I use the async command for this invocation.   If that line is executed, I can not reliably quit this process.  Calling `_result.join()` causes a hang.  If a `pdb.set_trace()` is invoked before calling this, I can sometimes use a keyboard interrupt to kill the subprocess.  

This pattern previously worked.  I am not sure if this has stopped working due to a regression, or this is just frail code that somehow previously worked by luck.

Any help would be greatly appreciated.

```
# stdlib
import time

# pypi
from fabric import task
from fabric.connection import Connection

# ==============================================================================

@task
def test(c: Connection) -> None:
    "run test"

    with c.cd("../.."):
        _result = c.run(
            'python -c "input(\'press any key\')"',
            hide="both",
            warn=True,
            asynchronous=True,
        )
        print("RUNNING ASYNC")
        # _result is an Invoke promise

        print("waiting for startup")
        # wait 2 seconds, it should still be active
        time.sleep(2)

        _result.runner.kill()  # will set return_code to -9

        print("waiting for shutdown")
        time.sleep(2)

        # import pdb; pdb.set_trace()
        _result = _result.join()    

        print("done!")
        print(_result.stderr)
```

Fabric 3.2.2
Paramiko 2.9.2
Invoke 2.2.0
Python 3.10

**Comment by jvanasco** [comment]
Update: Invoking `c.run` with `pty=True` reliably makes this code work again.

**Comment by davidjmemmett** [comment]
Okay, thank you, I will close this issue.
