### ISSUE TITLE
'lsb_release' is not recognized as an internal or external command, while trying to run command on remote server

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [fabric/fabric#2310]
I have created **fabfile.py** where I declared all my tasks. This is example:

    from fabric.tasks import task
    from fabric.connection import Connection

    @task
    def server_version(c: Connection):
        c.run('lsb_release -a')

Then I have created separate `dev.yml` file where I've set my configs:

    host: "my.ip.address"
    user: "username"
    port: 22
    connect_kwargs:
        password: "my_password"
        look_for_keys: false
        allow_agent: false
    env:
        env1: "Env1"
    run:
        echo: true

Then I've launched by using this command:

    fab --config ..\dev.yml server-version

It Throws me this error:

    'lsb_release' is not recognized as an internal or external command

Why this is happening. I even tried to use other commands like uname. It is like it does not know any commands at all.

**Comment by davidjmemmett** [comment]
Hi @SuperMasterBlasterLaser, it looks like you're attempting to connect to a Microsoft Windows machine, which is what is printing `...  is not recognized as an internal or external command`. As `lsb_release` is part of the Linux Standard Base PDA Specification, I would not expect this to be available on Microsoft Windows.

I would suggest that you double-check the hostname of the machine you are trying to connect to. If you're still experiencing issues, please feel free to raise a new ticket, taking care to fill out the full issue template.

I hope this helps.

Cheers,
David
