### ISSUE TITLE
Custom python package using fabric - how to look for tasks collection?

### ISSUE THREAD

**Issue by nexgen** [fabric/fabric#2312]
I want to create a custom python package using fabric.

The goal is that after the user installs this package they can simply view the commands by typing:
fab --list

The problem is, it looks for fabfile.py in the root directory of the project. How can I make it look for tasks collection in my package without user have to configure anything?

**Comment by davidjmemmett** [comment]
Hi @nexgen,

I don't think there is anything sensible to suggest, as automatically loading other modules would require tampering with files outside of your own package. The cleanest solution I can think of is making your own entry point instead of using `fab`.

I hope this helps.

Cheers,
David
