### ISSUE TITLE
Unexpected space when adding a Line in Fabric.js 6.3.0

### ISSUE THREAD

**Issue by yashChapaniOB** [fabric/fabric#2314]
**When adding a Line object to the canvas using Fabric.js 6.3.0, an unexpected space appears around the line. This behavior was not present in Fabric.js 5.3.0, where lines rendered correctly without extra space**.

**Steps to Reproduce**

- Create a new Fabric.js canvas
- Add a Line object to the canvas using the code provided below
- Render the canvas

**Expected Behavior**
The line should render on the canvas without any extra space around it, as it did in Fabric.js 5.3.0.

`var line = new fabric.Line([10, 10, 200, 10], {
                        borderColor: '#0069FF',
                        borderScaleFactor: 1.5,
                        centeredScaling: false,
                        centeredRotation: true,
                        shadow: shadow,
                        cornerSize: 15,
                        lockScalingFlip: true,
                        cornerColor: '#0069FF',
                        cornerStyle: 'circle',
                        isLocked: false,
                        visible: true,
                        stroke: shape.stroke,                  
                        clipPath: undefined,
                        excludeFromExport: false,
                        strokeWidth: 15
                        transparentCorners: false,
                        _controlsVisibility: {
                            tl: false,
                            tr: false,
                            br: false,
                            bl: false,
                            ml: true,
                            mt: false,
                            mr: true,
                            mb: false,
                            mtr: true
                        },
                        type: 'line',                 
                    });
                    
                       canvas.add(line)
                       canvas.renderAll()

                       `
                       
                       
                       

![Fabric js Line Issue](https://github.com/user-attachments/assets/cda8cbb0-8014-4bf1-899e-b06eb063993d)

**Comment by davidjmemmett** [comment]
Wrong project I'm afraid, please do your due diligence before raising issues.
