### ISSUE TITLE
Shadow overlap on the Shape (Circle, Rect, Line ) when Shape's opacity decrease

### ISSUE THREAD

**Issue by yashChapaniOB** [fabric/fabric#2315]
When decreasing an Shape's opacity in Fabric.js 6.3.0, the opacity of its shadow does not change correspondingly. This results in shadows appearing too strong relative to the object's opacity, creating an unrealistic visual effect.

     var option = {};
     option['objectCaching'] = true;
     option['isLocked'] = false;
     option['element_type'] = "basicShape";
     
     let ctx = this.canvas.getContext('2d');
     
     const shadow = new Shadow({
        affectStroke: false
        blur:0
        color:"#000000ff",
        includeDefaultValues:true,
        nonScaling:false,
        offsetX:50,
        offsetY:50,
      });
      
     var rect = new Rect({
                        angle: 0,
                        fill: #FFDE59
                        borderColor: '#0069FF',
                        borderScaleFactor: 1.5,
                        centeredScaling: false,
                        centeredRotation: true,
                        cornerSize: 15,
                        cornerColor: '#0069FF',
                        cornerStyle: 'circle',
                        shadow: shadow,
                        lockScalingFlip: true,
                        isLocked: false,
                        visible: true,
                        stroke: shape.stroke,
                        strokeDashArray: shape.strokeDashArray,
                        clipPath: undefined,
                        excludeFromExport: false,
                        strokeWidth: shape.strokeWidth ?? 0,
                        transparentCorners: false,
                        rx: 0,
                        ry:0,
                        _controlsVisibility: {
                            tl: true,
                            tr: true,
                            br: true,
                            bl: true,
                            ml: true,
                            mt: true,
                            mr: true,
                            mb: true,
                            mtr: true
                        },
                        type: 'rect',
                        element_type: 'basicShape',
                        ...option
                    });
                    
       this.canvas.add(rect);
       this.canvas.renderAll();

![image](https://github.com/user-attachments/assets/074f1e8c-8d78-4b04-a22d-03fd265700a5)

**Comment by davidjmemmett** [comment]
Wrong project I'm afraid, please do your due diligence before raising issues.
