### ISSUE TITLE
Prefix injected into print statement?

### ISSUE THREAD

**Issue by jco-c** [fabric/fabric#2319]
**Describe the bug**
When running this script:
```python
from fabric import Connection, Config

def make_connection(host: str, user: str, password: str) -> Connection:
    config = Config(overrides={"sudo": {"password": password}})
    return Connection(
        host=host, user=user, connect_kwargs={"password": password}, config=config
    )

def sudo_file_exists(host: str, user: str, password: str, file: str) -> bool:
    """
    try etc/passwd, exists on nearly every linux based system
    """
    with make_connection(host, user, password) as c:
        result = c.sudo(f"test -e {file}", warn=True)
        if result.exited == 0:
            return True
        return False

print(sudo_file_exists(my_host, my_user, my_pw, "/etc/passwd") 
```
I would expect the output to be: `True`

Instead, I get the output `[sudo] password: True`

I would guess that there is a setting to not inject anything into stdout/print - but for version 2 and above I can't find anything in the documentation.

**To Reproduce**
Use the script above with your own credentials

**Environment**

Python-version: 3.13.0
fabric-version: 3.2.2
OS client: Win 11
OS server: Ubuntu 24.04.1 LTS

**Comment by davidjmemmett** [comment]
Hi @jco-c,

If you check the output of the return value, you'll find it's the boolean as you expected. What you're seeing is the sudo prompt which is written to stderr.

If you'd like to buffer stderr to hide it, you can provide your own file-like object to `run.err_stream`:
```
...
Config(
        overrides={
            "sudo": {
                "password": password,
            },
            "run": {
                "err_stream": StringIO(),
            },
        },
    )
...
```

Cheers,
David
