### ISSUE TITLE
put() not expanding tildes correctly

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#323]
### Description

IRC user `mercurial` reports that when he calls `put('blah.tar.gz', '~/target_existing_directory')`, Fabric spits out [a "File not found" IOError abort](https://gist.github.com/877024). Replacing the tilde with an absolute path works correctly. This implies that the tilde replacement is broken.

For reference, his local system is OS X 10.6 and his remote is Ubuntu 10.04.

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2011-03-18** at **07:37pm EDT**

**Comment by peterbjorgensen** [comment]
I think this bug is back. I am using fabric 2.5.0 on Arch linux with python 3.9.1
