### ISSUE TITLE
put() fails with Paramiko "Channel closed." SSHException

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#343]
### Description

Here is the interactive session that explains the problem:

<pre>
In [1]: import paramiko

In [2]: from fabric.api import *

In [3]: from django.conf import settings as djsettings

In [4]: paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)

In [5]: env.key_filename = djsettings.SSH_PRIVATE_KEY

In [6]: with settings(host_string='framebox.org', user='turutanov'):
   ...:         run('whoami')
   ...:     put('README', '~')
   ...: 
[framebox.org] run: whoami
DEBUG:paramiko.transport:starting thread (client mode): 0x238a750L
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_5.6)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'arcfour256', 'arcfour128', 'blowfish-cbc', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', '3des-cbc', 'cast128-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'arcfour256', 'arcfour128', 'blowfish-cbc', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', '3des-cbc', 'cast128-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
DEBUG:paramiko.transport:using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Trying key deaaf8134bb5b9f28fb15bc3f7e4fec1 from /Users/dgl/Workspace/42-deploy/keys/id_rsa
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
DEBUG:paramiko.transport:[chan 1] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 1] Max packet out: 32768 bytes
INFO:paramiko.transport:Secsh channel 1 opened.
DEBUG:paramiko.transport:[chan 1] Sesch channel 1 request ok
DEBUG:paramiko.transport:[chan 1] Sesch channel 1 request ok
[framebox.org] out: turutanov
[framebox.org] out: DEBUG:paramiko.transport:[chan 1] EOF received (1)
DEBUG:paramiko.transport:[chan 1] EOF sent (1)

Out[6]: 'turutanov'
DEBUG:paramiko.transport:[chan 2] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 2] Max packet out: 32768 bytes
INFO:paramiko.transport:Secsh channel 2 opened.
DEBUG:paramiko.transport:[chan 2] EOF sent (2)
---------------------------------------------------------------------------
SSHException                              Traceback (most recent call last)

/Users/dgl/Workspace/42-deploy/<ipython console> in <module>()

/Users/dgl/.virtualenvs/deploy-env/src/fabric/fabric/network.pyc in host_prompting_wrapper(*args, **kwargs)
    301             host_string = raw_input("No hosts found. Please specify (single) host string for connection: ")
    302             interpret_host_string(host_string)
--> 303         return func(*args, **kwargs)
    304     return host_prompting_wrapper
    305 

/Users/dgl/.virtualenvs/deploy-env/src/fabric/fabric/operations.pyc in put(local_path, remote_path, use_sudo, mirror_local_mode, mode)
    376         and callable(local_path.read))
    377 
--> 378     ftp = SFTP(env.host_string)
    379 
    380     with closing(ftp) as ftp:

/Users/dgl/.virtualenvs/deploy-env/src/fabric/fabric/sftp.pyc in __init__(self, host_string)
     16     """
     17     def __init__(self, host_string):
---> 18         self.ftp = connections[host_string].open_sftp()
     19 
     20 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/client.pyc in open_sftp(self)
    388         @rtype: L{SFTPClient}
    389         """
--> 390         return self._transport.open_sftp_client()
    391 
    392     def get_transport(self):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/transport.pyc in open_sftp_client(self)
    825         @rtype: L{SFTPClient}
    826         """
--> 827         return SFTPClient.from_transport(self)
    828 
    829     def send_ignore(self, bytes=None):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/sftp_client.pyc in from_transport(cls, t)
    103         if chan is None:
    104             return None
--> 105         chan.invoke_subsystem('sftp')
    106         return cls(chan)
    107     from_transport = classmethod(from_transport)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/channel.pyc in invoke_subsystem(self, subsystem)
    238         self._event_pending()
    239         self.transport._send_user_message(m)
--> 240         self._wait_for_event()
    241 
    242     def resize_pty(self, width=80, height=24):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/channel.pyc in _wait_for_event(self)
   1082         if e is None:
   1083             e = SSHException('Channel closed.')
-> 1084         raise e
   1085 
   1086     def _set_closed(self):

SSHException: Channel closed.

In [7]: import fabric

In [8]: fabric.version.VERSION
Out[8]: (1, 0, 1, 'final', 0)

In [9]: paramiko.__version__
Out[9]: '1.7.6 (Fanny)'
</pre>

Main points are:
1. Code above works for other hosts;
2. The same error appears on two ALTLinux setups, maybe it's distro specific;
3. run() works, but put() doesn't;
4. Tried both Fabric 1.0.1 from PyPI and lastest version from GitHub repo

---

Originally submitted by **David Leadbeater** ([dgl](https://github.com/dgl)) on **2011-04-26** at **11:58am EDT**

**Comment by mrts** [comment]
This may be caused by the SFTP subsystem being disabled.

To enable the SFTP subsystem, uncomment the following line in `/etc/ssh/sshd_config` and restart the `sshd` service:
```
Subsystem sftp /usr/lib/openssh/sftp-server
```
