### ISSUE TITLE
Failover between IPv4/IPv6?

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#372]
## Scenario

Local virtual machine setup is forwarding SSH to host port e.g. `2200` but `fab -H localhost:2200` fails with `Connection refused` (`Low level socket error`). However, `fab -H 127.0.0.1:2200` works fine.

## Diagnosis

This appears to be due to VMs only forwarding ports on IPv4, but the host resolving `localhost` to IPv6 (`::1`), at least in the socket/syscall Fabric/Paramiko is using. Thus, since there is no port forward on IPv6, the connection fails.

## Proposed solution

If possible, have the connection function try the other IP type upon connection failure. Analysis:

* Plus: no more oddball problems and having to remember to use `127.0.0.1` in this particular situation
* Plus: would also fix the problem in case it appears in non-VM scenarios
* Minus: implicit/magic, might screw up other use cases somehow
    * Though this feels unlikely, given that it would only fire on a hard-failure situation, i.e. connection failure.

Potential approaches:

* Re-resolve the given hostname, assuming this is even possible
* Target this specific VM scenario, i.e. literally say "if resolved to `::1` and connection failure, explicitly switch to trying `127.0.0.1`"

----

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2011-07-01** at **03:12pm EDT**

**Comment by displague** [comment]
Is there a way to specify arbitrary ssh config parameters in a fabfile?  If so you could force ipv4 or ipv6, as in the `ssh -4` and `ssh -6` arguments.  I have a need for this.

**Comment by bitprophet** [comment]
Actually, this got mostly fixed in a semi recent Paramiko issue - I totally forgot we had an open issue on this side. See https://github.com/paramiko/paramiko/issues/22 which was released in Paramiko 1.16.0.

@displague re: explicitly forcing only one or the other, that's a newer, yet unsolved issue, also Paramiko specific: https://github.com/paramiko/paramiko/issues/770.
