### ISSUE TITLE
Implement tunnelling

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#38]
### Description

It should be possible to tunnel all the commands through a single entry point in the network. 

---

Originally submitted by **Anonymous** () on **2009-07-27** at **05:22pm EDT**
### Attachments
- [monkeypatch.py](https://gist.github.com/e3e96664765748151c05)
- [fabric.patch](https://gist.github.com/34a60a4fbe86e6866eb5)
### Relations
- Related to #275: Consider forking Paramiko
- Duplicated by #344: Tunnelling SSH over HTTP Proxies
- Related to #78: Add Tunneling Context to Fab
- Related to #72: SSH key forwarding

**Comment by puppet-py** [comment]
@bitprophet: Hi.. I am trying to use fabric module to solve this tunneling:
Node1-- ssh--Node2--ssh--Node3--(use namespace of node3 to ssh) --Node4 --run sudo cmds on Node4
Can I achieve the above(my blocker is the use of namespace to ssh from node3 to node4) by using the monkeypatch.py utility
Any guidance much appreciated

**Comment by bitprophet** [comment]
@puppet-py Probably a better question for the mailing list, not a comment on a defunct ticket :) I personally have not done any multi-hop tunneling like that, so not sure how well it'll work.
