### ISSUE TITLE
Init scripts frequently fail to start their daemons

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#395]
### Description

I've gotten multiple reports of this on IRC, as well as a comment on #350, and now a [mailing list thread](http://lists.nongnu.org/archive/html/fab-user/2011-07/msg00024.html).

No clear cause yet, and while it's been reported multiple times I don't expect that it is a constant problem or we'd be hearing much more about it. In some very limited testing on my end so far, I can recreate the problem maybe 30-50% of the time -- but it is reproducible.

Symptom is simply that init-style scripts responsible for starting daemons and then returning immediately, will return OK, return code of 0 and "success" status message printed to stdout -- but will not actually spin up the daemon in question.

My personal test was done via latest master targeting an Ubuntu 10.04 (Lucid) VM and the stock Apache2 package's init script.

---

Originally submitted by **Jeff Forcier** ([bitprophet](https://github.com/bitprophet)) on **2011-07-23** at **07:25pm EDT**
### Relations
- Related to #350: fabric hangs up some remote command (for daemon program)

**Comment by HyukjinKwon** [comment]
As I mentioned here fabrickit ( a wrapper of fabric libs ) https://github.com/HyukjinKwon/fabrickit/commit/cceb8bfb8f960a3ac41b24c64b8358bd6e7a0366

You can absolutely easily start a program as a daemon without specific configurations or settings.
This is anyway a kind of Shell execution and therefore there should be a way to do what Shell can do.

Try this:

`run("sh -c '((nohup %s > /dev/null 2> /dev/null) & )'" % cmd, pty=False)`

I tried this and it works perfectly fine.
