### ISSUE TITLE
No documentation for ~/.fabricrc

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#42]
### Description

It is noted at http://docs.fabfile.org/0.9/compatibility.html#other-backwards-incompatible-changes that it is possible to configure fabric via a ~/.fabricrc file, but searching the documentation yieds no explanation as to how that's accomplished.

---

Originally submitted by **Mikkel Høgh** ([mikl](https://github.com/mikl)) on **2009-07-28** at **04:13pm EDT**

---

Closed as _Wontfix_ on **2009-11-08** at **11:32am EST**

**Comment by constantinius** [comment]
The information seems to be lost again, as the links are no longer accessible.
