### ISSUE TITLE
@task object docstrings not visible to doctest

### ISSUE THREAD

**Issue by gregglind** [fabric/fabric#421]
fabfile.py
------------

    """

    $ python -m doctest fabfile  # will see t1 but not t2

    """

    from fabric.api import task

    def t1():
        """ 
        >>> t1()
        'b'
        """
        return 'a'

    t2 = task(t1)

WrappedCallableTask  should promote up all the docstrings maybe?

**Comment by kaaveland** [comment]
This is indeed because of a doctest implementation detail, see: https://github.com/python/cpython/blob/2.7/Lib/doctest.py#L973-L980

There are cases of other people running into this problem as well, I think it'd make the most sense to get this fixed in doctest (although that does seem hard).

**Comment by kaaveland** [comment]
The workaround would be to use http://docs.fabfile.org/en/latest/api/core/docs.html#fabric.docs.unwrap_tasks with doctest (not familiar enough with doctest to see how inconvenient that is convenient).

**Comment by kaaveland** [comment]
Corresponding upstream issue: http://bugs.python.org/issue21740

**Comment by kaaveland** [comment]
There was a patch, but it didn't make it into 2.7. Apparently using `functools.update_wrapper` should make this work in python 3.
