### ISSUE TITLE
rsync_project symlink option

### ISSUE THREAD

**Issue by rizumu** [fabric/fabric#439]
rsync has an option:
       -l, --links
              When symlinks are encountered, recreate the symlink on the destination.
 
It could be useful to optionally pass ``links=True`` to enable recreation of symlinks when using ``fabric.contrib.project.rsync_project``, otherwise symlinks will by default be ignored by rsync.

**Comment by bitprophet** [comment]
rsync_project grew an arbitrary flags option, so I think this is no longer necessary.
