### ISSUE TITLE
Execute should be able to reference locally available tasks

### ISSUE THREAD

**Issue by mitchellh** [fabric/fabric#479]
Hello,

Working with the "new" (for me!) 1.3 version and loving it so far. But I'm finding some oddities based on what I would expect to be behavior, in this case with the new `execute` function. I have a module named `deploy` (so living in `deploy.py`) which I import tasks from. Here is a hypothetical `fabfile`:

```python
import deploy
```

Here is a hypothetical `deploy.py`:

```python
from fabric.api import execute, task

@task(default=True)
def deploy():
    execute("foo")

@task
def foo():
    print("Foo called!")
```

The above actually doesn't work because `execute` expects a valid task name. But note that that pushes knowledge into the deploy module of knowing how the deploy module is imported into a Fabfile. So, sure, I can do this to make it work:

```python
execute("deploy.foo")
```

So that works. But what if I then change the fabfile to this:

```python
import deploy as old_deploy
```

Now the old deploy actually breaks! 

I think this knowledge of how a module is imported doesn't belong in the module. In fact, I think before checking for a valid task name, I think that the `execute` semantics should check the currently available tasks and try to execute that. Then you can do whatever you want wit the knowledge you're 100% sure you have in your module, and it will always work.

Best,
Mitchell

**Comment by bitprophet** [comment]
Rolling into pyinvoke/invoke#170
