### ISSUE TITLE
Nested roles

### ISSUE THREAD

**Issue by sjmh** [fabric/fabric#518]
Would be nice to allow 'nested' roles for ease of calling specific sets of roles.

Because roledefs allow callables, this can be done already by adding this to your fabfile:

```python
def get_roles(*roles):
    return lambda:[y for x in roles for y in env.roledefs[x]]

env.roledefs = {
    'site1' : ['hostA','hostB','hostC'],
    'site2' : ['hostD','hostE','hostF'],
    'all'   : get_roles('site1','site2')
}
```

Could either implement get_roles as an API function or make it more transparent:

```python
env.roledefs = {
    'site1' : ['hostA','hostB','hostC'],
    'site2' : ['hostD','hostE','hostF'],
    'all'   : ['site1','site2']
}
```

Which would seem to require a rework of the merge function to identify values that are actually role keys.  Would also have to prevent circular references.

Thoughts on which way would be 'better'?  For the user, it seems like the transparent method would be cleaner, although more effort to implement.

**Comment by bitprophet** [comment]
Closing as "easier to do in the less-opinionated v2".
