### ISSUE TITLE
Add a skip_on_prompts

### ISSUE THREAD

**Issue by reeesga** [fabric/fabric#521]
If I cronjob a fabric task towards multiple hosts (-H <role>) and one of them has e.g. changed password, the session hangs, asking for a password. If I set the "abort_on_prompts", the session exits instead, and the rest of nodes in the role are never tasked.

So I'm needing something like a "skip_on_prompts" for my fully automated fabfile.

Can I make up this behaviour somehow? I tried setting env.abort_on_prompts=True, then wrapping into a warn_only=True, but the abort proceeds anyway. 

Or, put in another way, warn_only=True should take precedence over abort_on_prompts=True.

**Comment by KarnG** [comment]
Hello Experts, I am newbie into the fabric, i have the same problem "password prompt" if it has wrong password, How i can customise by below fab file..

import sys
from fabric.api import *
env.skip_bad_hosts=True
env.command_timeout=160
env.user = 'user1'
env.shell = "/bin/sh -c"
env.warn_only = True
env.abort_on_prompts = True
env.password = 'pass123'
def readH():
    env.hosts = [line.strip() for line in sys.stdin.readlines()]

def cpam():
  with settings(warn_only=True):
      output=sudo("/grid/it/bin/cyberAddHost.sh",shell=False)
