### ISSUE TITLE
Allow fabric to use dotted python paths

### ISSUE THREAD

**Issue by dcolish** [fabric/fabric#540]
Gives the ability for a user to define a module in their PYTHONPATH which provides fabric commands. The user can then load that file from the commandline by running:

    fab -f my.custom.fabfile

By default, fabric should look for the module fabfile in the PYTHONPATH. If no module is found, it falls back to the regular fabfile discovery process.

**Comment by eddawley** [comment]
+1 for this feature. 

Basically without it, there is no good way to deploy tools into a virtualenv that in turn provide fabric commands.  Only workaround right now is to have setuptools copy your fabfile as a [script](https://docs.python.org/2/distutils/setupscript.html#installing-scripts) or as [additional files](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) but then you still have to reference the full path every time you run fab.

Ideally fab would by default look for a fabfile module available on the pythonpath.  Having the ability to specify a custom module via -f or a new arg (-m maybe) would be the next step.

**Comment by bitprophet** [comment]
v2 is being built on http://pyinvoke.org which provides an improved namespacing & loading functionality, which does (by default, & overriding this behavior is easier there as well) try doing module imports (e.g. `inv -c <module name>`) in favor of loading specific file paths. Going to close this in favor of that.
