### ISSUE TITLE
Allow fabric to be service-centric

### ISSUE THREAD

**Issue by ZZelle** [fabric/fabric#541]
Currently from my point of view fabric is host-centric, i would like to allow fabric to be service-centric.
Let me explain through a use case what i mean by host/service-centric and the associated feature proposal.

### Use case:
I want to deploy (or any other action) an application composed of some services (S1, S2, S3 ...) on some hosts (H1, H2, H3...).
Application requirements:

 * A service might be instantiated multiples times  (ex: H1, H2 host S1 service instances)
 * A host might host multiple service instances (ex: H1 hosts S1, S2 instances)
 * A host cannot host multiple instances of the same service (don't know how to handle it otherwise)

The application i currently manage is composed of ~15 services, 30 hosts, ~100 service instances and ~20 actions (which takes to execute from 1s to 2 minutes per service instances)

What i would like : ``` fab deploy``` deploys service instances on hosts and more generally fab action apply on service instances 
the action when it has a meaning

Solutions:

### Fabric current way (host-centric):

 * allocate services to hosts through env.roledefs (every service is represented by a role)

```
env.roledefs = dict(S1=['H1','H2'], S2=['H1'], 'S3'=['H1', 'H2', 'H3'])
```

 * define a deploy task for every with role restrictions

```
@task
@roles('S1')
def S1_deploy():
     # deploy S1 instance
```

same for S2_deploy, S3_deploy ...

 * call every deploy tasks

```
fab S1_deploy S2_deploy S3_deploy
```

Does the job but applicable only if the application has few services and few actions.
We cannot deploy S1/S2 service concurrently

### Wrap fabric:

 * define a fabric wrapper fab2. For example the call to ```fab2 deploy``` will be transformed into

  ```fab S1_deploy S2_deploy ...``` 

   * do not allow concurrency between service actions

 or call ```fab S${X}_deploy```  concurrently

   * allow concurrency between service actions, 
   * but i loose some fab capabilities (runs_once for example)
 * S${X}_${action} must exist for every service and action

### Fabric new way (service-centric):

 * allow host string to include the optional service information: ```username@hostname:port/servicename```
 * define a task proxy which will transfert every call to the implementation associated to the host string service 

Development to support it (i will provide a code proposal next week because i currently lost my repo connection):

 * patch fabric.network.normalize to accept the optional servicename information
 * define the env.service attribute when servicename is provided in the host string
 * define a service task proxy class (ServiceProxyTask ?) to subclass which reroutes call to the right implementation
  * Task implementations will respect (for example) the pattern ${taskname}_service_${servicename} or ${taskname}_service_default
  * Task name is deduced from class function names
  * One subclass of ServiceTask for every task ? Or a ServiceProxyTask subclass could provide more than one task

Usage changes: 

 * previous fabric env.roledefs becomes: 

``` env.hosts = ['H1/S1', 'H2/S1', 'H1/S2', 'H1/S3', 'H2/S3', 'H3/S3' ]```

 * S1_deploy, S2_deploy, S3_deploy becomes:

```
class DeployClass(ServiceTask):

     def deploy_service_S1(self):
           # deploy S1 instance 
....
```

 * You will handle services with full fab facilities !

**Comment by bitprophet** [comment]
The much-less-opinionated host/collection API in the upcoming v2 should make implementing this sort of approach much easier for users who need it.
