### ISSUE TITLE
Specify namespace on command line

### ISSUE THREAD

**Issue by mjtamlyn** [fabric/fabric#557]
I'm developing a fairly large set of fabric commands, and namespacing is briliant! However we quite often need to run several tasks at once, but all in the same namespace. It'd be nice to have a shortcut for these:

```
fab --namespace=my.lovely.namespace command1 command2 command3
```

as an alias for

```
fab my.lovely.namespace.command1 my.lovely.namespace.command2 my.lovely.namespace.command3
```

I would propose `-N` as the short command as it's not currently in use.

**Comment by bitprophet** [comment]
Suspect this is now mostly solved at the Invoke layer as of Fabric 2.0 - the namespacing is much more fleshed out overall, you can specify specific collection/namespace to load via CLI flags, etc. If the use cases here are still missing something, please look for open issues over on https://github.com/pyinvoke/invoke or file one there if an existing one isn't found. Thanks!
