### ISSUE TITLE
Split out non-ssh-dependent features into separate lib

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#565]
Things are coming to a head and it'd be good to split out Fabric's task execution stuff into its own "third party" tool/library so it can be used/referenced independently of our SSH functionality.

Right now, anybody wanting to use Fab-as-runner must still install `ssh` and `PyCrypto`, which sucks.

And if we're splitting it between task running and SSH, having "Fabric" be "SSH + dependency on new runner tool" makes much more sense (both re: backwards compatibility, and overall usefulness) than vice versa.

Speaking of backwards compat, I am marking this 2.0 because it makes *more* sense to do it at a 2.0 backwards incompat barrier (since at the very least it adds a new install dependency to Fabric), **but** doing the split in, say, 1.6 or 1.7 should also be quite possible if the timing is better.

----

To be clear, this new tool would:

* Maybe, possibly, but probably not just be us glomping onto an existing tool like Paver
    * Paver tries to do too much and I've never been a big fan of how its API feels
    * Really not aware of any other tools that are at all well known and fit the use case any better
    * EDIT: [Baker](http://pypi.python.org/pypi/Baker/1.02) actually looks half decent, though it's obviously not a perfect match (nothing would be, anything would require some tweaks.)
* Have a distinct identity from Fabric, while probably remaining "affiliated"
    * Name brainstorm incoming.
* Encompass the "run Python callables as tasks from the CLI with args" functionality that currently exists within Fabric
* Likely entail some refactoring of how that machinery works, if only just to make post-ripout integration easier
* Probably get some of the remaining big task-runner "missing features" implemented right off the bat (really just #452)

**Comment by dmr** [comment]
Sorry if this if off topic but I sort of have to ask again: 
Where can I find fabric 2?
I really like invoke and it feels like a huge improvement, but what is missing for an invoke 1.0 release? (described as the basis for fabric 2)

**Comment by bitprophet** [comment]
@dmr I'm in the middle of getting a Fabric 2 working on top of Invoke. A bunch of features to be ported over from Fabric 1 will inform design decisions for Invoke (for new features or existing ones - e.g. the recent config overhaul was one of these), so I don't want to label Invoke 1.0 until it's been "battle tested" sufficiently.

My plan is to have an alpha of Fabric 2 ready for the public by PyCon at the latest (ideally much sooner) and that will lead into Fabric 2.0 + Invoke 1.0.

**Comment by dmr** [comment]
Thank you for the clarification, where can I help?

**Comment by bitprophet** [comment]
I'm working on it in a private branch for the short term until I get something I'm happy with and will be announcing on twitter/mailing list/etc once I'm ready for feedback, so please stay tuned.

**Comment by reinout** [comment]
It is August again, so it is time for the once-every-half-year question "where is fabric 2?" :-)

**Comment by dmr** [comment]
I started switching to invoke in combination with shell commands and some Paramiko because fabric is the last package without python3 support in my project

**Comment by tebanep** [comment]
Any ETA for Fabric 2.0 and Invoke 1.0 as Python 3.5 was released yesterday and will be the default in Ubuntu 16.04 LTS?
