### ISSUE TITLE
Class-based task sets

### ISSUE THREAD

**Issue by kmike** [fabric/fabric#573]
Semi-real-word example:

    # super_deploy/mysql.py
    
    @task
    def execute_sql(sql):
       # ...

    @task
    def create_db(db_name):
        sql = # ...
        execute_sql(sql)

    @task
    def create_user(user, password):
        sql =  #...
        execute_sql(sql)

    @task
    def setup_db(db_name, user, password):
        create_db(db_name)
        create_user(user, password)

And then someone wants to change ``execute_sql`` behavior (e.g. to print sql queries). The first solution is monkey-patching:

    from super_deploy import mysql

    @task
    def my_execute_sql(..):
        # ...
    mysql.execute_sql = my_execute_sql

But this is monkey-patching and monkey-patching is not ok.

Sane solution is inheritance. Let's see how current class-based tasks may help:

    class SetupDbTask(Task):
        name = 'setup_db'
     
        def execute_sql(self, sql):
            # ...

        def create_db(self, db_name):
            sql = # ...
            self.execute_sql(sql)

        def create_user(self, user, password):
            sql =  #...
            self.execute_sql(sql)

        def run(self, db_name, user, password):
            self.create_db(db_name)
            self.create_user(user, password)

Nice! We can now subclass SetupDbTask and override 'execute_sql' method. But: we've lost create_user, create_db and execute_sql tasks, and we really want to be able to call them separately.

Ok, next attempt:

    class Mysql(Task):
        name = 'mysql'
     
        def execute_sql(self, sql):
            # ...

        def create_db(self, db_name):
            sql = # ...
            self.execute_sql(sql)

        def create_user(self, user, password):
            sql =  #...
            self.execute_sql(sql)

        def setup_db(self, db_name, user, password):
            self.create_db(db_name)
            self.create_user(user, password)

        def run(self, name, *args, **kwargs):
             method = getattr(self, name)
             return method(*args, **kwargs)

Great, we now can override execute_sql and we have all tasks:

     $ fab mysql:create_db,db_name

The downsides are awkward calling syntax and the fact tasks won't show up in ``fab --list``.

It is possible to have class-based task sets without these downsides as external projects (see e.g. https://github.com/kmike/fabric-taskset and https://github.com/ramusus/fabriclassed ) but this is a useful pattern and core support would allow a less hackish implementation. So I propose to add some sort of class-based task sets to the core fabric. Class based task sets seems to be even more useful than class-based tasks: in my experience tasks themselves tend to be small and rewriting them as classes only adds lines of code, it is the task combination problem that should benefit from class-based approach.

**Comment by bitprophet** [comment]
This is now invoke/invoke#199.
