### ISSUE TITLE
fabric.contrib.project.upload_project doesn't respect remote_dir

### ISSUE THREAD

**Issue by oselivanov** [fabric/fabric#597]
Part of script:

    with cd('remote_dir/remote_subdir'):
        upload_project(local_dir='inside_dir/inside_subdir', remote_dir='remote_3rd_dir')

Log:
...
[host.com] run: tar -xzf inside_subdir.tar.gz
[host.com] out: tar (child): inside_subdir.tar.gz: Cannot open: No such file or directory
...

But:

    with cd('remote_dir/remote_subdir/remote_3rd_dir'):
        upload_project(local_dir='inside_dir/inside_subdir')

works perfect.

**Comment by kaaveland** [comment]
This was fixed it https://github.com/fabric/fabric/pull/584
