### ISSUE TITLE
DNS issues with HostName in SSH config

### ISSUE THREAD

**Issue by yuvadm** [fabric/fabric#619]
Very simple scenario:

``` python
env.use_ssh_config = True

@hosts(['example'])
def test():
    run('uname')
```

and with the following SSH config:

```
Host example
  HostName example.com
```

I'm getting this:

``` bash
$ fab test
[example] Executing task 'test'
[example] run: uname

Fatal error: Name lookup failed for example.com 

Underlying exception:
    nodename nor servname provided, or not known

Aborting.

# BUT!

$ ssh example uname
Linux
```

Any idea what's going on?

**Comment by styts** [comment]
Got bitten by the extra whitespace bug too, posting this here for future searchers:
The error I was getting was `Fatal error: Name lookup failed for hosts` - since we were using the dictionary-based `env.roledefs` definition.
