### ISSUE TITLE
backticks in run() don't work as expected

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#62]
### Description

```
In [2]: run('touch test.pid && kill `cat test.pid`')
No hosts found. Please specify (single) host string for connection: xyzhomework.com
[xyzhomework.com] run: touch test.pid && kill `cat test.pid`
Please enter passphrase for private key: 
[xyzhomework.com] err: cat: test.pid: No such file or directory
```

The file is created as expected.

Interestingly,
    run('echo `touch test.pid`')
doesn't error out, and creates test.pid in my home directory, as expected (yes, I did delete it after the previous run first).

Also,
    In [4]: run('kill `cat test.pid`')
    [xyzhomework.com] run: kill `cat test.pid`
    [xyzhomework.com] err: kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
seems right, and after echoing a nonexistant PID into test.pid, I get
    In [5]: run('kill `cat test.pid`')
    [xyzhomework.com] run: kill `cat test.pid`
    [xyzhomework.com] err: /bin/bash: line 0: kill: (999) - No such process
which is also right.

My guess, then, is that there's something odd going on with subshells and whatnot.

[30 seconds of experimentation later]

Yep, 'cause
    run('touch test.pid && kill `cd && cat test.pid`')
works just fine.  So, something along the same lines as when you're cd-ed into a directory, delete and recreate said directory from another shell, and then do an ls in the original - you get nothing, because of some things that I learned in my systems programming class and promptly forgot.

I'm not really sure what the best way to handle this is (if at all, and if it is in fact a fabric problem, and not paramiko), so you're on your own there.

---

Originally submitted by **James Pearson** (xiong.chiamiov) on **2009-09-17** at **07:33pm EDT**

---

Closed as _Done_ on **2009-11-08** at **11:45am EST**

**Comment by ambsw-technology** [comment]
We ran into this as well.  Found the Git issue after some hair pulling.  Any reason backtick wasn't added to the default escapes?

**Comment by ploxiln** [comment]
it was: https://github.com/fabric/fabric/blob/master/fabric/operations.py#L43

you should probably open a new issue with a concrete example of your problem, fabric version, etc
