### ISSUE TITLE
Hiding tasks from --listing

### ISSUE THREAD

**Issue by JensRantil** [fabric/fabric#678]
I have a larger fabric script that contains a bunch of different tasks. Initially I would issue

```
fab task1 task2 task3 ...
```

but then the number of tasks grew in proportion so much that I created a single task so that I could issue my command like so

```
fab bigtask
```

and it would issue all initial tasks using the `execute(...)` function. Now when I issue `fab --list` I get a fairly long list of tasks that I'm 99% of the times am not interested in executing. **Request: Be able to hide certain tasks from `--list`ing.**

Now you may be wondering why I simply can't remove `@task` decorator and make basic function calls from my bigtask task. Two reasons:
- Some of the subtasks are using `@runs_once` decorator while others aren't. I expect that decorator to not work for non-`@task`s. Am I wrong?
- I would love future users/colleagues to be able to use my script easily. Therefor, being able to hide certain tasks in the listing would making it way more clear for them which task to execute.

To concretize, my proposal is as follows: **Never list tasks with names starting with an underscore, `_`, _unless_ the filter proposed in #134 is in use.** This proposal goes hand in hand with the Pythonesque way of making functions private.

What do you think of this?

**Comment by sochoa** [comment]
From [here](https://mail.python.org/pipermail/python-ideas/2014-May/027824.html) (mail.python.org > python-ideas): 

```python
__all__ = []
def export(f):
    sys._getframe(1).f_globals.setdefault("__all__", []).append(f.__name__)
    return f

def do_stuff1():
    pass

@export
def do_stuff2():
    pass
```

Which results in this:  
```
$ fab -f my-fabfile.py -l
Available commands:

    do_stuff2
```
