### ISSUE TITLE
Global parallelization doesn't play nice with @runs_once?

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#681]
Haven't looked but suspect this is simply because the parallel machinery is unaware of `@runs_once` and so by the time `@runs_once`'s memoization implementation kicks in, it's already inside its own multiprocessing subprocess, and so of course the reliance on shared state for memoization to function, means it runs once per host.

Assuming that's accurate, make the parallel machinery aware of `@runs_once`'s desired behavior, either by looking for an existing attribute, or adding a 'hint' in `@runs_once`'s implementation and look for that.

**Comment by daniyalzade** [comment]
Quick question here though, in the parallel mode, how can I ensure that a task is run only once, such as a cleanup task at the end of the execution?

**Comment by bitprophet** [comment]
@daniyalzade please use the mailing list or irc for that sort of question, thanks!
