### ISSUE TITLE
Default output for `fab` without arguments

### ISSUE THREAD

**Issue by techtonik** [fabric/fabric#686]
Now that `fabric` has so many options that they don't fit the screen it makes sense to change the output when `fab` is executed without arguments. I propose it to be different when a `fabfile.py` is present:

    Usage: fab [options] <command>[:arg1,arg2=val2,host=foo,hosts='h1;h2',...] ...

    Options:
      -h, --help            show detailed help about fabric options 
    
    Commands from fabfile.py:
        some
        commands

**Comment by bitprophet** [comment]
Moving to pyinvoke/invoke#287
