### ISSUE TITLE
How to make some sub-tasks parallel and others not?

### ISSUE THREAD

**Issue by philfreo** [fabric/fabric#692]
I want to say `fab production deploy` where I have tasks like

```
def staging():
    # ... 

def production():
    # ... other similar stuff
    env.hosts = env.roledefs['webservers']

def deploy(branch=None):
    if branch:
        env.branch = branch

    checkout_latest()
    print_commits()
    upload_static_assets()
    symlink_current_release()
    restart_services()
```

And I want all of the sub-tasks of `deploy` to be run in parallel on all of the webservers. Putting `@parallel` at the top of `deploy` would do this.

However what I really need is for all of the sub-tasks inside of `deploy` to be run in parallel, _except_ for `upload_static_assets`, which should only be run on 1 of the webservers after the previous 2 sub-tasks were completed.

Can't figure out any good way to do this that doesn't require changing what I type on the command line. Advice?

**Comment by ryanjdillon** [comment]
Or maybe StackOverflow? I had the same challenge, and I think I found it here more easily than the mailing list (and certainly more easily than IRC).
