### ISSUE TITLE
rsync_project does not use env.password to login remote server

### ISSUE THREAD

**Issue by kuntelin** [fabric/fabric#817]
I execute a command "fab -u user -p passwd -H 192.168.1.1 update".
But it will prompt password login.
Example code as following:

@task
def update
    print "Username: %s" % env.user
    print "Password: %s" % env.password
    sudo("ip addr list")
    print "before rsync_project"
    rsync_project(remote_dir="/tmp", delete=True, extra_opts="-e ssh")
    print "after rsync_project"

**Comment by sidnaik03** [comment]
use upload_project() method with use_sudo=True option
`upload_project(local_dir='/home/..../..../....', remote_dir='/var/www/...', use_sudo=True)`
