### ISSUE TITLE
Improvement SED

### ISSUE THREAD

**Issue by Poil** [fabric/fabric#827]
Hi,

The function sed is not really a SED, it's a search and replace, we can do more with the sed command line.

I think the sed function need to take one more parameter named "action"
Like that we could run an "append" "prepend" with the power of SED
The biggest problem is that the "action" is not at the same place in the sed command line

Exemple of cool stuff we can't do with fabric today 

    #this will add a new line containing mytext after my search pattern
    sed '/my search pattern/ a mytext' myfile.txt
    # this will insert a new line  containing mytext before my search pattern
    sed '/my search pattern/ i mytext' myfile.txt
    # this will insert a new line containing mytext at line 3
    sed '3 i mytext' myfile.txt
    # this will add a new line containing mytext at line 3
    sed '3 a mytext' myfile.txt

Best regards,

**Comment by Russell-Jones** [comment]
See http://www.fabfile.org/roadmap.html

<blockquote>
Fabric 1.x, while not quite yet end-of-life’d, has reached a tipping point regarding internal tech debt & ability to make improvements without harming backwards compatibility.

As such, future 1.x releases (1.6 onwards) will emphasize small-to-medium features (new features not requiring major overhauls of the internals) and bugfixes.
</blockquote>
