### ISSUE TITLE
sudo fails in parallel mode even when no password should be prompted

### ISSUE THREAD

**Issue by jontsai** [fabric/fabric#832]
Not sure if it's a bug, or I'm using `sudo` incorrectly

`def restart_webserver():`
`"""Restarts Apache`  
`"""`
`run('sudo /etc/init.d/apache2 restart') # works`
`#sudo('/etc/init.d/apache2 restart') # fails with the error below`

`sudo: /etc/init.d/apache2 restart`
`Fatal error: Needed to prompt for a connection or sudo password (host: localhost), but input would be ambiguous in parallel mode`

I have a file in `/etc/sudoers.d` to allow `deploy` user to run (`sudo /etc/init.d/apache2 restart`):
`Cmnd_Alias WEBSERVER = /etc/init.d/apache2`
`deploy ALL=(ALL) NOPASSWD:WEBSERVER`

**Comment by alonha** [comment]
Thanks. You helped me a lot :-)

**Comment by toby5box** [comment]
This fix did not work for me. I can also run passwordless sudo in my account, but these fail:

```

        run('sudo git pull')


        sudo('git pull', shell=False)
```
