### ISSUE TITLE
put(): empty string in remote_path not replaced by the remote current working directory

### ISSUE THREAD

**Issue by jmce** [fabric/fabric#835]
Documentation for put() claims that "an empty string, in either path argument, will be replaced by the appropriate end's current working directory".   But (in Fabric 1.5.3)
setting remote_path='' the remote home directory is selected instead. With

    remote_path = remote_path or home

remote_path becomes a absolute path (home), thus 'honoring' cd() is skipped.

**Comment by bitprophet** [comment]
I *think* this has been solved since. Can reopen again if not the case.

**Comment by patrickf3139** [comment]
I'm using Fabric 1.10.2 and this issue definitely has not been fixed yet. Is this only fixed in the dev build @bitprophet ?

**Comment by bitprophet** [comment]
This does look like same as #370, let's roll into that one.
