### ISSUE TITLE
env.user overriden by User from ssh_config (contrary to documentation)

### ISSUE THREAD

**Issue by artyom** [fabric/fabric#848]
[Leveraging native SSH config files][1] section of original documentation states that:

> …if env.user/env.port are set, they override global User/Port values

Unfortunately, I see the opposite behavior.

Consider having the following `fabfile.py`:

```Python
import sys
from fabric.api import env, roles, task, run
from fabric.context_managers import settings

env.forward_agent = True
env.use_ssh_config = True
env.ssh_config_path = 'ssh_config'
env.roledefs = {
    'myrole': ['testbox'],
}

@roles('myrole')
@task
def testme():
    print >>sys.stderr, env.user
    run('whoami')
    with settings(user='myuser'):
        print >>sys.stderr, env.user
        run('whoami')
```

If I use this `ssh_config` file:

	Host testbox
		User root

I get the following output from `fab testme` (run by root user):

	[testbox] Executing task 'testme'
	root
	[testbox] run: whoami
	[testbox] out: root
	[testbox] out: 
	
	myuser
	[testbox] run: whoami
	[testbox] out: root
	[testbox] out: 
	
	
	Done.

Note, that `env.user` seen as `myuser` inside `settings` context manager, but `run` command ignores this and uses user from `ssh_config`.

[1]: http://docs.fabfile.org/en/1.6/usage/execution.html#leveraging-native-ssh-config-files

**Comment by bitprophet** [comment]
Believe this is obviated by a more recently submitted PR (may not be merged yet but if not it's in one of the release milestones).
