### ISSUE TITLE
Invalid escaped string in sed function

### ISSUE THREAD

**Issue by inabhi9** [fabric/fabric#867]
These are the sed arguments:
` files.sed('main.php', "'client_id'.*", '"client_id" => "4389222323451441",') `

Now the sed function automatically escaped the single quote with the slash and it became \'. The whole string in shell executes like this

` sed -i.bak -r -e 's/\'client_id\'.*/"client_id" => "4389222323451441",/g' main.php `

which is invalid the string should be:
` sed -i.bak -r -e 's/'\''client_id'\''.*/"client_id" => "4389222323451441",/g' main.php `

Please look at this issue.

I recommend to add one more argument to function which decides the string should be escaped automatically or not so developer can escape the string manually.

**Comment by jaraco** [comment]
This issue also affects `comment` and makes it impossible to use `comment` on lines that contain single quotes [This SO answer](http://stackoverflow.com/a/1250279/70170) also presents a technique for escaping.

**Comment by jaraco** [comment]
I believe this is a dupe of #567

**Comment by bitprophet** [comment]
Yup sed is rife with escaping problems :( #567 is the main ticket for that right now, thanks @jaraco (and thanks for the input, @inabhi9 !)
