### ISSUE TITLE
Dynamically created tasks not detected

### ISSUE THREAD

**Issue by chrisspen** [fabric/fabric#900]
I'm attempting to dynamically create Fabric tasks to set environment variables for specific deployment platforms. e.g. `fab staging deploy` or `fab production deploy` where the Fabric task functions "staging" and "production" are dynamically created based on configuration scripts.

However, if I use the [task decorator](http://docs.fabfile.org/en/1.6/usage/tasks.html) at runtime, the commands are reported as not found.

e.g. fabfile.py

```
from fabric.api import task

def _test():
    pass

staging = task(_test, name='staging')
```

but when I go to execute:

```
[user@localhost: ~] fab staging
Warning: Command(s) not found:
    staging
```

Oddly, the task is detected if I don't use the task decorator anywhere (causing Fabric to only look at only old-style commands).

Am I using the decorator correctly? As far as I can tell, there's no difference in the executable object created dynamically verses hardcoded. How do I allow Fabric to detect my dynamic tasks/commands?

**Comment by DylanYoung** [comment]
FYI: it also won't work if the task isn't assigned as a module global/attribute (for truly dynamic task generation: I guess there is no actual task registry???).  You'll have to explicitly assign it to `globals()` (ugly, I know).
