### ISSUE TITLE
Namespacing breaks when using fabric.api.run()

### ISSUE THREAD

**Issue by pikeas** [fabric/fabric#901]
This works as advertised:

    # __init__.py
    import my_module as m

    # fab -l display tasks as m.<task>

This behavior is unexpected:

    # __init__.py
    from fabric.api import run
    import my_module as m

    # fab -l displays tasks as my_module.<task>

This causes problems when `__init__.py` also defines tasks.

**Comment by kaaveland** [comment]
Can't seem to reproduce this now.

It does not recognise plain defs from `my_module` as tasks, so I had to set them with `@task` in `mymodule`, but that doesn't seem to break for me.
