### ISSUE TITLE
network.py:prompt_for_password uses env.user rather than env.host_string

### ISSUE THREAD

**Issue by miracle2k** [fabric/fabric#911]
The documentation page on library use says that functions like ``run()`` should only depend on ``env.host_string``. In fact, however:

     >>> env.host_string = "me@host"
     >>> run("ls")
     [me@host] Login password for 'michael':

``network.py.connect()`` parses the host_string, but then does not give the parsed username to the password getter.

This seems to be a display issue only, albeit a confusing one.

**Comment by bitprophet** [comment]
Reasonably sure this has been solved by PRs since.
