### ISSUE TITLE
Fabric mangles \r without a way to turn it off

### ISSUE THREAD

**Issue by PaulMcMillan** [fabric/fabric#918]
Fabric very nicely manages newlines such that they display correctly even when the remote system newlines don't match the local convention. However, there's not a way to turn this off, which sucks if you're trying to (ab)use the system to transfer binary data from a remote stdout into a local variable.

The offending code is here:
https://github.com/fabric/fabric/blob/master/fabric/io.py#L107-L141

My use case was a remote tcpdump to stdout that I needed to capture and pass along to the stdin of a program started with subprocess.

Looking at the code, I'm not quite sure quite where the correct patch would be to add a "don't mangle my output", but I assume it's another setting.

The easiest workaround ended up being to pipe through the base64 command line utility. It's worth noting that OSX doesn't agree with linux about what -d means, so if you need to support osx you can use `openssl base64 -d` which does have the same semantics in both places.

**Comment by dgloe** [comment]
I'm seeing Fabric adding \r to every newline except the last one. Here's a comparison of a command run locally and through Fabric:

    0001160   t   e                                   u   p       i   n   t
    0001200   e   r   a   c   t   i   v   e  \n                   5   8    
    0001220                   0   x   3   a       c   0   -   0   c   0   s
    0001240   1   4   n   2           c   o   m   p   u   t   e            
    0001260                       u   p       i   n   t   e   r   a   c   t
    0001300   i   v   e  \n                   5   9                       0
    0001320   x   3   b       c   0   -   0   c   0   s   1   4   n   3    
    0001340       c   o   m   p   u   t   e                           d   o
    0001360   w   n       i   n   t   e   r   a   c   t   i   v   e  \n
    0001377

    0001200       u   p       i   n   t   e   r   a   c   t   i   v   e  \r
    0001220  \n                   5   8                       0   x   3   a
    0001240       c   0   -   0   c   0   s   1   4   n   2           c   o
    0001260   m   p   u   t   e                                   u   p    
    0001300   i   n   t   e   r   a   c   t   i   v   e  \r  \n            
    0001320       5   9                       0   x   3   b       c   0   -
    0001340   0   c   0   s   1   4   n   3           c   o   m   p   u   t
    0001360   e                           d   o   w   n       i   n   t   e
    0001400   r   a   c   t   i   v   e  \n
    0001410

Is this the same bug or something new? I'm using Fabric 1.8.0.

We might be able to work around this by somehow suppressing Fabric output and printing it ourselves after removing the \r characters.

**Comment by bitprophet** [comment]
Version 2 eschews any mandatory transformation of remote streams besides decoding from bytes to Unicode, so this is definitely a non-issue from 2.0 onwards.
