### ISSUE TITLE
Setting multiple shell environment variables desn't work properly under Windows with local()

### ISSUE THREAD

**Issue by jorisvddonk** [fabric/fabric#949]
On Windows, when using shell_env to set environment variables, not all environment variables get set properly when using local(). Specifically, only the first variable gets set (any others are completely ignored) and the value assigned to that variable will be wrong as well (something like `"bar" SET baz="qux"` where `bar` is expected).

Test case:
https://gist.github.com/jorisvddonk/6162658

Results on Windows 7:
https://gist.github.com/jorisvddonk/6162668

Results on Linux (Ubuntu 12.04):
https://gist.github.com/jorisvddonk/6162673

**Comment by bitprophet** [comment]
Rolling into PR.
