### ISSUE TITLE
lcd() context with local() and CDPATH includes output of cd command

### ISSUE THREAD

**Issue by erlkonig** [fabric/fabric#980]
When using something like

    with lcd(target_dir):
           output = local('...........')

while the environment variable CDPATH is present, Bash will output what directory it ends up in the target_dir was a simple name (no slashes).  The docs (for cd()) suggest that running a command ends up doing "cd target_dir && command", but if CDPATH is present the model would need to be "cd target_dir >/dev/null && command" to be reliable.  Otherwise the command's output will have a generally unanticipated prefixed directory name, and horribly break some fab jobs for only certain users.

Alternatively, fab could unset CDPATH by default, and be documented as doing so, though there is a small chance some nutter is using that extra output deliberately.

**Comment by sivy** [comment]
This is probably ok, but need to look at how `cd` and `lcd` are implemented to see how large a change this is.

**Comment by sivy** [comment]
Looks like the change would be to https://github.com/fabric/fabric/blob/1.9/fabric/operations.py#L661
