### ISSUE TITLE
Open SSH test tools for users (was: Testing fabric in another library)

### ISSUE THREAD

**Issue by davidhalter** [fabric/fabric#993]
I'm using fabric in a project (to be released OS soon) and it seems to be hard to test it. The reason is simple: SSH stuff is hard to test. Obviously you could test things against `localhost`, but the approach that you chose with your `@server` decorator is just much easier.

So why don't you offer a module called `fabric.test` that offers access to these this facility: https://github.com/fabric/fabric/blob/master/tests/server.py.

That obviously includes thinking about if this is a good interface, but I would be willing to help out here - if this "proposal" would be accepted.

**Comment by bitprophet** [comment]
I made progress on this in the recent past (think it went out in 2.1): http://docs.fabfile.org/en/2.2/api/testing.html

Those APIs aren't 100% perfect but they work reasonably well for our internal testing, and most importantly, they're public. I expect we'll iterate on them as our internal needs mature or as others discover & use them.
