### ISSUE TITLE
Combination of cd/prefix/put doesn't work.

### ISSUE THREAD

**Issue by davidhalter** [fabric/fabric#995]
Using something like this:

```
from fabric.api import *
from StringIO import StringIO

def test():
    with cd('/home/user/test'):
        with prefix('source venv/bin/activate/'):
            put(StringIO('Foobar'), 'foobar.txt')
```

I get this error:

```
Requested: mv "c8a6a7c2a9b07ae9d9495cbd9ad9b5373bb98469" "/home/user/test/foobar.txt"
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "source venv/bin/activate && mv \"c8a6a7c2a9b07ae9d9495cbd9ad9b5373bb98469\" \"/home/user/test/foobar.txt\""

/bin/bash: venv/bin/activate: No such file or directory
```

That's not correct - the whole `venv` stuff does exist, but fabric doesn't respect it (look at the generated command above). There's no cd in the command.

**Comment by toastdriven** [comment]
I tried to reproduce as much of this as I could & ended with the following:

    from __future__ import print_function

    from StringIO import StringIO
    import os

    from fabric.api import cd, prefix, put, run
    from fabric.state import env


    def test_995():
        try:
            os.remove('/tmp/test_echo.sh')
        except OSError:
            pass

        with cd('/tmp'):
            with prefix('FOO=bar '):
                print(env.cwd)
                print(env.command_prefixes)
                put(StringIO('echo $FOO'), 'test_echo.sh', use_sudo=True)
                print("Go look for /tmp/test_echo.sh")

Unfortunately, this **doesn't** reproduce the issue. Removing `use_sudo=True` doesn't seem to have any effect.

@sivy suggested maybe the `source venv/bin/activate` (or another post-activate hook) might be messing with things.

**Comment by bitprophet** [comment]
Thanks @toastdriven - going to close this pending more feedback from the afflicted.
